### ISSUE TITLE
how to configure vagrant so that it doesn't try to create shared folders

### ISSUE THREAD

**Issue by matighet** [hashicorp/vagrant#1004]
The shared folders are creating issues with my VMs right now, most likely because I don't have VirtualBox tools installed.
However, I don't really need shared folders, so ideally would like to disable that feature for my VMs.

Is there a way to disable shared folders in Vagrantfile?

Here is the error I'm getting:

{{{
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -t vboxsf -o uid=`id -u proxyuser`,gid=`id -g proxyuser` v-root /vagrant
}}}

**Comment by madelaney** [comment]
I'm seeing the same issue with Vagrant 1.7.2 and VirtualBox
```
Installed Version: 1.7.2
Latest Version: 1.7.2
 
You're running an up-to-date version of Vagrant!
```

**Comment by tuscland** [comment]
+1

**Comment by jakeczyz** [comment]
I seem to only have problems with synced folders *after* my initial build and boot.  Since they aren't really supported/useful for cloud environments (e.g., aws, digital ocean), I don't really want/need them locally.  I do, however, need my vagrant folder itself to sync to /vagrant, but it can happen using rsync, as happens for the cloud.  Is there a clean way to disable synced/shared/mounted /vagrant folder but continue to be able to rsync its contents once on build?  I'm running the latest vagrant and vbox. Thanks!

**Comment by smiller171** [comment]
I'm running the latest vagrant and virtualbox. I can start up ubuntu/trusty64 just fine, but if I package it up and try to re-use it it fails to mount /vagrant. I'm attempting to get it to ignore all mounts, but none of the methods posted here work.

**Comment by vhosakot** [comment]
When I did `vagrant up` with the box `centos/7 (virtualbox, 1703.01)`, `==> default: Rsyncing folder: /root/ => /vagrant` was stuck for me too, and adding
`config.vm.synced_folder '.', '/vagrant', disabled: true`
in Vagrantfile resolved the issue for me and rsync did not happen.

**Comment by tzakrajs** [comment]
Sorry for bumping this thread once again. This fix (adding `config.vm.synced_folder '.', '/vagrant', disabled: true` the Vagrantfile) allowed me launch a vagrant machine using Windows Subsystem for Linux when seeing the error: `The host path of the shared folder is not supported from WSL.` I typically run `vagrant up` from a bash shell in Ubuntu for Windows and whenever I did so from a Linux path (not in /mnt/c/) the preceding error appeared.
