### ISSUE TITLE
Running Host PowerShell Commands no longer works in 2.1.2

### ISSUE THREAD

**Issue by MichaelMitchellM** [hashicorp/vagrant#10051]
### Vagrant version
2.1.2

### Host operating system
Windows 10

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
# ...
config.trigger.after :up do |trigger|
  trigger.name = "Import Cert on Host"
  if Vagrant::Util::Platform.windows? then
    trigger.run = {inline: "PowerShell setup/certs/ImportCertificate.ps1 -NewCertPath \"#{File.dirname(__FILE__) + "/data/ca/certs/ca.cert.pem"}\""}
  end
end
# ...
```

### Debug output
https://gist.github.com/MichaelMitchellM/c97c8f35442f6dc947e945110131e3e3

### Expected behavior
Execute PowerShell command on host machine.

### Actual behavior
Tried to run the described PowerShell command in some weird array split on spaces.

### Steps to reproduce
1. Make sure you're on Vagrant version 2.1.2 (worked fine in 2.1.1)
2. Attempt to run a PowerShell Command in a .run = (inline: "<command>"}

**Comment by briancain** [comment]
Hello @MichaelMitchellM - you do not actually need to prepend your command with the powershell program. Vagrant by default will use Powershell on Windows hosts to execute inline commands.

That said, it looks like you're trying to just run an external script rather than an inline script. In that case, you should instead use the `path` command instead of `inline`. Your code instead would look like

```ruby
trigger.run = {path: "setup/certs/ImportCertificate.ps1", args: ["-NewCertPath","#{File.dirname(__FILE__) + '/data/ca/certs/ca.cert.pem'}"]}
```

Let me know if that works, thanks!

**Comment by MichaelMitchellM** [comment]
Hello @briancain 
This does work!
Although using path/args I can accomplish everything I need, I am still curious if inline PowerShell commands are supported.

Thank you!
