### ISSUE TITLE
Please provide AppImage file for download

### ISSUE THREAD

**Issue by probonopd** [hashicorp/vagrant#10093]
Please provide AppImage file for download on https://www.vagrantup.com/downloads.html.

Please __DO NOT__ put an AppImage into another archive like a `.zip` or `.tar.gz`. While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional `appimaged` daemon, among other things. Besides, the beauty of the AppImage format is that you never need to unpack anything. Furthermore, packing an AppImage into some form of archive prevents the AppImage from being added to the central catalog of available AppImages at https://github.com/AppImage/AppImageHub.

https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by chrisroberts** [comment]
Hi there and sorry for the delay in response to this issue! Many thanks for all the hard work you have put into AppImage and the various tools around it.

With regards to the appimage being distributed within an archive, this is simply due to how the internal release process works and is supported. With Vagrant being a console based application, there wasn't much worry about any kind of desktop integration. And since distribution of the application is via the HashiCorp releases site there doesn't seem to be any harm in how it's currently provided.

Thanks again and cheers!
