### ISSUE TITLE
Trigger runs script before checking path

### ISSUE THREAD

**Issue by sparris9** [hashicorp/vagrant#10103]
### Vagrant version
2.1.2

### Host operating system
Windows 10

### Guest operating system
hashicorp/precise64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

MESSAGE='Hi, Mom!'

Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/precise64"
  
    config.trigger.before :up do |trigger|
        trigger.info = "Unmounting Samba share..."
        trigger.run = {:path => "scripts/echo.bat #{MESSAGE}"}
    end
end
```

### Debug output
https://gist.github.com/sparris9/2090d4de0c421cc7eb487e58637a1572

### Expected behavior
Vagrant should check the path first, then run the batch file.

### Actual behavior
Vagrant ran the script then barfed.

### Steps to reproduce
1. `vagrant up`

### References
Are there any other GitHub issues (open or closed) that should be linked here?

I did not search.

**Comment by briancain** [comment]
From what I can tell, it looks like this has already been fixed in a recently shipped version of Vagrant. I just tried on macOS and windows by passing in additional "arguments" into the path setting like this issue mentions and both platforms gives me an error about not being able to find the script without running it. If you're still experiencing this problem with a new version let me know and I can re-open the issue. Thanks!
