### ISSUE TITLE
Debian kernel 4.9.0-6-amd64  conflicts

### ISSUE THREAD

**Issue by BonBonSlick** [hashicorp/vagrant#10163]
### Vagrant version
Vagrant 1.9.1

### Host operating system
Debian 9.5

### Guest operating system
Debian 9.5, not sure 

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "base"
end
```

### Debug output
https://paste.ofcode.org/KG9dTgC6k2gHBdKNiep4zN

### Expected behavior
vagrant is up and running

### Actual behavior
says that module does not exists for current debian kernel version

### Steps to reproduce
1. install debian, 
2. get last kernel version 9.*
3. try to run vagrant (installing required packages like ruby, virtualbox etc)

### References
do not know

**Comment by chrisroberts** [comment]
Hi there,

The root cause of the virtualbox error is that you do not have the headers installed for your kernel so it cannot properly build the module. The relevant information from the debug output you provided is this:

```
This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.
The distribution packages containing the headers are probably:
    linux-headers-amd64 linux-headers-4.9.0-6-amd64
```

Once you install that package, you should be able to successfully build the vbox modules and virtualbox will work as expected. I would also recommend grabbing a more current version of Vagrant from the downloads page: https://www.vagrantup.com/downloads.html

Cheers!

**Comment by BonBonSlick** [comment]
@chrisroberts  i have installed this packages, installed vagrant from deb file, still the same error https://paste.ofcode.org/Wj7zFZD4CSaCXWYQi6LBv

**Comment by BonBonSlick** [comment]
@chrisroberts  thank you
sudo apt-get install linux-headers-4.9.0-6-amd64
sudo dpkg -i vagrant_2.1.4_x86_64.deb solved
