### ISSUE TITLE
Automatically bring box up when requrired for another command

### ISSUE THREAD

**Issue by spawnia** [hashicorp/vagrant#10188]
### Vagrant version

2.1.4

### Host operating system

Windows

### Steps to reproduce

1. I run a command that requires the vagrant machine to run, such as `ssh`, `provision` or `reload`.
2. I forgot that my machine is currently not running.

### Expected behavior

Vagrant notices my machine is not running, brings it up for me and then executes the desired command.

### Actual behavior

I receive a friendly error that tells me to execute `vagrant up`. I would like this to happen automatically.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for opening this issue. Unfortunately, this feature request is not something that we will be able to implement within Vagrant core as it would change the existing behavior of Vagrant in quite a drastic way. 

Cheers!

**Comment by spawnia** [comment]
Yes. It changes the behaviour. That is the entire point.

This is not going to break anyone's use case, it is just more convenient. Please reconsider, as this would make vagrant more easy to use. That is why it was made, right? To make developers lifes easier..

**Comment by briancain** [comment]
Hello @spawnia - Changing the core behavior of these commands will almost certainly break other users workflows who are expecting the functionality of these commands to exit and or halt when guests do not exist yet (especially for folks who use Vagrant inside of scripts and rely on exit codes to determine state). Updating core Vagrant to magically bring up vms after a failed command was run would be very unexpected for them, as this behavior would be intentional for your use case, would be unintentional for everyone else. This could likely be accomplished however potentially with a third party plugin for Vagrant, or a set of bash functions, but doesn't belong inside Vagrant core. Thanks for opening and issue, and sorry we couldn't be more helpful.
