### ISSUE TITLE
No auto correct standart ports (eg. 3389, 5985)

### ISSUE THREAD

**Issue by Fguhhla** [hashicorp/vagrant#10185]
Vagrant do not auto correct the standart ports on converge a windows virtual box.

On convege vagrant doesn't map the windows ports for winrm and rpd (3398 / 5585 ) to unused ports. Result: No winrm connection can be established ~converge failed.

Vagrant version
2.1.2

Host operating system
Windows 10 x64

Guest operating system
Windows 2012r2 & 2016 Server

Link to vagrant -debug log: https://gist.github.com/Fguhhla/00a4f94fe23867bf9a23854f2c460fb6

**Comment by chrisroberts** [comment]
Hi there,

Based on the debug log the port forwarding is correctly applied. The run results in an error due to the guest not responding. Please validate that your guest is properly running and accessible from the host system. If you still encounter problems, please create a new issue and include all the information requested by the template to help us to identify the core issue.

Cheers!
