### ISSUE TITLE
Please remove dead links

### ISSUE THREAD

**Issue by xyr115** [hashicorp/vagrant#10183]
As Box-cutter is no longer providing binaries, there is a 404 error thrown in. At the very least there could be a redirection on these pages so that people aren't confused.

I've found this to be true for Centos72 and 73

https://vagrantcloud.com/box-cutter/boxes/centos73/versions/2.0.21/providers/virtualbox.box

Thanks

**Comment by chrisroberts** [comment]
Hi there,

Those boxes are configured as "external boxes" on Vagrant Cloud which point to an external location. Vagrant Cloud only does what is requested by the user (in this case, redirecting to a given location). The 404 error that is generated because the box is no longer available is the correct behavior in this case.

Cheers!
