### ISSUE TITLE
Does Vagrant still support Pageant?

### ISSUE THREAD

**Issue by thorn0** [hashicorp/vagrant#10195]
### Vagrant version
Vagrant 2.1.4

### Host operating system
Windows 10 Home x64

### Guest operating system
Ubuntu 12.04 LTS

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.ssh.forward_agent = true
end
```

### Expected behavior
The keys loaded to Pageant should be used in the guest OS.

### Actual behavior
```console
vagrant@precise64:~$ ssh -T git@github.com
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
```

### Steps to reproduce
1. Run Windows
2. Ensure Pageant is running with your key loaded
3. Setup a simple VM with Vagrant, specify `config.ssh.forward_agent = true`
4. Run this machine and try to use your key there

### References
There are many issues that mention that Pageant works for agent forwarding. For example:
- #8615 
- #8415
- #8367
- [etc](https://github.com/hashicorp/vagrant/issues?q=pageant)

It does not work for me however. Am I missing something? Or did it break?

**Comment by func0der** [comment]
We are opening dozens of tickets to get this removed and just use the openssh ssh agent and there you come breaking it all ^^ 

Explanation: 
Vagrant ssh and the provisionig process of Vagrant use different ssh libraries, why so ever.
`vagrant ssh` seems to use the `ssh` binary if it finds one. I do not know what happens if it does not.
So if you are running for example git bash, it would use the openssh ssh binary.

`vagrant provision` and the sorts use net-ssh which does not properly support openssh agents and uses only pageant.

So this is a big problem for now. If you can, use the openssh agent and a properly formatted key for now to connect to your machine via `vagrant ssh` and have agent forwarding enabled. You still have to use `pageant` for `vagrant up/provision` etc. for now.

Since you are on Windows 10, try the WSL and install an Ubuntu. You can use it to control your vagrant and should be 100% on the openssh implementation, since all of the above works uniform under a Linux host.

**Comment by thorn0** [comment]
Thanks a lot for clarifying this confusion @func0der. Indeed, during the provisioning phase, Pageant works. Just checked it. From all those issues, I couldn't understand that it works _only_ during that phase. Would've been great if these known problems were somehow reflected in the docs.

FWIW, I'd prefer to simply use Pageant for everything since I'm already using it.

**Comment by chrisroberts** [comment]
@thorn0 Hi. After investigating this for a bit I was able to reproduce the same behavior you were experiencing. I started with a very simple Vagrantfile that would list the keys available with a provisioner:

![10195-1](https://user-images.githubusercontent.com/266674/45908827-5b199900-bdb3-11e8-8305-da70ece55fb0.png)

Then I started pageant and added a custom key:

![10195-2](https://user-images.githubusercontent.com/266674/45908886-ba77a900-bdb3-11e8-8c45-5a28d7725604.png)

Once I had that set, I first ran `vagrant provision`, when displayed the expected key in pageant. After I ran `vagrant ssh -c "ssh-add -l"` which resulted in an error within the guest attempting to connect to the agent (verifying that the forward had not succeeded):

![10195-3](https://user-images.githubusercontent.com/266674/45908968-3114a680-bdb4-11e8-921b-eb7a0a989c23.png)

The reason for this is that the net-ssh library creates a pseudo socket to connect to pageant. Since the `vagrant ssh` command is executing the openssh binary, it needs a socket to connect to for the forwarding. To provide this I installed ssh-pageant (https://github.com/cuviper/ssh-pageant) via msys2. I then started it, and set the environment variable for the location of the socket:

![10195-4](https://user-images.githubusercontent.com/266674/45909185-4dfda980-bdb5-11e8-8c55-d404e6887f86.png)

And that makes everything work as expected.

I'll be adding a short section to the documentation describing what I have here with using ssh-pageant.
