### ISSUE TITLE
request: a "Hello World" test img/box just like docker's 

### ISSUE THREAD

**Issue by marxenegls** [hashicorp/vagrant#10227]
The platform is buggy as my arthritis ridden grandmother ,so it would be more than convenient to have a small image, nanoserver to test various providers. I couldn't find anything under 500Mb 
& nanoserver 300Mb virtualbox/only 

and frankly i much rather know the size of the image i'm about to test than how many times it was downloaded, at least if i had to scour the site for a small test image i could but the way the details are set now i can't, not without going into every image and then see its size at the very bottom in shady grey .. is it just me that cares about bandwidth here ? +time ? beans ...

Been struggling with getting plugins to install and diff providers to launch . The whole process would not only be less wasteful but quicker too , especially since every provider has its own peculiarities . 

thanks

**Comment by briancain** [comment]
Hi @marxenegls -

We already have an issue in place tracking the work to enhance Vagrant Cloud with the ability to sort by image size here which should be coming soon: https://github.com/hashicorp/vagrant/issues/10138

If you want something small for testing, we mention in the docs to use [hashicorp/precise64](https://app.vagrantup.com/hashicorp/boxes/precise64) which is a little over 300 mb. There are plenty of other smaller boxes as well, but that box is frequently used by support for testing Vagrant. It also covers the three providers HashiCorp is responsible for maintaining aside from Docker (which in that case, you could just use the "Hello World" container you mentioned).

If you have found a bug installing a provider such as vmware, feel free to open a new issue. Otherwise if you have any more general questions, I recommend emailing the Vagrant up mailing list. This GitHub repo is for tracking bugs. Thanks!

**Comment by marxenegls** [comment]
ok 300Mb is within acceptable range ..i have pulled a VyOs image few days ago i dont remember the login creds and there's nothing about it anywhere .. it's as if there's some secret way on managing stuff here .. Docker hub documents everything , and even when images aren't documented you could still  make some sense out of the dockerfile  but vagrantfile is pretty much empty besides the name of the provider and image you got nothing else ... 

Vagrant.configure("2") do |config|
  config.vm.box = "sysnet4admin/VyOS"
end 

how am i gonna access the image after it loads with that info ? 
i know i logged in the first time i loaded this image and i should'áv taken notes then ..
