### ISSUE TITLE
Official centos/7 image backwards private network config with virtio nic_type

### ISSUE THREAD

**Issue by skyscooby** [hashicorp/vagrant#10278]
### Vagrant version
Vagrant 2.1.5

### Host operating system
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
Virtualbox version 5.2.18

### Guest operating system
centos/7 (virtualbox, 1809.01)
CentOS Linux release 7.5.1804 (Core) 

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network :private_network, ip: "192.168.33.10", nic_type: "virtio"
end
```
### Debug output
https://gist.github.com/skyscooby/883800f863d383f97fc7d93004d7a55d

### Expected behavior
eth0 should be NAT adaptor (Adapter 1 in virtualbox)
eth1 should be hostonly adapter with private IP (Adapter 2 in virtualbox)

### Actual behavior
Vagrant up fails to complete as connectivity is lost after network config / restart.
Hangs at: default: Configuring and enabling network interfaces...
In virtualbox the configuration is correct with Adapter 1 set to NAT and Adapter 2 set to hostonly.
ifconfig inside the VM shows MAC assigned to eth0  is the hostonly adapter and eth1 is the NAT adaptor as the configuration files are configured with eth0 configured with DCHP and eth1 with static IP vagrant can no longer communicate with the VM.

** Note this does not happen with the same version of the centos/6 image using virtio it also does not seem to happen if the adaptor type left blank however the performance and stability of the VM is so much better with virtio we found it necessary to use that NIC type.

### Steps to reproduce
1. vagrant up with provided Vagrantfile.

**Comment by briancain** [comment]
Hey there @skyscooby - For now, I recommend using a different box like `bento/centos-7.5` which doesn't seem to have this issue.

From what I can tell in the debug gist, the `nmcli` tool thinks `iface` is a device. It looks like `nmcli` has changed how the subcommand `disconnect` works, which is why Vagrant fails to configure the guest.

**Comment by richard-scott** [comment]
Change your NIC type to something other than virtio:
```
vb.customize ["modifyvm", :id, "--nictype1", "82540EM"]
```

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
