### ISSUE TITLE
WinRM no longer able to connect since Windows 10 1809.

### ISSUE THREAD

**Issue by Delpire** [hashicorp/vagrant#10309]
It seems since the latest release of Windows 10 (1809), I am no longer able to complete a `vagrant up` command. WinRM seems to be enabled correctly. In VirtualBox I can see that all the ports are configured correctly. If I use VirtualBox to go into the machine, it seems that WinRM is configured correctly.

I have tried this on two separate host machines, and I get the same issue. `vagrant up` does successfully start up the machine, but then it is unable to connect.

### Vagrant version
Installed Version: 2.1.5
Latest Version: 2.1.5

### Host operating system
Windows 10 x64 (1803) and Windows 7 x64

### Guest operating system
Windows 10 x64 (1803) and Windows 10 x64 (1809)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "windows_10_x64_vs2017_virtualbox.box"
end
```

Though I have tried changing the ports to use ssl.

### Debug output
https://gist.github.com/Delpire/05c8a0c6b9e16a8db5255f73c2d8571e

### Expected behavior
`vagrant up` should complete successfully and provision.

### Actual behavior
WinRM or something is timing out.

### Steps to reproduce
1. Used a packer build to build and update a Windows 10 box.
2. Run vagrant up

### References
Not any I have seen so far.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
