### ISSUE TITLE
Vagrant doesn't have the proper permissions in windows 

### ISSUE THREAD

**Issue by meiry** [hashicorp/vagrant#10335]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Vagrant 2.2.0

### Host operating system
windows 10 

### Guest operating system
ubuntu/trusty64

i installed the windows Vagrant installation using the default configuration .
2 questions : 

1. After running : 
d:\HashiCorp\Vagrant\bin>vagrant box add ubuntu/trusty64
where is the download folder ? 

2.after running : 
d:\HashiCorp\Vagrant\bin>vagrant init ubuntu/trusty64 

im getting this error , why ?:  
```
d:\HashiCorp\Vagrant\bin>vagrant init ubuntu/trusty64
The user that is running Vagrant doesn't have the proper permissions
to write a Vagrantfile to the specified location. Please ensure that
you call `vagrant init` in a location where the proper permissions
are in place to create a Vagrantfile.

**Comment by briancain** [comment]
Hi @meiry - 

1) Vagrant has a "global" folder where it downloads boxes and stores other configurations, so it won't be in the local folder where you run `vagrant box add box`.

2) This is likely because you're trying to run vagrant inside the installation location for Vagrant, which is likely owned by Administrator. You should be running vagrant outside of that location, probably some where around `C:\Users\yourusernamehere`.

This issue tracker is meant for bugs, so please redirect any more questions to the mailing list. Thanks! :tada:

**Comment by meiry** [comment]
@briancain  
Thanks for the answer , 
Where is this ? Vagrant has a "global" folder  ?
i can't find ant info when i search google ...

**Comment by briancain** [comment]
@meiry - the home folder is located at `~/.vagrant.d` by default.
