### ISSUE TITLE
Vagrant status bug with loop on VM creation

### ISSUE THREAD

**Issue by sofianinho** [hashicorp/vagrant#10369]
### Vagrant version
Vagrant 2.2.0

### Host operating system
Linux 4.15.0-38-generic #41~16.04.1-Ubuntu SMP x86_64 GNU/Linux (Ubuntu 16.04)

### Guest operating system
Ubuntu 18.04 (Official Vagrant cloud image: ubuntu/bionic64  (virtualbox, 20181030.0.0))

### Vagrantfile
I have 2 versions not working the same. In the first (let's call it noargs), I fix my number of VMs before:
```ruby
# -*- mode: ruby -*-
# # vi: set ft=ruby :

$total = 3 

Vagrant.configure("2") do |config|
  (1..$total).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.network "private_network", ip: "192.168.25."+"#{i+10}"
      node.vm.provision "shell", inline: "echo hello from node #{i+10}"
    end
  end
  
end
```
In the second version (call it args), I have a command line argument added to define the number of VMs at runtime:
```ruby
# -*- mode: ruby -*-
# # vi: set ft=ruby :

require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: vagrant [options] up"
  options[:nodes] = 1
  opts.on("-n", "--nodes NUM", OptionParser::DecimalInteger, "Number of nodes. Default: 1") do |w|
    options[:nodes] = w
  end
end.parse!

$total = Integer(options[:nodes])

Vagrant.configure("2") do |config|
  (1..$total).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.network "private_network", ip: "192.168.25."+"#{i+10}"
      node.vm.provision "shell", inline: "echo hello from node #{i+10}"
    end
  end
  
end
```
Note that I also converted the (options[:nodes]) with to_i method.

### Debug output
Full gist here: https://gist.github.com/sofianinho/f8851a088f7ad3adf384282c513f7da8
What you can see is:
- How I bring up 3 machines with the `args` version
- The hidden .vagrant/machines folder indicating the 3 machines created (they are up and running in VirtualBox)
- vagrant status command _`only`_ sees node-1 but not the others
- vagrant global-status sees all 3 nodes

### Expected behavior
- vagrant status should see all 3 machines
- vagrant ssh would work with all 3 nodes

### Actual behavior
- vagrant status indicates only node-1, while global-status sees all 3. Only in the `args` version, the `noargs` version where the number of VMs is static is fine. Only when this same number of VMs comes in an argument that vagrant behaves that way
- vagrant ssh only works with node-1. The immediate consequence is that you have to manually ssh into the VMs using this command for node-2, for instance at the private ip 192.168.25.12 :
```sh
ssh -i .vagrant/machines/node-2/virtualbox/private_key vagrant@192.168.25.12
```
You have to accept the signature and remove it if you destroyed the VM (or else you get the ssh warning that the host has changed):
```sh
ssh-keygen -f "/home/user/.ssh/known_hosts" -R 192.168.25.12
```
### Steps to reproduce
1. Use the `noargs` Vagrantfile for  a simple looped VM creation
2. Use the `args` version and introduce your VM number as indicated (by the way, the vagrant help menu is  overwritten by the one produced by 'optparse' but of course only i nyour current folder)
3. Use the commands vagrant status and vagrant global-status, see your VirtualBox GUI and see that the results are incoherent

I tried upgrading from Ruby 2.3 to 2.5 on my system (I thought it had something to do with how integer variables are used in Ruby) with no success. I want this kind of setup where I give my number of VMs at runtime to avoid writing an additional bash script for my personal project of creating Kubernetes clusters in VMs with vagrant and kubeadm.

Thanks in advance for your help and guidance.

### References
- The gist for debug: https://gist.github.com/sofianinho/f8851a088f7ad3adf384282c513f7da8
- No other issue is related as far as I could tell
- ...

**Comment by chrisroberts** [comment]
Hi there,

The Vagrantfile isn't intended to modify the behavior of the Vagrant CLI, and the usage in that manner would be considered "undefined". A better way to implement what you have described is by using an environment variable to set the number of instances.  Then you could set `total = ENV.fetch("NUM_NODES", 1).to_i`. 

Now, why you see all three nodes when you run `vagrant up` and not when you run `vagrant status` has to do with how the Vagrantfile is evaluated. When you run `vagrant up`, it is getting a value for the number of nodes, the 3 nodes are defined, and you then see them come up. When your run `vagrant status`, you are not providing the number of nodes, so when the Vagrantfile is evaluated the default of 1 is set, and only one node gets defined which is all that is displayed.

Setting the number of nodes via environment variable will allow you to export the value and see consistent behavior when the Vagrantfile is loaded. Otherwise that information will need to be persisted in some way and loaded to allow the Vagrantfile to be properly evaluated as expected.

Hope that helps. Cheers!

**Comment by sofianinho** [comment]
That helps actually, thanks!
I was considering switching to the ENV version, I'll do that then. Thank you.
