### ISSUE TITLE
Plain qemu backend?

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10392]
I think it's awesome that Vagrant supports libvirt as a provider, but unfortunately libvirt mostly targets Linux hosts, making it difficult to use libvirt boxes on macOS and Windows. Could we get a plain vanilla `qemu` provider, for running non-x86 boxes on more hosts?

**Comment by briancain** [comment]
Hey there @mcandre ! This is definitively a reasonable idea and probably something that people would find very useful! Unfortunately, writing a new provider from scratch is a large amount of work and probably not something the Vagrant dev team will have time for in the foreseeable future. I think this could make for a perfect third party plugin like `vagrant-libvirt`, however! I'm going to go ahead and close this issue just so that it doesn't become stale since it's a feature request rather than a bug. Thanks again though for the feature request! :heart:
