### ISSUE TITLE
Remove some log noise

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10423]
Vagrant does a good job of communicating low-level logs to the Vagrant user, such as SSH behavior. However, some of these low-level operations often convey more information that the user needs, clogging up Vagrant output. Could we reduce some of the logs, to make it easier for users to see the output they want to see?

For example, SSH often performs several connection resets and retries when booting VM's. Could these logs be suppressed, and re-enabled when the Vagrant user explicitly turns on verbose mode?

**Comment by chrisroberts** [comment]
This is controllable by using the `VAGRANT_LOG` environment variable. The `--debug` flag simply sets the `VAGRANT_LOG` value to `"debug"`. You can generate less output with the logger by setting it to a different value:

```
VAGRANT_LOG=info vagrant up
```

https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_log

Cheers!

**Comment by mcandre** [comment]
What is the default log level?

> By default, Vagrant does not actively show any log messages.

This is false, at least on my machine. SSH connection resets amd retries are shown. I am not using the debug log level, just Vagrant default values.

**Comment by briancain** [comment]
@mcandre - When you use the `--debug` flag, `VAGRANT_LOG` is set to _debug_ level. Otherwise if you're not using the `--debug` flag or setting the `VARGANT_LOG` environment variable, what you are seeing is something directly printed from Vagrant itself. If you simply want to reduce the number of SSH connection resets you see, you might to upgrade to the latest version of Vargant, 2.2.1, as it includes this fix https://github.com/hashicorp/vagrant/pull/10321 which tries to reduce the noise that the SSH communicator has.
