### ISSUE TITLE
Unable to destroy container when using docker provider in multi-machine configuration

### ISSUE THREAD

**Issue by jamesla** [hashicorp/vagrant#10424]
When using a multi machine vagrant file the docker provider is unable to destroy a container. It works fine if you use the exact same config except without multi machine configured.

### Vagrant version
2.2.1

### Host operating system
Ubuntu 18.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.define "vm" do |box|
    box.vm.box = "bento/ubuntu-16.04"
  end

  config.vm.define "test" do
    config.vm.provider "docker" do |d|
      d.image = "nginx"
    end
  end
end
```

### Debug output
https://gist.github.com/jamesla/98986d7c015303282b7ef1bb0aa3c88b

### Expected behavior
It should delete the container

### Actual behavior
Throws a validation warning about not being able to find a property that is there

### Steps to reproduce
1. use the above vagrant file
2. vagrant up 
3. vagrant destroy (throws here)

**Comment by bdube** [comment]
I have a very similar issue. It seems like the docker provider validation logic has issues with multi-machine contexts, even if there is only one machine.

**Comment by chrisroberts** [comment]
Hi there,

The error you are encountering seems to originate from configuration validation which is occurring due to the structure of the Vagrantfile. When updating the provider configuration for the `"test"` guest, the configuration needs to be scoped directly to that guest. For example, updating the Vagrantfile like this will allow it to properly validate:

```ruby
Vagrant.configure("2") do |config|
  config.vm.define "vm" do |box|
    box.vm.box = "bento/ubuntu-16.04"
  end

  config.vm.define "test" do |c|
    c.vm.provider "docker" do |d|
      d.image = "nginx"
    end
  end
end
```

Cheers!
