### ISSUE TITLE
install the vagrant-vbguest error

### ISSUE THREAD

**Issue by Zereker** [hashicorp/vagrant#10442]
### Vagrant version
Version: 2.2.1

### Host operating system
Ubuntu-16.04.05 LTS

### Guest operating system
VirtualBox 5.2.22

### Debug output
ERROR warden: Error occurred: wrong number of arguments (given 0, expected 1+)
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::CommandPlugin::Action::InstallGem:0x0000000002019cd8>

### Expected behavior
vagrant plugin install vagrant-vbguest

### Actual behavior
error

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
