### ISSUE TITLE
SSHInsertKeyUnsupported error on Centos 7 Guest in Windows Host

### ISSUE THREAD

**Issue by sharavanan2010** [hashicorp/vagrant#10519]
### Vagrant version
VMware Workstation 15 Pro
Vagrant 2.0.2
Plugins:
  vagrant-hostmanager (1.8.9)
  vagrant-omnibus (1.5.0)
  vagrant-vbguest (0.16.0)
  vagrant-vmware-desktop (1.0.0)
     - Version Constraint: 1.0.0

### Host operating system
Windows 10 Pro

### Guest operating system
Centos 7 

### Vagrantfile
https://gist.github.com/sharavanan2010/8d11a1a63f4f317228ac9c0b0972e2e5

### Debug output
https://gist.github.com/sharavanan2010/1c92ce011a38b980009ed293e8f851b8

### Expected behavior
Able to replace the insecure private key

### Actual behavior
Vagrant up failed with SSHInsertKeyUnsupported error

### More info
Running below command from host
E:\DevstackImages\centos_linux_7_standard_sp0_64_eng_vmware-1>vagrant ssh-config
Host default
  HostName 192.xxx.xxx.175
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile E:/DevstackImages/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes

**Comment by chrisroberts** [comment]
Hi there,

Looking at the debug output Vagrant is detecting the guest as a Windows guest which is causing the error when attempting to insert the new public key. Since your Vagrantfile does not have any entries identifying the guest, please check the Vagrantfile contained within the box itself and verify that it is not explicitly setting the guest.

**Comment by sharavanan2010** [comment]
Thanks @chrisroberts
I have updated the vagrantfile in the box itself and SSH key is inserted into box. Now I'm getting different issue, unable to create shared folder in guest OS.
Debug Log:
https://gist.github.com/sharavanan2010/2a9dc55e22e9d13057d2e560830638c8

Vagrantfile contained in box:
https://gist.github.com/sharavanan2010/140b2427cebf430e3595a1d995acf896

Vagrantfile in Project Folder:
https://gist.github.com/sharavanan2010/60ab1bf627bc793b3e5a8d86e1a11f81

vmware log:
https://gist.github.com/sharavanan2010/b03d67a897d925df6c8285608394b9b9

**Comment by chrisroberts** [comment]
When the guest is running can you manually enable shared folders via the GUI and mount them within the guest? The guest tools should write to a log file on the guest as well and will likely have more information on the underlying issue.

**Comment by sharavanan2010** [comment]
Manually i could able to create shared folder via VMware workstation GUI

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
