### ISSUE TITLE
Network 

### ISSUE THREAD

**Issue by erplsf** [hashicorp/vagrant#10604]
### Vagrant version
Vagrant 2.2.3

### Host operating system
Arch Linux

### Guest operating system
Alpine Linux v3.8 via generic/alpine38

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"

  config.vm.network "private_network", type: "dhcp"
end

```

### Debug output
https://gist.github.com/erplsf/5d88befa6daf11115b97cef659ea35d2

### Expected behavior
Box is booted up and accessible with it's private network set up

### Actual behavior
Box is not created, and outputs errors related to setting up a network interface

### Steps to reproduce
1. Install virtualbox as one and only provider
2. Create aforementioned Vagrantfile
3. run ```vagrant up```

**Comment by ladar** [comment]
Vagrant is using the wrong syntax/commands for an Alpine system. The vagrant-alpine plugin _might_ fix this issue, or you can try using the following Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"

  config.vm.network "private_network", type: "dhcp", auto_config: false

  config.vm.provision "shell",
    run: "always",
    inline: "ifconfig eth1 inet dhcp"

  config.vm.provision "shell",
    run: "always",
    inline: "printf \"\nauto eth1\niface eth1 inet dhcp\n\""
end
```

The second provision command makes the change persist across reboots, which you may, or may not want.

**Comment by ladar** [comment]
Sorry, typo in the previous post. Forgot to redirect the second inline script command:

```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"

  config.vm.network "private_network", type: "dhcp", auto_config: false

  config.vm.provision "shell",
    run: "always",
    inline: "ifconfig eth1 inet dhcp"

  config.vm.provision "shell",
    run: "always",
    inline: "sudo bash -c 'printf \"\nauto eth1\niface eth1 inet dhcp\n\" >> /etc/network/interfaces'"
end
```

**Comment by vmmello** [comment]
I'm also having this problem. In addition to having a broken hostname setup when specifying `config.vm.hostname` option.

It looks to me that the root cause of this problem is that the current boxes for Alpine are using ALT Linux plugin modules as there's no specific module for Alpine.

I'm following up with a pull request with some small workarounds to fix these specific problems (until there's a proper plugin namespace for Alpine).

**Comment by chrisroberts** [comment]
@ladar Hi! After digging into this a bit and trying to figure out why ALT was ending up being used as the guest I found: https://github.com/lavabit/robox/blob/master/tpl/generic-alpine39.rb#L35 

Just curious if there was any specific reason for setting the guest to `:alt`?

**Comment by chrisroberts** [comment]
And with some more testing, there doesn't seem to be anything which requires fixing here. After installing the `vagrant-alpine` plugin, I'm able to configure the hostname as well as configure networks without problem. Using the generic box, you'll need to override the guest in your Vagrantfile since it's getting set to `:alt`. So, in your Vagrantfile you'll need to add:

```ruby
Vagrant.configure("2") do |config|
  ...
  config.vm.guest = :alpine
end
```

With that change and the plugin, everything should work as expected. 

Cheers!
