### ISSUE TITLE
with private_network cannot ssh to guest on subsequent boots.

### ISSUE THREAD

**Issue by briandilley** [hashicorp/vagrant#10619]
The below (very simple) `Vagrant` file results in a working machine on the first `vagrant up` but any subsequent `vagrant halt` and `vagrant up` results in a non-working machine in that the networking configuration seems messed up for some reason because it's not possible to `vagrant ssh` to the machine.

### Vagrant version
    briandilley@brians-mac-pro:~/Projects/vagrant-development-box$ vagrant -v
    Vagrant 2.2.0

### Host operating system
    OSX

### Guest operating system
    Linux (Ubuntu trust64)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "10.0.2.31", auto_configure: true, virtualbox__intnet: true
  config.vm.network "private_network", ip: "10.0.2.32", auto_configure: true, virtualbox__intnet: true
  config.vm.network "private_network", ip: "10.0.2.33", auto_configure: true, virtualbox__intnet: true

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = 6144
     vb.cpus = 2
  end

end
```

### Debug Output
Available at this gist: https://gist.github.com/briandilley/29621c3f6105f397ceeb00db6deab1b2

### Expected behavior
Guest should be accessible via standard means using `vagrant ssh` whilst also having an internal only network with 3 adapters.

### Actual behavior
Host is unable to ssh into guest using `vagrant ssh` on subsequent boots (initial boot works, none else)

### Steps to reproduce
1. vagrant up
2. vagrant halt
3. vagrant up

**Comment by sakisdog** [comment]
Same issue here with ubuntu/trusty64. Problem seems to be related with VirtualBox 6. If i install virtualbox 5.2 everything works as expected. But with virtualbox 6.0.2 and 6.0.4 i have the same problem.

**Comment by briandilley** [comment]
I installed virtualbox  5.2 and still have this problem.

**Comment by briandilley** [comment]
Added a gist for the debug output: https://gist.github.com/briandilley/29621c3f6105f397ceeb00db6deab1b2

**Comment by briandilley** [comment]
Shit, accidentally closed the issue - so I've reopened it :D

**Comment by briandilley** [comment]
confirmed broken for `debian/jessie64` as well

**Comment by chrisroberts** [comment]
Hi there. I was able to get this reproduced locally and do some inspection to try and determine the underlying cause. The easiest solution to this issue is to not use the same subent as the NAT interface. So instead of creating the private network interfaces within the 10.0.2.0/24 space, putting them in, for example, the 10.0.4.0/24 space will allow things to work as expected. After reload ssh availability is still seen via the port forward as expected.

One thing that was noticed was that applying the same setup to `bento/ubuntu-18.04` didn't cause the same behavior. After a reload there were no issues reaching the guest via the port forward. It turns out that when networkd is setting up the interfaces it adds an extra entry into the routes which isn't seen in previous versions. So, on trusty64 for example, if you open the guest GUI, login and run this command:

```
sudo route add -net 10.0.2.2 netmask 255.255.255.255 metric 100 dev eth0
```

(which is what you find in ubuntu 18.04) suddenly everything works. So that is at least a workaround, but the best fix is to just move the internal network off the NAT subnet.

Cheers!

**Comment by briandilley** [comment]
@chrisroberts thanks a bunch for the help - that worked perfectly!
