### ISSUE TITLE
Request: MirOS guest plugin

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10630]
https://www.mirbsd.org/

MirOS AKA MirBSD is a fork of OpenBSD with some caveats. Vagrant can be overridden to work okay with MirOS guests with some quick configuration tweaks, which we can promote to a default guest plugin:

* `uname -a` => `MirBSD vagrant.vagrantup.com 10 Kv#10r80-20080310 GENERIC#1069 i386`
* SSH: use `mksh -l`
* `sudo_command` is `sudo -H %c`
* `build_rsync_chown`: MirOS's find utility does not support plus (`+`) syntax for -exec, and expects a terminating semicolon (`;`)
* `pkg_add` is located in /usr/mpkg/sbin. For some reason, cap_db / login.conf are unable to consistently add this directory to noninteractive PATH for use with Vagrant provisioning scripts.
* `PKG_PATH` is `https://www.mirbsd.org/MirOS/v10/Pkgs/i386`
* SSH key insertion appears to work as-is. However, MirOS appears to prefer that SSH user configuration, such as `authorized_key` modifications, be done at path `$HOME/.etc/.ssh` rather than `$HOME/.ssh`
* Finally, MirOS version "current" explicitly blocks VirtualBox from installing this operating system. Not sure why. So for VBox users at least, MirOS v10 is the last usable version.

**Comment by jbonhag** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it is a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
