### ISSUE TITLE
Vagrant global-status doesn't work with custom names

### ISSUE THREAD

**Issue by Cerv1** [hashicorp/vagrant#10632]
### Vagrant version
Vagrant 2.2.3

### Host operating system
Ubuntu 18.04.1 LTS

### Guest operating system
Any

### Vagrantfile
```ruby
  config.vm.define "#{name}" do |manager|
    manager.vm.box = "#{os}"
    manager.vm.hostname = "#{name}"
    manager.vm.network "private_network", ip: "#{ip}"

    manager.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 4
    end

    manager.vm.provision "file",
      source: "../../../some/file",
      destination: ".file"

    manager.vm.provision "shell",
      path: "#{prov_script}",
      args: ["", "", "#{branch}"]
  end
```

Where `name` is a local variable given as a parameter to vagrant using `getoptlong`. 

When I run `vagrant status` I only see the folowing output:

```
$ vagrant status
Current machine states:

manager                   not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```
But if I use `vagrant --name=<name> status` where name is a created VM I see the following:
```
$ vagrant --name=test status
Current machine states:

test                    poweroff (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```
Is there any way to list **all** the *"custom"* machines without specifying the `--name` parameter?

Thanks in advance,
Cerv1.

**Comment by briancain** [comment]
Hello @Cerv1 - There is no officially supported `--name` flag in Vagrant, and since it looks like you gave a partial Vagrantfile, I'm assuming there is probably a function inside your Vagrantfile trying to parse the `--name` flag to assign the name of a guest on the fly. If you run `vagrant status` with two different guest names that replace the name for a single config block, essentially what Vagrant sees is two separate guests and Vagrantfiles:

```ruby
Vagrant.configure("2") do |config|
# name == manager (default??)
  config.vm.define "manager" do |manager|
    # config stuff
  end
end
```

```ruby
Vagrant.configure("2") do |config|
# name == "test"
  config.vm.define "test" do |manager|
    # config stuff
  end
end
```

Vagrant stores this information locally as two different guests. Since the Vagrantfile only defines _one_ guest, that is why you are only seeing one guest appear with `vagrant status`. If you want two guests, then you need to define two guests. Otherwise replacing the guests name on the fly with a custom `--name` flag is kind of like erasing the previous guest with a new guest, and then the "old" guest disappears from Vagrants knowledge with the replacement name when it goes to parse your Vagrantfile.

Hopefully that makes sense...thanks!
