### ISSUE TITLE
Timeout waiting for machine to boot when using Virtualbox 6's Hyper-V support

### ISSUE THREAD

**Issue by edmorley** [hashicorp/vagrant#10660]
### Vagrant version
Vagrant 2.2.3

### Host operating system
Windows 10 Pro x64 (1809)

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_version = "201812.27.0"
end
```

### Debug output
https://gist.github.com/edmorley/ccf04d36686093b6947f068e94232c58

### Expected behavior
Vagrant up to succeed, or else if Vagrant is not expected to work with Virtualbox 6 with its new Hyper-V support, then for a warning to be issued rather than the several minute long SSH connection timeout loop.

### Actual behavior
Vagrant up fails to complete, giving this error after several minutes of waiting at the `SSH auth method: private key` line...

```
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. 
```

Looking at task manager shows several `VBoxHeadless.exe` processes left behind, using 0% CPU.

Until these stray `VBoxHeadless.exe` processes are killed:
* The virtualbox management UI hangs when trying to interact with the newly created VM (eg to view its config).
* Running `vagrant destroy -f` hangs.

I also tried the `bento/ubuntu-18.04` and `bento/ubuntu-16.04-i386` images, however the issue still occurs.

### Steps to reproduce
1. Enable Hyper-V on Windows 10 (all checkboxes ticked under the "Hyper-V" section in the "Turn windows features on and off" panel)
2. Install Virtualbox 6.0.4 (which has support for Hyper-V) and Vagrant 2.2.3
3. `vagrant init --box-version 201812.27.0 bento/ubuntu-16.04`
4. `vagrant up`

### References
Possibly related to these?
- https://forums.virtualbox.org/viewtopic.php?f=6&t=90853&start=45#p439467
- https://www.virtualbox.org/ticket/18387

**Comment by briancain** [comment]
Hey there @edmorley - This looks to be an experimental feature of Virtualbox 6.0:

https://blogs.oracle.com/virtualization/oracle-vm-virtualbox-60-now-available

> Improved Integration with Microsoft Hyper-V: Oracle VM VirtualBox can now be used on a Windows host where Hyper-V is running. No configuration is required. Oracle VM VirtualBox detects Hyper-V automatically and uses Hyper-V as the virtualization engine for the host. This is an experimental feature.

My guest also seems to be stuck, but I know both work fine on their own when they are used separately. Especially after reading the forum post, it seems like this is just an issue with VirtualBox. I recommend using only one or the other instead of having both enabled, as the feature might still have some issues being worked out. Thanks!

**Comment by lmcdougald** [comment]
There's still an issue here, though -- Vagrant detection defaults to Virtualbox if it's installed, even if Hyper-V is enabled and active. That isn't good behavior until Virtualbox "just works" on Windows Hypervisor Platform.

**Comment by briancain** [comment]
@lmcdougald - prior to this change in VirtualBox 6, Hyper-V and VirtualBox were not compatible and Windows would bluescreen, so you wouldn't have had these two together in the first place and still would of had to have been explicit about what provider you wanted by only having one of them installed. Because this feature is still experimental on VirtualBox side, that is still true today then if you want to use one of these hypervisors. I haven't found anything yet, but unless VirtualBox exposes a way for us to control where VMs are created, either inside of Hyper-V or VirtualBox, there's not much Vagrant can do right now with this issue.

If you need to be explicit in using the Hyper-V provider over VirtualBox, you can always either set the option per guest in your Vagrantfile, or set the environment variable: https://www.vagrantup.com/docs/providers/default.html

**Comment by lmcdougald** [comment]
To control where VMs are created? VirtualBox creates VMs within VirtualBox and those VMs will never appear in the Hyper-V management tools nor use Hyper-V networking, etc. It's just a question of whether it gets direct access to the VT processor extensions (e.g. pre-6.x behavior) or has to use an API (WHP: Windows Hypervisor Platform) to get them.

I think it makes sense for Vagrant to use its detection abilities to make the best choice given available information. Specifically, if Hyper-V is enabled, Vagrant should set the environment variable automatically during installation on Windows until such time as the VirtualBox WHP support hits stable. 

Based on how long QEMU took, it could easily take VirtualBox a year to reach stable, and, barring work on the Hyper-V provider's networking support, it is reasonable to assume most users who have Hyper-V enabled want the Hyper-V provider to be used. This solution would still allow users to easily override and use whatever provider they want.

**Comment by briancain** [comment]
> it is reasonable to assume most users who have Hyper-V enabled want the Hyper-V provider to be used. This solution would still allow users to easily override and use whatever provider they want.

If they want to use Hyper-V, I've already mentioned how they can tell Vagrant to do this today:

```ruby
config.vm.provider :hyperv
```

Or set the environment variable to set the 'default' provider:

```
VAGRANT_DEFAULT_PROVIDER="hyperv"
```

Vagrant _does_ have a list of default providers to try if none are specified, but this is not what the issue is talking about here. This issue is specifically about users explicitly requesting to use _VirtualBox_, but VirtualBox deciding to use Hyper-V as a backend when both are installed and enabled. If users want to use Hyper-V, they have ways of telling Vagrant to do so. Please re-read the Oracle release notes:

> Oracle VM VirtualBox detects Hyper-V automatically and uses Hyper-V as the virtualization engine for the host.

**Comment by lmcdougald** [comment]
If Vagrant is used on a system with Hyper-V enabled and VirtualBox 6.0 installed, Vagrant will attempt to use VirtualBox instead of Hyper-V. 

Until VirtualBox stabilizes its WHP-based backend (and yes, this is the correct name for it), there is no reason to use VirtualBox by default in that scenario. This current default behavior should be avoided in this specific circumstance to create the best out-of-the-box scenario and prevent user frustration. 

If you think that's outside of the scope of this issue, I'll happily create another issue.
