### ISSUE TITLE
The executable 'vmrun' Vagrant is trying to run was not found in the PATH variable. This is an error. Please verify this software is installed and on the path.

### ISSUE THREAD

**Issue by Fashaun** [hashicorp/vagrant#10716]
### Vagrant version - Vagrant 2.2.3
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
This is the operating system that you run locally. 

mac os 

### Guest operating system
This is the operating system you run in the virtual machine.
aws linux

### Vagrantfile
- no changes 

### Expected behavior
What should have happened?
- Package vm to box file
### Actual behavior
What actually happened?
- Show error message

### Steps to reproduce
1. Install vagrant plugin vagrant-package-vmware
2. package vmware box

**Comment by briancain** [comment]
Hey there @Fashaun - The plugin `vagrant-package-vmware` is not actually an officially supported plugin, and therefore this is not the right place to report issues for that. If you have a debug gist showing what actually went wrong we might be able to help but it seems like it's probably that plugin rather than vagrant itself. It should also be noted that if you're running the actual official vmware plugin, it already has the package feature built in.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
