### ISSUE TITLE
add support for shell :reboot to linux guests

### ISSUE THREAD

**Issue by rgl** [hashicorp/vagrant#10753]
it would really nice to have support for shell :reboot on linux based guests like we can do with windows guests:

```ruby
config.vm.provision :shell, inline: "echo 'Rebooting...'", reboot: true
```

without this, we still have to use the vagrant-reload plugin as:

```ruby
config.vm.provision :reload
```

**Comment by secret104278** [comment]
I recently write this plugin to implement linux reboot guest capability https://github.com/secret104278/vagrant_reboot_linux/tree/master

It takes official windows reboot capability as reference.
However, there is a known issue that `/vagrant` is not mounted after reboot.

Is there any suggestion to improve this plugin or add it into official repo?

**Comment by briancain** [comment]
Hi @secret104278 - Ideally the linux guest cap version would be a generic "linux" capability that would work in _most cases_. But in reality we will probably also have to add guest specific caps for distros that don't fit the generic "mold" and need more platform specific shutdown commands. Like for example your guest plugin assumes systemd, where as not all linux guests support that. I haven't looked into exactly how we'd probably implement this in Vagrant core, but I imagine it will look almost identical to the [windows reboot capability](https://github.com/hashicorp/vagrant/blob/master/plugins/guests/windows/cap/reboot.rb) but instead of executing powershell scripts, we would probably do something else.

**Comment by tianyuanhao** [comment]
@secret104278 Maybe you could mount `/vagrant` again after reboot. Take a look at  [mount_virtualbox_shared_folder.rb](https://github.com/hashicorp/vagrant/blob/85acf0cac724ef4bfda593a66e0c17f7e4110da0/plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb).
