### ISSUE TITLE
Vagrant Cloud box downloads often stall

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10757]
Hi, I am a huge fan of Vagrant! I'm getting a lot of utility out of this system, and am thankful for the graciously libris Vagrant Cloud hosting that helps developers share their images!

I do want to point out one issue I've noticed with Vagrant Cloud: Box downloads often stall at 0 bytes / second, and I'm not sure why. Like, doing `vagrant up && vagrant ssh -c 'cd /vagrant && make` && vagrant halt` for several dozen guest platforms, gets stuck halfway through with these random download stalls.

As a workaround, I copy the name of the box that is failing to download, manually `vagrant box add`..., and rerun my scripts until all the box images have successfully downloaded. Not the most fun way to work, when download sizes are measured in GiB.

I'm using the latest stable Vagrant v2.2.4, but I have noticed this problem happening for several earlier versions as well.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
