### ISSUE TITLE
Vagrant doesn't build on Solaris systems because of bcrypt_pbkdf

### ISSUE THREAD

**Issue by PanProminic** [hashicorp/vagrant#10773]
### Vagrant version
source code 2.4.4

### Host operating system
Solaris like systems, we have OmniOS CE 

### The error:
bundle install failed when installing bcrypt_pbkdf

The following command caused the error:
gcc -I. -I/opt/ooce/ruby-2.5/include/ruby-2.5.0/amd64-solaris2.11
-I/opt/ooce/ruby-2.5/include/ruby-2.5.0/ruby/backward
-I/opt/ooce/ruby-2.5/include/ruby-2.5.0 -I. -D_XOPEN_SOURCE=700   -fPIC
-I/usr/include/gmp -m64 -o bcrypt_pbkdf.o -c bcrypt_pbkdf.c
make: Fatal error: Command failed for target `bcrypt_pbkdf.o'

make failed, exit code 1

Gem files will remain installed in
/opt/ooce/ruby-2.5/lib/ruby/gems/2.5.0/gems/bcrypt_pbkdf-1.0.0 for inspection.
Results logged to
/opt/ooce/ruby-2.5/lib/ruby/gems/2.5.0/extensions/amd64-solaris-2.11/2.5.0-static/bcrypt_pbkdf-1.0.0/gem_make.out

An error occurred while installing bcrypt_pbkdf (1.0.0), and Bundler
cannot continue.
Make sure that `gem install bcrypt_pbkdf -v '1.0.0' --source
'https://rubygems.org/'` succeeds before bundling.

### Possible fix:
It is because bcrypt_pbkdf failed to build on all Solaris systems. 
the source code will build if we change bcrypt_pbkdf version to **1.0.1rc1** in **vagrant.gemspec**

**Comment by chrisroberts** [comment]
I had initially thought about just removing the dependencies from the gemspec and explicitly installing the gems when building the Vagrant packages which would allow them to be opt-in. However, the dependency really should remain in the gemspec so things work as expected when using Vagrant outside of the installers. 

Since this is fixed in net-ssh/bcrypt_pbkdf-ruby#3 I'm going to just mark this as upstream, being fixed once the next version is released.

**Comment by soapy1** [comment]
resolved by https://github.com/hashicorp/vagrant/pull/12216
