### ISSUE TITLE
Enhancement: Allow one to specify 100% of the processors of the host in Vagrantfile

### ISSUE THREAD

**Issue by marcosdiez** [hashicorp/vagrant#10781]
Sometimes we use emulation just because we want to test a different OS or some OS configuration.

In this case, we are not testing performance and hence want as much as our host system can afford.

Therefore, on `Vagrantfile`, in the CPU settings, there should be an option to use all the CPUs in the current machine.

That means no matter if I am in a small machine or the biggest one I can afford, the emulated one would have as much cpu as possible

**Comment by briancain** [comment]
Hey there @marcosdiez - Thanks for opening an issue!

I don't think something like this should belong in Vagrant. Mostly because assigning a virtual machine with all the available cores in my experience actually gives worse performance to both the VM and the host machine running your hypervisor. If your guest and host are fighting for resources, both machines will end up pretty slow.

If you really still want to do this, or at least configure it so that it is a certain fraction of the total number of CPUs, you can write a ruby script in your Vagrantfile to determine the number of cpus and go from there:

```ruby
def total_cpus
  require 'etc'
  Etc.nprocessors
end

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |v|
    v.cpus = total_cpus - 2
  end
end
```

I haven't tested that :point_up: , but you get the idea. Also how you assign the total cpus depends on what provider you are using.

Thanks!
