### ISSUE TITLE
VBoxManage: error: Failed to load unit 'lsilogicscsi'

### ISSUE THREAD

**Issue by utkonos** [hashicorp/vagrant#10780]
**Version:** Vagrant 2.2.4
**Provider:** VirtualBox 6.0.4 r128413
**Host:** macOS 10.14.4
**Guest:** ubuntu/cosmic64 v20190404.0.0

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/cosmic64"
  config.vm.provision :shell, path: "bootstrap.sh"
end
```

### bootstrap.sh
```
#!/usr/bin/env bash
echo "success"
```

### Debug output
https://gist.github.com/utkonos/02307b22f9847ba952e7dbb8bf7056da

### Expected behavior
VM snapshot should pop off the stack.

### Actual behavior
Fails with error:
`VBoxManage: error: Failed to load unit 'lsilogicscsi' (VERR_SSM_LOADED_TOO_LITTLE)`
An identical error occurs when running `vagrant snapshot restore`

### Steps to reproduce
```
$ vagrant up --no-provision
$ vagrant snapshot push
$ vagrant provision
$ vagrant snapshot pop
```

**Comment by briancain** [comment]
Hey there @utkonos - This to me looks like a virtualbox bug. Did you happen to upgrade VirtualBox after taking that snapshot at all? I recommend reading this thread, it seemed to have the solution:

https://forums.virtualbox.org/viewtopic.php?f=3&t=91192

And here's the virtualbox ticket:

https://www.virtualbox.org/ticket/18263

I _think_ there's a patched version of VirtualBox out too according to that ticket, but it looks to just be a "testbuild" instead of in an official release yet. Hopefully that fixes your issue!

Thanks!

**Comment by stanislaw** [comment]
This sometimes starts happening to my VM as well: I am doing a `vagrant up` command and seeing this message.

My current solution: `vagrant reload` reloads the machine and the error goes away.

**Comment by ttibensky** [comment]
@stanislaw thank you. your comment made me realise that I killed my VM in a non-proper way and than it wasn't able to start again. `vagrant reload` discards previous state and spins up the VM successfully

**Comment by cblicous** [comment]
Thanks with the vagrant reload, that helped me too
