### ISSUE TITLE
Setting synced directory to `/home/vagrant` results in ssh permission error

### ISSUE THREAD

**Issue by hito** [hashicorp/vagrant#10818]
**Vagrant 2.2.4**

I can see issues for this dating back to 2014.

```
VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 2.2.4'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/bionic64'
  config.vm.synced_folder './..', '/home/vagrant'

  # provision the machine with a shell script
  config.vm.provision 'shell', path: './../_shared/provision.sh'
end
```

Error:

```
$ vagrant ssh
vagrant@127.0.0.1: Permission denied (publickey).
```

**Comment by briancain** [comment]
Hello @hito - This makes sense, considering what you are doing when you overwrite your home directory. Vagrant places its key in the `known_hosts` file, which allows it to ssh into the guest. When you configure the guest to have a synced folder at `/home/vagrant`, it overwrites the entire folder with the contents of your synced folder. You could get around this by saving the `known_hosts` file in your source dir so that it still ends up in place. Or you could sync your files elsewhere so that you don't delete your home directory. Thanks for reporting the issue!

**Comment by hito** [comment]
I'm very silly sometimes, I was thinking of `~/.vagrant.d` only on the host. Sorry about that.
