### ISSUE TITLE
nested-hw-virt

### ISSUE THREAD

**Issue by husxwy** [hashicorp/vagrant#10825]
### Vagrant version
Vagrant 2.2.3

virtualbox 6.0.4
```
config.vm.provider "virtualbox" do |v|
v.memory = 1024
v.cpus = 1
v.nested-hw-virt = on
```

```
error message 
Path: <provider config: virtualbox>
Line number: 51
Message: NameError: undefined local variable or method `hw' for main:Object
```

can use the param nested-hw-virt  ?
how to  use for the param have '-' like?

**Comment by briancain** [comment]
Hi @husxwy - The variable you are using doesn't exist for the virtualbox provider, so that's why you are getting that error message.

I think you are actually looking for something like this:

```
config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
end
```

However I am pretty sure this feature only works if you have an AMD processor. Anyway, that is the option you are looking for!
