### ISSUE TITLE
Feature Request: Manage a guest from multiple hosts

### ISSUE THREAD

**Issue by lioramilbaum** [hashicorp/vagrant#10874]
As a user, I would like to be able to manage a guest machine from multiple hosts.  It is only applies for guests which are hosts in a public cloud, like AWS.

I want to spin a guest from one host and to be able to ssh or destroy from another host.

**Comment by SHANTH2013** [comment]
Manage a guest from multiple hosts is true if the user have permissions to do so from console. However user as Guest machine can manage other machines based on the roles and policy applied from IAM.

**Comment by lioramilbaum** [comment]
@SHANTH2013  I am not following

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
