### ISSUE TITLE
"Reset is not implemented for this connection" error using reset_connection

### ISSUE THREAD

**Issue by dms-cat** [hashicorp/vagrant#10871]
### Vagrant version
2.2.4

### Host operating system
Arch Linux

### Guest operating system
Ubuntu 18.04

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|
  config.vm.provision 'ansible_local' do |ansible|
    ansible.playbook = 'setup-development-vm.yml'
    ansible.compatibility_mode = '2.0'
  end
end
```

### Expected behavior
The connection should be reset

### Actual behavior
Ansible prints

> [WARNING]: Reset is not implemented for this connection

and doesn't reset the connection.

### Steps to reproduce
1. Use `ansible_local` to configure the instance
2. Use `reset_connection` anywhere within the Ansible files

This makes it clunky to do anything with new groups assigned to the ansible user, because the commands all have to be wrapped in `sg - docker -c "…"`.

**Comment by binary-manu** [comment]
This doesn't seem a problem with Vagrant, or even with Ansible itself.

Probably, what happens is that, since you are using the `ansible_local` provisioner, it uses the `local` Ansible connection plugin, therefore there is no real connection to reset. For Ansible to be able to spawn processes with the user belonging to the new group, it should inherit those settings from a parent process, since group information is usually loaded once at login time.

You may try splitting the provisioning process into two parts:

1. add the `vagrant` user to the extra groups using a provisioner
2. do a `vagrant reload`
3. do the rest using a second provisioner

I don't know if this can be done from the Vagrantfile itself, but it should be easy be automate using a simply shell script that calls `vagrant provision --provision-with step1|step2`.

Good luck.

**Comment by dms-cat** [comment]
Thanks @binary-manu, I was able to use two `config.vm.provision 'ansible_local'` sections to achieve this.
