### ISSUE TITLE
mount_options for hyperv.

### ISSUE THREAD

**Issue by benlumia007** [hashicorp/vagrant#10886]
does mount_options work for hyperv and i can't seem to figure out how.... dmode/fmode doesn't work. dir_mode and file_mode either. what exactly is the correct to use mount_options.

**Comment by briancain** [comment]
@benlumia007 - I believe most Hyper-V vms end up using SMB, so you would need to use the proper mount_options associated with that kind of synced_folder: https://www.vagrantup.com/docs/synced-folders/smb.html

That option is very dependent on what kind of synced_folder your guest is. Without seeing a Vagrantfile and or a log with debug output it's very difficult for us to help you. If your vm doesn't end up being SMB, you should look to see how it's syncing your folders so that you can refer to the docs on what you should be using. Thanks!

**Comment by benlumia007** [comment]
@briancain 

I know that Hyper-V uses SMB which is fine, but being able to change the permission is not doable, I have looked into using `mount_options => [ "dmode=775", "fmode=774" ]`, apparently, i also tried file_mode and dir_mode and it doesn't work. 

the reason why i asked is because,  without changing the permissions, certain things I'm trying to do, won't work especially wp-cli for WordPress.

**Comment by benlumia007** [comment]
can i get an answer to this, even if the issue is closed?

**Comment by briancain** [comment]
@benlumia007 - you should be able to change the owner and group of the folder with the existing options: https://www.vagrantup.com/docs/synced-folders/basic_usage.html#group and https://www.vagrantup.com/docs/synced-folders/basic_usage.html#owner

As far as permissions with SMB, I recommend reading this comment: https://github.com/hashicorp/vagrant/issues/8522#issuecomment-458568014

Otherwise, it looks like you should actually be using `file_mode` and `dir_mode`: https://wiki.ubuntu.com/MountWindowsSharesPermanently

Vagrant simply passes those mount options along to the tool its using to sync folders, so I recommend reading up on SMB to figure out how to use it.

**Comment by benlumia007** [comment]
@briancain 

thanks for the help, so i found out that i had it right, with the dir_mode and file_mode, the only differnce, it was working, but the permission were wrong,  so by adding  0 before 775/774, works so i guess that the 0 makes a difference from what I can tell.
