### ISSUE TITLE
`__connect_nonblock': Operation already in progress - connect(2) for 127.0.0.1:2222 (Errno::EALREADY)

### ISSUE THREAD

**Issue by 5730447921-PW** [hashicorp/vagrant#10893]
### Vagrant version
Vagrant 2.2.4

### Host operating system
Windows 10 Version 1903 using WSL Ubuntu 18.04.2 LTS

### Guest operating system
CentOS 7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end

```

### Debug output
https://1drv.ms/u/s!AlVGhO4ejWrWk0JG-w6RAVACEhQq

### Expected behavior
Guest machine starts successfully.

### Actual behavior
Created guest machine is forced shutdown and destroyed.
/opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:1198:in `__connect_nonblock': Operation already in progress - connect(2) for 127.0.0.1:2222 (Errno::EALREADY)

### Steps to reproduce
1. vagrant up

**Comment by briancain** [comment]
Hi @5730447921-PW - Does this happen every time you bring up a guest? Do you have any other machines or instances of Vagrant running? Have you tried running Vagrant outside of WSL, like in Powershell?

**Comment by 5730447921-PW** [comment]
Does this happen every time you bring up a guest?
- Yes.

Do you have any other machines or instances of Vagrant running?
- No.

Have you tried running Vagrant outside of WSL, like in Powershell?
- I tried running with Windows 64-bit version of Vagrant but there was different error output when vagrant tried to ssh to the guest machine. 

> Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/7' version '1902.01' is up to date...
==> default: Setting the name of the VM: SET_default_1560395951567_31314
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.<br/>
If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.<br/>
If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.<br/>
If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

Debug output
https://1drv.ms/u/s!AlVGhO4ejWrWk0iVYMNme5fhmVgK

**Comment by briancain** [comment]
@5730447921-PW - Ahh, so before you were using 32-bit version of Vagrant?

The log you posted is not actually an error! Which is good :smile: 

This is unfortunately fairly common with that box I've found. It's just that the box takes a while to boot up it seems, and so the timeout waiting for boot was exceeded. It might still be up and running just fine after the time out. You could try to extend it or log onto the machine and figure out if it has any networking. However...I typically recommend people use boxes like `generic/centos7` or `bento/centos-7` instead as they don't seem to have the same problem.

**Comment by 5730447921-PW** [comment]
> Ahh, so before you were using 32-bit version of Vagrant?

No, I meant I've been using the windows 64-bit version so I downloaded 64-bit vagrant and tried running with it. Sorry for my english.

I tried to extend the timeout value to 10 mins and tried to use a generic/centos7 box instead but the problems were still same, both in WSL and Windows.

However, I used to successfully run Vagrant using WSL before I upgraded my windows to 1903 version. I think this may cause the problems.

**Comment by briancain** [comment]
@5730447921-PW - after bringing up the box with Vagrant (and after it times out), are you able to log into the machine through the GUI? And if so does it have networking at all? Or can you ssh yourself outside of Vagrant and reach the machine that way?

**Comment by gadgetmg** [comment]
I don't care much to dig further into "why", but I was having this exact problem. Just like you, I had the latest version of Vagrant (2.2.5) with the VirtualBox provider running inside Ubuntu 18.04 via WSL on Windows 10 1903.

I had not noticed this before because I recently was exclusively using Windows boxes so I was always communicating over WinRM to the VMs. But after trying to spin up a CentOS 7 box on a whim, I discovered SSH communication was completely broken.

From WSL, the VM would boot and then Vagrant would crash with the "Operation already in progress" exception. From native Windows, it would hang indefinitely trying to connect and eventually timeout like you saw as well. The machine booted fine, but port forwarding must have silently failed as netstat confirmed nothing was listening on 2222.

This was, however, working for me previously on 1903. So I started rolling back Vagrant releases until I eventually needed to downgrade VirtualBox as well.

**As soon as I reinstalled VirtualBox 5.2.30, everything worked.** I upgraded Vagrant back to 2.2.5 and again, all was fine.

**Comment by gadgetmg** [comment]
See this post on StackOverflow: https://stackoverflow.com/questions/48478869/cannot-bind-to-some-ports-due-to-permission-denied

This is caused by some Hyper-V services "reserving" seemingly random ranges of ports. 2222 happens to be in that range so VirtualBox and Vagrant never succeed in forwarding it. Oracle, in their infinite wisdom, decided that it was not worth bothering the user with an error when the bind failed.

Specifically, the feature that I had to disable in Windows was "Hyper-V Services" under "Hyper-V" > "Hyper-V Platform". There may be other services as Hyper-V has its tentacles in a lot of Windows services nowadays. I had originally used this feature to build Hyper-V templates from VHDX files, but I can live with using another dedicated machine for that.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
