### ISSUE TITLE
suggestion:  vagrant should enforce changing password to some non default.

### ISSUE THREAD

**Issue by queglay** [hashicorp/vagrant#10900]
As a suggestion I think its not great practice to allow vagrant boxes to even start with a non default password.  its possible for people new to vagrant to have no idea that the vagrant user even has a password, and that it is a bad password.

Upon a first boot, users should be prompted to change it automatically.

**Comment by chrisroberts** [comment]
Hi there. The use of a known username and password is by design, as is the use of a known public/private key for SSH. If you would like to not persist the default username and password, there are a few options:

* Create a box with non-default credentials
* Add a provisioner to update the default credentials on first boot
* If using the SSH communicator, update the sshd_config to only allow public key authentication

Cheers!
