### ISSUE TITLE
`vagrant up`: Read hypervisor from metadata.json

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10942]
If I understand the BOX format correctly, then the list of available hypervisors is easy enough for Vagrant to query on `vagrant up`.

* If the box is already imported locally, then select a hypervisor from the `providers` key in a `metadata.json` file, if present.
* If the box is to be downloaded remotely, such as from Vagrant Cloud, then query Vagrant Cloud for the list of available providers.

Either way, the user should not have to supply `VAGRANT_DEFAULT_PROVIDER` configuration (through environment variables no less) in `Vagrantfile`'s, or worse, runtime `--provider <provider>` command line arguments on `vagrant up`, since this information is already included in the boxes.

An explicit provider hypervisor name should only be required should the user desire to override the default hypervisor for a given box name. 80% of the time, this information is machine automatable, no reason to ask for this as explicit configuration in duplicate.

Now, I have been in the habit of packing my own base boxes and I do wonder if I may have been setting those up wrong; Maybe this auto-provider logic is already implemented! Can someone with experience using Packer confirm or deny whether Packer correctly populates the hypervisors in `metadata.json` when building Vagrant box artifacts?

I would assume that if I manage three Debian guest Packer builds with three `package.json` files, for three hypervisors, then the resulting three .BOX files would each contain exactly one of these hypervisors as `provider` keys in `metadata.json`. Right?

Finally, one thing I would like to clarify, is whether Vagrant Cloud is smart enough to provide the full list of hypervisors in BOX downloads. I suspect the user will only see the hypervisor they specifically request / the default `virtualbox` provider, and see no other providers for a box of the same name. But I just don't know.

**Comment by briancain** [comment]
Hi @mcandre - users are not actually required to set the environment variable `VAGRANT_DEFAULT_PROVIDER`, nor do they have to use the flag. You can specify which provider a guest should have directly inside your Vagrantfiles guest definition:

```ruby
config.vm.define "fedora" do |c|
    c.vm.box = "generic/fedora28"
    c.vm.provider :virtualbox
end
```

As an example, this fedora guest is configured to always use VirtualBox, unless overridden by the --provider flag.

That being said, this metadata file has no notion of a "default" provider. Vagrant does technically default to VirtualBox, but it's really only for legacy reasons. I'm not sure what a default provider would be for a given Vagrant box, but that could probably be configured like with the Vagrantfile above inside the boxes archive. Then if users wanted a different box they could do so by adding their own provider config or using the `--provider` flag.

In terms of packer and metadata.json files, that likely depends on how you've set up your template. If you read the docs, for the most part the only key required in there is the provider key. Otherwise it's mostly a free for all for what structure you have. And that data is really only used when someone runs `vagrant box list -i`.

Also yes, Vagrant Cloud will give you lots of data about any given box you have access to. I recommend reading the Vagrant Cloud API docs: https://www.vagrantup.com/docs/vagrant-cloud/api.html#example-response-4

Thanks!
