### ISSUE TITLE
run_remote trigger doesn't work with openstack provider

### ISSUE THREAD

**Issue by bstillwell** [hashicorp/vagrant#10956]
### Vagrant version
Vagrant 2.2.5

### Host operating system
CentOS Linux release 7.6.1810 (Core)

### Guest operating system
CentOS Linux release 7.6.1810 (Core)

### Vagrantfile
```ruby
      node.trigger.before :destroy do |trigger|
        trigger.name = "Removing salt key"
        trigger.run_remote = { inline: "salt-call saltutil.revoke_auth" }
      end
```

### Expected behavior
The command to remove the salt key for the VM should be executed before destroying the VM.

### Actual behavior
$ vagrant status
Current machine states:

utility001             active (openstack)
cephmon001             active (openstack)
cephmon002             active (openstack)
cephmon003             active (openstack)
cephosd001             active (openstack)
cephosd002             active (openstack)
cephosd003             active (openstack)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

$ vagrant destroy cephosd002
==> cephosd002: Running action triggers before destroy ...
==> cephosd002: Running trigger: Removing salt key...
Could not run remote script on cephosd002 because its state is active

### Steps to reproduce
1. Create a trigger on destroy that uses run_remote to execute a command on a VM
2. Attempt to destroy the VM with vagrant destroy
3.

### Additional information
The bug seems to be in lib/vagrant/plugin/v2/trigger.rb which is erroring out if the state is not 'running':

          elsif @machine.state.id != :running
            if on_error == :halt
              raise Errors::TriggersGuestNotRunning,
                machine_name: @machine.name,
                state: @machine.state.id
            else
              @machine.ui.error(I18n.t("vagrant.errors.triggers_guest_not_running",
                                        machine_name: @machine.name,
                                        state: @machine.state.id))
              @machine.ui.warn(I18n.t("vagrant.trigger.on_error_continue"))
              return
            end
          end

**Comment by briancain** [comment]
Hi @bstillwell - Yes...unfortunately the vagrant openstack provider doesn't follow Vagrants way of defining guest states, and instead reads its state from the openstack API and returns whatever is given:

https://github.com/ggiamarchi/vagrant-openstack-provider/blob/30964bdc5ae0fbad90dc09d40b85ac9bf6df929a/source/lib/vagrant-openstack-provider/action/read_state.rb#L34-L38

```ruby
if !server['OS-EXT-STS:task_state'].nil?
  server['OS-EXT-STS:task_state'].downcase.to_sym
else
  server['status'].downcase.to_sym
end
```

Perhaps there's a more sustainable approach here that we can use to determine a guests state. Another approach might be making the vagrant-openstack provider have "alias" states that mirror what Vagrant defines for its guests :thinking: Otherwise we would mostly be guessing or hard coding various states for any given provider which could break the moment openstack (or any other provider) changes their API :disappointed:

**Comment by briancain** [comment]
I'm going to go ahead and close this, as I view this more as a big with how the openstack provider handles guest states and the fact that it differs from all other provider states. There's nothing we can really do in Core vagrant. It looks like an issue has already been opened to address this on the openstack provider plugin, so hopefully that gets fixed. Thanks!
