### ISSUE TITLE
No valid IDs were given to the NFS synced folder implementation to prune.

### ISSUE THREAD

**Issue by Amin01Kz** [hashicorp/vagrant#10994]
Hi, I'm using Vagrant 2.2.5 with Hyper-v on Windows 10 Pro to run laravel/homestead and whenever I try to start the vagrant with _vagrant up_ it says: 

>  No valid IDs were given to the NFS synced folder implementation to
> prune. This is an internal bug with Vagrant and an issue should be
> filed.

cmd result:
![image](https://user-images.githubusercontent.com/20126084/61963719-7fe92900-afe1-11e9-9e00-f31cc9bc5502.png)

also tried with _vagrant reload --provision_ but get the same result.
and folders that are supposed to be synced, they aren't (this is the issue!). 
also I have access to the vagrant via ssh and it works fine

my Homestead.yaml file: 
![image](https://user-images.githubusercontent.com/20126084/61963610-40bad800-afe1-11e9-9832-0dae8c6be8a5.png)

Any idea how to fix it?
Thanks in advance.

**Comment by briancain** [comment]
Hi @Amin01Kz - The homestead project is located here: https://github.com/laravel/homestead

With Vagrant, you would set a private network for your guest config:

```ruby
# inside your Vagrantfile
guest.vm.network "private_network", ip: "192.168.33.99"
guest.vm.synced_folder "source", "dest", type: "nfs"
```

Since you're not using a Vagrantfile, I can't say if Homesteads yaml config is properly setting it. If you can reproduce this using a Vagrantfile I'd be happy to reopen the issue and take a look. Thanks!
