### ISSUE TITLE
Global ~/.vagrant.d/Vagrantfile influences default provider 

### ISSUE THREAD

**Issue by externl** [hashicorp/vagrant#11028]
### Vagrant version
```bash
❯ vagrant -v
Vagrant 2.2.5
```

### Host operating system
```bash
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87
```

### Guest operating system
Any `vmware_desktop` box

### ~/.vagrant.d/Vagrantfile
This global Vagrant contains various configurations for several providers
```ruby
Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb|
        vb.customize [ "modifyvm", :id, "--uart1", "off" ]
        vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    config.vm.provider "vmware_desktop" do |v, override|
        v.linked_clone = true
    end

    config.vm.provider :aws do |aws, override|
        aws.access_key_id = "key_id"
        aws.secret_access_key = "secret_access_key"
    end
end
```

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "some-vmware–desktop-box"
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "1024"
  end
end
```

### Debug output
I can add if really necessary.

### Expected behavior
vmware_desktop should be chosen as the default provider

### Actual behavior
The first provider configured in the global Vagrantfile is chosen as the provider

```
❯ vagrant status
Current machine states:

default                   not created (virtualbox)

The environment has not yet been created. Run `vagrant up` to
create the environment. If a machine is not created, only the
default provider will be shown. So if a provider is not listed,
then the machine is not created for that environment.
```

```
DEBUG environment: Initial usable provider list: [[6, :virtualbox], [5, :aws], [10, :vmware_desktop], [10, :vmware_fusion]]
DEBUG environment: Priority sorted usable provider list: [:vmware_desktop, :vmware_fusion, :virtualbox, :aws]
DEBUG environment: Preferred provider list: []
DEBUG environment: Using provider `virtualbox` detected in configuration and usable.
 INFO environment: Getting machine: default (virtualbox)
 INFO environment: Returning cached machine: default (virtualbox)
```

### Steps to reproduce
1. Crete Vagrantfiles as described above
2. run `vagrant status`

I understand that vagrant makes this decision as `~/.vagrant.d/Vagrantfile` is has the first loaded provider config, but I wonder if it should make the default provider decision based soly on non-global Vagrantfile configuration.

**Comment by briancain** [comment]
Hi @externl ! If you wish to always have a specific default provider, Vagrant gives you an environment variable that you can use to pick your provider of choice:

https://www.vagrantup.com/docs/providers/default.html

In this case you would be able to specify `vmware_desktop` if you wanted that to always be your default. Thanks!

**Comment by externl** [comment]
@briancain I work in an environment with multiple Vagrantfiles and which multiple providers. The issue is switching back and forth. Setting an env variable is not reasonable in this.

https://www.vagrantup.com/docs/providers/basic_usage.html#default-provider

> In normal day-to-day usage, the --provider flag is not necessary since Vagrant can usually pick the right provider for you. More details on how it does this is below.

> As mentioned earlier, you typically do not need to specify --provider ever. Vagrant is smart enough about being able to detect the provider you want for a given environment.

I assume these statements also hold true for the env variables? Likewise I assume that `~/.vagrant/Vagrantfile` is for setting provider configurations as I described in my example?

In this case I think vagrant should be intelligent enough to figure out the right provider.

Also note that in my case the box *only* exists for `vmware_desktop`, not for `virtualbox`.

**Comment by briancain** [comment]
@externl - You can also be more specific about your guest and the provider its going to use. For example:

```ruby
 config.vm.define "hashicorp" do |h|
    h.vm.box = "hashicorp"
    h.vm.provider :vwmare_desktop
  end
```

The guest "hashicorp" then will default to `vmware_desktop` unless specified with the provider flag, and `vmware_desktop` will be its default.

But ultimately the issue here is that because you've configured everything with the top scope `config` option, there isn't really a priority as to which provider to pick from other than the default provider list. There's nothing wrong with doing that, but your default guest treats all of the various provider options as equal, and therefore defaults over to the default provider. So if you have a guest that should always be `vmware_desktop` I recommend defining it and configuring it to do doing what I did above.

**Comment by externl** [comment]
Thanks, @briancain, I'll try that.

**Comment by externl** [comment]
```
 config.vm.define "hashicorp" do |h|
    h.vm.box = "hashicorp"
    h.vm.provider :vwmare_desktop
  end
```

Configuring the box like this still doesn't help, probably because `virtualbox` is still being picked up first in `~/.vagrant/Vagrantfile`

**Comment by briancain** [comment]
Doing this also worked for me:

```ruby
Vagrant.configure("2") do |config|
  # ... other config up here

  # Prefer VMware Fusion before VirtualBox
  config.vm.provider "vmware_desktop"
  config.vm.provider "virtualbox"
end
```

Found in the [default provider](https://www.vagrantup.com/docs/providers/basic_usage.html#default-provider) docs.

**Comment by externl** [comment]
The issue is with having global config stuff set in `~/.vagrant.d/Vagrantfile`. Do you have stuff set in yours like I described above?

**Comment by externl** [comment]
Since the `~/.vagrant.d/Vagrantfile` is being ran before `Vagrantfile`, it seems that no matter how you configure `Vagrantfile`, it's default provider is determined by the order of any config done in `~/.vagrant.d/Vagrantfile`

**Comment by briancain** [comment]
> Since the ~/.vagrant.d/Vagrantfile is being loaded before Vagrantfile's configure block, it seems that no matter how you configure Vagrantfile, it's default provider is determined by the order of any config done in ~/.vagrant.d/Vagrantfile (the vagrantfile in the vagrant home dir)

Ah ok, so there's a couple things here:

1. The `~/.vagrant.d/Vagrantfile` is always loaded second, after the Vagrantfile inside the box is evaluated, but before any of your project files. This is important for 2... ->
2. When Vagrant is determining what provider to use, it has a default list of providers, but it picks up the configuration you have supplied in your global config and sees VirtualBox is defined first, and usable, thus making it the provider to use. However...
3. This behavior exists with any Vagrantfile as well, not just with the globally defined one. If you place that same block at the very top of your projects Vagrantfile and the VirtualBox provider is usable, the guest machines become VirtualBox guests unless specified with a flag or environment variable.

Maybe we need to make the docs clearer. I believe the default provider list is used if there aren't specific configuration options that exist and influence how a guest is configured. The default provider list _does_ work as expected when determining a provider to use, but if there are existing configurations that tell Vagrant what to use, it uses that. But, if your Vagrantfile has no `config.vm.provider` config options, it defaults to the internal default list.

That being said, the flag option to specify a provider is still available to use, as well as the environment variable:

https://www.vagrantup.com/docs/providers/default.html

We could potentially add a switch or new config option that locks a guest to a specific provider:

```ruby
guest.vm.required_provider :vmware_desktop
```

Or something like that. But to get things going immediately, your best bet is to rely on the provider flag or use the default provider environment variable since that feature will require some development work plus a release. If that makes sense, I'd say we could open a new enhancement request.
