### ISSUE TITLE
Sound gets awkward while wearing Bluetooth Headset on MacOS

### ISSUE THREAD

**Issue by Sironheart** [hashicorp/vagrant#11046]
### Vagrant version
Vagrant 2.2.5

### Host operating system
MacOS

### Expected behavior
Everything should stay as it is before the start of the VM

### Actual behavior
As soon as I start a virtualbox and I wear bluetooth headsets the sound gets really awkward and the microphone turns on. After a few seconds everything gets back to normal. This is currently fixable by adding the following to the provider part of the Vagrantfile, but I think this should be the default behavior, if possible.

Fix for Vagrantfile:
```
machine.vm.provider "virtualbox" do |vbox|
  ...
  vbox.customize ["modifyvm", :id, "--audio", "none"]
  ...
end
```

### Steps to reproduce
1. Create a virtualbox Machine, while wearing bluetooth headset.
2. Start VM without the fix
3. Listen to music or something via headset. The sound should get awkward.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- (Kitchen-Vagrant Issue)[https://github.com/test-kitchen/kitchen-vagrant/issues/388]

**Comment by briancain** [comment]
Hi there @Sironheart - This is actually a result of how the box is packaged, not something Vagrant is setting. You can get more context on this issue here: https://github.com/hashicorp/vagrant/issues/10430. The fix you have is correct. If you don't wish to use that customize command, you could repackage the Vagrant box with that customize command, or make a request to the box owner to do the same thing. You could also make it a global option for all virtualbox guests if you set it with the `config` option like `config.vm.provider "virtualbox"...` some where inside your Vagrantfile.

Sorry for the trouble!
