### ISSUE TITLE
student@127.0.0.1: Permission denied (publickey).

### ISSUE THREAD

**Issue by YousefSaber** [hashicorp/vagrant#11086]
I’m using Ubuntu 19.04 OS as my main host machine and Ubuntu 18.04 LTS as guest machine installing it using vagrant as shown in this course anyway
using vagrant v2.2.5

when I try to log into the created user as shown in the video steps it gives me this error from my host machine

```
joseph@joseph-X541UJ:~/Desktop/Ubuntu 18.04$ ssh student@127.0.0.1 -p 2222
student@127.0.0.1: Permission denied (publickey).
```
I’ve created a student user with a password on my quest machine how do I fix this problem please

```
vagrant@ubuntu-bionic:~$ finger student
Login: student Name: Learner
Directory: /home/student Shell: /bin/bash
Never logged in.
No mail.
No Plan.
```

**Comment by briancain** [comment]
Hey there @YousefSaber - Vagrant configures ssh to use private key auth rather than a password by default. When you run ssh with a different user you created in the guest, it's very likely it's using the same ssh config and also is expecting a private key rather than a password for authentication. You can either update your ssh config to not expect a private key, or add Vagrants insecure public key into your new users `~/.ssh/known_hosts` file so that it can accept the corresponding private key as an authentication method. Thanks! If you need more help I recommend messaging the Vagrant Up google mailing list for user support.
