### ISSUE TITLE
Network unrelated commands hang when proxy not configured

### ISSUE THREAD

**Issue by rbuquet** [hashicorp/vagrant#11082]
### Vagrant version
2.2.5

### Host operating system
Windows 10 Pro Version 1803

### Debug output
I'll provide a full debug in a Gist as soon as possible. Meanwhile here is what I noticed:

`vagrant help --debug` shows that it's hanging on
```
DEBUG checkpoint_client: waiting for checkpoint to complete...
```
and on
```
INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000004b32910>
```
### Expected behavior
Output help message without hanging.
Commands like `help` should be completely offline and independent of network quality / configuration.

### Actual behavior
`vagrant help` took more than 30 seconds to execute

I noticed that if I disconnect from the network (airplane mode, ethernet cable unplugged), it gets a lot better (5s), and even better if I configure properly the proxy (2s).
```
$env:HTTP_PROXY="http://my.proxy.host:port"
$env:HTTPS_PROXY="http://my.proxy.host:port"
```
Once I configured the proxy and had a normal execution, commands will not hang anymore, even if I "unconfigure" the proxy.
But it will eventually hang again less than a week after.

My guess is that vagrant will try to fetch its last available version on every command.
Once it had the info, it will wait for some time (a day?) before asking again.

### Steps to reproduce
1. vagrant help

### References
https://stackoverflow.com/questions/57997292/vagrant-cli-hangs-on-windows-10

**Comment by chrisroberts** [comment]
Hi there. 

Yes, this is vagrant checking for any new releases to provide notification. Once it has successfully received information, it will used the cached result for awhile until it tries again (which is why you no longer experience the lag after it can connect).

You can disable the check by setting the `VAGRANT_CHECKPOINT_DISABLE` environment variable (https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_checkpoint_disable).

Cheers!
