### ISSUE TITLE
Support for PowerShell 6 on WSL

### ISSUE THREAD

**Issue by lcy0321** [hashicorp/vagrant#11085]
### Vagrant version
2.2.5

### Host operating system
WSL on Windows 10

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior
Working normally

### Actual behavior
```
Vagrant failed to initialize at a very early stage:

Failed to locate the powershell executable on the available PATH. Please
ensure powershell is installed and available on the local PATH, then
run the command again.
```

### Steps to reproduce
Run `vagrant up` on WSL on Windows 10 that has only PowerShell 6 on PATH.

### References
[What's New in PowerShell Core 6.0 | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6#renamed-powershellexe-to-pwshexe)

---

PowerShell 6 has changed its executable location from `/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe` to `/mnt/c/Program Files/PowerShell/6/pwsh.exe` 

I modified `util/powershell.rb`, change
```ruby
@_powershell_executable = "powershell"
```
to
```ruby
@_powershell_executable = "pwsh"
```
and it seems work.

**Comment by yeszman** [comment]
Fixed this by adding "%SYSTEMROOT%\System32\WindowsPowerShell\v1.0" to the environment PATH

**Comment by very-random-man** [comment]
I had this issue also on WSL2 but the problem seemed to be that it was looking for `powershell` rather than `powershell.exe`. I set up a symlink and this step worked. 

```
$ sudo ln -s /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe /usr/local/bin/powershell
$ which powershell
/usr/local/bin/powershell
```

Now i just get ACL errors as PowerShell can't find the WSL2 directory so I get the impression this is a bit of a non-starter. ;-)

**Comment by muddman** [comment]
I had the same issue and it turned out I had mountd /mnt/c with the incorrect permissions when I was trying to fix a permissions issue while running test-kitchen that required metadata (that'll teach me to copy/paste commands off the internet).  I fixed it with the following:

```
sudo umount /mnt/c
sudo mount -t drvfs C: /mnt/c -o metadata,umask=22,fmask=11
```

You can also [set the defaults ](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)in `/etc/wsl.conf`:
```
# Enable extra metadata options by default
[automount]
enabled = true
root = /mnt/
options = "metadata,umask=22,fmask=11"
mountFsTab = false
```

I needed to exit and run `wsl -t Ubuntu-18.04` before the settings were updated.
