### ISSUE TITLE
Windows 10 vagrant is spending time in powershell doing something before actually doing anything useful

### ISSUE THREAD

**Issue by kozmaz87** [hashicorp/vagrant#11160]
### Vagrant version
PS C:\Users\Ubul> vagrant -v
Vagrant 2.2.6

### Host operating system
Windows 10

### Guest operating system
N/A

### Output
```ruby
PS C:\Users\Ubul> Measure-Command {C:\HashiCorp\Vagrant\bin\vagrant.exe status}
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 9
Milliseconds      : 750
Ticks             : 97501033
TotalDays         : 0.000112848417824074
TotalHours        : 0.00270836202777778
TotalMinutes      : 0.162501721666667
TotalSeconds      : 9.7501033
TotalMilliseconds : 9750.1033
```

### Expected behavior
immediate response with the help page

### Actual behavior
10 seconds just to get a help message

### Steps to reproduce
1. type vagrant

On inspection it seems that vagrant is launching the ruby interpreter which keeps idling while the CPU is spending 100% in Powershell for seconds until vagrant finally executes. Same behaviour was observed during installation. It took forever to copy files.... Nothing else is slow on this machine. It has an NVME SSD and performs well otherwise.

**Comment by chrisroberts** [comment]
Hi there. I believe the underlying cause of the issue is Vagrant running a version check on powershell to ensure it is supported. Would you please provide a gist with the output from:

```
VAGRANT_LOG=debug VAGRANT_LOG_TIMESTAMP=1 vagrant
```

Thanks!

**Comment by gjabouley-invn** [comment]
Hello

Although Vagrant commands are then performing just fine, it is quite annoying to wait 15 seconds for each Vagrant command :wink:

Gist: https://gist.github.com/gjabouley-invn/2e7f4cae13301d8c79f405cad36e196a
Windows 10 1809
VirtualBox 6.0.14
Vagrant 2.2.6

**Comment by gjabouley-invn** [comment]
Hello
any update on this issue?
I just upgraded to 2.2.7 but slowness are still there, making it a bit painful to use Vagrant daily on Windows 😢

**Comment by jbonhag** [comment]
Hello,

Thanks for sending a copy of the debug log. Vagrant usually takes a second or two to load, and some of that time is spent running PowerShell commands to check the local environment. However, the debug log indicates that PowerShell is taking up to 5 seconds to run certain commands, which is definitely unusual.

Would you mind running the following command in PowerShell (outside of Vagrant) to see how long it takes?

```
C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0/powershell.EXE -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command $x = (Get-VMHost).Name; if($x -eq [System.Net.Dns]::GetHostName()){ Write-Output 'true'}
```

Thanks very much!

**Comment by gjabouley-invn** [comment]
@jbonhag sure, overall duration is around 4 seconds

```
start=11:15:46.29
Get-VMHost : The term 'Get-VMHost' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:7
+ $x = (Get-VMHost).Name; if($x -eq [System.Net.Dns]::GetHostName()){ W ...
+       ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-VMHost:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

end=11:15:50.42
```

I don't have HyperV feature enabled:
![image](https://user-images.githubusercontent.com/47566129/79321169-3cd23b80-7f0b-11ea-9d56-ee440bc25d9b.png)

**Comment by jbonhag** [comment]
Hi,

The slowness that is being reported in this issue is most likely an issue with PowerShell and not with Vagrant. Unfortunately, Vagrant needs to run these commands in order to collect information about the host environment, so if PowerShell is being slow that will also make Vagrant seem slow. 

If you're using VirtualBox, you may see faster startup times if you explicitly specify the VM provider. You can specify the provider either by setting the environment variable `VAGRANT_DEFAULT_PROVIDER=virtualbox` or running `vagrant up --provider virtualbox`.

Lastly, there is a tool called [Ngen.exe](https://docs.microsoft.com/en-us/dotnet/framework/tools/ngen-exe-native-image-generator) that might help improve PowerShell's startup time. Here are a couple of resources that may be useful:

* [Speeding Up PowerShell Startup – Updating Update-Gac.ps1](https://devblogs.microsoft.com/powershell/speeding-up-powershell-startup-updating-update-gac-ps1/)
* [Calling powershell.exe is extremely slow](https://serverfault.com/questions/761301/calling-powershell-exe-is-extremely-slow)

If you see any performance improvements after using Ngen, we'd love to hear about them.

Cheers! :smile:

**Comment by gjabouley-invn** [comment]
Hello
i can confirm than setting `VAGRANT_DEFAULT_PROVIDER=virtualbox` is helping, making commands few seconds faster. Great!
Not sure i'll be able to try out Ngen.exe, if yes then i'll post some feeback.

**Comment by jbonhag** [comment]
Glad to hear it! Thanks for the report. 😄
