### ISSUE TITLE
How to add 2 new virtual machines to the existing environment

### ISSUE THREAD

**Issue by willzhang** [hashicorp/vagrant#11206]
i change the NodeCount =4 to   NodeCount = 6, but it can't create 2 new vm, how can i do that ,the exit 4 vm have install something ,i don't want to destroy them.

```
    1910test04: [TASK 1] Install aliyun repo
    1910test04: [TASK 2] Install desired packages
    1910test04: [TASK 3] Config ssh connection
    1910test04: [TASK 4] Disable SELinux and firewalld
    1910test04: setenforce: SELinux is disabled
==> 1910test05: VM not created. Moving on...
==> 1910test06: VM not created. Moving on...
```

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  
  NodeCount = 6

  (1..NodeCount).each do |i|
    config.vm.define "1910test0#{i}" do |node|
      node.vm.box = "centos1910"
      node.vm.hostname = "1910test0#{i}"
      node.vm.network "private_network", ip: "172.16.5.3#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "1910test0#{i}"
        v.memory = 4096
        v.cpus = 2
      end
    end
  end

end
```

**Comment by briancain** [comment]
Hey there @willzhang - You should be able to bring up those vms by using their names directly.

First of all, you should be able to see them by simply running `vagrant status` in your environment. Next, you should then be able to bring them up using this command:

```
vagrant up 1910test05 1910test06
```

Since you are using their name directly, Vagrant should only deal with those new VMs, and leave your other existing ones alone. I hope that helps, thanks! If you have any more questions please direct them to the Vagrant up mailing list.

**Comment by willzhang** [comment]
Ok,thanks
