### ISSUE TITLE
Enhancement: Typeahead for commands and provisioned machine names

### ISSUE THREAD

**Issue by jzielke84** [hashicorp/vagrant#11210]
### Expected behavior
Vagrant should offer type-ahead for commands and machines of Vagrantfile.

A great enhancement would be to offer typeahead for provisioned machines residing in the .vagrant folder and also for the standard commands like up, provision etc.

**Comment by briancain** [comment]
Hi there @jzielke84 - Are you looking for autocomplete on the command line? If so, we have that already! https://github.com/hashicorp/vagrant/blob/master/contrib/bash/completion.sh You just ned to put that file in the appropriate place on disk, and `source` it so that it loads into your current bash session. Thanks

**Comment by jzielke84** [comment]
@briancain Oh how cool is that! Thanks for pointing out. I'll import this into my zsh.
