### ISSUE TITLE
 "Vagrant box outdated" and "vagrant up" both are not showing latest version of box from locally hosted catalog file

### ISSUE THREAD

**Issue by eddi0815** [hashicorp/vagrant#11228]
# Vagrant version
Vagrant 2.2.6

### Host operating system
Debian 10 and Windows 10

### Guest operating system
Debian 10

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.box = "debian" 
  #config.vm.box_url = "http://localhost/vagrant/debian/debian.json"
  config.vm.box_url = "file:///var/www/html/vagrant/debian/debian.json"
  
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
end
```

### Debug output
https://gist.github.com/eddi0815/cae742ee6e4a962c43c442de755d5609

```
$ vagrant box outdated
Checking if box 'debian' version '0.1.0' is up to date...
``` 

``` 
$ vagrant box outdated --global
* 'generic/debian10' for 'virtualbox' is outdated! Current: 1.9.38. Latest: 2.0.6
* 'debian' for 'virtualbox' is outdated! Current: 0.1.0. Latest: 0.2.0
``` 

### Expected behavior
**vagrant box outdated** should inform about a new version, too.

### Actual behavior
No information about a new version. The same behaviour with **vagrant up**

### Steps to reproduce
1. I'm using catalog for box versioning as you can see in my vagrantfile and I have this file on localhost
2. I have even tried putting this file at same path of vagrantfile but still no success
3.    Box updates are not even being check on vagrant up

### References
I have the same problem like it is described in issue https://github.com/hashicorp/vagrant/issues/10254

**Comment by briancain** [comment]
Hey there @eddi0815 , from the debug log, it looks like the issue is that Vagrant had recently checked for an update, and is within the update threshold to not check again. From your debug log:

```
INFO interface: output: Checking if box 'debian' version '0.1.0' is up to date...
 INFO box: box update check is under the interval threshold
 INFO box: Skipping box update check
```

It looks like once an update has been checked for, Vagrant waits about 1 hour until it decides that it's worth it to check again for an update. You could try to either wait an hour (although at this point since the issue is opened, it's probably been past that threshold), or you could manually delete the file and try again. If you remove this update file from Vagrants global data dir or wait an hour, do you still experience the same update behavior?

The file should be at:

> /home/brian/.vagrant.d/boxes/your-box-name/0.1.0/virtualbox/box_update_check

You will have to update the path accordingly (for the user, and for `your-box-name`, and maybe replace the version if I guessed wrong), as I don't know what it might be called on your file system

**Comment by eddi0815** [comment]
Yes. You are right. That also the reason why it was working sometimes. I was struggling with this issue many days. is that somewhere mentioned in the documentation and I didn't see this?

**Comment by briancain** [comment]
@eddi0815 - Unfortunately, it doesn't seem to be documented. We can fix that. Thanks for pointing it out!
