### ISSUE TITLE
Cannot pass environment variables to provisioner with winssh communicator

### ISSUE THREAD

**Issue by jojonas** [hashicorp/vagrant#11232]
### Vagrant version
Vagrant 2.2.3, but the same error exists in the current master.

### Host operating system
Linux 4.19, Debian 10.2 (Buster)

### Guest operating system
Windows 10 via VirtualBox

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.communicator = "winssh"
  config.vm.box = "win10"
  config.vm.provision "shell", path: "provision.ps1", env: { "foo" => "bar" }
end
```

#### provision.ps1
```powershell
Set-StrictMode -Version Latest
Write-Output "Hello World!"
```

### Debug output
Cannot provide the full debug output, but the following stack trace completely explains the issue:
https://gist.github.com/jojonas/e7a9cc179614869e745daf07703a81cd

Important error message:
```
vagrant-2.2.3/plugins/provisioners/shell/provisioner.rb:116:in `block (3 levels) in provision_winssh': protected method `generate_environment_export' called for #<VagrantPlugins::CommunicatorWinSSH::Communicator:0x000055f467fccbf8> (NoMethodError)
```

### Expected behavior
The Powershell script should have been executed, printing "Hello World!"

### Actual behavior
An error was thrown, see above.

### Steps to reproduce
1. Provision a box via WinSSH.
2. Pass the `env` hash to `config.vm.provision`.
3. Get a stack trace. Provisioner is not executed.

### Explanation
[1] calls protected function `generate_environment_export` [2].

[1] https://github.com/hashicorp/vagrant/blob/v2.2.3/plugins/provisioners/shell/provisioner.rb#L116
[2] https://github.com/hashicorp/vagrant/blob/v2.2.3/plugins/communicators/ssh/communicator.rb#L729

**Comment by briancain** [comment]
Hey there @jojonas - Thanks for reporting this issue! Although the fix for making `generate_environment_export` available to the winssh communicator is an easy one, it revealed a more serious issue with the winssh communicator that will be a bit more difficult to fix. In the mean time, is it possible for you to use `winrm` instead of `winssh` for your communicator? I just tried that with one of my windows guests, and it doesn't have the issue that you reported. Thanks

**Comment by jojonas** [comment]
Hi, sorry for the delayed answer. I figured that the switch needed some architectural restructuring, that's why I didn't attempt fixing the bug myself... For now I'm using a workaround, basically not passing any variables to the provisioners, as I prefer SSH for security reasons, however in the long term an actual fix would be great. Let me know if I can be of any help. Thanks!

**Comment by jbonhag** [comment]
Hi @jojonas,

We just merged a fix for this issue into master. If you'd be willing to check it out, that would be awesome, otherwise it will be out in the next Vagrant release.

Here's an example of the fix in action:

Vagrantfile:
```
  config.vm.provision "shell", path: "provision.ps1", env: { "foo" => "bar" }
```

provision.ps1:
```
Set-StrictMode -Version Latest
Write-Output "Hello, $env:foo!"
```

Vagrant output:
```
$ vagrant provision
==> default: Running provisioner: shell...
    default: Running: /var/folders/n0/z9w8y28d7j5dmnp0332cvv240000gp/T/vagrant-shell20200311-43289-gvsb2x.ps1
    default: Hello, bar!
```

Thanks again for the initial bug report!

**Comment by DanielChuDC** [comment]
@jbonhag I faced  problem while echo $env:foo

My environment in rhel8. May I know how to use env flag? there has no example in [vagrant official website](https://www.vagrantup.com/docs/provisioning/shell.html#env)

> Set-StrictMode -Version Latest
> Write-Output "Hello, $env:foo!"
