### ISSUE TITLE
Only run scripts on the first virtual machine created using the loop

### ISSUE THREAD

**Issue by willzhang** [hashicorp/vagrant#11247]
Only run scripts on the first virtual machine created using the loop?
how do that?

i have a shell script , i want run it at the first node when i run vagrant up.

### vagrant file
```
 -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  
  NodeCount = 6

  (1..NodeCount).each do |i|
    config.vm.define "centosvm0#{i}" do |node|
      node.vm.box = "centos7"
      node.vm.hostname = "centosvm0#{i}.example.com"
      node.vm.network "private_network", ip: "172.16.5.1#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "centosvm0#{i}"
        v.memory = 4096
        v.cpus = 2
      end
    end
  end

end
```

**Comment by jbonhag** [comment]
Hi @willzhang,

Since the Vagrantfile is just Ruby, you could write something like this:

```
  (1..NodeCount).each do |i|
    config.vm.define "centosvm0#{i}" do |node|

      # Only run scripts on the first virtual machine
      if i == 1
        node.vm.provision "shell", path: "bootstrap.sh"
      end

      ...
    end
  end
```

This will only run the provisioning script on the first virtual machine during `vagrant up` as well as `vagrant provision`.  I hope that helps!

As a side note, we do try to keep the issue tracker reserved for Vagrant bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up).

Thanks for using Vagrant and have a great day! 😄
