### ISSUE TITLE
Issue to install Vagrant in MacOS

### ISSUE THREAD

**Issue by debabratakarfa** [hashicorp/vagrant#11242]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
2.2.6

### Host operating system
Mac OS Catalina

### Guest operating system
Install issue with Mac OS.

### Expected behavior
Install properly.

### Actual behavior
Saying malicious software.

### Steps to reproduce
1. Visit https://www.vagrantup.com/downloads.html
2. Download for Mac

### References
Attached screenshot.
<img width="522" alt="Screenshot 2019-12-08 22 29 53" src="https://user-images.githubusercontent.com/2614495/70392940-fc1d5f80-1a0a-11ea-8c2a-db0ac7990b62.png">

**Comment by jbonhag** [comment]
Hi there,

There are new restrictions for applications imposed by Apple starting with Catalina. Included in these new restrictions is the requirement for notarization which requires submission of the application build to Apple and an acceptance before it can be packaged and distributed.

We are working on integrating this process into our build system and will have it available for our next release.  In the meantime, please check out https://github.com/hashicorp/vagrant/issues/11127 for some suggested workarounds.

Since that issue already covers notarization issues with Vagrant on Catalina, I'm going to close this one as a duplicate.  We appreciate you taking the time to report your findings.

Thanks and have a great day! 😀
