### ISSUE TITLE
ansible inventory only

### ISSUE THREAD

**Issue by rvalle** [hashicorp/vagrant#11255]
We run ansible in many different ways, one o those is inside a docker container.

We would like Vagrant to only generate the ansible inventory without attempting to run the actual playbook.

Is that possible? I have attempted --no-provision flag but that seems to disable the whole functionality.

Is there  a whay to control which command gets executed on provisioning?

**Comment by briancain** [comment]
Hey there @rvalle - From what I am reading in the Vagrant docs, if Vagrant is generating your inventory, it should be located locally inside your local vagrant metadata folder `.vagrant` here:

https://www.vagrantup.com/docs/provisioning/ansible_intro.html#the-inventory-file

> .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory

If you use the `--no-provision` flag, that inventory file might not get generated. If you have any more questions, I recommend emailing the Vagrant Up mailing list, as there will be more people there to help answer your question! Otherwise, this repository is for bug reports. If you have a bug then please open a new issue with the information asked so that we can assist you. Thanks!

**Comment by rvalle** [comment]
This is meant to be a feature request. As it's not possible to generate the inventory without triggering the provisioning. 

In some environments, such as CI/CD, this is desirable.

**Comment by briancain** [comment]
Hey there @rvalle - Based on how Vagrant is currently architected, the ansible inventory generation is tied to the ansible provisioner plugin, so disabling provisioning means you won't generate an inventory file. If you simply just want the file, you could write a playbook that is essentially a "no-op" against your hosts to grab the file out from the `.vagrant` folder after the provisioning is done.

**Comment by rvalle** [comment]
@briancain that was my initial idea, in fact it is the pattern that I always use with this provider.

However, it still requires an ansible to be installed and working.

I am running this inside a CI container in Gitlab, I don't want to bring the whole python stack for a no-op.

IMHO it is reasonable to have the Ansible provider only generate the inventory (as an option) without further dependencies. I.e. if ansible.playbook is omitted.

If you look at the Ansible documentation about Vagrant, they tip the users on how to run the playbook outside of the Provisioning functionality too. Since playbook development requires multiple runs, my guess is that the "no-op" pattern is widely used.
