### ISSUE TITLE
Vagrant version Issue 

### ISSUE THREAD

**Issue by prasant-ku-rout** [hashicorp/vagrant#11266]
Hello Team , i have installed Vagrant with below specification , while running "Vagrant up" command getting error as mentioned in section below. could you please help to resolve this 

### Installed Plugin 
**vagrant-vmware-desktop (2.0.3, global)**
### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = false
  end
end

### Expected behavior
It should spin up Ubuntu VM

### Actual behavior
Running the "Vagrant Up" Command getting below Error 
Vagrant failed to initialize at a very early stage:

**The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

If you're on Windows and just installed VirtualBox, you have to
log out and log back in for the new environmental variables to take
effect. If you're on Linux or Mac, verify your PATH contains the folder
that has VBoxManage in it.**

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by briancain** [comment]
Hey there @prasant-ku-rout - This is because the box you selected, [ubuntu/trusty64](https://app.vagrantup.com/ubuntu/boxes/trusty64), does not have a `vmware_desktop` provider. It only supports VirtualBox, so when you try to use that box it attempted to use the `virtualbox` provider instead. I recommend finding a box that supports the `vmware_dekstop` provider if you wish to continue using that provider. Thanks!
