### ISSUE TITLE
I cant's install vagrant-disksize plugin

### ISSUE THREAD

**Issue by claytonnog** [hashicorp/vagrant#11280]
I can't install the vagrant-disksize plugin...

vagrant -v
Vagrant 2.2.6

Fedora release 31 (Thirty One)

I just tried to install the dependencies, but still does not work.

-------------------------------------
$ vagrant plugin install vagrant-disksize
Installing the 'vagrant-disksize' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 2.1.2)
  Activated fog-core-2.1.2
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 2.1.2), 2.1.2 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)

**Comment by jbonhag** [comment]
Hi there,

This looks like a conflict between the version of fog-core installed (2.1.2) and the version required by vagrant-libvirt (~> 1.43.0).  I'd recommend uninstalling fog-core 2.1.2 and reinstalling the vagrant-libvirt plugin so that it can bring in the correct versions of its dependencies.

If you have additional issues with installing Vagrant plugins, please open an issue against the appropriate plugin repository.

Thanks and have a great day! 😄
