### ISSUE TITLE
Allow minor version upgrades of provider

### ISSUE THREAD

**Issue by dragetd** [hashicorp/vagrant#11294]
Vagrant explicitly checks for VirtualBox 4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 6.0. 6.1 was released release in december.

I know it is a burden to keep up with the API compatibility, but a change in the minor version (6.0 vs. 6.1) has a high chance of not breaking vagrant. I suggest a different behavior:  Keep the major version checks. For minor versions, allow using number higher than the last tested version but print a warning when executing.

Alternatively a commandline option like `--provider-ignore-version` or something like this.

**Comment by jbonhag** [comment]
Hi there,

You raise a very good point.  It can be frustrating for users when a new version of a virtualization provider comes out and Vagrant takes a little while to catch up.  However, our preference is to be more conservative in terms of which versions we support, since we have no control over the nature of changes from one version to the next.

This also gives us some extra time to test the stable version of a provider before releasing a version of Vagrant that supports it.

I hope you'll understand where we're coming from.  It can be tricky syncing up changes across all the different pieces of the Vagrant ecosystem, but we believe that this provides the best possible experience for our users overall.

As a side note, you can always [install Vagrant from source](https://www.vagrantup.com/docs/installation/source.html) if you wish to be on the cutting edge of what Vagrant supports with VirtualBox.

Cheers!

**Comment by dragetd** [comment]
Thanks for the insights!

I also had a chat with the VBox people. They consider updates between 6.x and 6.y to be 'major', i.e. they decided it is fine to break things and they do not recommend using the CLI interface for such access anyways.

They have an API. But I was told be the VBox people that the API is also evolving each version, thus it would not really help at this point. Which I am not sure how exactly this correlates… I have to get into the COM API and find out how it works. E.g. if fields are just 'added', can a programm still use the old API?

I wonder if that is the reason vagrant is also not use the API. But before I open a discussion about that, I want read more about this myself. :)

**Comment by atwright147** [comment]
What about the possibility of adding `--provider-ignore-version` as a command line option as @dragetd suggested (and I was about to)?

This seems like it would cover all bases. In normal use, the user would run Vagrant without the option, but when VBox, VMware etc is updated and Vagrant gets out of alignment, we could use the option to get it working in the interim.
