### ISSUE TITLE
Continuation of #11301

### ISSUE THREAD

**Issue by rememberthebear** [hashicorp/vagrant#11305]
I apologize.  I guess I didn't do a good enough job explaining the problem the first time.  I am fully aware of what the error means, so please do not insult me in thinking that an explanation of the error is in any way an acceptable solution.  I also have the most up to date official version of vagrant installed on my machine as well, and the package command works perfectly fine when running the vagrant package when I am using the latest officially released version of vagrant that is installed using the installation package.  So, we have this scenario where the officially released version of vagrant works fine, but is not compatible with the most recent version of virtualbox, and the latest dev build supports the latest version of virtualbox, but does not have the same stability and access to the resources that it needs that the vagrant installation does.  To be 100% clear, **that is the problem.**  I look forward to working with you on a solution for this issue and **not** seeing it closed with a quick throw away answer.

**Comment by chrisroberts** [comment]
Hi there,

The error you posted in your previous issue was due to a lack of `bsdtar` on the system which Vagrant could use. Running a development version of Vagrant is much different than running Vagrant from the official installers. When Vagrant is run in development mode, the onus is on the user to provide all required executables. There is no guarantee that running a development version of Vagrant will have the same access to dependency executables. As it is being run directly from the repository, there is no way to provide those dependencies.

The currently released version of Vagrant works with VirtualBox 6.0.X versions so downgrading VirtualBox until the next release is one viable workaround. Our next release will be coming in the next few days, which will also resolve the VirtualBox specific issue.

Cheers
