### ISSUE TITLE
Usually the salt-master is installed before salt-minions...

### ISSUE THREAD

**Issue by Reiner030** [hashicorp/vagrant#11313]
So the call in:

https://github.com/hashicorp/vagrant/blob/a4d5ee6ac1aa88d827fc05e2ba85a90bc40ba004/plugins/provisioners/salt/provisioner.rb#L379

must fail because the minion(s) is/are not setup yet (if there is one minion different from the local master vagrant guest to be setup)!
This can be ignored by general salt option `--hide-timeout`

**Comment by briancain** [comment]
Hey there @Reiner030 - Typically when users open github issues, we ask that they fill out the information we ask to help us get an idea of what issues you are facing. Are you experiencing an error with using the salt provisioner? And if so, please provide us with a debug log so that we can help you and try to reproduce what's going wrong. Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Comment by Reiner030** [comment]
Hi @briancain 
there was too much github "spam" created by saltstack stale-bot last weeks so I have overseen this issue answer.

The problem ist that there is no real informative log... except that saltstack exitcode of initial mentioned call returns != 0 so the provisioning task is failed and stopped.

I can try to resetup an instance next days.

**Comment by briancain** [comment]
Hi @Reiner030 - do you have any more information about this issue now?

**Comment by briancain** [comment]
Hey there, I'm going to once again close this issue due to a lack of response. I cannot reproduce the issue described, and due to a lack of Vagrantfile and debug log, I don't have much more information to go off of. I am going to go ahead and close this issue. If you are still experiencing problems, please open a new issue with the requested information so that we can assist you. Thanks!
