### ISSUE TITLE
Wrong url for centos/8 box

### ISSUE THREAD

**Issue by acikogun** [hashicorp/vagrant#11324]
### Vagrant version
Vagrant 2.2.6

### Host operating system
Windows 10

### Guest operating system
centos/8

### Vagrantfile

N/A

### Debug output
https://gist.github.com/acikogun/df3fd0b1be7e1494f9bdc2e97dda7541

### Actual behavior
`vagrant box add centos/8`

> ==> box: Loading metadata for box 'centos/8'
>     box: URL: https://vagrantcloud.com/centos/8
> This box can work with multiple providers! The providers that it
> can work with are listed below. Please review the list and choose
> the provider you will be working with.
> 
> 1) libvirt
> 2) virtualbox
> 
> Enter your choice: 2
> ==> box: Adding box 'centos/8' (v1905.1) for provider: virtualbox
>     box: Downloading: https://vagrantcloud.com/centos/boxes/8/versions/1905.1/providers/virtualbox.box
>     box: Download redirected to host: cloud.centos.org
>     box:
> An error occurred while downloading the remote file. The error
> message, if any, is reproduced below. Please fix this error and try
> again.
> 
> The requested URL returned error: 404 Not Found

**Comment by briancain** [comment]
Hey There @acikogun - The centos organization is the one that has picked an [external URL](http://cloud.centos.org/centos/8/vagrant/x86_64/images/CentOS-8-Vagrant-8.0.1905-1.x86_64.vagrant-virtualbox.box) to host their Vagrant box. You will need to contact them instead, since they are the ones managing that box and hosting that image. Thanks for the report!
