### ISSUE TITLE
Defining a mac adress for 2 boxes creates package errors with apt-get update

### ISSUE THREAD

**Issue by queglay** [hashicorp/vagrant#11360]
### Vagrant version
Vagrant 2.2.6

### Host operating system
CENTOS7

### Guest operating system
bento/ubuntu-16.04

### Vagrantfile
```ruby
bridgenic = "enp9s0f0"

servers=[
  {
    :hostname => "ansiblecontrol",
    :mac_string => "EEDDAAA1987C",
    :bridgenic => bridgenic,
    :box => "bento/ubuntu-16.04",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "firehawkgateway",
    :mac_string => "000C291F5C51",
    :bridgenic => bridgenic,
    :box => "bento/ubuntu-16.04",
    :ram => 1024,
    :cpu => 2
  },
]

Vagrant.configure(2) do |config|
    config.vbguest.iso_path = "https://download.virtualbox.org/virtualbox/6.0.14/VBoxGuestAdditions_6.0.14.iso"
    config.vbguest.auto_update = false
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.box_version = "201912.03.0"
            node.vm.define machine[:hostname]

            if machine[:mac_string] == 'none'
                node.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: bridgenic
            else
                node.vm.network "public_network", mac: machine[:mac_string], use_dhcp_assigned_default_route: true, bridge: bridgenic
            end
            
            node.vm.provider "virtualbox" do |vb|
                vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
                vb.gui = false
                # Customize the amount of memory on the VM:
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--cpus", machine[:cpu]]
            end

            node.vm.provision "shell", inline: "export DEBIAN_FRONTEND=noninteractive; sudo apt-get update"
          
        end
    end
end
```

### Debug output
https://gist.github.com/queglay/e0ff0fbe30774a2f39974756fe2318a5

### Expected behavior
When defining a mac adress there should be no dns issues or ability to run apt-get update.

### Actual behavior
It's taken me a really long time to get this far and reduce the problem to these variables.  this only started to arise once I began using 2 vagrant boxes.  If a mac address is defined, the second box will have issues with apt-get update.  Strangely, although the first box is identical (except for the actual mac address it uses to avoid conflicts), it has no problem.  

### Steps to reproduce
1.  vagrant up

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! I'm trying to reproduce this issue on a CentOS 7 machine with VirtualBox 6.0.16r135674 and Vagrant 2.2.6. So far, I haven't had much luck, so I was wondering if you'd be willing to try a couple of things to help narrow down the issue.

- Are you able to manually re-provision the second box after the initial failure?

```
vagrant provision firehawkgateway
```

- Do you get different results if you provision both VMs manually, for example:

```
vagrant up --no-provision
vagrant provision ansiblecontrol
vagrant provision firehawkgateway
```

- There are multiple IP addresses associated with archive.ubuntu.com and security.ubuntu.com. It may be that your DNS server is returning an IP address that your network can't route to for some reason.  Would you mind trying:

```
vagrant ssh firehawkgateway -c "telnet 91.189.88.31 80"
vagrant ssh firehawkgateway -c "telnet 91.189.91.14 80"
```

- Do you get different results if you bridge to a different host adapter?

- Is it always the second machine that fails? If you reverse the order of the boxes, does the `ansiblecontrol` machine fail instead?

- Finally, could you please the network configuration from both guests using `ip addr` and `ip route`?

Sorry for the seemingly random list of requests, but this will hopefully get us closer to the root cause. Thanks for putting in the time to isolate this issue.

Cheers!

**Comment by queglay** [comment]
After tinkering further, I found that when I changed the mac address of the VM having the issue, the problem went away.  sometime later I reproduced the same issue.  after the next mac address I generated though, the problem did not reoccur since then.  If this arises again, what do you think I should do to further investigate?

**Comment by chrisroberts** [comment]
Hi @queglay. Glad that the adjustments sorted things out. Without being able to do any local inspection it's hard to say. My best guess is that either the MAC is in use elsewhere (though changing it and then encountering the behavior again suggests that may not be the issue) or that the arp tables aren't getting updated. If you don't need to manually define the MAC, then just removing that would likely resolve the issues. However, if you _do_ need to provide a custom value, using an address in the local range would reduce the chances for issues.

Notably, in your example above, the first MAC address defined is within the valid local range, but the second is not. This VirtualBox ticket provides the valid ranges for local assignments:

https://www.virtualbox.org/ticket/12044

Cheers!
