### ISSUE TITLE
After reboot, Vagrant will not mount shared folders.  Only 'vagrant reload' works.

### ISSUE THREAD

**Issue by queglay** [hashicorp/vagrant#11368]
### Vagrant version
Vagrant 2.2.6

### Host operating system
CENTOS 7

### Guest operating system
ubuntu 16

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.define "firehawkgateway" do |firehawkgateway|
    firehawkgateway.vm.box = "bento/ubuntu-16.04"
  end
end
```

### Debug output
https://gist.github.com/queglay/3b5c6f923ad5c9d3f55ee896cf5f0ecc

Also a log of the shell operations to show the missing folder-
```
vagrant@vagrant:~$ ls /vagrant/
Vagrantfile
vagrant@vagrant:~$ touch /vagrant/test
vagrant@vagrant:~$ ls /vagrant/
test  Vagrantfile
vagrant@vagrant:~$ sudo reboot
Connection to 127.0.0.1 closed by remote host.
Connection to 127.0.0.1 closed.
[user@workstation test-vagrant-mount]$ vagrant ssh
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-170-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Overheard at KubeCon: "microk8s.status just blew my mind".

     https://microk8s.io/docs/commands#microk8s.status

0 packages can be updated.
0 updates are security updates.



This system is built by the Bento project by Chef Software
More information can be found at https://github.com/chef/bento
Last login: Mon Feb  3 11:08:42 2020 from 10.0.2.2
vagrant@vagrant:~$ ls /vagrant/
vagrant@vagrant:~$ ls /vagrant/
vagrant@vagrant:~$ ls /vagrant/
vagrant@vagrant:~$ exit
logout
Connection to 127.0.0.1 closed.
[user@workstation test-vagrant-mount]$ vagrant reload
==> firehawkgateway: Attempting graceful shutdown of VM...
==> firehawkgateway: Checking if box 'bento/ubuntu-16.04' version '201912.15.0' is up to date...
==> firehawkgateway: Clearing any previously set forwarded ports...
==> firehawkgateway: Fixed port collision for 22 => 2222. Now on port 2204.
==> firehawkgateway: Clearing any previously set network interfaces...
==> firehawkgateway: Preparing network interfaces based on configuration...
    firehawkgateway: Adapter 1: nat
==> firehawkgateway: Forwarding ports...
    firehawkgateway: 22 (guest) => 2204 (host) (adapter 1)
==> firehawkgateway: Booting VM...
==> firehawkgateway: Waiting for machine to boot. This may take a few minutes...
    firehawkgateway: SSH address: 127.0.0.1:2204
    firehawkgateway: SSH username: vagrant
    firehawkgateway: SSH auth method: private key
==> firehawkgateway: Machine booted and ready!
GuestAdditions are newer than your host but, downgrades are disabled. Skipping.
==> firehawkgateway: Checking for guest additions in VM...
    firehawkgateway: The guest additions on this VM do not match the installed version of
    firehawkgateway: VirtualBox! In most cases this is fine, but in rare cases it can
    firehawkgateway: prevent things such as shared folders from working properly. If you see
    firehawkgateway: shared folder errors, please make sure the guest additions within the
    firehawkgateway: virtual machine match the version of VirtualBox you have installed on
    firehawkgateway: your host and reload your VM.
    firehawkgateway: 
    firehawkgateway: Guest Additions Version: 6.1.0
    firehawkgateway: VirtualBox Version: 6.0
==> firehawkgateway: Mounting shared folders...
    firehawkgateway: /vagrant => /home/user/git/test-vagrant-mount
==> firehawkgateway: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> firehawkgateway: flag to force provisioning. Provisioners marked to run always will still run.
[user@workstation test-vagrant-mount]$ vagrant ssh
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-170-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Overheard at KubeCon: "microk8s.status just blew my mind".

     https://microk8s.io/docs/commands#microk8s.status

0 packages can be updated.
0 updates are security updates.



This system is built by the Bento project by Chef Software
More information can be found at https://github.com/chef/bento
Last login: Mon Feb  3 11:11:50 2020 from 10.0.2.2
vagrant@vagrant:~$ ls /vagrant/
test  Vagrantfile

```

### Expected behavior
Mounts should be present after reboot.

### Actual behavior
Rebooting the vm with the 'reboot' command within will break vagrant shared folders.  

This is problematic if the vm is being provisioned remotely (for example with Ansible), and for security reasons there is no ability to execute 'vagrant reload' on the host/metal.  vagrant reload has no problem, but we should be able to reboot the machine with the reboot command within.

As far as I can tell, this is a known issue by some others.
https://stackoverflow.com/questions/23894739/synced-folders-lost-when-rebooting-a-vagrant-machine-using-the-ansible-provision

### Steps to reproduce
1. ```vagrant up```
2. ```sudo reboot```
3. The shared folder is missing.

### References
https://stackoverflow.com/questions/23894739/synced-folders-lost-when-rebooting-a-vagrant-machine-using-the-ansible-provision

**Comment by ferrarimarco** [comment]
@queglay  I guess so, but does this happen when [rebooting with a shell provisioner](https://www.vagrantup.com/docs/provisioning/shell.html#reboot)?

**Comment by CtrlC-Root** [comment]
I posted a work-around to this in the linked StackOverflow question from above (see https://stackoverflow.com/a/61261742/937006) but I'm reproducing it here for posterity.

----

In case anyone else runs into this issue and finds this question like I did here's how I worked around the issue:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "..."

  # create a shared folder for the top-level project directory at /vagrant
  # normally already configured but for some reason it isn't on these boxes
  # https://www.vagrantup.com/docs/synced-folders/virtualbox.html#automount
  # http://www.virtualbox.org/manual/ch04.html#sf_mount_auto
  config.vm.synced_folder ".", "/mnt/vagrant", id: "vagrant", automount: true
  config.vm.provision "shell", inline: "usermod -a -G vboxsf vagrant"
  config.vm.provision "shell", inline: "ln -sf /media/sf_vagrant /vagrant"

  # More settings omitted...
end
```
There's a few parts to this solution:

 1. The first line assigns a specific `id` of `vagrant` to the shared folder. This is important because the automatic mount functionality in VIrtualBox uses `/mnt/sf_<id>` by default. It also mounts the folder at `/mnt/vagrant` to keep it out of the way. Ideally you'd pick a more obscure location that's present on all of your VMs or just document not to use it there.
 2. The third line creates a symbolic link from the automatic mount location at `/mnt/sf_vagrant` to the usual place users expect the shared folder at `/vagrant`.
 3. The second line adds the `vagrant` user in the virtual machine to the `vboxsf` group. This is necessary to access files inside `/mnt/sf_vagrant` because the guest utilities mount the folder with `root:vboxsf` ownership. They also set appropriate file and directory modes so it works fine in practice but you do need to be a member of the `vboxsf` group.

This solution has the following benefits:

 * The mount at `/mnt/sf_vagrant` is automatically mounted by the virtualbox guest utilities after a reboot so `/vagrant` should always be available.
 * It does not require installing plugins or using any outside tools.

It has the following drawbacks:

 * Potential for unexpected behavior if users find and use the `/mnt/vagrant` mount. That mount will only be present if the virtual machine was most recently booted / rebooted through the `vagrant` console client otherwise it will not be present.
 * It requires a relatively recent version of VirtualBox and Vagrant.
