### ISSUE TITLE
Vagrant 2.2.7 with VirtualBox 6.1 - clipboard syntax changed

### ISSUE THREAD

**Issue by scoter-oracle** [hashicorp/vagrant#11370]
2.2.7 doesn't work for me

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'kane_project/windows-10' version '1903' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
A customization command failed:

["modifyvm", :id, "--clipboard", "bidirectional"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "ce2ae2de-d509-46e4-82ac-11df167cf2d5", "--clipboard", "bidirectional"]

Stderr: Oracle VM VirtualBox Command Line Management Interface Version 6.1.2
(C) 2005-2020 Oracle Corporation
All rights reserved.

Usage:
# ...

VBoxManage: error: Unknown option: --clipboard
>

Please fix this customization and try again.

$ vagrant -v
Vagrant 2.2.7

**Comment by scoter-oracle** [comment]
VBoxManage syntax had changed in VirtualBox 6.1.
"--clipboard" (VBox 6.0 and older) had been replaced by "--clipboard-mode"

**Comment by briancain** [comment]
Hey there @scoter-oracle - As mentioned on several other issues, this is not a Vagrant bug. The box you are using specifies this option explicitly in the Vagrantfile that is shipped with it. Because Virtualbox changed the command line flag, all boxes that specify that flag need to update to the new flag. This is nothing something Vagrant can do, as it is explicitly set inside the Vagrantfile shipped with the box you are using by the author who made that box. Unfortunately a lot of boxes use this command line option it seems, so many are now broken because of the change Virtualbox made in 6.1. However, this is from a explicit "customize" command inside these boxes, and not something Vagrant is setting or has control over. I hope that makes sense, thanks!

**Comment by scoter-oracle** [comment]
hey @briancain thanks for the clarification
