### ISSUE TITLE
Allow setting default SMB credentials in my user Vagrantfile

### ISSUE THREAD

**Issue by AnthonyMastrean** [hashicorp/vagrant#11413]
### Vagrant version
Vagrant 2.2.7

### Host operating system
Windows 10

### Guest operating system
Any

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.synced_folder ".", "/vagrant"
end
```

### Expected behavior

I should be able to setup default SMB credentials for _any_ subsequent SMB synced folder in my user Vagrantfile.

That's this one, per the docs:

```
~/.vagrant.d/Vagrantfile
```

https://www.vagrantup.com/docs/vagrantfile/#load-order-and-merging

### Actual behavior

Since the `smb_username` and `smb_password` and `mount_options` are method parameters on `synced_folder`, I cannot easily set defaults in a way that still allows me to share this Vagrantfile with coworkers.

> *Note:* my janky workaround doesn't actually work, so I'm not sure I have a workaround... will continue exploring.

I have to do something janky like...

**~/.vagrant.d/Vagrantfile**
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  default_smb_username = "..."
  default_smb_password = "..."
  default_mount_options = "..."
end
```

And then in my ultimate Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.synced_folder ".", "/vagrant", smb_username: default_smb_username, smb_password: default_smb_password
end
```

### Steps to reproduce
1.
2.
3.

**Comment by AnthonyMastrean** [comment]
Oh, well, my janky workaround doesn't actually work... I guess the Vagrantfile merging method is more about building and merging Vagrant conf and less about like merging Ruby source files.

So, that's even worse? I don't even have a bad workaround 😆

**Comment by briancain** [comment]
Hi @AnthonyMastrean - You should be able to potentially set these values as variables as you did, do you have a debug log of the result of running that Vagrantfile?

**Comment by briancain** [comment]
Also please be aware that I _think_ the smb password is usually your system password :see_no_evil: Vagrant will typically scrub the logs with that, but always good to double check before sharing anything! Thanks.

**Comment by briancain** [comment]
Also additionally, I should mention, since it seems like you are configuring the default share, you shouldn't actually need to do any of this. You should simply be able to put this line in your global Vagrantfile, and it should apply to all guests:

## ~/.vagrant.d/Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", smb_username: "username here", smb_password: "password here"
end
```

`config` is a top scope option, and Vagrant will apply it to each guest that has that specific synced folder (which by default, is every guest because `/vagrant` will always be synced unless disabled).

**Comment by AnthonyMastrean** [comment]
Variables _inside_ the configure block scope didn’t seem to survive to merging. Global variables outside the block scope seemed to work. 

You’re right about overriding the default synced folder in my user Vagrantfile. I think that’ll work in the short term. But, it will only work easily for the default synced folder. I don’t think I’m going to like adding _every_ SMB synced folder I come across to my user Vagrantfile!

And, actually wouldn’t synced folders in the folder/project scope override the same in the user scope? So, maybe I couldn’t use it that way.

The other problem is, I really want to share these Vagrantfiles in source control with team members that may or may not end up setting up defaults. It would be nice if the default credentials solution is hidden from anyone not using it (unlike, adding globals to my user Vagrantfile and referencing them in the project Vagrantfile).

**Comment by briancain** [comment]
To your last point, I imagine each of your team members probably have different smb_username and smb_passwords? Those values are your _host_ system username and password, not the guest username and password that you're bringing up with Vagrant. So unless all of you have the same username and password, there isn't much value here in setting a default value to share in git if you're trying to get a usable default across multiple different machines for different people. Leaving them blank will just prompt your teammates for their host password. Which could be annoying, but at least it won't be a wrong default value.

There isn't really a great way to set these values across a team, but mostly because of what they are. Each person should have a unique username and password, which makes it difficult to share. You could potentially abstract out these values and read them from a config file (like a json or yaml structure), and expect your team to fill out those values in the config file to prevent their Vagrantfile from adding unstaged changes or being wrong against the master branch with their local username/password. Then at least there won't be any extra changes to ignore with git, but the downside is now you have your system password in a json or yaml file in your project directory.

**Comment by AnthonyMastrean** [comment]
@briancain I'm definitely talking about per-user host credentials. That's why I'm asking for per-user Vagrantfile configuration. I am, in fact, already checking Vagrantfiles into source control and they are using _more_ synced folder definitions than just the default. I was trying to keep the convo generic, but we were getting a little lost without details.

**Comment by briancain** [comment]
@AnthonyMastrean I guess I'm not 100% clear as to what the feature request is... you should be able to define these defaults like:

### ~/.vagrant.d/Vagrantfile

```ruby
DEFAULT_SMB_USERNAME="username"
DEFAULT_SMB_PASSWORD="password"

Vagrant.configure("2") do |config|
    # setting this synced folder is not required, btw. The variables above 
    # will be accessible anywhere as long as it gets loaded by Vagrant
    config.vm.synced_folder ".", "/vagrant", smb_username: DEFAULT_SMB_USERNAME,
        smb_password: DEFAULT_SMB_PASSWORD
end
```

Or those could also exist in your local Vagrantfile in your project directory too. That seems like it should cover the use case you are looking for, or am I missing something? :thinking:

**Comment by chrisroberts** [comment]
> The other problem is, I really want to share these Vagrantfiles in source control with team members that may or may not end up setting up defaults. It would be nice if the default credentials solution is hidden from anyone not using it (unlike, adding globals to my user Vagrantfile and referencing them in the project Vagrantfile).

An easy solution to this is to reference environment variables for the values within the configuration. Then users can opt-in to setting them if they like, and if they don't they will be prompted by Vagrant when setting up the synced directories:

```ruby
Vagrant.configure("2") do |config|
  config.vm.synced_folder '.', '/vagrant', smb_username: ENV["SMB_USERNAME"], smb_password: ENV["SMB_PASSWORD"]
end
```

Cheers!
