### ISSUE TITLE
Vagrant is unable to detect HOME directory on MacOS

### ISSUE THREAD

**Issue by ssbarnea** [hashicorp/vagrant#11410]
### Vagrant version
```
Vagrant 2.2.6
```
### Host operating system
MacOS 10.15

### Guest operating system
Any

### Expected behavior
When HOME variable is not defined vagrant should use currect OS provided APIs to retrie the user home directory instead of relying on hardcoded value of `/var/root/.vagrant.d`, which is obvious incorrect.

### Actual behavior
What actually happened?
```
CMD: ['/usr/local/bin/vagrant', 'up', '--no-provision'] returned 1
### 2020-02-23 19:00:15 ###
Vagrant failed to initialize at a very early stage:

The home directory you specified is not accessible. The home
directory that Vagrant uses must be both readable and writable.

You specified: /var/root/.vagrant.d
CMD: ['/usr/local/bin/vagrant', 'status', '--machine-readable', 'instance'] returned 1
```

### Steps to reproduce
```
uset HOME
vagrantup
```

Some tools do filter environment variables and there is no guarantee that HOME is defined on any platform. One practical example is tox testing framework, which by default does not pass this environment variable, mainly in order to better isolate the testing.

**Comment by briancain** [comment]
Hey there @ssbarnea - Vagrant does not strictly rely on the HOME environment variable to determine the global user data path. By default, if the environment variable `VAGRANT_HOME` is not set, or if `USERPROFILE` is not set, Vagrant will default to `~/.vagrant.d` as the default path. It does not hardcode `/var/root/.vagrant.d`:

https://github.com/hashicorp/vagrant/blob/74e54483c6f0ffe2ce9027643517544bbd58acd2/lib/vagrant/shared_helpers.rb#L99-L118

This is where things likely break. Your shell probably can't actually determine where `~` is because you unset HOME, so when Ruby tries to expand `~/.vagrant.d` with Pathname, it likely ends up with `/var/root` instead of whatever your local user home directory is.

For example, unsetting home with Ubuntu using bash does not replicate this behavior:

```
vagrant@vagrant:~/test$ echo $HOME
/home/vagrant
vagrant@vagrant:~/test$ unset HOME
vagrant@vagrant:/home/vagrant/test$ echo $HOME

vagrant@vagrant:/home/vagrant/test$ vagrant up hashicorp
Bringing machine 'hashicorp' up with 'virtualbox' provider...
==> hashicorp: Importing base box 'hashicorp/bionic64'...
==> hashicorp: Matching MAC address for NAT networking...
==> hashicorp: Checking if box 'hashicorp/bionic64' version '1.0.282' is up to date...
==> hashicorp: Setting the name of the VM: test_hashicorp_1583255942822_89091
==> hashicorp: Clearing any previously set network interfaces...
==> hashicorp: Preparing network interfaces based on configuration...
    hashicorp: Adapter 1: nat
==> hashicorp: Forwarding ports...
    hashicorp: 22 (guest) => 2222 (host) (adapter 1)
==> hashicorp: Booting VM...
==> hashicorp: Waiting for machine to boot. This may take a few minutes...
    hashicorp: SSH address: 127.0.0.1:2222
    hashicorp: SSH username: vagrant
    hashicorp: SSH auth method: private key
    hashicorp: Warning: Connection reset. Retrying...
    hashicorp:
    hashicorp: Vagrant insecure key detected. Vagrant will automatically replace
    hashicorp: this with a newly generated keypair for better security.
    hashicorp:
    hashicorp: Inserting generated public key within guest...
    hashicorp: Removing insecure key from the guest if it's present...
    hashicorp: Key inserted! Disconnecting and reconnecting using new SSH key...
==> hashicorp: Machine booted and ready!
==> hashicorp: Checking for guest additions in VM...
    hashicorp: The guest additions on this VM do not match the installed version of
    hashicorp: VirtualBox! In most cases this is fine, but in rare cases it can
    hashicorp: prevent things such as shared folders from working properly. If you see
    hashicorp: shared folder errors, please make sure the guest additions within the
    hashicorp: virtual machine match the version of VirtualBox you have installed on
    hashicorp: your host and reload your VM.
    hashicorp:
    hashicorp: Guest Additions Version: 6.0.10
    hashicorp: VirtualBox Version: 6.1
==> hashicorp: Mounting shared folders...
    hashicorp: /vagrant => /home/vagrant/test
```

If you must unset HOME, you should be able to instead set VAGRANT_HOME to the desired directory so that your test framework can still function with Vagrant. Hope that makes sense...thanks!
