### ISSUE TITLE
Unable to install box. 

### ISSUE THREAD

**Issue by sandersjj** [hashicorp/vagrant#11467]
### Vagrant version
Vagrant 2.2.7
Vagrant Box bento/ubuntu-16.04
Virtual Box 6.0.18

### Host operating system
Mac OS Catalina 10.15.2

### Guest operating system

bento/ubuntubento/ubuntu

### Vagrantfile

```ruby
dir = File.dirname(File.expand_path(__FILE__))

require 'yaml'
require "#{dir}/puphpet/ruby/deep_merge.rb"
require "#{dir}/puphpet/ruby/to_bool.rb"

configValues = YAML.load_file("#{dir}/puphpet/config.yaml")

provider = ENV['VAGRANT_DEFAULT_PROVIDER'] ? ENV['VAGRANT_DEFAULT_PROVIDER'] : 'local'
if File.file?("#{dir}/puphpet/config-#{provider}.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-#{provider}.yaml")
  configValues.deep_merge!(custom)
end

if File.file?("#{dir}/puphpet/config-custom.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-custom.yaml")
  configValues.deep_merge!(custom)
end

data = configValues['vagrantfile']

Vagrant.require_version '>= 1.8.1'

Vagrant.configure('2') do |config|
  eval File.read("#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}")
end
```

### Debug output

https://gist.github.com/sandersjj/3fe5f6879fea6c604f055054183d89f8

### Expected behavior

To install the box without any problems

### Actual behavior
/sbin/mount.vboxsf: mounting failed with the error: No such device

Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

### Steps to reproduce

1.Install the box mentioned
2.Install vagrant-bindfs
3.Install vagrant-vbguest

I tried to install specific versions of vagrant-bindfs and vbguest. But I keep getting this error.

**Comment by briancain** [comment]
Hey there @sandersjj - Can you please confirm if this simple Vagrantfile works for you with no plugins installed:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
end
```

The error you are seeing isn't an issue with installing the box, as it looks like from the debug log you were able to download and unpack it. The issue here seems to be that the guest additions on the box you are using aren't available.

So for example, when I use that simplified Vagrantfile, with the latest version of that box, I am able to bring up the guest and mount shared folders without issue. It's likely if you can do that with the simplified Vagrantfile, it has something to do with the plugins you are using, or your puphet Vagrantfile (which was left off the report, btw). Anyway, let us know if any of the above helps. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
