### ISSUE TITLE
Vagrant provisioning fails with the following error 

### ISSUE THREAD

**Issue by srish-bhargava** [hashicorp/vagrant#11478]
default: /tmp/vagrant-shell: line 1: apt-get: command not found
    default: sudo: dpkg: command not found
    default: /tmp/vagrant-shell: line 3: apt-get: command not found
    default: /tmp/vagrant-shell: line 5: apt-get: command not found
    default: /tmp/vagrant-shell: line 6: python3: command not found
    default: /tmp/vagrant-shell: line 7: apt-get: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! It looks like you are running a provisioner that is meant for a Debian/Ubuntu system, but the box that you're using doesn't have the Debian packaging tools installed. Would you mind posting a copy of the Vagrantfile you're using so we can confirm? Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
