### ISSUE TITLE
i need to modify disk controller mode(vm's default value is not useful) in Vagrantfile,What parameters should I use

### ISSUE THREAD

**Issue by 3479785008** [hashicorp/vagrant#11493]

**Comment by briancain** [comment]
Hey there @3479785008 - There's no supported way that I know of to change a guests disk controller. I assume you are talking about VirtualBox? Next time, please fill out the issue template that we provide instead of removing it.

You might be able to change it manually through the GUI for now while the vm is powered off: https://www.virtualbox.org/manual/ch05.html#harddiskcontrollers However, even with the recent new addition of disk management for VirtualBox, it currently only supports using the SATA controller.

If you have a feature request with a use case for this, we'll be happy to take a look. Feel free to open a new feature request issue for this. Otherwise I'm going to go ahead and close this. Thanks!
