### ISSUE TITLE
$vagrant plugin install vagrant-share fails --> fog-core version config issue

### ISSUE THREAD

**Issue by bjpcjp** [hashicorp/vagrant#11519]
### Vagrant version

2.0.2

### Host operating system

ubuntu 18.0.4 LTS

### Guest operating system

hashicorp/bionic64

### Vagrantfile

  config.vm.box = "hashicorp/bionic64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 4567

### Debug output

https://gist.github.com/bjpcjp/6c44091abd0e8e7b35b30cb0d773709a

### Expected behavior

successful plugin installation

### Actual behavior

Bundler confused by two conflicting versions of fog-core, one of which no longer exists.

### Steps to reproduce

1.  $vagrant plugin install vagrant-share
2.  $gem list --local fog-core

### References

n/a

**Comment by Tomasthanes** [comment]
I'm getting the same error.

Differences in configuration:
- Host operating system: Windows 10 (Build 18362.720)
- Guest operating system: Ubuntu 18.04 LTS

Vagrant File:
unless Vagrant.has_plugin?("vagrant-ohai")
  raise "vagrant-ohai plugin is not installed! Install with 'vagrant plugin install vagrant-ohai'"
end
...
Vagrant.configure(2) do |config|

 config.vm.define 'web1' do |n|
    n.vm.box = 'bento/centos-7.2'
    n.vm.box_version = '2.3.1'
    n.vm.hostname = 'web1'
    n.vm.network :private_network, ip: '192.168.10.43', nic_type: "virtio"
    n.vm.provision :shell, inline: NODE_SCRIPT.dup
   set_hostname(n)
  end
...
(from a Chef video training up on udemy)

Steps to reproduce
1. $vagrant plugin install vagrant-ohai
Installing the 'vagrant-ohai' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 1.45.0)
  Activated fog-core-1.45.0
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 1.45.0), 1.45.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)

**Comment by chrisroberts** [comment]
Hi there. The error that is being encountered is due to a dependency conflict with something using a later version of fog-core. The vagrant-libvirt plugin has a constraint in place that limits the allowed version to any anything >= 1.43.0 and < 1.44.0. The system installed gems have no impact on Vagrant installations using the official installers. 

Upgrading your version of Vagrant will likely help to provide with better error messages. If you are unable to determine where the dependency conflict is occurring, removing all plugins and installing again manually can help to determine where the problem is originating.

Cheers!
