### ISSUE TITLE
Windows installation fails if installer is located on a different drive to the installation target directory

### ISSUE THREAD

**Issue by iamfraggle** [hashicorp/vagrant#11529]
### Vagrant version

Issue seen on 2.2.6 and 2.2.7 installers, not tried any others.

### Host operating system

Windows 10 (1909)

### Guest operating system

N/A

### Vagrantfile

N/A

### Debug output

N/A

### Expected behavior

Vagrant should install

### Actual behavior

Installer gives popup "Error reading from file <path_to_installer>. Verify that the file exists and that you can access it."  'Retry' and 'Cancel' buttons are available.  Retry results in the same popup appearing again.  Cancel results in a failed installation.

### Steps to reproduce

1. Place installer .msi file on a drive different to the drive where you want to install Vagrant (in my case D:)
2. Run installer
3. Give desired install location that is on a different drive to where the installer is (in my case the default: C:\HashiCorp\Vagrant)

### References

N/A

If it's any help, the thing in the log file that made me try moving the installer was that I could see the variable TARGETDIR was being set to D:\, which made me suspicious.

[vagrant.log](https://github.com/hashicorp/vagrant/files/4498081/vagrant.log)

**Comment by jbonhag** [comment]
Hi there,

Thanks for letting us know about this issue! Unfortunately I wasn't able to replicate this issue, so we'll need a little more information to figure out what's going on.

I downloaded the Vagrant installer to `E:\Home\Fraggle\Windows User\Downloads`, and ran the installer using this command in a non-elevated PowerShell:

```
msiexec /lvx vagrant.log /i vagrant_2.2.7_x86_64.msi
```

Vagrant installed to C:\HashiCorp\Vagrant with no issues.

Would you mind sharing the exact command that you ran? Do you get a different result if you run the installer through the GUI as opposed to a command-line?

Also, what happens if you set TARGETDIR to `C:\`, for example:

```
msiexec TARGETDIR=C:\ /lvx vagrant.log /i vagrant_2.2.7_x86_64.msi
```

Thanks!

**Comment by iamfraggle** [comment]
Okay solved it.  The error message was actually entirely correct.  The permissions on the file did not allow access to Administrators, so when the privileges were escalated to perform the install, the admin process couldn't access the installer.  I'm assuming that when it worked I happened to move it to a location where the permissions allowed Admin access.

False alarm.  Thanks for the help.
