### ISSUE TITLE
DOCS Getting started - Provisioning, minor change.

### ISSUE THREAD

**Issue by shaun-lloyd** [hashicorp/vagrant#11594]
Not sure where to file this. But the docs are wrong.

https://www.vagrantup.com/intro/getting-started/provisioning.html

bootstrap.sh
apache default folder is /var/www/html not /var/www.

**Comment by shaun-lloyd** [comment]
bootstrap.sh
#!/usr/bin/env bash

apt-get update
apt-get install -y apache2
if ! [ -L /var/www/html ]; then
  rm -rf /var/www/html
  ln -fs /vagrant/public_html /var/www/html
fi

**Comment by briancain** [comment]
Hey there @shaun-lloyd - This is because you end up syncing your shared folder to `/var/www`. Your initial `vagrant` folder has an `html` folder, which ends up at `/var/www/html`, aka the default apache folder DocumentRoot. Otherwise you would end up syncing you html folder to `/var/www/html/html`. It might make sense to explain that you are creating the default html folder inside your Vagrant folder possibly.
