### ISSUE TITLE
Vagrant is remarkably slow

### ISSUE THREAD

**Issue by chrisdoherty4** [hashicorp/vagrant#11601]
### Vagrant version

Vagrant 2.2.7

### Host operating system

Ubuntu 18.04
Ubuntu 19.10
Ubuntu 20.04 

### Debug output

[![asciicast](https://asciinema.org/a/LhCiCu4F6HdocgbnEdKi6oaVf.svg)](https://asciinema.org/a/LhCiCu4F6HdocgbnEdKi6oaVf)

https://gist.github.com/chrisdoherty4/83fd293ccb3dc5d33f6e0394d743fdf3

### Expected behavior

`vagrant -h` takes a reasonable amount of time, along with all other commands.

### Actual behavior

The vagrant cli tool takes an obnoxiously long time to execute.

**Comment by jbonhag** [comment]
Hi @chrisdoherty4,

Would you mind creating a gist with the output of `vagrant -h --debug-timestamp` so we can assist with this issue further? Thanks!

**Comment by chrisdoherty4** [comment]
@jbonhag updated description with link

**Comment by chrisdoherty4** [comment]
@jbonhag I just made the asciicast public as well, my bad!

**Comment by chrisroberts** [comment]
Hi there,

You can easily speed up execution time by using the `.deb` package installation. You'll notice there is a discrepancy in the duration reported by `time`, and the duration shown by the timestamps in debug mode. That is because you are running the appimage, not Vagrant directly. With appimage, everything that Vagrant requires is packed into a single, compressed executable. When you run it, the contents are decompressed and attached to a temporary point in the tmp directory, at which point Vagrant is then executed.

The benefit of this is that the appimage version of Vagrant can be dropped on most linux hosts and will "just work". The drawback is there is a speed hit due to the unpacking requirement when running the command. 

So your best bet will be to install Vagrant using the `.deb` package and you'll shave off the unpacking time you are currently waiting on when running Vagrant.

Cheers!

**Comment by chrisdoherty4** [comment]
Mystery solved. Thank you!

**Comment by chrisdoherty4** [comment]
Hey

I installed the deb package and noticed that, while it's an improvement, it still seems rather slow for something as trivial as a help command. 

On average I get around 1.8 seconds for `vagrant -h`.

https://gist.github.com/chrisdoherty4/7fcd3bdd2667a66bfad8e6cdba0353d2
