### ISSUE TITLE
vagrant plugin update fails on time out

### ISSUE THREAD

**Issue by marcpaterno** [hashicorp/vagrant#11600]
### Vagrant version

Vagrant 2.2.9

### Host operating system

macOS Mojave
### Debug output

https://gist.github.com/marcpaterno/35650dd5a790f101fa91fcaecda15b8b

### Expected behavior

My out-of-date plugins should get updated.

### Actual behavior

A time out error.

### Steps to reproduce

1. vagrant plugin update

### Additional note

I can ping gems.hashicorp.com with no problem. However,

```
wget https://gems.hashicorp.com/specs.4.8.gz
```
also fails after several re-tries.

**Comment by chrisroberts** [comment]
Hi there,

This type of error is usually due to local network configuration. I have confirmed the files are all properly accessible from multiple locations. If you are on a network that proxies traffic and performs any filtering, you may need to request the domain be added to an allow list for the request to be successful. It may also be useful to set `http_proxy` environment variables, depending on your local environment.

Cheers!
