### ISSUE TITLE
Vagrant often leaves behind VirtualBox files after removing Vagrant instances

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#11659]
This has been a persistent issue since the early days. We'd love some more exit traps to ensure that provider files are properly removed upon user request to delete the Vagrant VM.

**Comment by jbonhag** [comment]
Hi there,

Would you be willing to list some scenarios where you're seeing files left behind? I did a quick `vagrant up`/`vagrant destroy` using the `hashicorp/bionic64` box and I don't see any VirtualBox files left in `.vagrant` or `$HOME/VirtualBox VMs`.

Thanks!

**Comment by chrisroberts** [comment]
Hi there. I'm going to close this issue due to lack of any relevant and actionable details. If you feel that this issue is valid and represents a bug within Vagrant, please provide a detailed description by filling out the information requested by the new issue template. Please be sure to include the current behavior, the expected behavior, and a simple Vagrantfile to reproduce the state you are encountering.

Cheers!
