### ISSUE TITLE
Vagrant lock read_state in 2.2.9 new behaviour breaking vargrant usage.

### ISSUE THREAD

**Issue by Yivan** [hashicorp/vagrant#11700]
### Vagrant version
2.2.9

### Host operating system
Windows 10 Pro

### Guest operating system
Debian Buster

### Vagrantfile

```ruby
# ...
    config.trigger.after [:up, :reload, :resume] do |t|
      t.name = "Do something"
      t.run = { :inline => "vagrant ssh -c '/path/to/script/myscript.sh'" } 
    end
# ...
```

### Debug output

==> vagrant-docker: Running trigger: Do something...
    vagrant-docker: Running local: Inline script
    vagrant-docker: vagrant ssh -c '/path/to/script/myscript.sh'
    vagrant-docker: An action 'read_state' was attempted on the machine 'vagrant-docker',
    vagrant-docker: but another process is already executing an action on the machine.
    vagrant-docker: Vagrant locks each machine for access by only one process at a time.
    vagrant-docker: Please wait until the other Vagrant process finishes modifying this
    vagrant-docker: machine, then try again.

### Expected behavior

It happen on the latest Vagrant version. On previous 2.2 release it was working ok.

### Actual behavior

Cannot no more call vagrant command in triggers, as inline command or as well in path script which call vagrant commands.

### Steps to reproduce

Add a trigger like in the code snippet and make vagrant up.

This is really a big regression, or a new feature/change which should have been introduced in major vagrant version.
It breaks totaly the usage of our VMs for our team. We have rather complexe vagrantfile, some of them call vagrant command (ssh, reload, up, halt) during the main vagrant command up.

I hope it can be fixed/restored.

Thanks.

**Comment by chrisroberts** [comment]
Hi there,

This does not appear to be a regression within Vagrant. Starting a new Vagrant process from a running Vagrant process is not recommended and the results of that behavior can only be classified as "undefined". This is due to the various checks and locks Vagrant performs during an execution to prevent multiple executions from attempting to perform modifications on a guest in parallel. In the example you provide, a remote file is being executed on the guest. Triggers provide a mechanism to perform the same task without requiring a new instance of Vagrant to be spawned:

```ruby
# ...
    config.trigger.after [:up, :reload, :resume] do |t|
      t.name = "Do something"
      t.run_remote = { :inline => "/path/to/script/myscript.sh" } 
    end
# ...
```

The `run_remote` can also handle things like rebooting the guest (for guests with supporting reboot capabilities). If there is a specific use case that the triggers configuration is unable to support and you feel like it should, please feel free to open an enhancement issue.

Cheers!

**Comment by Yivan** [comment]
Thanks for your fast reply on this.
I totally understand it has been done to prevent some race condition (calling vagrant command inside vagrant command need strict scripts coding with rigorous check on status).
Just hoping we won't have no more surprise on such change on minor update ; )

In the meantime I recoded our scripts to not use vagrant command inside script but use hyperv or vbox cli command directly. All is working great now : ))

I wasn't aware of this run_remote, i read the documentation, yes it will do it for remote ssh command to run from trigger. Thanks!

For those wanting to SSH inside a script called by `vagrant up`, for instance we use this:
`ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$VM_METADATA_PATH"/machines/"$VM_HOSTNAME"/hyperv/private_key -q vagrant@"$VAGRANT_IP" "linux command here"`  (variable are pretty self explanatory).

I confirm this isue could be close so.
Best regards.

**Comment by chrisroberts** [comment]
@Yivan You shouldn't need to call out to `ssh`. The `run_remote` option that I showed in my last comment will accomplish the same thing as the `ssh` command you are running. And since it supports the same options that provisioners do, you can also use it for rebooting if needed:

https://www.vagrantup.com/docs/provisioning/shell#reboot

Cheers!

**Comment by Yivan** [comment]
Yes I saw this reboot option, but i wasn't thinking I can call it with trigger. Great news !
Thanks again for your help.
