### ISSUE TITLE
Vagrant destroy triggers are not working as expected

### ISSUE THREAD

**Issue by AnmSaiful** [hashicorp/vagrant#11722]
### Vagrant version

2.2.6

### Host operating system

Windows 10 Pro, v1909, build-18363.900

### Guest operating system

centos/7 (virtualbox, 1905.1)

### Vagrantfile

```ruby
Vagrant.configure( '2' ) do | config |

    config.trigger.before :destroy do | trigger |

        puts "Before destroy"

    end

    config.trigger.after :destroy do | trigger |

        puts "After destroy"

    end
end
```

### Expected behavior

`Before destroy` and `After destroy` should be printed only once the `vagrant destroy` command is executed.

### Actual behavior

But it is printed with all the vagrant commands, for example `vagrant up`.

### Special note

It works with the `vagrant-triggers` plugin.

**Comment by chrisroberts** [comment]
Hi there,

You are seeing multiple outputs because you are printing output directly from the block. Configuration blocks within the Vagrantfile can (and many times are) read multiple times in a single run, which is what is causing you to see the output every time. Updating your trigger block to use the trigger output methods will make it behave in the expected manor:

```ruby
Vagrant.configure( '2' ) do | config |
    config.trigger.before :destroy do | trigger |
        trigger.info "Before destroy"
    end
    config.trigger.after :destroy do | trigger |
        trigger.info "After destroy"
    end
end
```

or, if you want to use `puts`, you can use the `ruby_block` option:

```ruby
Vagrant.configure( '2' ) do | config |
    config.trigger.before :destroy do | trigger |
        trigger.ruby do
          puts "Before destroy"
        end
    end
    config.trigger.after :destroy do | trigger |
        trigger.ruby do
          puts "After destroy"
        end
    end
end
```

You can find more information around trigger usage here: https://www.vagrantup.com/docs/triggers/usage

Cheers!

**Comment by AnmSaiful** [comment]
Excellent! It works. Thank you so much for the prompt response. :-)
