### ISSUE TITLE
QUESTION: Is it possible configure property for Vagrant user?

### ISSUE THREAD

**Issue by sasadangelo** [hashicorp/vagrant#11720]
Hi all,

First of all, excuse me if this is not the right place where to submit my question. Reading the documentation I haven't found a solution and for this reason, I think it could be valid to log it as a feature request.

I have a program code that I need to test with Vagrant on VirtualBox. This software creates a user with UID 1000 (for several reasons) but when I provision it on Vagrant I got an error because the UID of the software user conflicts with the default vagrant user that has UID 1000 by default (I think because it is the first allocable UID in Linux).

Is there a way to assign to the vagrant user a different UID?

I checked the documentation and I don't see any option.

I would like something that allows me in the Vagrant file to specify the id to assign to the vagrant user.

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! There isn't really an easy way to change the UID for the Vagrant user. However, many boxes on Vagrant Cloud publish Packer templates so you could build a custom Vagrant box with a different UID for the vagrant user.

For example, if you wanted to use one of the Bento box templates as a starting point, you could change the uid in the following line from `1000` to `1001`, and that would leave UID 1000 available for the software user.

https://github.com/chef/bento/blob/master/packer_templates/ubuntu/http/preseed.cfg#L24

The challenge with changing the UID inside an active VM is that the vagrant user has to be logged in to run commands on the guest. But you could do something like this:

1. Create a software user (e.g. UID 1001)
2. Add software user to sudoers file
3. SSH in as software user
4. Change UID for vagrant user (e.g. UID 1002)
5. Change ownership for vagrant files to new UID
6. SSH in as vagrant user
7. Change UID for software user (e.g. UID 1000)
8. Change ownership for software user files to new UID

This is going to be difficult to automate, which is why I'd recommend building a custom box, especially if you're interested in reusing it or sharing it with others.

Finally, [HashiCorp Discuss](https://discuss.hashicorp.com/c/vagrant/24) is a great place to ask general Vagrant questions.

Cheers! 😄
