### ISSUE TITLE
Boxes download very slow

### ISSUE THREAD

**Issue by brentclark** [hashicorp/vagrant#11730]
Good day

Id like to report there is an issue with your provider of boxes. 
It would appear your provider is AWS. 

virtualbox.box               3%[+                                     ]  11.03M  9.17KB/s    eta 8h 36m

Regards
Brent

**Comment by jbonhag** [comment]
Hi there,

Thanks for reporting this issue! Box downloads can occasionally be slow depending on where you're located due to the performance of S3. Some boxes are also hosted on external servers, which unfortunately we can't control the performance of.

For S3-backed boxes, we have decided to implement a CDN to aid with box delivery which should result in a performance gain in all regions. Please keep an eye on #11354 for further updates regarding this feature.

Cheers! 😄
