### ISSUE TITLE
Vagrant Homestead Windows 10 Pro, Hyper v not working.

### ISSUE THREAD

**Issue by TonyTheDev1919** [hashicorp/vagrant#11874]
Vagrant requires administrator access to create SMB shares and
may request access to complete setup of configured shares.
Exporting an SMB share failed! Details about the failure are shown
below. Please inspect the error message and correct any problems.

Host path:

Stderr:

Stdout:

**Comment by soapy1** [comment]
Hey there, thanks for opening up an issue. In order to understand what is going wrong with Vagrant we'll need a bit more information. Could you share:
* the version of Vagrant you are running
* the host and guest OS
* a copy of your Vagrantfile
* the debug output (https://www.vagrantup.com/docs/other/debugging)

thanks!

**Comment by TonyTheDev1919** [comment]
My antivirus was blocking poweshell.exe
