### ISSUE TITLE
Question: ARM64 (Apple Silicon) Support

### ISSUE THREAD

**Issue by strega-nil** [hashicorp/vagrant#12051]
Hey all!

We on the vcpkg team are wondering if there are any plans to support Apple Silicon as a host/target, and what y'all would recommend for doing that? If the answer is just "wait for VirtualBox support", that's fine and I understand.

Thanks,
Nicole

**Comment by chrisroberts** [comment]
Hi,

We currently are planning on supporting darwin ARM. In the immediate term, rosetta 2 _should_ handle running Vagrant, and in the near term future we'll be distributing universal packages (once we have some hardware to start messing with). 

Vagrant itself running on ARM is different than the providers Vagrant utilizes running on ARM. Right now, VMware Fusion is currently compatible to run on ARM due to Fusion no longer using kexts and relying completely on the virtualization and vmnet frameworks provided by macOS. This change has also resulted in networking issues that have not yet been resolved (like port forwarding to the loopback is not working, creating custom networks with defined subnet/mask not working). As for VirtualBox, I have not seen any sign that they will be supporting the ARM architecture (https://forums.virtualbox.org/viewtopic.php?t=98742#p479067).

And all of this is still ignoring the fact that as of currently, I am unaware of any way to run x86 virtualization via the macOS virtualization framework on ARM hardware. At this point most discussions around it seem to be glossed over with "running Windows" which after digging have so far always referred to an ARM version of Windows. If I am mistaken and there is some sort of support for x86 virt via the macOS virtualization framework I will be very delighted. But as of now, I haven't seen any sign of it.

Hope that answers the question well enough. If you have more questions around this, please feel free to post over on discuss (https://discuss.hashicorp.com/c/vagrant/24) which is a little better geared towards questions/conversation.

Cheers!

**Comment by strega-nil** [comment]
Thanks so much @chrisroberts :)
