### ISSUE TITLE
Authentication w/ Vagrant Repo Failing in 2.2.13 and 2.2.14

### ISSUE THREAD

**Issue by bellds** [hashicorp/vagrant#12079]
### Vagrant version
2.2.13 and 2.2.14

### Host operating system
macOS v11.0.1 (Big Sur)

### Guest operating system
N/A

### Expected behavior
Upgrading Vagrant from v2.2.4 to v2.2.13 or 2.2.14 should break the authentication capabilities with a Vagrant Repo - if the authentication was working in v2.2.4 then it should continue to work in later versions of vagrant.

### Actual behavior
Neither vagrant v2.2.13 or 2.2.14 are authenticating properly with my vagrant repo.  I am getting a 401 with my repository after upgrading to these two versions.  If I downgrade my vagrant back to 2.2.4 then vagrant authenticates with the vagrant box repository without issue.

### Debug Output
[vagrant2.2.4-AddDebug-Redacted.log](https://github.com/hashicorp/vagrant/files/5599133/vagrant2.2.4-AddDebug-Redacted.log)
[vagrant2.2.13-AddDebug-Redacted.log](https://github.com/hashicorp/vagrant/files/5599134/vagrant2.2.13-AddDebug-Redacted.log)
[vagrant2.2.14-AddDebug-Redacted.log](https://github.com/hashicorp/vagrant/files/5599137/vagrant2.2.14-AddDebug-Redacted.log)

**Comment by motazEmad** [comment]
I faced this issue too, using vagrant v2.2.14, on operating system: windows 10 enterprise

running below commands: 
`curl -u "myuser" "https://#internalArtifactoryUrl#/api/vagrant/auth"
%output_Token%

set ATLAS_TOKEN=%output_Token%
set VAGRANT_SERVER_URL=https://#internalArtifactoryUrl#/api/vagrant/myproject

vagrant box add "https://#internalArtifactoryUrl#/api/vagrant/myproject/base"`

The result that vagrant was not able to get the metadata of the box due to authentication failed

After uninstalling vagrant v2.2.14, and installing v2.0.4 it worked swiftly

**Comment by shailygupta** [comment]
I am facing the same issue as well, it looks like this is due to the HTTP headers introduced in version 2.2.11 (https://github.com/hashicorp/vagrant/issues/12080)

**Comment by chrisroberts** [comment]
Closing this and keeping #12080 open to track this issue.
