### ISSUE TITLE
vagrant up failed - split: bad URI

### ISSUE THREAD

**Issue by Ed87** [hashicorp/vagrant#12082]
### Vagrant version

2.2.14 

### Host operating system

Windows 10 Build 18863

### Guest operating system

Linux.

### Vagrantfile

```
# Vagrant.configure("2") do |config|
  config.vm.box = "cb-training-pipeline-fundamentals-1588693109"
  config.vm.box_url = "cb-training-pipeline-fundamentals-1588693109.box"
end
```

### Debug output

https://gist.github.com/Ed87/0490c316dfb8dedd08f8629ae4483979

### Expected behavior

VM should fire up without any issues

### Actual behavior

The VM is not booting but rather throwing up errors for a bad URI. The URI being referenced is my corporate proxy settings for Git Bash. 
I have already unset corporate proxy for Bash using  
git config --global --unset https.proxy
git config --global --unset http.proxy

Verified the same using 
git config --global -l (There are no proxies configured for Bash)

I am not working behind a corporate proxy but rather a private wifi network -- I have also diasbaled proxy in Windows settings

### Steps to reproduce

1. Install Vagrant and VirtualBox
2. Download VM's ZIP archive and extract to desktop 
3. cd to un-archived folder 
4. Run vagrant up 

### References

- https://github.com/udacity/fullstack-nanodegree-vm/issues/107
- https://stackoverflow.com/questions/26414803/vagrant-proxyconf-split-bad-uri-error-on-installing-plugin-for-vagrant

**Comment by soapy1** [comment]
Hey there, thanks for submitting an issue. Could you provide a full debug gist

```
$ vagrant up --debug 2>&1 | Tee-Object -FilePath ".\vagrant.log"
```

**Comment by Ed87** [comment]
What is " -FilePath" .

Is it a variable for the path to that log file or i just run the command
as-is.


Regards

**Comment by soapy1** [comment]
`-FilePath` is an argument to give to [`Tee-Object`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/tee-object?view=powershell-7.1). In this case it will output the logs to the screen and to the file `.\vagrant.log`.

**Comment by Ed87** [comment]
Ok, thanks for the clarification.

**Comment by Ed87** [comment]
Good Day ,

Find attached the log .

**Comment by Ed87** [comment]
Added gist 
[vagrant.log](https://github.com/hashicorp/vagrant/files/5621379/vagrant.log)

**Comment by soapy1** [comment]
So, it looks like you are trying to reference a local box to use? If so, you can give the full path to the box to `config.vm.box`

```
Vagrant.configure("2") do |config|
  config.vm.box = "/full/path/to/cb-training-pipeline-fundamentals-1588693109.box"
end
```

**Comment by Ed87** [comment]
I have done so ,
![VG2](https://user-images.githubusercontent.com/23119187/100820768-9dd96000-3457-11eb-9e0f-ab8480058482.JPG)
![VG1](https://user-images.githubusercontent.com/23119187/100820786-a6ca3180-3457-11eb-82f2-3b1c70b7a16d.JPG)

 same exception :

**Comment by Ed87** [comment]
I  have done either of the below and im still getting same error message :

[image: VG2.JPG]


[image: VG1.JPG]

Regards,

**Comment by soapy1** [comment]
You shouldn't need to provide a `box_url` if you provide a full path to the box with the `box` option. So, you can remove the `box_url` option from the Vagrantfile. 
However, I'm not sure where Vagrant is pulling this url from. Do you have any Vagrant environment variables set to `http://useranme:@password.xx.xx.xx:8080/`?

**Comment by roland-urban** [comment]
Hello, I have the same problem since today.

After a Windows update to version "Windows 10 Pro 20H2 19042.662" I have the same problem today with all vagrantfiles that worked yesterday.

I have updated Vagrant from 2.2.13 to 2.2.14 to 2.2.15.dev but the error message remains.

Here is a simple test-case after "Vagrant Init" with the log file as attachment.
`
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
end
`

[vagrant.log](https://github.com/hashicorp/vagrant/files/5647044/vagrant.log)

**Comment by chrisroberts** [comment]
This looks to be either the same or related issue raised in #12080

**Comment by soapy1** [comment]
Looking into this issue a little bit more, the issue arises due to an invalid URI hanging around in an environment variable.
This error is coming from the `excon` library when its doing it's [proxy configuration](https://github.com/excon/excon/blob/c32e416da37b49c7f697391c86b32a28d3178355/lib/excon/connection.rb#L513). In particular, it looks like its taking the environment variable [`HTTP_PROXY` or `HTTPS_PROXY`](https://github.com/excon/excon/blob/c32e416da37b49c7f697391c86b32a28d3178355/lib/excon/connection.rb#L536). The library has some instructions for [how to setup proxies](https://github.com/excon/excon#proxy-support). You should be able to set the environment variable `NO_PROXY` to disable this feature. 

In the case that you do want to have a proxy setup, you can test to see if the URI is valid by trying it out in a ruby repl, eg.
```
irb(main):020:0> URI.parse("http://127.0.0.1:3128/")
=> #<URI::HTTP http://127.0.0.1:3128/>
irb(main):021:0> URI.parse("127.0.0.1:3128")
Traceback (most recent call last):
        7: from /Users/sophia/.rbenv/versions/2.7.1/bin/irb:23:in `<main>'
        6: from /Users/sophia/.rbenv/versions/2.7.1/bin/irb:23:in `load'
        5: from /Users/sophia/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        4: from (irb):21
        3: from /Users/sophia/.rbenv/versions/2.7.1/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
        2: from /Users/sophia/.rbenv/versions/2.7.1/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
        1: from /Users/sophia/.rbenv/versions/2.7.1/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split'
URI::InvalidURIError (bad URI(is not URI?): "127.0.0.1:3128")
```

ref: RFC for URIs https://www.ietf.org/rfc/rfc2396.txt (Also note the section on "Reserved Characters")
