### ISSUE TITLE
Why does vagrant up have a documented default indicating the VM should be destroyed on error?

### ISSUE THREAD

**Issue by electrofelix** [hashicorp/vagrant#12098]
I'm currently getting questions about why vagrant-libvirt is destroying the domain (libvirts name for a VM) on error and referencing hashicorp/vagrant#11692 as indicating that upstream (vagrant) consider it an issue with vagrant-libvirt.

Someone has noted that they have recently run into this in vagrant-libvirt/vagrant-libvirt#1122

Given the CLI help output:
https://github.com/hashicorp/vagrant/blob/a15fc2640d0ddf40bd35aa29ad4edb826417eecb/plugins/commands/up/command.rb#L32-L35

And the statements in hashicorp/vagrant#11692

> In the plugin, when an error occurs, it attempts to recover the action stack: https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/wait_till_up.rb#L97 which can end up calling the Destroy action. So in this case, it calls that action, and DestroyDomain is called. But this is all isolated to the vagrant-libvirt plugin, so the fix will be there.

What is the expected behaviour of the the `vagrant up --destroy-on-error` and `vagrant up --no-destroy-on-error`, because it seems that matching the option docstring behaviour is considered a bug in vagrant-libvirt.

If the intention is that providers should not destroy their VM when this option is set to true, I think maybe the docstring should be changed to reflect that

**Comment by chrisroberts** [comment]
Hi @electrofelix,

The expected behavior when the option is true (`--destroy-on-error`) is that if an error is encountered during the `vagrant up` process, it should destroy the guest. If the option is false (`--no-destroy-on-error`) then the guest should remain in what ever failed state it encountered so the user can then inspect it.

I believe that, based on the issue linked, everything is behaving as expected. It was just being pointed out that the plugin is responsible for calling the actions (not Vagrant itself in this case) and that if it were unexpected or a bug, it's not something we could fix. 

If I didn't fully answer your question, or I'm missing something else, just let me know and I'll be happy to open this back up :slightly_smiling_face: 

Cheers
