### ISSUE TITLE
Virtual Machine Hangs while provisionning inline powershell script

### ISSUE THREAD

**Issue by linzeyan** [hashicorp/vagrant#12092]
### Vagrant version
```shell
$ vagrant -v
Vagrant 2.2.14
```
### Host operating system

`Windows 10 Pro 2004`

### Guest operating system

`Windows Server 2019`

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.box_check_update = false
  config.vm.hostname = "win1"
  config.vm.define vm_name = "win1"
  config.vm.provider "hyperv"
  config.vm.network "public_network", bridge: "External-VSwitch"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.winrm.max_tries = 20
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 20

  $script = <<-'SCRIPT'
    netsh.exe interface ip set address "Ethernet" static 192.168.20.199 255.255.255.0 192.168.20.1
  SCRIPT

  config.vm.provider "hyperv" do |hv|
    hv.cpus = "2"
    hv.memory = "2048"
    hv.vmname = "win"
    hv.auto_start_action = "StartIfRunning"
    hv.enable_virtualization_extensions = true
    hv.linked_clone = true
    hv.ip_address_timeout = 240
  end

  config.vm.provision "shell", privileged: "true",  inline: $script
end
```

### Debug output

https://gist.github.com/linzeyan/1f8d78bf81429afd99a79a55cea8cf76

### Expected behavior

The VM should have been configured properly, and command `vagrant up` should exit correctlly.

### Actual behavior

The IP address is properly set.
But command `vagrant up` hangs.

### Steps to reproduce

1. `vagrant up`

**Comment by chrisroberts** [comment]
Hi there,

The issue is occurring due to the provision script modifying the guest machine address which causes the current connection to the guest machine to be dropped and timeout. You may be able to work around this by forcing the communicator to be reset:

https://www.vagrantup.com/docs/provisioning/shell#reset

or by configuring the desired address and rebooting the guest:

https://www.vagrantup.com/docs/provisioning/shell#reboot

Cheers
