### ISSUE TITLE
"Guest-specific operations were attempted on a machine that is not ready for guest communication."

### ISSUE THREAD

**Issue by keypulse** [hashicorp/vagrant#12206]
### Vagrant version
2.2.6

### Host operating system
Ubuntu 20.04.02 LTS
$ uname -a
Linux werk 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Guest operating system
RHEL 7.5
$ uname -a
Linux comp6 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

### Vagrantfile

```ruby
  config.vm.define "comp6", autostart: false do |comp6|
    configureRhel7 comp6
    comp6.vm.provider :virtualbox do |v|
      v.memory = 3000
      v.cpus = 3
    end
    comp6.vm.hostname = 'comp6.ics.test'
    comp6.vm.network :private_network, ip: '172.16.254.213'
    comp6.registration.name = 'comp6.ics.test'
    comp6.registration.serverurl = reg_serverurl
    comp6.registration.baseurl = reg_baseurl
    comp6.registration.ca_cert = reg_cacert
    comp6.registration.activationkey = 'aci-development-7Server-Vagrant'
    comp6.registration.auto_attach = true
    comp6.registration.org = 'ICS-ACI'
  end
```

### Debug output

This has not happened before nor after, as I ran in debug=info and planned on pasting the log to gist.

### Expected behavior
vagrant up comp6 -> normal output and complete vagrant node started successfully

What should have happened?
vagrant node should have been completed OK and up as expected

### Actual behavior
$ vagrant up comp6
Bringing machine 'comp6' up with 'virtualbox' provider...
==> comp6: Importing base box 'ics/rhel7'...
==> comp6: Matching MAC address for NAT networking...
==> comp6: Setting the name of the VM: slurm-vagrant_comp6_1614017429123_89833
==> comp6: Fixed port collision for 22 => 2222. Now on port 2200.
==> comp6: Clearing any previously set network interfaces...
==> comp6: Preparing network interfaces based on configuration...
    comp6: Adapter 1: nat
    comp6: Adapter 2: hostonly
==> comp6: Forwarding ports...
    comp6: 22 (guest) => 2200 (host) (adapter 1)
==> comp6: Running 'pre-boot' VM customizations...
==> comp6: Booting VM...
==> comp6: Waiting for machine to boot. This may take a few minutes...
    comp6: SSH address: 127.0.0.1:2200
    comp6: SSH username: vagrant
    comp6: SSH auth method: private key
    comp6:
    comp6: Vagrant insecure key detected. Vagrant will automatically replace
    comp6: this with a newly generated keypair for better security.
==> comp6: Machine booted and ready!
**Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.**

What actually happened?
comp6 booted, but with vagrant hostname (instead of specified one) and gave the mentioned error, informing me to report a bug.

### Steps to reproduce
I was not able to reproduce myself, this was a one-off but still should be reported.  I halted comp6, VAGRANT_DEBUG=info vagrant up and it came up as expected.

### References
N/A

Are there any other GitHub issues (open or closed) that should be linked here?
I didn't find any with this error.

**Comment by chrisroberts** [comment]
Hi there,

Without access to the box to reproduce the error locally, the only help I can really provide is my best guess at the cause of the error. Based on the timing of the error, I would assume that Vagrant is attempting to connect to the guest again with the newly generated key pair, and that the connection cannot be established. The most common cause of this issue, from my experience, is due to the network configuration with the box not being fully stable with what is generated when a new guest is created. This results in the adapter used for the nat connection to request a new dhcp lease, drop the current address, and acquire a new one. 

I'd say the best bet is to start a new guest, and then run through the system logs for when the guest was starting up and look for network device changes, specifically if an address was acquired, and then dropped and re-acquired. Usually this can occur due to device naming changes but the logs will help to provide more context for they way.

Hope that helps!
