### ISSUE TITLE
Multiple local synced_folder plugins break default folder sharing

### ISSUE THREAD

**Issue by vohi** [hashicorp/vagrant#12208]
### Vagrant version

2.2.14

### Host operating system

macOS 10.15.7

### Guest operating system

Various: Linux (general/ubuntu2004), Windows (own box)
Providers: virtualbox, vmware_desktop, azure

### Vagrantfile

The following is a very stripped down version. I implement two local synced-folder plugins in my local project (ie. not proper vagrant plugins). Once I have two such plugin classes, the default folder syncing no longer happens, and is instead attempted through the second plugin (ie the mutagen plugin in this case).

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.2.4"

require "vagrant/capability_host"

module CloudTools
  class Plugin < Vagrant.plugin("2")
    name "Cloud tools"
    synced_folder(:cloud) do
      SyncedFolder
    end
  end

  class SyncedFolder < Vagrant.plugin("2", :synced_folder)
    def usable?(machine, raise=false)
      return true
    end
    def enable(machine, folders, options)
      folders.each do |id, folder|
        machine.ui.info "Preparing the cloud #{folder[:hostpath]} => #{folder[:guestpath]}"
      end

    end
  end
end

module Mutagen
  class Plugin < Vagrant.plugin("2")
    name "Mutagen.io based syncing"
    synced_folder(:mutagen) do
      SyncedFolder
    end
  end

  class SyncedFolder < Vagrant.plugin("2", :synced_folder)
    def usable?(machine, raise=false)
      return true
    end
    def enable(machine, folders, options)
      folders.each do |id, folder|
        machine.ui.info "mutagen sync create #{folder[:hostpath]} => #{folder[:guestpath]}"
      end
    end
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder ".", "/stuff"
  config.vm.synced_folder "/tmp", "/tmp/cloud_tools", type: :cloud
  config.vm.synced_folder "~", "/home/me", type: :mutagen
end
```

### Debug output

https://gist.github.com/vohi/ff6fad99b6a54e4f51d980e349b52115

The regular output shows the problem:

```
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Preparing the cloud /private/tmp => /tmp/cloud_tools
==> default: mutagen sync create /Users/vohi => /home/me
==> default: mutagen sync create /Users/vohi/vagrantbug => /stuff
```

### Expected behavior

Each folder should be synced through a different  implementation: "." via the default folder mounting, /tmp via the first plugin, ~ via the mutagen plugin.

### Actual behavior

Instead, folder that should be shared via default folder sharing are shared via mutagen.

The contents of the synced_folders cache in `.vagrant/machines/default/virtualbox` are

```
{"cloud":{"/tmp/cloud_tools":{"type":"cloud","guestpath":"/tmp/cloud_tools","hostpath":"/private/tmp","disabled":false,"__vagrantfile":true}},"mutagen":{"/home/me":{"type":"mutagen","guestpath":"/home/me","hostpath":"/Users/vohi","disabled":false,"__vagrantfile":true},"/stuff":{"guestpath":"/stuff","hostpath":"/Users/vohi/vagrantbug","disabled":false,"__vagrantfile":true}}}`
```

Event the default-synced folder has type "mutagen".

### Steps to reproduce

`$ vagrant up`

To see the issue not happening, you have to remove the second plugin implementation (ie remove the

```
synced_folder(:mutagen) do
  SyncedFolder
end
```

stanza). It is NOT enough to not use the plugin.

**Comment by soapy1** [comment]
This is happening because if no synced folder type is specified then Vagrant tries to guess at the default synced folder type. The algorithm for this is something like:

1. Get together all the synced folder plugins that are available
2. Order the plugins by priority (the default priority is 10). The higher the priority numbered plugins are tried before the lower priority ones
3. Go through the list of plugins, take the first plugin that is "usable"

In order to ensure that the cloud and mutagen plugins don't interfere with the builtin plugins you can set the priority for them. That will look something like:

```
class Plugin < Vagrant.plugin("2")
    name "Cloud tools"
    synced_folder(:cloud, 9) do
      SyncedFolder
    end
  end
```

This will set the priority of the plugin to "9", instead of the default "10". So, synced folders that do not have a specific type defined like `config.vm.synced_folder ".", "/stuff"`, should be mounted as one of the other builtin synced folder types (given that those plugins are indeed usable).

Making the modification for the priority of the cloud and mutagen plugins I got the desired results: 
```
<snip>
==> default: Preparing the cloud /private/tmp => /tmp/cloud_tools
==> default: mutagen sync create /Users/sophia => /home/me
==> default: Mounting shared folders...
    default: /stuff => /Users/sophia/project/vagrant
```

**Comment by vohi** [comment]
Awesome, thanks a ton!
