### ISSUE TITLE
RFE - bring back the ability to set an ip with VMware provider on BigSur

### ISSUE THREAD

**Issue by AntonioMeireles** [hashicorp/vagrant#12218]
@chrisroberts 

on https://github.com/hashicorp/vagrant/issues/12122 and quoting you stated :

> (...) The latest version of the vagrant vmware utility includes specialized error messages for vmware fusion on big sur when attempting to set private network addressing on guests. It is no longer supported due to fusion moving to the vmnet framework on macos instead of using their own vmnet implementation. 
>
>  @chrisroberts in https://github.com/hashicorp/vagrant/issues/12122#issuecomment-773508630

would you consider to get this functionality back through the vagrant-vmware-desktop by taking advantage of macOS's [`bootpd` machinery](https://www.unix.com/man-page/osx/5/bootptab/)  as an workaround  until VMware and Apple get it right on their side ? 

Basically, and at sight, one would still loose the ability to set custom netmasks *but* could at least lock again the IP by having a line edited in `/etc/bootptab`.  (with format `## hostname hwtype hwaddr ipaddr bootfile`) and then force it's consumption (`sudo killall -1 bootpd` on macOS host)

FWIW I mostly use Vagrant with Fusion Pro to test _stuff_, and the loss of the ability to set an IP in a private_network in Big Sur is a major deal breaker for me that messes with almost everything :/, so getting this back somehow would really, really be a major step forward. 

Thanks in advance and a great weekend!

António

**Comment by chrisroberts** [comment]
Hi there,

Unfortunately, this is not something that is possible for us to do. I spent quite a bit of time working on functionality to create custom network devices and configuring them to match the previous functionality found with macOS and Fusion prior to Big Sur. It couldn't be finalized, however, due to the fact that once the new network device exists, there is no way to connect that device to the Virtual Machine. The best we could, given the constraints imposed by the platform, was create in internal implementation to get port forwarding in a working state (though it's just tunneling, not actually forwarding). 

If the virtualization framework adds support for creating networking devices attached to specific devices, I'll be happy to take another swing at it. But until then, there's not much that we can do about the missing feature.

Cheers!

**Comment by AntonioMeireles** [comment]
@chrisroberts 

thanks for your prompt and frank reply!

(thinking loud) in the meantime would be possible to tweak the vagrant vmware utility to just have some sort of  flag (non default) that resorted to the previous behaviour ? (i.e. still doing nothing **but** not blocking possibility of user setting manually ip in vagrantfile -  just printing a BIG warning instead). 

_rationale_ is ... that ressurrected `ip: ...` wouldn't do anything as now from utility PoV but would be respected by otter plugins that depend on it (like say `vagrant-hostsupdater`)... **and** then if user **also** manually set a macaddress in the Vagranfile for each VM **and** manually edited `/etc/bootptab` to match things would, at sight, just behave as they had in the past. or even that isn't possible ?

thanks in advance and thanks for your great work!

**Comment by chrisroberts** [comment]
So, what you are suggesting would be possible, but I am super hesitant about including any kind of workarounds that attempt to hide the actual problem. From the "getting things to work" point of view, the suggestion is very practical. However, this allows things to seem like they are working correctly when in reality they are actually broken. 

Since the feature is missing in Fusion, and cannot be added into Fusion unless support for it is added to the macos virtualization / vmnet frameworks, it feels much safer to work under the assumption that the functionality will not be available. While this is an annoyance for users with previously working Vagrantfiles and plugin authors, the result of the required fixes is everything acts as expected. What is exceedingly difficult with introducing workaround behavior when an expected feature is broken or missing is that it is very hard to understand the implications a workaround may have on existing plugins or user environments. In some cases it may allow things to work as expected. In other cases, though, things may break in hard to understand ways.

Thank you for the suggestions, and I wish that I could provide a better answer/response to this request other than having to just handle the loss of the feature. I know this change has caused a lot of issues for people's setup and usage with Vagrant. It's one of the reasons I'm avoiding Big Sur until it's absolutely necessary. 

Cheers!

**Comment by AntonioMeireles** [comment]
@chrisroberts 

thnxs!
