### ISSUE TITLE
vagrant ssh not working after migrating box to new machine - exit status 255

### ISSUE THREAD

**Issue by pedrocaseiro** [hashicorp/vagrant#12269]
### Vagrant version
2.2.9

### Host operating system

Windows 10 PRO

### Guest operating system

debian10

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 3002, host: 3002 
  config.vm.network :forwarded_port, guest: 4000, host: 4000
  config.vm.network :forwarded_port, guest: 5432, host: 5432
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 4002, host: 4002
  config.vm.network :forwarded_port, guest: 3006, host: 3006
  config.vm.network :forwarded_port, guest: 7000, host: 7000
end

```

### Debug output

https://gist.github.com/pedrocaseiro/b1614eed54dba7052624f011bb104c91

### Expected behavior

It should have SSH'd

### Actual behavior

Had a debian vagrant box (using virtualbox) in my windows 10 machine. Did a factory reset on my machine, but before that I've saved the debian machine and the vagrant files to an external hard disk. Pasted the files back again after the factory reset and changed the machine's path on virtualbox to match the new path. Running `vagrant up` spins up the machine in virtualbox but hangs at the SSH part. Trying to ssh with `vagrant ssh` also hangs. Seems to be an ssh/keys configuration problem.

Create a new debian box works perfectly.
### Steps to reproduce

1. `vagrant up`
2. `vagrant ssh`

**Comment by avoidik** [comment]
should `Net::SSH::Exception` be added to `SSH_RETRY_EXCEPTIONS` too? what do you think @chrisroberts?

**Comment by chrisroberts** [comment]
@avoidik No, that wouldn't help here as there is likely something else wrong.

@pedrocaseiro This isn't something we'll likely be able to help debug since it's not something that we can really reproduce locally. My best guess is that the virtual machine is improperly configured due to the manual copy and it's failing to properly start up. The best way to begin diagnosing the problem is to open the virtual machine UI from the VirtualBox GUI. This way you can see if the virtual machine is even able to properly boot up. If it is, you can log into it from the UI and test to see if there is some sort of networking configuration issue or if the sshd service isn't starting for some reason. 

The other alternative, and likely the easiest, is to just destroy the guest and `vagrant up` a new one, but do note that anything within existing guest would be deleted. 

Cheers!
