### ISSUE TITLE
Problem fetching box from Artifactory 

### ISSUE THREAD

**Issue by tomasnorre** [hashicorp/vagrant#12261]
### Vagrant version

`2.2.15`

### Host operating system

Ubuntu 20.04

### Vagrantfile

No relevant for this problem. 

### Debug output
```sh
> HEAD /artifactory/api/vagrant/devboxes/boxnamev10.box?access_token=<token> HTTP/1.1
....
> GET /artifactory/api/vagrant/devboxes/boxnamev10.box HTTP/1.1
```

Results in 403

### Expected behavior

When I do a vagrant up, I would expect vagrant to fetch the artifact from my artifactory. 
I would expect the access token to be present on the GET Request as well. 

### Actual behavior

The access_token is missing on the GET Request and I end up getting a HTTP 403 Forbidden. 

When doing a manual get with cURL and access_token added it works like expected.

### Steps to reproduce

1. Set following variables in your shell. 

```sh
export ATLAS_TOKEN="<token>"
export VAGRANT_SERVER_URL="server_URL"
export VAGRANT_SERVER_ACCESS_TOKEN_BY_URL=true
``` 

2.  run `vagrant up --debug`
3. You will see that the access_token is only set on HEAD Request and not on GET Request.

### References

Are there any other GitHub issues (open or closed) that should be linked here?
- https://github.com/hashicorp/vagrant/issues/12080

PS: I have left out some of the information you asked for as I didn't find them relevant, please correct me if i'm wrong.

**Comment by tomasnorre** [comment]
I've been looking a little into this. 

It looks too me like the AUTH HEADER variant is still used at this place in the `downloader.rb` and not with the `?access_token=<token>` as the HEAD Request ist made. 
 
https://github.com/hashicorp/vagrant/blob/main/lib/vagrant/util/downloader.rb#L248

Disclaimer: I'm not a Ruby developer, So I might be completely wrong.

**Comment by soapy1** [comment]
Hey there,
thanks for opening up an issue! Could you additionally provide a full debug log? There is some additional logging that happens when an authentication token or header is getting added to a request that might shed some light on this issue. 

> https://github.com/hashicorp/vagrant/blob/main/lib/vagrant/util/downloader.rb#L248

This `@auth` comes from [checking if the url](https://github.com/hashicorp/vagrant/blob/main/lib/vagrant/util/downloader.rb#L45) is of the form `http://<user>:<password>@<address>`

>Update: I think this is the test class I should look at
https://github.com/hashicorp/vagrant/blob/main/test/unit/plugins/commands/cloud/auth/middleware/add_authentication_test.rb

yes!

**Comment by tomasnorre** [comment]
Hi,

I have added the complete output from `--debug`  in this gist. 
https://gist.github.com/tomasnorre/bc4b23e430b713064ca98a124c502412
