### ISSUE TITLE
SSH | Ed25519 required as secure key-pair

### ISSUE THREAD

**Issue by Ricky-Tigg** [hashicorp/vagrant#12284]
**OS:** Fedora; **Vagrant version:** vagrant-2.2.9-6.fc34.noarch

RSA | Creaion of insecure key-pair
```
$ vagrant --no-color ssh-config
Host default
  HostName 192.168.122.210
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/(...)/.vagrant/machines/default/libvirt/private_key
  IdentitiesOnly yes
  LogLevel FATAL
$ ssh-keygen -lf ~/.vagrant/machines/default/libvirt/private_key
2048 SHA256:IzNl9z/PU+/GdGaWpqCf1T4dKQ5Bx83i/kCxSuSl3iE no comment (RSA)
```
A unique existent key – an Ed25519 – is presented there as "_insecure key detected_" while the one it is being replaced by is precisely of that kind – an RSA 2048 bits. That's indeed the opposite of what is presented  as "_better security_". A fully non-insecure key is expected and even a secure one – an Ed25519 then.
```
$ vagrant up
(...)
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
```

**Comment by chrisroberts** [comment]
Hi there,

The message you are referring to is not making any claims about the type of key in use. If the vagrant detects that the default SSH key (located in VAGRANT_HOME) is used for connecting to the guest, it will remove it from the guest's authorized_keys list, generate a new key, and add the new key to the guest's authorized_keys. Vagrant assumes the default key is insecure due to it generally being a publicly known key (which box creators use when configuring the box). If you do not want this key to be replaced you can instruct Vagrant to leave the key in place using the `insert_key` communicator option: https://www.vagrantup.com/docs/vagrantfile/ssh_settings#config-ssh-insert_key

Cheers

**Comment by Ricky-Tigg** [comment]
Hello. You must have been in such a hurry to close this report that you missed the confusion of the message exhibited. I did refer to the SSH key pairs created via OpenSSH, whose default location on host is `$HOME/.ssh/`. That was that existent Ed25519 key that was intended to be taken in account by Vagrant.

Omitting the mention of  the SSH key created while `vagrant up` is taking place is not an option. There must not be place for confusion here. A message respecting users by being transparent and explicit, must be exhibited, instead of letting users discover by themselves what was meant by that _better security_. Security matters to users and should be as well as much to Vagrant.

Here is a fair model:
```
$ vagrant up
(...)
    default: Insecure public SSH key detected in VAGRANT_HOME. Vagrant will
    default: automatically replace it by a newly generated SSH RSA 2048 bits key-pair. 
```
