### ISSUE TITLE
Unable to update kernel on CentOS 7

### ISSUE THREAD

**Issue by alexgit2k** [hashicorp/vagrant#12299]
### Vagrant version

2.2.15

### Host operating system

Windows 10

### Guest operating system

CentOS 7

### Vagrantfile

```ruby
Vagrant.require_version ">= 2.0"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider :virtualbox do |box|
     box.name = "test"
     box.customize ["modifyvm", :id, "--nictype1", "virtio"]
     box.customize ["modifyvm", :id, "--nictype2", "virtio"]
     box.customize ["modifyvm", :id, "--paravirtprovider", "default"]
     box.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     box.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
     box.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
```

### Debug output

https://gist.github.com/alexgit2k/3d9de30bb07c2ece97d8f4f7f1882806

### Expected behavior

Updated kernel-package should have been installed.

### Actual behavior

Unable to find updated kernel-package (kernel-devel-3.10.0-1127.el7.x86_64)

### Steps to reproduce

1. vagrant up

### Workaround

1. vagrant ssh
2. sudo yum -y update kernel
3. exit
4. vagrant reload --provision

**Comment by soapy1** [comment]
Hey there,
this is expected behavior. Vagrant won't install packages onto the guest machine unless configured to do so. You might be able to get your desired behavior by either:

1. Using a box that has updated an kernel
or
2. Using [triggers](https://www.vagrantup.com/docs/triggers) to install the kernel package before the vb guest additions plugin runs. Something like
```
  config.trigger.before :"VagrantPlugins::ProviderVirtualBox::Action::CheckGuestAdditions", type: :action do |trigger|
    trigger.info = "Before the provision!"
    trigger.run_remote = {
      inline: "yum -y update kernel"
    }
  end
```
Note, to use triggers you will need to enable the trigger [experimental feature](https://www.vagrantup.com/docs/experimental).

**Comment by alexgit2k** [comment]
@soapy1 Thanks, for the fast feedback. This is already the most recent official CentOS 7 box (see https://app.vagrantup.com/centos/boxes/7). However, the problem was related with the vagrant plugin vbguest, so I filed an issue there: https://github.com/dotless-de/vagrant-vbguest/issues/406
