### ISSUE TITLE
Add ifdown check into configure_networks.rb for debian guests + IPv6 DAD timeout

### ISSUE THREAD

**Issue by k-y** [hashicorp/vagrant#12326]
### Vagrant version

2.2.14 (also present in 2.2.15)

### Host operating system

debian 10 (buster)

### Guest operating system

debian 10 (buster)

### Vagrantfile

```ruby
  config.vm.network "private_network", ip: "192.168.C.D"
  config.vm.network "private_network", ip: "192.168.C.E"
  config.vm.network "private_network", ip: "xxxx:yyyy:aaaa::1"
  config.vm.network "private_network", ip: "xxxx:yyyy:bbbb::1"
```
Could we get the same interface [check](https://github.com/hashicorp/vagrant/blob/v2.2.15/plugins/guests/alpine/cap/configure_networks.rb#L48) for debian guests similar to how #12134 was addressed?

We also have a case that occurs occasionally when the DAD (Duplicate Address Detection) check times out when we add IPv6 interfaces; would be nice to get a retry in this [block](https://github.com/hashicorp/vagrant/blob/v2.2.15/plugins/guests/debian/cap/configure_networks.rb#L169-L172).

### References

#12181

**Comment by soapy1** [comment]
Looking into this a little bit, I couldn't find a scenario where an extra check is required when configuring networks with nettools. The configure line always [returns true](https://github.com/hashicorp/vagrant/blob/v2.2.15/plugins/guests/debian/cap/configure_networks.rb#L150) so should be working in order. When the device exist it gets brought down, when it doesn't exist it does not error. I'm happy to make a modification here though if I missed something and there is an error mode here.

Otherwise, https://github.com/hashicorp/vagrant/pull/12421 addresses the retry issue. 

Cheers!

**Comment by soapy1** [comment]
I'm going to go ahead and close this issue since https://github.com/hashicorp/vagrant/pull/12421 has been merged
