### ISSUE TITLE
Enhancement Request: Support providers with alternative power down capabilities from graceful shutdown

### ISSUE THREAD

**Issue by electrofelix** [hashicorp/vagrant#12368]
Currently the vagrant-libvirt is carrying it's own graceful shutdown capabilities, this is partly due to it being implemented before there was awareness of the builtin GracefulHalt, however since then we can't easily switch across because there is no ability to provide any fallbacks should the use of the ssh connection to the machine for some reason not work to allow the guest capability to initiate a power down. Libvirt has the ability initiate a shutdown separately to a poweroff that uses ACPI signals to ask a VM to shutdown. The same shutdown mechanism is what is used by libvirt in the event the host machine is being shutdown.

**Describe the solution you'd like**
A mechanism for providers that support it, to provide a fall back graceful shutdown procedure in the event the guest halt capability doesn't exist or cannot work. This should still be executed under the same timeout constraints as the existing graceful shutdown so that if it does not succeed, the next step is to hand off to the stop action.

**Describe alternatives you've considered**
Currently handling graceful power down, however it means any time there are overall improvements such as options around timeout or options for force halt, we have to re-implement the same behaviour as is already provided.

**Comment by chrisroberts** [comment]
Hi! This should be totally possible with Vagrant as it is currently implemented today. The VirtualBox provider does this sort of thing (where the guest capability is tried first, and if the state fails to change the provider forcibly stops the guest). I spun out a PR to show how it could be implemented on the vagrant-libvirt repo :slightly_smiling_face: 

If that provides the correct behavior that you're looking for, then we can close this up. If not, just let me know and we can talk through it some more.

Cheers!

**Comment by electrofelix** [comment]
Possible better if I try and write both the current behaviour and suggested change in pseudo code to show the difference.

Current:
- Start timer
   - Attempt shudown via communicator
- If any error besides timeout (e.g. `Errors::GuestCapabilityNotFound` or `Errors::MachineGuestNotReady`)
   - send shutdown ACPI signal (this should still execute within the provided timeout)
- If timeout error triggered
   - call power off (pull power cord)

Using builtin GracefulHalt:
- Start timer
   - Attempt shudown via communicator
- If failed for any reason
   - call power off (pull power cord)

The difference between the power off and shutdown is that disk caches can be flushed in the case of the shutdown signal assuming the guest has support enabled, while the power off can corrupt the same as pulling the plugin on a real machine.

Essentially I'm looking for an extension to the builtin GracefulHalt to execute the following lines in the event that the ssh capability doesn't exist or the machine communicator wasn't ready for some reason: https://github.com/vagrant-libvirt/vagrant-libvirt/blob/1e4eeb6f8b2fd31e2de0948c57f954730858da60/lib/vagrant-libvirt/action/halt_domain.rb#L32-L37

Right now because the following lines swallow the guest capability not existing, the machine communicator not being ready, and the timeout, there is no way to distinguish which triggered the result of failing to gracefully shutdown.
https://github.com/hashicorp/vagrant/blob/9933fec019574f8c080f73072e253b51f27d38c7/lib/vagrant/action/builtin/graceful_halt.rb#L59-L67

This in turn means before calling poweroff https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1310/files#diff-fbfd269450855a06655267d51e6674f9021cd4b014459505001907306417acc8R17 there is no way to determine whether should attempt calling the ACPI shutdown first (https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1310/files#diff-fbfd269450855a06655267d51e6674f9021cd4b014459505001907306417acc8L36) because it's not possible to establish if still within the timeout limit easily.

I believe VirtualBox also has the capability to send a shutdown signal instead of powering off, and while the docker provider currently just calls stop, it could similarly use the communicator to initiate a halt and only call stop subsequently, but I'm not sure it's particular useful there. More just useful to consider the docker stop analogous to the ACPI shutdown signal to help understand the concept. Since presumably the docker provider never used the communicator to halt, there would be no need to include support for trying that first and then falling back to calling stop with a timeout. Don't know enough about HyperV, but I'd guess that as it's virtualization the same concept of the guest having an ACPI chipset is probably supported, just depends on whether the guest has the required software installed to listen for the signal and react appropriately.


Hopefully this explains it a bit better. I'm sure I could wrap the gracefulHalt and Halt with a time check and if it's less than the timeout, use the remaining time as the timeout for attempting shutdown. I might well still attempt if it's thought that it's not worthwhile attempting to support this type of fallback as it would still improve things while still matching the existing capabilities for vagrant-libvirt. Wanted to see if the overall concept of the provider having it's own fallback graceful shutdown was something worth exploring first.

**Comment by chrisroberts** [comment]
I missed that `shutdown` call to the domain when I was spinning out that PR on Friday, so apologies for that. I think that the behavior you are looking for is still available with the existing setup and won't require additional features to support it. I updated the PR I have open to include a new action (`ShutdownDomain`) which results in a shutdown process like:

```
 GracefulHalt -> ShutdownDomain -> HaltDomain
```

If the `GracefulHalt` action succeeds, then nothing else is done. If it fails for whatever reason (timed out, communicator error, etc) the `ShutdownDomain` action will run. The actual error which caused the `GracefulHalt` action to fail won't be relevant since the `ShutdownDomain` is simply checking for a desired state. If the domain is still running, the `ShutdownDomain` action runs. Likewise, after it has completed, if the desired state wasn't reached, the `HaltDomain` can forcibly halt it.

The action builder is really flexible, and I'm pretty sure we can get the desired behavior you're looking for from it as it currently exists. My big hesitation with adding something like fallback behavior is that it will likely be insufficient for all cases (since there may be 3 different ways to stop a guest for a specific provider, or 4, etc). Using the builder directly to provide different fallbacks leaves it extremely flexible and doesn't impose any restrictions that may make it undesired based on the specific provider. 

Anyway, have a look and let me know what you think! :slightly_smiling_face:

**Comment by electrofelix** [comment]
While the proposed solution allows the chaining, it can result in waiting double the requested timeout, which is one of the things I'm looking to avoid. That requires wrapping calling GracefulHalt with something that tracks whether the timeout was exceeded and then have that decide whether to call ShutdownDomain or HaltDomain, which means back to retrieving the timeout and duplicating the handling of the graceful halt timeout config outside of GracefulHalt.

Maybe if the error had was available as the result it would allow a decision to be made, but either way I think end up needing to understand the timeout config option and know whether to apply it. I suspect given the need to see if the action completes within the timeout, it'll either be call the GracefulHalt action directly within another or wrap the chain with a start timer type of action so can check whether the time since exceeds the timeout and then decide which to call.


I do think I've a better idea of how to chain the actions after this though, thanks for going through it in detail.

**Comment by electrofelix** [comment]
I've often been meaning to add some better tests around the actions in vagrant-libvirt not only to validate some of the chained behaviour, but also to improve my understanding of how they chain as well.

Conceptually is it possible to start one action, have it record the start time, then call `@app.call(env)` to allow an inner action to execute and subsequently for control to return after just that action to and then check the time taken subsequently? Or does control only return after the entire list of Actions have completed and then is processed up the call chain in the reverse order?

e.g. Given the following
```
# env2 is at this level
b3.use Call, ShutdownDomain, :shutoff, :running do |_, b4|
  b4.use Call, GracefulHalt, :shutoff, :running
end

if !env2[:result]
  b3.use HaltDomain
end
```

And have the following in the `ShutdownDomain` action:
```
        def call(env)
          timeout = env[:machine].config.vm.graceful_halt_timeout
          domain = env[:machine].provider.driver.connection.servers.get(env[:machine].id.to_s)
          start_time = Time.now.to_i

          # calling the next action in the middleware
          @app.call(env)

          # might be using the wrong units here, but just following the concept
          shutdown_timeout = Time.now.to_i - start_time
          return unless shutdown_timeout < timeout

          if env[:machine].state.id == @source_state
            env[:ui].info(I18n.t('vagrant_libvirt.shutdown_domain'))
            domain.shutdown
            domain.wait_for(shutdown_timeout) { !ready? }
          end

          env[:result] = env[:machine].state.id == @target_state
        end
```

Which one of the following is the correct chain of execution:
* Start `ShutdownDomain` -> `GracefulHalt` -> Finish `ShutdownDomain` -> `HaltDomain`
* Start `ShutdownDomain` -> `GracefulHalt` -> `HaltDomain` -> other actions -> Finish `ShutdownDomain`

If it's the latter, is there a way besides explicitly calling the action running from within the action itself similar to something like at https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/wait_till_up.rb#L68-L74

**Comment by chrisroberts** [comment]
The point you make about timeout durations and what caused the `GracefulHalt` action not to succeed is a very good one, especially when you want to respect the defined graceful halt timeout and not unintentionally double it. That can be easily solved by setting some metadata into the state while from the `GracefulHalt` action. We could do something like:

```ruby
env['GracefulHalt.timeout_exceeded'] = true
env['GracefulHalt.timeout_used'] = remaining # where remaining is total allowed wait - duration of timeout block
env['GracefulHalt.error'] = true
env['GracefulHalt.error_type'] = err.class
env['GracefulHalt.error_message'] = err.message
```

This would make it easy for subsequent actions to make decisions based on what happened previously.

Now, for the action/builder stuff you have just above this, the sequence will be based on how the actions are registered with the builder. In your example, specifically, it won't run due to `Call` requiring a block for building its internal `Builder` instance (so it will just result in an error). If the `b4.use Call, GracefulHalt, :shutoff, :running` was instead `b4.use GracefulHalt, :shutoff, :running`, then the order would be:

```
ShutdownDomain -> GracefulHalt -> HaltDomain
```

The reason for this is due to the `Call` usage in the builder. I'm going to take the `action_halt` builder defined in libvirt, trim it a bit, and then adjust based on your snippet above. That way we can have a complete builder usage that we can breakdown without losing any context on some implied state. So we'll start out with this:

```ruby
Vagrant::Action::Builder.new.tap do |b1|
  b1.use Call, IsRunning do |env, b2|
    next unless env[:result]
    b2.use Call, ShutdownDomain, :shutoff, :running do |_, b3|
      b3.use GracefulHalt, :shutoff, :running 
    end

    if !env[:result]
      b2.use HaltDomain
    end
  end
  b1.use Message, "Halt is complete"
end
```

The `Call` action runs the callable provided in an isolated runner, and then uses the result and the block defined in the definition to create a new builder (which gives us a new substack of actions). So, when the `ShutdownDomain` action is called, it is the lone action so wrapping the `@app.call(env)` with timing information won't matter because there is nothing else for it to execute. Once it has completed, It will call the `GracefulHalt` action.

Now, we get to the `env[:result]` check, which _should_ be okay, but may have been modified elsewhere (since other actions use that key as well). With the `Call` action usage, and the value check within the block provided, we know that the `env[:result]` value is coming from the callable action given to `Call`. Finally, we'll get to the `Message` and execution is done. So the ordering goes:

```
IsRunning -> ShutdownDomain -> GracefulHalt -> HaltDomain (conditionally) -> Message
```

One thing to consider is that actions are generally single purpose to perform a specific task, which makes them easy to reuse in other location, and as such shouldn't care about any context around their execution. Even in a scenario where no checks are done and the actions are executed regardless (relying on them to only run if required):

```ruby
Vagrant::Action::Builder.new.tap do |b|
  b.use ShutdownDomain, :shutoff, :running 
  b.use GracefulHalt, :shutoff, :running 
  b.use HaltDomain
end
```

Now, here, you would start to get the behavior you are looking for, but won't quite be right:

```
ShutdownDomain starts -> GracefulHalt -> HaltDomain -> ShutdownDomain finishes
```

You could force a new substack to get the behavior you want:

```ruby
Vagrant::Action::Builder.new.tap do |b|
  b.use Call, Message, "Attempting nice shutdowns..." do |_, b2|
    b2.use ShutdownDomain, :shutoff, :running 
    b2.use GracefulHalt, :shutoff, :running
  end
  b.use HaltDomain
```

Now we'll get an order like:

```
Message -> ShutdownDomain starts -> GracefulHalt -> ShutdownDomain finishes -> HaltDomain
```

However, if the `GracefulHalt` action is providing some metadata that the `ShutdownDomain` can utilize to make decisions about things like the timeout duration, there's no need for adding extra complexity to wrap other actions and prevents it from having to assume about its usage. Instead, it can just check for some value and use them if found.

I hope that was helpful and didn't veer off track of the explanations you were looking for. If it did, please let me know!

**Comment by electrofelix** [comment]
This is fantastic, I think it's giving all the possible options. I suspect Shutdown in this case is a special case as it's tightly coupled to `GracefulHalt` so handling it in a special way is probably alright as long as I add comments for the next person to understand.

Needing to expose stuff specially from GracefulHalt compared to any other builtin/general action doesn't seem ideal to me unless it becomes similar to the packaging helper actions which do pass some state between them, to then allow the provider specific export/package action to export without needing to handle everything.

I expect I'll likely look to create an action runner unit level test that exercises the halt behaviour to replace the existing testing of a single action and look to combine that with your work to separate out to individual actions and experiment with the different approaches you've suggested to try and complete my understanding and that way I can pick one of the various approaches.

I guess this can be closed?

**Comment by chrisroberts** [comment]
Okay, I'll close this up but if you need to follow up, feel free to just open a new issue with a link to this one for context and we can pick it back up. 

Cheers!
