### ISSUE TITLE
Vagrantfile is executed twice under WSL

### ISSUE THREAD

**Issue by ProfAccCH** [hashicorp/vagrant#12402]
We observed that the evaluation of a Vagrantfile is different between WSL and other platforms.
The prefix code before the "configure" blocks is executed twice on WSL which might result in different results between the platforms. It seems that it is executed as on a Linux host and as on a Windows host.
I couldn't find any explanation for this behaviour in the "Load Order and Merging" section of the Vagrantfile documentation.

### Vagrant version

vagrant version 2.2.16 (occured also on 2.2.15)

### Host operating system

Windows version 1909 OS build 18363.1500 with Ubuntu 20.04.2 in WSL 1

### Vagrantfile

```ruby
puts "Call me once please"
Vagrant.configure("2") do |config|
 
end
```

### Debug output

The debug output is available here:
https://gist.github.com/ProfAccCH/b4698122eddceb6261b66434fab1dc5d

### Expected behavior
I would expect that the "puts" statement is executed only once. 

### Actual behavior
We see the "puts" on WSL we see it twice. This will give problems to all non idempotent statements.

### Steps to reproduce

1. call "vagrant up" for the provided Vagrantfile

**Comment by chrisroberts** [comment]
Hi there,

This is expected behavior of the Vagrantfile and there is no guarantee of the file only being evaluated once during a single command invocation. The Vagrantfile (as well as specific sections within the Vagrantfile) can and are evaluated multiple times during a single run. For things that need to only be run a single time (like a `puts` statement from your example), a global variable is a simple way to guard that:

```ruby
if !$vagrantfile_puts_called
  $vagrantfile_puts_called = true
  puts "Call me once please"
end

Vagrant.configure("2") do |config|

end
```
