### ISSUE TITLE
An error occurred while downloading the remote file. The error message, if any, is reproduced below. Please fix this error and try again.

### ISSUE THREAD

**Issue by Jpanda124** [hashicorp/vagrant#12492]
Good evening!

We are using Vagrant and Oracle Virtual machine to build virtual box for our application team .

Getting below error while downloading vagrant box from our Artifactory .

![image](https://user-images.githubusercontent.com/80794653/129277725-d95c2cd2-e6f0-4bfc-8c66-23f0447864cb.png)

![image](https://user-images.githubusercontent.com/80794653/129277946-9d4a7972-344b-4e50-acea-4f6fdb3d91f0.png)

Manually we can download the box , also through "curl " command we can download box .
Pointing the box url on local file is working fine .
anvm.vm.box_url = "file:///C:/Devops/Vagrant//analytics.box"

Any help  is appreciated .Thanks

**Comment by chrisroberts** [comment]
Hi there,

Setting the `VAGRANT_SERVER_ACCESS_TOKEN_BY_URL` will likely resolve the issue you are encountering. This is due to a change in how Vagrant authenticates with Vagrant Cloud that artifactory does not support. Setting that environment variable will revert Vagrant to its old behavior.

https://www.vagrantup.com/docs/other/environmental-variables#vagrant_server_access_token_by_url

Cheers!

**Comment by Jpanda124** [comment]
@chrisroberts  : Thanks for the response but this didn't resolve my issue .

I added below to vagrant file 
ENV['VAGRANT_SERVER_ACCESS_TOKEN_BY_URL']="https://dmz.artifactory.com/artifactory/api/vagrant"

![image](https://user-images.githubusercontent.com/80794653/129631173-fa08bcf8-ece1-4b5f-8f9a-dc7e9e14ba56.png)


still getting the same error .
![image](https://user-images.githubusercontent.com/80794653/129631245-b640754a-9fbf-4226-8a34-e8b5755affb4.png)

Please help.
