### ISSUE TITLE
Vagrant setup error - Vagrant.cab is corrupt

### ISSUE THREAD

**Issue by aljazromih** [hashicorp/vagrant#12705]
I was installing Vagrant (2.2.19) for my coworker on Win 10 x64, Intel i7 3rd generation.
We got this error that Vagrant.cab is corrupt.

Install of version 2.2.19 worked.

**Comment by chrisroberts** [comment]
Hi there,

Just gave the installer a run and it is working as expected for both the 2.3.0 and 2.2.19 releases. Is this still an error which you are encountering?

**Comment by chrisroberts** [comment]
Hey there,

I am closing this due to lack of response. If this is still an issue, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us with the reproduction and allow us to provide recommendations. Thanks!
