### ISSUE TITLE
[docs] code intelligence

### ISSUE THREAD

**Issue by loynoir** [hashicorp/vagrant#12739]
**Is your feature request related to a problem? Please describe.**
Sorry, I know nothing about ruby language.

But, I guess code intelligence exists in ruby ecosystem.

And `vagrantfile` is written in ruby.

But I installed several vscode extensions, and see no code intelligence.

Is there code intelligence vscode solutions for ruby, or more specifically said `vagrantfile`?

### Expected
1. hover on `config.vm.disk`

show docs, need `export VAGRANT_EXPERIMENTAL="disks"`

2. tab after `config.vm.disk`
```ruby
config.vm.disk :disk, disk_ext: disk_ext, file: file, name: name, primary: primary, size: size
```

### Actual
1. hover on config.vm.disk

show nothing

 2. tab after config.vm.disk

show nothing

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Archlinux user. Install vagrant from package manager.

**Comment by chrisroberts** [comment]
Thank you for your feedback and recommendation, however, due to limited resources we are unable to prioritize this new work in our sprints. We are now closing this issue so that it is not stagnate.

The best way to get this implemented would be to submit a PR. If you want to discuss how to open a PR, I'd be happy to help with that.

Again, thank you for your suggestion. This is also an open source project we welcome contributions. Thanks!
