### ISSUE TITLE
[docs] Convert `Dockerfile` logic to vagrant

### ISSUE THREAD

**Issue by loynoir** [hashicorp/vagrant#12737]
### Question
What is vagrant equivalent to `Dockerfile` `FROM`?

`docker`, using `Dockerfile FROM`, can build new image, by adding new resources to existing image.

How can I build new vagrant box, by adding new resources to existing vagrant box?

### Dockerfile Example
https://docs.docker.com/engine/reference/builder/#escape

```Dockerfile
# escape=`

FROM microsoft/nanoserver
COPY testfile.txt c:\
RUN dir c:\
```

### Further
And with `docker-compose`,  `docker build` able to
- Build once
- Or build per start

Able to start container, when start system. eg:  docker-compose.yml `restart: always`

**Comment by loynoir** [comment]
Would be nice, if there is doc about how to convert `Dockerfile` to similar logic `Vagrantfile`. 😃

**Comment by chrisroberts** [comment]
Thank you for your feedback and recommendation, however, due to limited resources we are unable to prioritize this new work in our sprints. We are now closing this issue so that it is not stagnate.

The best way to get this implemented would be to submit a PR. If you want to discuss how to open a PR, I'd be happy to help with that.

Again, thank you for your suggestion. This is also an open source project we welcome contributions. Thanks!
