### ISSUE TITLE
`vagrant reload` did not bring up new VM when updated the `Vagrantfile`

### ISSUE THREAD

**Issue by astraw99** [hashicorp/vagrant#12886]
### Vagrant version
Installed Version: 2.3.0
Latest Version: 2.3.0

### Host operating system
MacOS 12

### Guest operating system
ubuntu-bionic-18.04-cloudimg-20220902

### Vagrantfile
See below.

### Debug output
```
...
==> lb: VM not created. Moving on...
...
```

### Expected behavior
1. Brint up the new VM based on the lastest `Vagrantfile`;
2. After new VM running, destroy the old VM;

### Actual behavior
1. First, we set the `Vagrantfile` like this:
```
config.vm.define "loadbalancer" do |node|
    node.vm.provider "virtualbox" do |vb|
        vb.name = "kubernetes-ha-lb"
        vb.memory = 512
        vb.cpus = 1
    end
    node.vm.hostname = "loadbalancer"
```

2. Then do the `vagrant up`;
3. After the loadbalancer VM running, we changed the name:
```
config.vm.define "lb" do |node|
    node.vm.provider "virtualbox" do |vb|
        vb.name = "kubernetes-ha-lb"
        vb.memory = 512
        vb.cpus = 1
    end
    node.vm.hostname = "lb"
```

4. Then do the `vagrant reload`, it just output `==> lb: VM not created. Moving on...`.

### Steps to reproduce
See above.

**Comment by chrisroberts** [comment]
Hi there,

This is due to the underlying way Vagrant currently works. The guest can still be located (and destroyed) via `vagrant global-status`. However, for interaction with a guest in a project, it must be defined in the Vagrantfile. This limitation is being removed in the new vagrant-go work, but the existing behavior in the current Ruby implementation will not be changed.

Cheers!
