### ISSUE TITLE
Vagrant file bypass 'config.vm.box_check_update = false' on ubuntu.

### ISSUE THREAD

**Issue by rodrigorootrj** [hashicorp/vagrant#12918]
### Expected behavior
Hi all, my vagrant use ubuntu s/o.  Every time i run $vagrant up, my vagrant run the ubuntu box with update.
But, when i use the entire: **config.vm.box_check_update = false** for disable update, the 'vagrant up' run update task again.
In documentation this entire work to disable that.
### Actual behavior

Currently, i use nat interface as default gateway(default vagrant setup). The ubuntu repositories not work over that. I need change default gateway after run the box, to ubuntu default repositories work.
After error, the box run, but not setup anything content in my vagrantfile.

### Reproduction information of error:
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libf/libfile-fcntllock-perl/libfile-fcntllock-perl_0.22-3build2_amd64.deb  Connection failed [IP: 185.125.190.36 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/manpages/manpages-dev_4.15-1_all.deb  Connection failed [IP: 91.189.91.38 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Unmounting Virtualbox Guest Additions ISO from: /mnt
umount: /mnt: not mounted.
==> core: Checking for guest additions in VM...
    core: The guest additions on this VM do not match the installed version of
    core: VirtualBox! In most cases this is fine, but in rare cases it can
    core: prevent things such as shared folders from working properly. If you see
    core: shared folder errors, please make sure the guest additions within the
    core: virtual machine match the version of VirtualBox you have installed on
    core: your host and reload your VM.
    core: 
    core: Guest Additions Version: 5.2.8_KernelUbuntu r120774
    core: VirtualBox Version: 6.1
    core: VirtualBox Version: 6.1
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

umount /mnt

Stdout from the command:



Stderr from the command:

umount: /mnt: not mounted.
```
#### Vagrant version

Vagrant 2.2.19

#### Host operating system

Mac
Virtual Box
#### Guest operating system

Ubuntu-18.04.06

#### Steps to reproduce

1. Make vagrantfile
2. vagrant up
3.

#### Vagrantfile
# All Vagrant configuration is done below. 
```
Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.box = "ubuntu18.04.6"  
  config.vm.define "core" do |core|    
    core.vm.network "public_network", ip: "192.168.1.216", bridge: "en0: Wi-Fi (Wireless)"
    config.ssh.dsa_authentication
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"    
    config.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end
```

**Comment by rodrigorootrj** [comment]
I remove the source list, from my ubuntu box. Now, i have problem with vboxsf.
```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1001,gid=1001,_netdev vagrant /vagrant

The error output from the command was:

: Invalid argument
```
But when retry vagrant up, my system work. what's going on?

**Comment by chrisroberts** [comment]
Hi there,

The underlying cause of the issue you are encountering is due to the box you are using, or a plugin you have installed. The `box_check_update` option controls whether or not Vagrant (on the host machine) checks if the box is use has been updated. The errors you are encountering are due to an `apt` command failing to download packages on the guest. This is occurring due to a provisioner defined defined in the box Vagrantfile, a plugin that you may have installed which is providing some extended functionality for the guest, or perhaps in your existing Vagrantfile if the entire thing was not provided in the original issue description. 

The Vagrantfile you provided is also defining a named guest but part of the configuration is being applied to all defined guests due to using the `config` variable instead of the `core` variable. The contents should look like this:

```ruby 
Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.box = "ubuntu18.04.6"  
  config.vm.define "core" do |core|    
    core.vm.network "public_network", ip: "192.168.1.216", bridge: "en0: Wi-Fi (Wireless)"
    conre.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"    
    core.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end
```

If you remove any installed plugins and try again with the `bento/ubuntu-18.04` box and still encounter errors, please provide a gist of the entire debug log (the output from running `vagrant up --debug`).

Cheers!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
