### ISSUE TITLE
checksum value with an actual working example needed

### ISSUE THREAD

**Issue by quantummixer** [hashicorp/vagrant#13040]
## Description 
The [current Vagrant documentation](https://github.com/hashicorp/vagrant/blob/main/website/content/docs/boxes/format.mdx) on how to generate `metadata.json` provides a dummy checksum value as an inline code example.   I am not sure if I am reading the documentation correctly or that the documentation is partial, but the following is my current assumptions and understanding base on my current situation:

1. I have created completed and followed through the entire instructions on this page to create the `box file` described [here](https://developer.hashicorp.com/vagrant/docs/providers/vmware/boxes#packaging).
2. I realized that I missed the `metadata.json` that needs to be created manually and it needs to be included into the same directory, before I run the `tar cvzf custom.box ./*` command to generate the final `tar.gz box file`.  
3. The issue is how can I compute the SHA512 checksum value of the final `custom.box` in advance, so I can satisfy the `checksum` value required inside the `metadata.json` file?  
4. Since `tar cvzf` outputs a `tar.gz` file, I cannot append `metadata.json` and if I am some how successful appending the `metadata.json` with `checksum` value of the previously generated `custom.box`, I will ultimately alter the `checksum` value again.  
5. What is the proper way to solve this dilemma?  

## Use case (optional) 
The user is unable to manually create a `metadata.json` that satisfy the most basic `box file requirement`, such as checksum integrity check.  

```
% vagrant up
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Box 'quantummixer/ubuntu-200405-focal-arm64' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Loading metadata for box 'quantummixer/ubuntu-200405-focal-arm64'
    default: URL: https://vagrantcloud.com/quantummixer/ubuntu-200405-focal-arm64
==> default: Adding box 'quantummixer/ubuntu-200405-focal-arm64' (v0.1.0) for provider: vmware_fusion
    default: Downloading: https://vagrantcloud.com/quantummixer/boxes/ubuntu-200405-focal-arm64/versions/0.1.0/providers/vmware_fusion.box
    default: Calculating and comparing box checksum...
The "metadata.json" file for the box 'quantummixer/ubuntu-200405-focal-arm64' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:

https://www.vagrantup.com/docs/boxes/format.html
```

## Supporting material 
Add links to related issues or supporting documentation. 

References documents read, consulted, followed:
1. https://developer.hashicorp.com/vagrant/docs/boxes/base
2. https://developer.hashicorp.com/vagrant/docs/providers/vmware/boxes
3. https://developer.hashicorp.com/vagrant/docs/boxes/format
4. https://github.com/hashicorp/vagrant/blob/main/website/content/docs/boxes/format.mdx
5. [stack answer: There is a catch, you can't add to a compressed archive](https://unix.stackexchange.com/a/13094)

#### Estimated task complexity time-frame (does not guarantee a delivery date)
* day

**Comment by chrisroberts** [comment]
Hi there,

I can see how the documentation is a bit confusing here and I'll see about getting an update to that page to make it a bit more clear.

The page is describing two different files: the "box file" and the "metadata file". 

The "box file" is a JSON document named `metadata.json` within the compressed box artifact. The only key/value pair that Vagrant cares about in that file is the `"provider"` value. 

The "metadata file" is a JSON document that is separate from the box artifact. It can be used to include additional information which Vagrant will use when adding a box. This metadata file can be provided to the `vagrant box add` command and allows you to specify extra information like version and checksum information.

Since you are using Vagrant Cloud, you should not need to worry about creating a metadata file. When Vagrant requests a box from Vagrant Cloud, Vagrant Cloud is returning a dynamically generated metadata file to Vagrant. If you want to include checksum information for your box, you can set the checksum type and value using the web UI. If you are uploading the box using the Vagrant CLI, those values can be set using the `--checksum` and `--checksum-type` flags when publishing the box. If you are using Packer, you can use the [`box_checksum` option](https://developer.hashicorp.com/packer/plugins/post-processors/vagrant/vagrant-cloud#box_checksum).

If you have any other questions about this, please do let me know. I'll see about getting an update for the documentation put together soon to address this confusion.

Cheers!
