### ISSUE TITLE
missing bash completion

### ISSUE THREAD

**Issue by Jeansen** [hashicorp/vagrant#13049]
### Debug output

`vagrant autocomplete install` puts the following in ~/.bashrc
```
# >>>> Vagrant command completion (start)
. /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/contrib/bash/completion.sh
# <<<<  Vagrant command completion (end)
```

### Expected behavior

After starting a new Terminal session I should have autocompletion available.

### Actual behavior

I see the following error messaga:

`-bash: /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/contrib/bash/completion.sh: No such file or directory`

#### Vagrant version

Vagrant 2.3.4

#### Steps to reproduce

1. vagrant autocomplete install
2. Open a new Terminal session with BASH
3.

#### Vagrantfile

```ruby
# Copy-paste your Vagrantfile here. Remove any sensitive information such as passwords, authentication tokens, or email addresses.
```

**Comment by pstric** [comment]
Same here after "vagrant autocomplete install --bash", except the location is /usr/share/vagrant/gems/gems/vagrant-2.3.4/contrib/bash/completion.sh

The folder /usr/share/vagrant/gems/gems/vagrant-2.3.4/ does exist, but there is no contrib folder.

After creating contrib/bahs/ and copying https://github.com/hashicorp/vagrant/blob/main/contrib/bash/completion.sh I have completion.

**Comment by soapy1** [comment]
Thanks for opening up an issue. In order to get a better idea of what is causing this problem could you share how you installed Vagrant? And if the `contrib` folder exists in your Vagrant installation. Thanks!

**Comment by Jeansen** [comment]
I installed it via the repository and APT. That's how I am doing it for over a year, now.  Here's what I have in my corresponding resource.list: `deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bullseye main`. The contrib folder is missing, in my case.

**Comment by soapy1** [comment]
Hmm, so taking a look inside the deb package it looks like the contrib folder and the autocomplete scripts are available. Then, installing using the method [described in the docs ](https://developer.hashicorp.com/vagrant/downloads)

```
 $ wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

 $ echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

 $ sudo apt update && sudo apt install vagrant
```

installs Vagrant to `/opt/vagrant/` which includes the Vagrant gem and the contrib folder (`/opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/contrib/`). So that all works properly (on [hashicorp/bionic64](https://app.vagrantup.com/hashicorp/boxes/bionic64) and [debian/bullseye64](https://app.vagrantup.com/debian/boxes/bullseye64))

```
$ vagrant autocomplete install
Autocomplete installed at paths:

- /home/vagrant/.bashrc

$ source ~/.bashrc
$
```

From your reports, I notice that the install locations are not what I would expect for Vagrant. Eg. `/usr/share/rubygems-integration` and `/usr/share/vagrant`. Are there special install steps or system specific details you can share?

**Comment by Jeansen** [comment]
Oh, boy. I just realized that a package from Debian came in that seems to be newer (because I am running SID/unstable). Obviously I forgot to pin the repo. Installing now from the Hashicorp repo shows that all is fine. I am sorry for any inconvenience.

**Comment by pstric** [comment]
Sorry about the delay, but I have been unable to reply before now.

I am on openSuse Tumbleweed, so my installation was via the main openSUSE
repository. openSUSE uses rpm instead of apt. Maybe their installation is
different, and 'vagrant autocomplete install' just assumes the host is
Ubuntu or some other apt based distro. Or maybe openSUSE packages the
vagrant rpm wrong. I don't know.

$ which vagrant
/usr/bin/vagrant

$ tail -3 .bashrc
# >>>> Vagrant command completion (start)
. /usr/share/vagrant/gems/gems/vagrant-2.3.4/contrib/bash/completion.sh
# <<<<  Vagrant command completion (end)

$ ls -l /usr/share/vagrant/gems/gems/vagrant-2.3.4/
totalt 244
drwxr-xr-x 1 root root     14 11 jan 14:52 bin
-rw-r--r-- 1 root root 222944 11 jan 14:52 CHANGELOG.md
drwxr-xr-x 1 root root      8  6 jan 08:30 contrib             <<--- I made
this!
drwxr-xr-x 1 root root     54 11 jan 14:52 keys
drwxr-xr-x 1 root root     34 11 jan 14:52 lib
-rw-r--r-- 1 root root   1059 11 jan 14:52 LICENSE
drwxr-xr-x 1 root root    200 11 jan 14:52 plugins
-rw-r--r-- 1 root root   2484 11 jan 14:52 README.md
-rw-r--r-- 1 root root   1566 11 jan 14:52 README.SUSE
drwxr-xr-x 1 root root    152 11 jan 14:52 templates
-rw-r--r-- 1 root root   4451 11 jan 14:52 vagrant-2.3.4.gemspec
-rw-r--r-- 1 root root      6 11 jan 14:52 version.txt

Den man. 9. jan. 2023 kl. 18.19 skrev Sophia Castellarin <
***@***.***>:
