### ISSUE TITLE
unable to login vagrant cloud

### ISSUE THREAD

**Issue by ayubwaheed** [hashicorp/vagrant#13079]
![image](https://user-images.githubusercontent.com/91366401/216795449-5fd3df6f-3099-4582-be2f-c33cd00e8935.png)

**Comment by soapy1** [comment]
Heya, thanks for opening up an issue. Could you share the steps to reproduce this issue?

**Comment by soapy1** [comment]
I see that this issue crops up when trying to log into an account that has been linked to HCP with the vagrant cloud cli. In order to authenticate with Vagrantcloud in this case you must use api tokens. You can setup a new token thru the web ui under the security settings (https://app.vagrantup.com/settings/security) and then login using the cli using the command `vagrant cloud auth login --token <MY TOKEN>`.

On the Vagrant side we should
- [ ] update the documentation for vagrant cloud cli authentication
- [ ] update Vagrant to produce a more helpful error message

**Comment by ayubwaheed** [comment]
Thanks for the solution.
