### ISSUE TITLE
Did not see .pcap file in the folder of Vagrantfile

### ISSUE THREAD

**Issue by LuoXin-s** [hashicorp/vagrant#13084]
I want to trace network activities using `nictrace` function provided by vagrant, but it does not works as expected.

#### Vagrant version
Vagrant 2.3.4

#### VirtualBox version
VirtualBox-7.0.6-155176-Win

#### Host operating system
win11

#### Guest operating system
ubuntu1804

#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus=2
    vb.customize ['modifyvm', :id, '--nictrace2', 'on'] 
    vb.customize ['modifyvm', :id, '--nictracefile2', 'traceb.pcap']
  end
end

```

**Comment by soapy1** [comment]
Hey there, looks like this is an issue with the nic card you are trying to trace. Taking a look at the vm in the virutalbox gui, only one network card is available. In that case you'll want to do a 

```
    vb.customize ['modifyvm', :id, '--nictrace1', 'on'] 
    vb.customize ['modifyvm', :id, '--nictracefile1', 'traceb.pcap']
```

Since this isn't a bug in Vagrant I'm going to go ahead and close this issue. 

ref: https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
