### ISSUE TITLE
Vagrant rdp --- need to disable default user vagrant

### ISSUE THREAD

**Issue by ayubwaheed** [hashicorp/vagrant#13082]
Heya! i am trying to access vagrant box rdp with administrator account but by default its accessing from vagrant user. 

Vagrant file config:
added winrm communicator
added user name
addes user password

![image](https://user-images.githubusercontent.com/91366401/218260260-cfd0529e-f374-497f-8426-90506eb9e158.png)

when do vagrant rdp  --its shows that user is administrator but connection get establish with vagrant user

![image](https://user-images.githubusercontent.com/91366401/218260319-d99a34d7-1650-45d3-8498-c88d4d54699f.png)

PLEASE ASSIST !!

**Comment by soapy1** [comment]
Hey there,

thanks for opening up an issue. In order to get a better understanding of the issue you are running into could you please share 
1. a copy of your Vagrantfile
2. a debug log https://developer.hashicorp.com/vagrant/docs/other/debugging

In order to change the rdp username use the config `config.rdp.username = "myrdpuser"`

**Comment by ayubwaheed** [comment]
Hey Sophia,
thanks for getting back to me. I  have tried to use config.rdp.username =
"myrdpuser"  but still machine getting default login vagrant. my vagrant
file is attached.

Thanks for your support.

**Comment by chrisroberts** [comment]
Hi there,

No Vagrantfile was provided in your last comment. If you can provide your Vagrantfile and a gist of the output generated from `vagrant rdp --debug` that would be helpful in determining the cause of the issue.

Cheers!

**Comment by chrisroberts** [comment]
Hey there,

I am closing this due to lack of response. If this is still an issue, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us with the reproduction and allow us to provide recommendations. Thanks!
