### ISSUE TITLE
Vagrant MSI install files for Windows do nothing

### ISSUE THREAD

**Issue by bradykelly** [hashicorp/vagrant#13142]
I have tried running both `vagrant_2.3.4_windows_amd64.msi` and `vagrant_2.3.4_windows_i686.msi` on Windows 10 Enterprise version 10.0.19044. My machine is a Dell Latitude 5530 laptop with an i7-1265U 1800MHz 10 Core CPU and 32GB ram. 

If I double click either file the system pauses briefly and returns to normal, with no installer starting up or any error message. I have also tried running the installer using `msiexec.exe` in PowerShell with the following command line to see if anything is written to a log file.

`msiexec.exe /I C:\Downloads\vagrant_2.3.4_windows_i686.msi /L*V "vagrant-install.log"`

When I run the above command line, the system again pauses very briefly and writes an empty (0 bytes long) log file and does nothing else.

**Comment by chrisroberts** [comment]
@bradykelly I'm not having any issues when installing the msi files. Are you still encountering the same behavior with the latest release? If so, do you have any virus scanners running?

**Comment by chrisroberts** [comment]
Hey there,

I am closing this due to lack of response. If this is still an issue, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us with the reproduction and allow us to provide recommendations. Thanks!
