### ISSUE TITLE
Vigrant installation

### ISSUE THREAD

**Issue by Toitech** [hashicorp/vagrant#13224]
Im having an error message while trying to install vigrant on my personal computer through the use of Window PowerShell.
The error i'm getting is :
schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) - The received certificate has expired.

please what should i do?

**Comment by kaitlincart** [comment]
Hi, 

Can you provide a gist of the debug output when you run Vagrant? If you do not need to verify the box, you can bypass the check with the [config.vm.box_download_insecure](https://developer.hashicorp.com/vagrant/docs/vagrantfile/machine_settings#config-vm-box_download_insecure) setting. 

Thanks,
Kait

**Comment by kaitlincart** [comment]
Hi,

I am closing this due to lack of response, we hope this means you were able to resolve your issue. If this is still an issue, please open a [new issue](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us with the reproduction and allow us to provide recommendations. Thanks!
