### ISSUE TITLE
ERROR: checksum of the downloaded box did not match the expected value on Vagrant 2.4.1

### ISSUE THREAD

**Issue by germanztz** [hashicorp/vagrant#13518]
Hi! I’m getting this error on the download image stage: “The checksum of the downloaded box did not match the expected value.” but it is showing the same checksum itself. Anybody knows what is going on?

Thanks

### Debug output

https://gist.github.com/germanztz/d44a0e15efae7a96e2785b9870175f54

#### Vagrant version

```
$ vagrant --version
Vagrant 2.4.1
```
#### Host operating system

```
Linux ---- 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

#### Guest operating system

n/a

#### Steps to reproduce

```
$ vagrant --version
Vagrant 2.4.1
$ uname -a
Linux ---- 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ vagrant up 
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'daimler/ubuntu-24.04-desktop' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'daimler/ubuntu-24.04-desktop'
    default: URL: https://vagrantcloud.com/api/v2/vagrant/daimler/ubuntu-24.04-desktop
==> default: Adding box 'daimler/ubuntu-24.04-desktop' (v1.0) for provider: virtualbox (amd64)
    default: Downloading: https://vagrantcloud.com/daimler/boxes/ubuntu-24.04-desktop/versions/1.0/providers/virtualbox/amd64/vagrant.box
    default: Calculating and comparing box checksum...
The checksum of the downloaded box did not match the expected
value. Please verify that you have the proper URL setup and that
you're downloading the proper file.

Expected: 86b5040d4e7a45d1345ae4d2954c3a94  ubuntu-24.04-desktop.box
Received: 86b5040d4e7a45d1345ae4d2954c3a94

```

#### Vagrantfile

n/a

**Comment by chrisroberts** [comment]
Hi there,

The issue is the checksum value that was set for the box itself. It appears that the user copied the entire output of the shasum command used, which includes the checksum and the file name. When comparing the values, they end up not matching. 

* `86b5040d4e7a45d1345ae4d2954c3a94  ubuntu-24.04-desktop.box` - value defined in the registry
* `86b5040d4e7a45d1345ae4d2954c3a94` - value computed by vagrant

The box publisher will need to update the checksum value for proper comparisons.

Cheers!
