### ISSUE TITLE
Unable to install vagrant-libvirt plugin due to gem conflict: excon-0.109.0 vs excon (~> 1.0)

### ISSUE THREAD

**Issue by pakosaan** [hashicorp/vagrant#13537]
### Debug output
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate fog-core-2.6.0, because excon-0.109.0 conflicts with excon (~> 1.0) (Gem::ConflictError)
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/specification.rb:1419:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/bundler.rb:769:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/bundler.rb:766:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/bundler.rb:766:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/bundler.rb:606:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/bundler.rb:358:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/plugin/manager.rb:141:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/plugin/manager.rb:151:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/action/install_gem.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/base.rb:17:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/install.rb:73:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/install.rb:72:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/install.rb:72:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/root.rb:69:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/environment.rb:319:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/bin/vagrant:248:in `<main>'
```

### Expected behavior
The plugin to be installed successfully and show it when `$ vagrant plugin list`

#### Vagrant version
Vagrant 2.4.1

#### Host operating system
```
# System Details Report
---

## Report details
- **Date generated:**                              2024-11-09 10:24:19

## Hardware Information:
- **Hardware Model:**                              Lenovo IdeaPad 3 15ALC6
- **Memory:**                                      8.0 GiB
- **Processor:**                                   AMD Ryzen™ 5 5500U with Radeon™ Graphics × 12
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               500.1 GB

## Software Information:
- **Firmware Version:**                            GLCN63WW
- **OS Name:**                                     Fedora Linux 41 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.6-300.fc41.x86_64

```

#### Steps to reproduce

1. vagrant plugin install vagrant-libvirt

**Comment by trinitronx** [comment]
I should add that this issue will affect any OS due to the `gem` dependency conflict on `excon`.

What happened here is:

- Upstream dependency `fog-core` `2.6.0` [just bumped the dependency on `excon` from `~> 0.71` to `~> 1.0`][3]
  - `vagrant-libvirt` depends on `fog-core ~> 2` and thus now after fog/fog-core@c6bbad9, sub-dependency constraint: `excon ~> 1.0`
    - This crosses the typical [SemVer][2] `MAJOR` version constraint boundary for just `excon`, while maintaining that `fog-core` just incremented the `MINOR` version.
    - This is generally fine so long as `fog-core`'s API itself has not experienced breaking changes.
    - In `.gemspec`, the general rule of thumb "best practice" is to keep the [pessimistic version constraint operator][4] on the major version boundary only, assuming that [SemVer][2] ensures breaking changes will increment the `MAJOR` version (again, this is generally fine...)
- Vagrant `2.4.2` installation _still includes_ the embedded version of `excon` v`0.112.0`: `/opt/vagrant/embedded/gems/gems/excon-0.112.0/`
- The new strict version dependency constraint, `excon ~> 1.0`, triggers here because this embedded version (`0.112.0`) of the dependency doesn't satisfy the constraint: `~> 1.0`.

So, while the plugins and their sub-dependencies are generally following the ideal case for specifying and bumping version constraints... due to Bundler & Ruby requiring sub-dependency gems to satisfy all the constraints, we end up with `excon` straddling the `MAJOR` version boundary.  Thus, there's now a conflict between Vagrant's sub-dependencies and `vagrant-libvirt` plugin's sub-dependencies.  Unless Bundler & Ruby allowed for isolated trees of leaf sub-dependencies to have different versions across an entire project stack, we need to match the versions being used across the plugin ecosystem.

Therefore, get this error:

```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/3.3.0/rubygems/specification.rb:2245:in `raise_if_conflicts': Unable to activate fog-core-2.6.0, because excon-0.112.0 conflicts with excon (~> 1.0)
```

Further details [explained here][1]

[1]: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1830#issuecomment-2466530451
[2]: https://semver.org/
[3]: https://github.com/fog/fog-core/pull/304/files
[4]: https://guides.rubygems.org/patterns/#pessimistic-version-constraint

**Comment by chrisroberts** [comment]
Sorry for the delay on this. As noted above, the vagrant_cloud gem was published with updated dependency constraints to loosen them and the 2.4.3 version of Vagrant has been released which will pull in this new version.

Cheers!
