### ISSUE TITLE
vagrant up not working properly

### ISSUE THREAD

**Issue by youssef-abbih** [hashicorp/vagrant#13553]
### Debug output

The complete debug output for the issue can be found [here](https://gist.github.com/youssef-abbih/39dcd2f1a5ef4f3fb15860a01b4d2f4a).

### Expected behavior

The virtual machine should have started successfully with the guest additions properly installed and synchronized. The `vagrant-vbguest` plugin should not raise any errors during the VM initialization.

### Actual behavior

The following error occurs during `vagrant up`:

```
/home/leond95/.vagrant.d/gems/3.3.6/gems/vagrant-vbguest-0.32.0/lib/vagrant-vbguest/hosts/virtualbox.rb:84:in `block in guess_local_iso': undefined method `exists?' for class File (NoMethodError)
```

Additionally, the virtual machine reports a mismatch between the VirtualBox version on the host (7.1) and the Guest Additions version (4.3.40). This mismatch causes issues with shared folders and other guest features.

#### Vagrant version

Vagrant 2.4.3  
vagrant-vbguest plugin version: 0.32.0  

#### Host operating system

Ubuntu 24.04  

#### Guest operating system

Ubuntu 14.04 (`ubuntu/trusty64`)  

#### VirtualBox version

7.1.4r165100  

#### Steps to reproduce

1. Initialize a new Vagrant environment using the `ubuntu/trusty64` box:
   ```bash
   vagrant init ubuntu/trusty64
   ```
2. Start the virtual machine:
   ```bash
   vagrant up
   ```

#### Vagrantfile

```ruby
# Vagrantfile used to reproduce the issue
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
end
```

### Request for assistance

I have been unable to resolve this issue despite several attempts, including:

1. Manually updating the Guest Additions.
2. Ensuring the latest version of `vagrant-vbguest` is installed.
3. Testing with different VirtualBox versions and configurations.

Could you provide guidance on resolving this bug, or confirm whether it requires changes in the `vagrant-vbguest` plugin or Vagrant itself? Any workarounds or fixes would be greatly appreciated.

**Comment by PaulNeumann** [comment]
The issue is with the vagrant-vbguest plugin. The `File.exists?` method used by the plugin was removed in Ruby 3.2, and Vagrant 2.4.3 uses Ruby 3.3.6.

Unfortunately, the vagrant-vbguest plugin is no longer maintained as of 17 December 2023. You can see the announcement on the repository's home page [here](https://github.com/dotless-de/vagrant-vbguest).

However, you **might** be able to patch the plugin to work correctly. The error message shows the file and line number where the `File.exists?` method is used. To try patching the plugin, open the file `/home/leond95/.vagrant.d/gems/3.3.6/gems/vagrant-vbguest-0.32.0/lib/vagrant-vbguest/hosts/virtualbox.rb` in a text editor. On line 84 of the file, change `File.exists?` to `File.exist?`.

This same issue affects other plugins, including vagrant-env (see https://github.com/hashicorp/vagrant/issues/13550).

I hope this helps.

**Comment by youssef-abbih** [comment]
Thank you, now vagrant work properly
