### ISSUE TITLE
Vagrant is always creating a new VM

### ISSUE THREAD

**Issue by Vloureiro** [hashicorp/vagrant#1454]
I'm using vagrant on Win7:

```
Virtualbox 4.2.8
Vagrant 1.0.6.dev
box_url "http://files.vagrantup.com/lucid32.box"
```

Until the last week, everythin is fine, vagrant created the VM once and then I was using it. But this week everytime I run "vagrant up" it creates a new VM, installing all my packages defined in chef-solo. Now I have 5 boxes in my Virtualbox, which only the first one is the real VM I use, with all my keys and development tools, but Vagrant just don't use it.

And there's more: vagrant is much, much slow now. What's going on?

**Comment by joequery** [comment]
I'm going to give @maoueh 's solution a try, as I've just lost my vm for the second time in two days on my Windows 8 machine :(

**Comment by maoueh** [comment]
Note that VirtualBox 4.3.20 and up has the fix for the problem with `./VBoxManage.exe showvminfo` command. Updating should resolve the issue.

**Comment by dheche** [comment]
I'm using vagrant 1.6.1, virtualbox 4.3.28, fedora 22

Updating .vagrant/machines/<machine_name>/virtualbox/id is not enought if your previous box is in save state (vagrant suspend). You should 'discard save state' from virtualbox first before you can vagrant up again.

**Comment by brainv** [comment]
any fix?

**Comment by eXistenZNL** [comment]
See how I solved it above.

**Comment by pabloleone** [comment]
I've the same problem.. everytime I switch repos, a new VM is created when I do vagrant up. I started with the .vagrant folder added to the repo and worked, I read on the internet that .vagrant shouldn't be in the repo, so I removed from the repo, since then everytime I switch branches, a new vm is created, so should I add the .vagrant folder to the repo?

Why this happens? is there any reason I'm missing?

It's very annoying because it works the way that it shouldn't.
