### ISSUE TITLE
Warning Guest Addition not present

### ISSUE THREAD

**Issue by gpsnail** [hashicorp/vagrant#1575]
I get the below warning 

```
No guest additions were detected on the base box for this VM! Guest
additions are required for forwarded ports, shared folders, host only
networking, and more. If SSH fails on this machine, please install
the guest additions and repackage the box to continue.
```

But when I check the value 

```
VBoxManage guestproperty get  MYID  /VirtualBox/GuestAdd/Version
```

I got the result 

```
Value: 4.2.10
```

I use version 1.1.5 of Vagrant, does Vagrant use a specific version of VB ?

I know this is probably link to the issue https://github.com/mitchellh/vagrant/issues/1179 but It seems to be quite different ?

**Comment by cbj4074** [comment]
@mitchellh Regarding the commit that "fixes" this issue, is there any reason not to approach it the other way around, that is, try `showvminfo` **first**, and then fall back to `guestproperty`?

The problem is that VirtualBox may report inaccurate data when the first method is tried. For example (and this is with the VM running):

```
VBoxManage guestproperty get homestead-7 /VirtualBox/GuestAdd/Version
Value: 5.2.12
```

```
VBoxManage showvminfo homestead-7 --machinereadable
...
GuestAdditionsVersion="5.2.18 r124319"
```

I'm not sure if, when, or how VirtualBox "updates" the `guestproperty` information by its own accord, but, clearly, there is the potential for it to be stale. (I've rebooted the host, too, and the information is not updated.)

Given the observations that I note at https://github.com/dotless-de/vagrant-vbguest/issues/300#issuecomment-416974724 , with regard to how `guestproperty` values are set, it seems that there is no guarantee that this value is even remotely accurate. One would think that the Guest Additions installer would update this value, but, alas, it does not.

Is there any harm in swapping the order in which these approaches are tried? It seems that doing so would give third parties who rely upon the `read_guest_additions_version` function better, more accurate information (see linked issue, just above, for example).

Thanks for any consideration!
