### ISSUE TITLE
vagrant up : The following SSH command responded with a non-zero exit status.

### ISSUE THREAD

**Issue by stattrak-dragonlore** [hashicorp/vagrant#1659]
Bringing machine 'default' up with 'virtualbox' provider...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] VM booted and ready for use!
[default] Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sed -e '/^#VAGRANT-BEGIN/,/^#VAGRANT-END/ d' /etc/network/interfaces > /tmp/vagrant-network-interfaces

```
$ vagrant -v
Vagrant version 1.2.2
```

**Comment by killua99** [comment]
In my case I did "sudo service nfs-xxxx-kernel restart" and it start working. Kinda weird tho

**Comment by shivapoudel** [comment]
This issue is till not fixed:
![capture-3](https://cloud.githubusercontent.com/assets/3774827/7148304/775670b8-e321-11e4-84bb-9c8290b298c7.PNG)

**Comment by klinkin** [comment]
@shivapoudel +1

**Comment by tshwangq** [comment]
anyone has a solution for windows?

**Comment by espellcaste** [comment]
Same problem here! Not sure what it is!

**Comment by edegaudenzi** [comment]
Also worked for me: https://github.com/mitchellh/vagrant/issues/1659#issuecomment-29805314

**Comment by catuss-a** [comment]
same problem..

**Comment by eduartua** [comment]
Guys I have the following issue:


0
down vote
favorite
I am starting using Rancher and Vagrant to create my local environment for development. Steps that I've done:

1) I already had VirtualBox installed.
2) I download and installed the Vagrant package for linux with

sudo rpm -i vagrant_1.7.2_x86_64.rpm  
After typing:

vagran --version  
I got

Vagrant 1.7.2  
3)Then I cloned the Rancher repo from GitHub:

git clone git@github.com:rancherio/rancher.git  
Which has the Vagrant file.

4)After executing:

sudo vagrant up  
Which is the step where I get the error, I got this:

==> rancher: Box 'coreos-alpha' could not be found. Attempting to find and install...
rancher: Box Provider: virtualbox
rancher: Box Version: >= 308.0.1
==> rancher: Loading metadata for box 'http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json'
rancher: URL: http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
==> rancher: Adding box 'coreos-alpha' (v709.0.0) for provider: virtualbox
rancher: Downloading: http://alpha.release.core-os.net/amd64-usr/709.0.0/coreos_production_vagrant.box
rancher: Calculating and comparing box checksum...
==> rancher: Successfully added box 'coreos-alpha' (v709.0.0) for 'virtualbox'!
==> rancher: Importing base box 'coreos-alpha'...
==> rancher: Matching MAC address for NAT networking...
==> rancher: Checking if box 'coreos-alpha' is up to date...
==> rancher: Setting the name of the VM:rancher_rancher_1434213461241_51852
==> rancher: Clearing any previously set network interfaces...
==> rancher: Preparing network interfaces based on configuration...
rancher: Adapter 1: nat
rancher: Adapter 2: hostonly
==> rancher: Forwarding ports...
rancher: 8080 => 8080 (adapter 1)
rancher: 22 => 2222 (adapter 1)
==> rancher: Running 'pre-boot' VM customizations...
==> rancher: Booting VM...
==> rancher: Waiting for machine to boot. This may take a few minutes...
rancher: SSH address: 127.0.0.1:2222
rancher: SSH username: core
rancher: SSH auth method: private key
rancher: Warning: Connection timeout. Retrying...
rancher: 
rancher: Vagrant insecure key detected. Vagrant will automatically replace
rancher: this with a newly generated keypair for better security.
rancher: 
rancher: Inserting generated public key within guest...
rancher: Removing insecure key from the guest if its present...
rancher: Key inserted! Disconnecting and reconnecting using new SSH key...
==> rancher: Machine booted and ready!
==> rancher: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!  

systemctl start system-cloudinit@-var-tmp-hostname.yml.service  

Stdout from the command:  



Stderr from the command:

Job for system-cloudinit@-var-tmp-hostname.yml.service failed because a configured resource limit was exceeded. See "systemctl status system-cloudinit@-var-tmp-hostname.yml.service" and "journalctl -xe" for details.  
Then when i go to the localhost:8080 there is no Rancher UI installed.

I'd really appreciate any help whit this.

**Comment by piclez** [comment]
eduartua I'm also having same error in another instance with CoreOS.

**Comment by saurabh-anatta** [comment]
When I did vagrant up Then got following error:-
DEBUG ssh: Exit status: 6
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant

Please any one can help to fix this problem

**Comment by Braunson** [comment]
:+1: Any updates on this? I'm running the Virtual Machine 5.0, Vagrant 1.7.4 on Windows 8. 

`The SSH command responded with a non-zero exit status.` This shows right after the text `Notice: Finished Catalog run in 92.92 seconds`

**Comment by Quberik** [comment]
I have this too.

    Notice: Finished Catalog run in 678.19 seconds
    The SSH command responded with a non-zero exit status.

**Comment by dhanashree89** [comment]
Hello guys,

Even after adding-->  vagrant ALL=(ALL) NOPASSWD:ALL to /etc/sudoers file in guest machine, I'm still getting the same error (as shown below) on mac. Any solution, hint to resolve this problem?

Error:

==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/xyz/Desktop/vagrant
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p /vagrant

Stdout from the command:

Stderr from the command:
sudo: no tty present and no askpass program specified

**Comment by veernaladivya** [comment]
Hi Guys,

please run the below command to fix the issue.

vagrant reload --provision

i tried it worked for me.

**Comment by Divyaganapathy** [comment]
![vagrant error](https://cloud.githubusercontent.com/assets/15605061/11891647/a3da6090-a586-11e5-925e-36c951aecfa4.png)

**Comment by Divyaganapathy** [comment]
can someone give me a solution

**Comment by catuss-a** [comment]
@Divyaganapathy looks like adb is not installed as root right?

**Comment by Divyaganapathy** [comment]
yes. How do i do it?

**Comment by catuss-a** [comment]
@Divyaganapathy Either you're running adb as root and provided your vm as non-root (vagrant uses default root if not specified) or you have not provided correctly your VM.

However you should not run use adb as root so you'd better set up a user and use it to provision and  connect to you vm ([here](https://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html))

**Comment by Divyaganapathy** [comment]
config.ssh shows command not found

**Comment by Hakscat** [comment]
Has anyone made any progress on solving this problem? In case it helps with the debug here is the log I get:

```
==> Vaprobash: >>> Updating Composer
==> Vaprobash: You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
==> Vaprobash: You are already using composer version 03299ff075236be27be356498d6c64def973fe41.
==> Vaprobash: >>> Setting Github Personal Access Token
==> Vaprobash: You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
==> Vaprobash: >>> Installing Global Composer Packages:
==> Vaprobash:      squizlabs/php_codesniffer:1.5.*
==> Vaprobash: Changed current directory to /home/vagrant/.composer
==> Vaprobash: You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
==> Vaprobash:                                                                                                    
==> Vaprobash:   [UnexpectedValueException]                                                                       
==> Vaprobash:   Your github oauth token for github.com contains invalid characters: "phpspec/phpspec:2.0.*@dev"  
==> Vaprobash:                                                                                                    
==> Vaprobash: require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by catuss-a** [comment]
@Hakscat It looks like your oauth token for github is corrupted ? ^^

**Comment by Hakscat** [comment]
Thanks @catuss-a. Had to edit my auth.json inside path-to-composer/.composer/. The auth token was corrupt in there. There seems to be some section in the install script that changes the value set here every time it is run back to "phpspec/phpspec:2.0.*@dev" rather than a valid token value.

**Comment by oalpha** [comment]
@Hakscat  
step1:  use putty to login  server
step2:  type cmd <b><code> composer config -g --unset github-oauth.github.com</code></b>
step3:  execute cmd <b><code>vagrant provision</code></b> on your host

**Comment by hdunderscore** [comment]
Same problem as @Hakscat, I had to chmod auth.json to prevent the corruption.

**Comment by anup4khandelwal** [comment]
I was getting the same error. I had accidentally deleted my /tmp directory. To fix the issue I manually create /tmp directory and the error was resolved.

sudo mkdir /tmp

**Comment by bachiri** [comment]
Hi every one i have a problem with the shared folder when i restart my Host and after running vagrant up i get 

![Uploading Screen Shot 2016-02-24 at 6.48.12 PM.png…]()

**Comment by bachiri** [comment]
Hi every one i have a problem with the shared folder when i restart my Host and after running vagrant up i get 

<img width="585" alt="screen shot 2016-02-24 at 6 48 12 pm" src="https://cloud.githubusercontent.com/assets/8291024/13296884/95fee618-db27-11e5-98fa-c545fb27c103.png">

**Comment by jcrben** [comment]
I think that if you have an error in your provisioning script, it will report this 'SSH command responded with non-zero exit status error' - so this issue is a bag of various issues. In my case it seems to have been caused by `grunt-notify` in combination with karma causing the EMFILE error (https://github.com/dylang/grunt-notify/issues/68).

**Comment by acmitch** [comment]
I got similar issues because my Vagrant version was not supported by VirtualBox. I simply updated VirtualBox and Vagrant to the latest versions and everything worked perfectly.

**Comment by emfluenceindia** [comment]
I am absolutely new to this. Today I tried to install VDD following steps and instructions as described at [https://www.drupal.org/node/2008792]. First time I received a series of "problems" after running `vagrant up` command (attached).
[vagrant-up-error.txt](https://github.com/mitchellh/vagrant/files/179159/vagrant-up-error.txt)

Then I created a new folder, put all `VDD` files into it and ran a fresh `vagrant up` from this folder. Now I have received 

> The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed.

How can I get out of this? I am on Windows 10.
Somebody please help!

**Comment by kisat** [comment]
**emfluenceindia** Did you find solution on Windows 10? I have a same problem on windows.

**Comment by emfluenceindia** [comment]
Hi Kisat, unfortunately I didn't have solution. I switched to XAMPP and now things look pretty good.

**Comment by kisat** [comment]
Hi. Thanks for your comment . I update vagrant 1.8.4 after that it is
working fine.

**Comment by razbakov** [comment]
I am using Mac. Yesterday everything worked perfectly. Since today doesn't work anymore.

```
vagrant -v
Vagrant 1.8.5
```

By `vagrant up` I have next problem:

```
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

set -e
mkdir -p /home/vagrant/projects
mount -o vers=3,udp 192.168.33.1:/Users/xxx/Projects/php5 /home/vagrant/projects
if command -v /sbin/init && /sbin/init --version | grep upstart; then
  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/home/vagrant/projects
fi


Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: requested NFS version or transport protocol is not supported
```

**Comment by ConnectedCat** [comment]
have the same issue here

**Comment by razbakov** [comment]
I posted more detailed report in #7646

**Comment by aidygus** [comment]
Same problem as @razbakov 

Windows 7, Vagrant 1.8.5, VB 5.1.2

**Comment by Festum** [comment]
Same as @razbakov
Windows 10 1511 x64, Vagrant 1.8.5, VBox 5.1.2

**Comment by oscarAG** [comment]
Hey everyone, I had this same issue and updating Oracle VirtualBox fixed it for me.

**Comment by ito2307** [comment]
I was using my Vagrant/homestead on Windows, i was programming in my project just when I want to close my homestead, not I allowed to close it simply, because showed me this message, also remember having running sudp apt-get upgrade, to install the latest version of the ldap.

zendframework/zend-ldap 2.7.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.

sudo apt-get install php7.0-ldap [default] GuestAdditions versions on your host (5.1.6) and guest (5.1.4) do not match. sudo: no tty present and no askpass program specified sudo: no tty present and no askpass program specified ==> default: Checking for guest additions in VM...

The following SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed!

apt-get update

Stdout from the command:



Stderr from the command:

sudo: no tty present and no askpass program specified
, had that force it with vagrant halt - force, is it?

**Comment by adamcee** [comment]
I encountered this issue recently on OS X 10.10.5 with VirtualBox 5.0.10 and Vagrant 1.8.

Checking `/etc/sudoers` before and after destroying/rebuilding the machine confirmed that something similar was occuring in the sudoers file as mentioned in [17046154](https://github.com/mitchellh/vagrant/issues/1659#issuecomment-17046154) - I was missing the lines:
`Defaults    exempt_group=sudo` and the `NOPASSWD:ALL` part of `%sudo   ALL=(ALL) NOPASSWD:ALL`.
Does anyone know what could be causing the sudoers file to get modified?

**Comment by arkataev** [comment]
recently I 've made a sudu dist --upgrade on my Homestead and then it started to fall down with 
`sudo: no tty present and no askpass program specified` error. 
As @rfay suggested I added `ALL=(ALL) NOPASSWD:ALL
Defaults:vagrant !requiretty` to `etc/sudoers.d/README` and it worked just fine

**Comment by edosurya** [comment]
I had this same issue and updating Oracle VirtualBox and Vagrant fixed it for me.
VirtualBox 5.0.26
Vagrant 1.8.6

**Comment by chendo19** [comment]
@nicolasgarnil  where do I have to add this line vagrant ALL=(ALL) NOPASSWD:ALL?

**Comment by adamcee** [comment]
@rfay 's solution [here](https://github.com/mitchellh/vagrant/issues/1659#issuecomment-17046154) seems to be working for me.

**However** as a relative `sudoers` noob I may have been adding the commands in the wrong place in `/etc/sudoers`. What finally worked for me was adding them to a file I created in `/etc/sudoers.d` (`/etc/sudoers` was including the `sudoers.d` directory in my case. This include occurred at the bottom of the file).

**Comment by Changsik00** [comment]
This issue has been resolved.

I guess .. you miss  "Password-less Sudo" part 
https://www.vagrantup.com/docs/boxes/base.html

In another way 
http://askubuntu.com/questions/406787/best-way-add-nopasswd-vagrant-user

**echo vagrant ALL=NOPASSWD:ALL > /etc/sudoers.d/vagrant**

**Comment by jarce6791** [comment]
I have this issue:
==> default: [DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and
==> default: make sure become_method is 'sudo' (default).
==> default: This feature will be removed in a
==> default: future release. Deprecation warnings can be disabled by setting
==> default: deprecation_warnings=False in ansible.cfg.

And after this show this issue:
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Please I need help with this

**Comment by Sufir** [comment]
I too have this problem:
> ==> Ubuntu Xenial 16.04 LTS x64 (PHP 7): Info: Stage[main]: Unscheduling all events on Stage[main]
> ==> Ubuntu Xenial 16.04 LTS x64 (PHP 7): Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
> ==> Ubuntu Xenial 16.04 LTS x64 (PHP 7): Notice: Applied catalog in 705.36 seconds
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

Config generated by puphpet, `ALL=(ALL) NOPASSWD:ALL` exists.
```
Vagrant 1.9.1
Win 8.1
VBox 5.0.32
```

**Comment by Nguonchhay** [comment]
I think we can resolve by this `sudo killall -9 ruby` as screen 
```
If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.
```

**Comment by ConAntonakos** [comment]
I ran into this today. I cannot `vagrant reload` at all. I'm also getting `non-zero exit status` error as an output.

**Comment by rayaqin** [comment]
I had to set up the proxy for it to work:

set HTTP_PROXY= xyz
set HTTPS_PROXY= xyz

**Comment by xiaoAtHouzz** [comment]
I got the same issue....Solved by restart my laptop......I dont know what to say....restarting is always a good solution...

**Comment by alpharameeztech** [comment]
I am using Ubuntu and i am getting the same error 
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown 'eth1' || true
/sbin/ip addr flush dev 'eth1'
# Remove any previous network modifications from the interfaces file
sed -e '/^#VAGRANT-BEGIN/,$ d' /etc/network/interfaces > /tmp/vagrant-network-interfaces.pre
sed -ne '/^#VAGRANT-END/,$ p' /etc/network/interfaces | tac | sed -e '/^#VAGRANT-END/,$ d' | tac > /tmp/vagrant-network-interfaces.post
cat \
  /tmp/vagrant-network-interfaces.pre \
  /tmp/vagrant-network-entry \
  /tmp/vagrant-network-interfaces.post \
  > /etc/network/interfaces
rm -f /tmp/vagrant-network-interfaces.pre
rm -f /tmp/vagrant-network-entry
rm -f /tmp/vagrant-network-interfaces.post

/sbin/ifup 'eth1'

Stdout from the command:



Stderr from the command:

bash: line 5: /sbin/ifdown: No such file or directory
bash: line 19: /sbin/ifup: No such file or directory


```

**Comment by briancain** [comment]
Hi @alpharameeztech - That error will likely be fixed if you upgrade your version of Vagrant to the latest.

**Comment by alpharameeztech** [comment]
@briancain I am using the latest version 
```
Vagrant 2.0.2

```

**Comment by briancain** [comment]
@alpharameeztech - the latest version is `2.1.2`. You can find that version here! https://www.vagrantup.com/downloads.html

Thanks.

**Comment by alpharameeztech** [comment]
Hey @briancain. Thank you for the update. I am gonna try and will let you know then :)

**Comment by alpharameeztech** [comment]
@briancain Gracias amigo :) the issue got resolved with a vagrant update.

**Comment by andela-tolotin** [comment]
Updating from 2.0.2 to 2.2.0 solved my problem

**Comment by calinblaga** [comment]
for me it was the guest additions and:
`vagrant plugin update vagrant-vbguest`
did the trick

**Comment by gregbast1994** [comment]
This is how I fixed it per [this comment above](https://github.com/hashicorp/vagrant/issues/1659#issuecomment-17046154)

Open the sudoers file (with visudo or you will break things).
`$ sudo visudo`

Add the following lines ABOVE the include to sudoers.d
`vagrant ALL=(ALL) NOPASSWD:ALL
Defaults:vagrant !requiretty`

Save, and ignore the prompt to edit the README

Reboot your system
`$ reboot`
