### ISSUE TITLE
Vagrant doesn't find puppet on VM

### ISSUE THREAD

**Issue by nlamirault** [hashicorp/vagrant#1737]
I create a box like that :

Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  #config.vm.network :hostonly, "10.1.2.45" #:hostonly or :bridged - default is NAT
  config.vm.network :private_network, :ip => '10.1.2.45'

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |vb|
     #vb.gui = true
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
    puppet.options = "--verbose --debug"
  end

end

$> vagrant up
[...]

$> vagrant ssh
Welcome to Ubuntu 12.04.2 LTS (GNU/Linux 3.2.0-23-generic x86_64)
- Documentation:  https://help.ubuntu.com/
  Welcome to your Vagrant-built virtual machine.
  Last login: Wed May 15 09:58:11 2013 from 10.0.2.2

$ puppet --version
2.7.11

$ which puppet
/usr/bin/puppet

$  ls /tmp/vagrant-puppet/
manifests  modules-0

$ exit
Connection to 127.0.0.1 closed.

$> vagrant provision
[default] Running provisioner: puppet...
The `puppet` binary appears to not be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed.

**Comment by huemans** [comment]
Hi all, having the same problem but still not sure how to fix based on above comments. which puppet on my host is usr/bin/puppet. I can see PATH on my guest but not sure what if anything its telling me or what to do with that info.

==> master1: Running provisioner: puppet...
The `puppet` binary appears not to be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed

$ vagrant ssh master1  -c 'sudo echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
Connection to X.X.X.X closed.

$ vagrant ssh master1  -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
Connection to X.X.X.X closed.

**Comment by BigPecan** [comment]
Is this issue continued anywhere? I am using vagrant 1.91 on windows 10 with Hyper-V and getting that error "==> default: Running provisioner: puppet...
The `puppet` binary appears not to be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed." trying to provision puppet
