### ISSUE TITLE
VM sometimes hangs in Grub (timeout -1) and waits forever

### ISSUE THREAD

**Issue by acesuares** [hashicorp/vagrant#1792]
There are many threads regarding '`vagrant up` hangs at "Waiting for VM to boot. This can take a few minutes".

However, I discovered that my problem had nothing to do with networking.
For some reason, the VM waited forever in GRUB. See screen shot.

![foo4](https://f.cloud.github.com/assets/2784/600606/5338e0ea-cc6b-11e2-9765-820a261762ba.png)

How to make a screen shot: https://github.com/gavD explains: https://github.com/mitchellh/vagrant/issues/1066#issuecomment-8824802

https://github.com/smoya explained how to fix tge grub-hanging problem it: https://github.com/mitchellh/vagrant/issues/391#issuecomment-12264830

So, would it be prudent to change the -1 timeout in grub to 10 in all packaged boxes?

Thanks a million to both gavD and smoya, or I would never have found the problem and being able to fix it!

**Comment by insprintorob** [comment]
I followed the advice here: http://serverfault.com/questions/243343/headless-ubuntu-server-machine-sometimes-stuck-at-grub-menu and it worked. This has happened to several previous vms, sometimes the boot record is overwritten by a software update.

**Comment by jay** [comment]
> I followed the advice here: http://serverfault.com/questions/243343/headless-ubuntu-server-machine-sometimes-stuck-at-grub-menu and it worked. This has happened to several previous vms, sometimes the boot record is overwritten by a software update.

Thanks for this. I had [data-science-toolbox/dst](https://atlas.hashicorp.com/data-science-toolbox/boxes/dst) hang a few times when I brought it up because I didn't do a graceful shutdown prior. I used to start it in the GUI to fix it as a workaround. Since then I've followed the accepted answer in the link you provided and set `GRUB_RECORDFAIL_TIMEOUT` to a short timeout and I haven't had a hang since. While this may not strictly be vagrant's problem I think on a headless boot via up one would expect it not to hang at grub. Perhaps @mitchellh you could consider making this change for the boxes hosted by HashiCorp at least? Otherwise there will be situations where grub just hangs forever, waiting. Thanks
