### ISSUE TITLE
Preparation to use vagrant on Windows is quite different that it may need a separate sections/doc

### ISSUE THREAD

**Issue by edwardt** [hashicorp/vagrant#1813]
Hi, 

The documentation about preparation and installation of  vagrant on windows is quite substantially different that it may warrant to create separate sections on that.

This blog describes that very well and it work very well (on Windows 7) -- a success the first time . 

http://www.habdas.org/developing-modern-web-applications-on-windows-vagrant/

Thanks

**Comment by cdenneen** [comment]
@mitchellh Vagrant doesn't correct CRLF as I took a working setup on Mac with Linux guest and went to ```vagrant up``` on Windows and the shell provisoner lines were breaking the scripts.

Using:

```
git config --global core.autocrlf input
```

and then doing clone fixed the problem during vagrant up.

**Comment by bman654** [comment]
Ditto @cdenneen .  I just installed Vagrant 1.7.2 and took a working setup that was built on Mac with Linux guest.

When I did a `vagrant up`, The shell provisioners fail with messages like this:

```
==> default: E
==> default: :
==> default: Unable to locate package unzip
==> default: rm:
==> default: cannot remove ???vault_0.1.2_linux_amd64.zip\r???
==> default: : No such file or directory
```

And when I `vagrant ssh` into the box, the shell script configured to run from `.bashrc` also failed due to line endings.

**Comment by cyberis** [comment]
Line endings in the shell provisioner aren't normalized to LF in version 1.8.1 either
