### ISSUE TITLE
vagrant public network available bridged network should support a default value for batch mode style operation

### ISSUE THREAD

**Issue by dodtsair** [hashicorp/vagrant#1865]
If you start up a vagrant vm with a public network configured and the host machines has multiple interfaces to bridge to vagrant will ask which interface to use.  Since vagrant is often used in scripts there should be a way to specify vagrant to run in a batch mode.  Specifically for public networks when there is no user to answer the question it would make sense to default to the network that is associated with the default route.

**Comment by bitifet** [comment]
In case it can be useful for someone, [here is handy snippet](https://github.com/bitifet/vagrants/blob/master/Snippets/dhcpNetwork.md) to automate MAC address and bridging interface selection.

MAC address is pseudo-randomly generated based on Vagrantfile inode number and also detect if it is a symlink (to get symlink itself inode) so that Vagrantfile can be reused (mo matter if it is copied or symlinked) to generate more envirnoments not bothering about adjusting new MAC address again.

But, on the other hand, that MAC is the same (and, hence, dhcp leased ip should be too) between vagrant destroy/rebuild processes not causing IP to change every time given environment is regenerated.

PD: Answering to @sneak: Detecting default route could be another good strategy too (good point!). I did it simply by selecting first active interface which works well for me. But it souldn't be difficul to add that filter if needed. ;-)

**Comment by FaizanNoor** [comment]
config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', ip: "192.168.1.111"
