### ISSUE TITLE
Want to pass parameters to VagrantFile from command line

### ISSUE THREAD

**Issue by Findekano** [hashicorp/vagrant#2064]
After a while my VagrantFile becomes fairly sophisticated (complicated). It will be very nice if Vagrant can provide a features that allows us to pass command line parameters into the Ruby script in VagrantFile.

For example, we can say:

``` bash
vagrant up --Dmode=test
```

in VagrantFile, it then is able to reference the parameter by 

``` ruby
case properties[:mode]
when "test"
    # ...
when "release"
    # ...
end
```

**Comment by lsloan** [comment]
I saw a [solution on Stack Overflow](http://stackoverflow.com/a/31070025/543738) that suggests using Ruby's `GetoptLong` class to get options from the commandline.  It would allow commands like:

```sh
vagrant --custom-option=option up
vagrant --custom-option=option provision
```

Special care may need to be taken to avoid interfering with vagrant's preexisting options.  Some users have reported problems with this solution, which may be due to the versions of vagrant or ruby being used.
