### ISSUE TITLE
Vagrant file in a completely separate folder.

### ISSUE THREAD

**Issue by CMCDragonkai** [hashicorp/vagrant#2292]
Hello, I've tried going through the docs to find this ability.

Basically if I have my Vagrantfile.. etc in a separate directory. Let's imagine C:\www\vagrant

But I want to setup the virtual box root to be C:\www, how would I go about doing this? Is there some CLI option to specify where to look for the vagrant file? And how do I differentiate the different paths inside the vagrant file? Some paths will obviously be inside the C:\www\vagrant, and some paths will refer to C:\www.

The reason I want to do this, is to create a version controlled repository for my vagrant configuration, which should be inside a folder, rather than at the root of C:\www, because that's just parent directory for all my other projects.

**Comment by displague** [comment]
@mitchellh  I am using the `load` paradigm to combine multiple Vagrantfiles.  While it generally works, when an otherwise independent Vagrantfile is pulled in this way the `synced_folder`s get based off of the wrapper `Vagrantfile`'s `VAGRANT_CWD`.

```ruby
Vagrant.configure(2, do |config|
   # Global things
end

# vagrant/ is a directory where other repos are cloned, each with their own Vagrantfile,
# each using some synced folders within their repo
Dir['vagrant/*/Vagrantfile'].each do |vagrantfile|
  load File.expand_path(vagrantfile) if File.exists?(vagrantfile)
end
```
I've considered that the `Dir` loop should `Dir.chdir` into the folder of the child `Vagrantfile`, and that `VAGRANT_CWD` should be set in the loop too.  I don't want to have to modify the child `Vagrantfile`s.

The problem I'm having is that the synced_folders don't work because the children are run from the parents directory.

It seems like `Vagrant.Config.Loader` may be the place to change the behavior unless there is a way to run vagrant this way without modification.  Thoughts?
