### ISSUE TITLE
Support Virtualbox NAT networking

### ISSUE THREAD

**Issue by phy1729** [hashicorp/vagrant#2779]
It would be nice to have a networking option that has access to the public internet and does not require any configuration on the guest for that network so that the Vagrantfile is portable.

**Comment by brifordwylie** [comment]
Would love to see this file (which appears to no longer be there :)
 https://github.com/phy1729/cv_config/blob/natnet-example/Vagrantfile

**Comment by mainframe** [comment]
Im having the same problem - running cluster of Vagrant boxes and it requires default route interfaces to be able to communicate with each other between VMs (ie to be in the same network). Model where adatper 1 has same private IP (and different private network/VLAN with no intercommunication) for every VM and is actually default route/gateway device - and for VMs interconnection there has to be a separate adapter/network - it seems an overcomplication in case of multi-vm scenario. In my case its a blocker for sure - as reconfiguring a complex cluster application is much more work than running and configuring VBox VMs manually with NAT network adapter. So I would urge to reconsider the importance of supporting NAT network adapter type (ie single NAT adapter with interconnect between VMs in this network) - in order to deliver better user experience also for multi-vm scenarios.

**Comment by euidzero** [comment]
My use case is precisely to test multi homed NAT'ed clients. So I need multiple NAT'ed NICs on different subnets all accessing the internet through the host IP. Currently I do not see how to achieve this  easily as (correct me if I'm wrong) Vagrant does not provide a way to add extra NAT adapters. 

Thanks for reconsidering adding this feature.

**Comment by kikitux** [comment]
@euidzero In your case, as Vagrant is not the tool, yoy may want to look into [packer](https://packer.io) there you can create a new VM modify the nics, etc.. 

note that packer is also a hashicorp product

**Comment by rutsky** [comment]
@phy1729, @mainframe have you managed to get VMs in single routable network that also NAT-ed to the Internet?

I'm struggling with [Kubernetes deployment in Vagrant with Ansible](https://github.com/kubernetes/contrib/tree/master/ansible/vagrant) and current default configuration brings a lot of issues.

Currently each VM in multi-VM configuration has two network adapters:
1. NAT-ed to the host network (and Internet). Packets are routed by default through this interface.
2. Private VMs network. Allows VMs to connect to each other.

E.g.:

```
# ip a
...
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:96:9e:8a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86299sec preferred_lft 86299sec
    inet6 fe80::a00:27ff:fe96:9e8a/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:48:ea:40 brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.5/24 brd 172.28.128.255 scope global dynamic eth1
       valid_lft 1099sec preferred_lft 1099sec
    inet6 fe80::a00:27ff:fe48:ea40/64 scope link 
       valid_lft forever preferred_lft forever
...
# ip route show
default via 10.0.2.2 dev eth0  proto dhcp  src 10.0.2.15  metric 1024 
10.0.2.0/24 dev eth0  proto kernel  scope link  src 10.0.2.15 
10.0.2.2 dev eth0  proto dhcp  scope link  src 10.0.2.15  metric 1024 
172.28.128.0/24 dev eth1  proto kernel  scope link  src 172.28.128.5 
...
```

Lots of applications in Kubernetes assumes, that host IP is an IP of default network interface, which is NAT interface in current default configuration, so they try to advertise and use NAT IP (which is same for all machines 10.0.2.15) which fails.

While it is possible to configure each application to use proper interface it's tedious and brings additional complexity to Ansible scripts (same Ansible scripts are used to configure Kubernetes on real hardware which usually have one interface that is connected to other machines and NATed).

Looks like using [NAT network](https://www.virtualbox.org/manual/ch06.html#network_nat_service) suggested by @phy1729 should resolve this issue and make multi-VM configuration closer to real multi-host setup.

Does anybody have working examples of using such NAT network in Vagrant? @phy1729 link to your example of such configuration got rotten.

**Comment by mainframe** [comment]
@rutsky - no my workaround was to move to Parallels Desktop instead :)

**Comment by stephenrlouie** [comment]
This worked for me. 
```
def nat(config)
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nic2", "natnetwork", "--nat-network2", "provision", "--nictype2", "virtio", "--macaddress2", "1234567890ab"]
    end
end

Vagrant.configure(2) do |config|
    config.vm.define "example", autostart: true do |build_example|
        nat(config)
        build_example.vm.box = $box
        build_example.vm.network "forwarded_port", guest: 80, host: 8080
        build_example.vm.network "forwarded_port", guest: 443, host: 8443
    end
end
```

If Vagrant could natively support this as a standard networking option, that would be awesome!

**Comment by riotejas** [comment]
We have the same requirements a @mainframe and others.  Running  a cluster of VMs that need to communicate with each other and public NAT using VirtualBox's 'nat network'  I can configure this using just VirtualBox with all VM having adapter 1 as 'natnetwork', but then I can't using Vagrant.  A 'vagrant up' fails because adapter 1 is not 'nat'  This make Vagrant unusable for me.  Please consider making this feature available.

**Comment by simonpie** [comment]
I support this feature request.  The fact that the main adapter cannot be set to a natnetwork and that we have to add a second NIC makes building ansible playbook to deploy complex software a headache. A lot of code as to be written to find the correct interface and its ip and injects it in all the correct places.  The killer is, you have no real idea if the playbook will work when you get to a real environnement where all the VMs are on the same network with only one NIC since your playbook has only been tested with two NIC, the main ip being on the second NIC.  Something **KVM** does out of the box.

Hence, it would make vagrant more useful if we could choose the kind of network for the first NIC and not being forced to add a second nic.

**Comment by rul** [comment]
I support these feature request as well. I have a use case where I want to setup a development environment for a software that provides dynamic iPXE scripts. The software is hooked up with a DHCP server that will be running on a VM, and the idea is that other VMs can boot, request and retrieve the iPXE script from there DHCP server (hence VM to VM communication), and then the booting VM will probably bring the kernel from outside (hence VM to Internet communication). In this case two NICs aren't useful because AFAIK iPXE firmware only asks for DHCP on the first adapter. Also, I can't use bridged networking because I don't want a second DHCP server on my LAN.

**Comment by Constantin07** [comment]
+1
I also need this functionality - NAT Network support as pure NAT is not enough to spin up a cluster of nodes with inter-connectivity + access to public internet.

**Comment by aizikil** [comment]
Dear devs we really need it !!!

**Comment by ljubon** [comment]
Do we have any response to this? Is virtualbox__natnet available?

**Comment by FelipeMiranda** [comment]
This Topic is from 2014 any news on that?

**Comment by jd-18723** [comment]
@briancain Could we get a definitive answer as to whether this feature request is dead?

Judging by the upvotes on comments, and recent activity, there is still quite a bit of appetite for having NAT Networking supported in vagrant.

**Comment by simonpie** [comment]
its a must have.

**Comment by chewi** [comment]
I managed to fudge around the lack of support here but proper support would be nice. However, it's quite useless until VirtualBox itself is fixed. [This issue](https://www.virtualbox.org/ticket/14748) is a showstopper.

**Comment by jd-18723** [comment]
@chewi Can you post your workaround, please?

**Comment by chewi** [comment]
Sorry for the wait.

```ruby
Vagrant.configure(2) do |config|
  config.vm.provider 'virtualbox' do |vb|
    # This is the important part. You could also add extras
    # like '--nictype1', 'virtio'.
    vb.customize ['modifyvm', :id, '--nic1', 'natnetwork', '--nat-network1', 'MyNatNetwork']
  end

  # This part is a bit weird but it keeps SSH working. You'll
  # need to manually configure the NAT network to forward 2222 to
  # 22 on whichever IP the guest is on. Static IP configuration
  # may therefore be simpler than DHCP.
  config.vm.network :forwarded_post, id: 'ssh', guest: 22, host: 2222, disabled: true
  config.ssh.guest_port = 2222
end
```
