### ISSUE TITLE
Stderr: VBoxManage.exe: error: Could not rename the directory 

### ISSUE THREAD

**Issue by akhabibullina** [hashicorp/vagrant#2813]
Hello, so I am experiencing the same problem now with Win7 64 bit and Vagrant 1.4.3 and VBox 4.3.6. I see a lot of people do, too(Google helps to find them).

I've read the issues #1198, #1809 and #1817 which are related but all of them are closed. Is there any way to solve the problem? Just in case somebody is interested to help I paste the full output below:

```
HP@akhabibullina /cygdrive/c/work/js-sprint
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Setting the name of the VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "2c7dff7f-3a05-4d7f-913f-bb903b999ae6", "--name", "js-vagrant"]

Stderr: VBoxManage.exe: error: Could not rename the directory 'C:\Users\HP\VirtualBox VMs\js-vagrant_1389604969925_48693' to 'C:\Users\HP\VirtualBox VMs\js-vagrant' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 2711 of file VBoxManageModifyVM.cpp
```

The name of VM is set explicitly as shown below and it doesn't help:

```
  config.vm.provider :virtualbox do |vb|
    vb.name = "js-vagrant"
  end
```

I also tried

```
vagrant up
vagrant halt
vagranth up
```

Which didn't help too.

I'd appreciate any help,
Anna.

**Comment by zorancco** [comment]
I think I narrowed these cases down to trying to provision boxes with a same "name", from 2 different accounts (think admin and your user account). The rename step will fail second time around for the box started with a different user account, since the directory vagrant is trying to rename to already exists, as it was created by the other account...

**Comment by mkharoub** [comment]
Hello ,
 In My case just delete folders in ~/VirtualBox VMs/homestead
if after you run vagrant up, this message "Your VM has become "inaccessible." Unfortunately, ..." appears 
simply remove .vagrant from HOMESATED folder and type vagrant up again. 

Hope this help :)

**Comment by synbaas** [comment]
In my case, re-installation on oracle vm manager is work for me.

**Comment by jrleonr** [comment]
Thanks @mkharoub that worked for me. It fixed my problem.

**Comment by pablovelasquez** [comment]
I deleted the boxes on virtual box gui  and that fixed it.

**Comment by jmtmoulin** [comment]
I ran into this error when I deleted a chef gem dependency (never again) and had to reinstall chefdk again.

Steps I had taken
1.) Going into the .VirtualBox directory

2.) make sure Virtualbox is not running, restart computer if confused.

3.)  Edit Virtualbox.xml line 59 (well for me) <SystemProperties defaultMachineFolder= ??
change the location to a new directory, I just placed it in a directory within my Documents folder. Save. Save copy of previous xml file somewhere else for safety purposes. 

4.) go to .vagrant.d\boxes --- you can delete past boxes that have been used before. Not sure if required. 

5.) Turn on VirtualBox. you'll know if you didn't turn off VirtualBox because your xml file will be overwritten. 

I've tried all the suggestions above but this was the only real solution. Good Luck!

**Comment by jofecolella** [comment]
I cannot find .VirtualBox directory, neither Virtualbox.xml. I am on a macOS Sierra.

Thank you

**Comment by Jagadhissh** [comment]
@mkharoub
thankq very much  i stuked with this from last 20 days.

thanks

**Comment by tiennsloit** [comment]
Thanks so much @mkharoub, worked for me too.

**Comment by spaskovich** [comment]
In windows I removed the box using the Virtual Box Gui (kept the files) and then went into the "Virtual Box VMs" directory in the active Users directory (C:/users/[Active User]/Virtual Box Vms) and renamed the directory in question to ..._old (in my case sites_8bb48533874 > sites_8bb48533874_old).  Ran vagrant up as admin and the environment came right up as usual.

I'm not sure if the initial step of removing the box was necessary...but these two steps worked nonetheless.
