### ISSUE TITLE
vagrant up not detecting a previously run VM

### ISSUE THREAD

**Issue by g8d3** [hashicorp/vagrant#2969]
Hi,

I am not sure how this part of Vagrant works, but I am getting:

```
$ vagrant up
[default] VM not created. Moving on...
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'opscode-ubuntu-12.04-i386'...
[default] Matching MAC address for NAT networking...
A VirtualBox machine with the name 'xxxxxxx' already exists.
Please use another name or delete the machine with the existing
name, and try again.
```

When I already had a VM working, I just wanted to restart VM to add a forwarded port, any help on this is appreciated.

Thanks.

**Comment by johnkramlich** [comment]
@mikevanwinkle your workaround worked for me.  I'm not sure if this is related but I took a snapshot of the vm prior to the issue showing up.  Pure speculation, but possibly the UUID changes when you take a snapshot and the vagrant files do not reflect that change.

**Comment by jack-hs** [comment]
Thanks @reynoldsalec, your solution worked for me too. And I know the cause of my issue:
My macbook was sleeping when it ran out of battery. So vagrant crashed/shutdown. And when I tried to start it up again it didn't look/find existing virtualbox, so it created a new one.

**Comment by droidlabour** [comment]
1. Create a new_box
2. vagrant ssh new_box and copy .ssh/authorized_keys
3. vagrant halt new_box
4. Replace the new VMDK with the older one.
5. vagrant up new_box [it'll ask for vagrant password ,just enter vagrant which is the default password for vagrant user]
6. To remove that password prompt, just replace the .ssh/authorized_keys with the one at Step 2

**Comment by dcorb** [comment]
Same here. My Mac ran out of battery.
I followed @reynoldsalec solution. Thanks! Step by step:
Run ``vboxmanage list vms``, copy the id of the problematic machine (between curly brackets)
Paste the id in this file, replacing the previous one:
``sudo nano .vagrant/machines/default/virtualbox/id``

I could "vagrant up" again, as normally.

**Comment by tonnyk** [comment]
Was experiencing same issue but running 
`sudo vagrant up` solved the issue

**Comment by ponchog** [comment]
The solution provided by @reynoldsalec and detailed by @dcorb worked for me. Thanks!

**Comment by ksingh7** [comment]
Thanks solution provided by @reynoldsalec worked for me as well. However this is  just a workaround.

@mitchellh  if i remember correctly this problem ( VM id got changed for vagrant ) occurred after i created snapshot of my vm. Earlier it was working fine. So do you managed find a permanent fix.

**Comment by ruskotron** [comment]
The most troubling aspect of this issue is that when it occurs it will trash your existing box!

It seems to me a fundamental flaw that you have a single command ("vagrant up") for both starting an existing box, and provisioning an existing one. The fact that vagrant makes the decision on which to do is based on some flawed logic around persisted UUIDs is a consequent issue.

**Comment by ksingh7** [comment]
@ruskotron  +1  
It would be more sensible if we have commands like
```sh
vagrant create foo
vagrant up foo
vagrant halt foo
```

**Comment by Dr-Horv** [comment]
@ruskotron @ksingh7 I agree. Quite an annoyance. Ran into this issue twice now, first time I didn't bother to find a solution but just created a new box, quite time consuming though.

Separate create/provision from starting a box would be good.

**Comment by ruskotron** [comment]
I would recommend ditching vagrant altogether for day-to-day management of VMs. It's great for provisioning new VMs, but the ever-present threat of it capriciously destroying your work means you shouldn't use it beyond that. Once you're set up you should just use the VM-system native tools for starting stopping your VMs.

I'm working with VirtualBox so I created this simple script that use the `VBoxManage` command:

https://gist.github.com/ruskotron/fbf04bac53d86d84498c

It will boot your VM by name (rather than UUID) and ssh into the correct local port (presuming you're using local NAT interface for SSH).

It logs in twice, once to setup your shares and a second time to start your session. Unfortunately as it stands you have to type in a password for each login, but it should be very straightforward to add your ssh private key to `~/.ssh/authorized_keys`.

Hopefully this helps some people.

**Comment by gitressa** [comment]
I ran into this when I wanted to create a new machine, and got the "A VirtualBox machine with the name 'xxxxxxx' already exists." message. As ConnorHoehn commented I changed "boxname: vlad" in settings.yml, and don't get the "vlad_vlad already exists" message, in stead a new VirtualBox machine is created.

**Comment by BobWhitelock** [comment]
I've had this issue occur as well; in my case this happened when attempting to `vagrant reload` a box with an nfs shared folder, and then when prompted for admin privileges to enable this I hit ctrl-c rather than enter my password. I then got this issue when trying to reload the box again. Changing the UUID as suggested above did fix this however.

**Comment by EIrwin** [comment]
Why is this issue closed? It is clearly still an issue and the proposed fixes are not sufficient.

**Comment by antarus** [comment]
Why is this issue closed? 
Every day on vagrant up, the problem occur...

**Comment by EIrwin** [comment]
@antarus I have the same issue, everyday I am forced to blast my VM and run vagrant up again. I am debating getting rid of Vagrant all together if I can't find a way around this.

**Comment by EIrwin** [comment]
So I am running Yosemite v10.10.3 and was having this issue frequently (multiple times per day).

I haven't been able to reproduce it 100% of the time, but I started running `vagrant suspend` prior to shutting down my laptop and it seems to happen less frequently (maybe not at all).

Obviously this is not a solution, but may help us track down the issue quicker.

Any update on this issue being reopened?

**Comment by budhrg** [comment]
Thanks @reynoldsalec for the solution. It worked well.

**Comment by pitbulmaniak** [comment]
Here the solution I found.
1. Go to VirtualBox Manager (GUI) and start the VM with the mentioned name from there.
2.  Figure out the id using "vboxmanage list vms" and update the id file (.vagrant/machines/default/virtualbox/id)
3. restart the VM from vagrant with graceful shutdown.
use 
>vagrant halt 
and then 
>vagrant up (--provision)

**Comment by kpatryk** [comment]
Yeap. This problem is still not solved so I guess this ticket should not be closed. I used the latest version of Vagrant 1.7.4 and VirtualBox 5.0.2 under Linux Mint 17 Qiana. 

The workaround provided by @reynoldsalec worked for me as well, but it is annoying as it occured to me twice today without any particular reason.

**Comment by robsmall** [comment]
@pitbulmaniak had the solution that worked for me.

**Comment by EIrwin** [comment]
Again, although helpful as a temporary fix, @pitbulmaniak and other temporary ways of getting by this are not a solution to the root problem. Lets open the issue and figure out the actual cause and find an actual solution for the long run.

**Comment by ruskotron** [comment]
Root problem as far as I'm concerned is that the 'up' command does something either benign, or utterly destructive depending on context. That's a regrettable design mistake and any other kind of fix is kludging around it. Unfortunately the book has already been written and published, and it already describes this as the vagrant workflow, so it makes a proper fix a bit of a commercial issue.

However I think a simple error-message when somebody tries to 'up' a VM in a directory where one exists (perhaps following a tutorial in the book) advising them of the new command (e.g. "vagrant start") would do the job nicely!

But ultimately it's hard to expect any heroics though seeing as this is free software.

**Comment by cjmosure** [comment]
@reynoldsalec solution worked for meh

**Comment by juukie** [comment]
Tanks @pitbulmaniak. Setting the correct id worked.

**Comment by siliconmeadow** [comment]
@reynoldsalec ++

**Comment by brycepj** [comment]
Is it silly to ask why I don't have a dir at `~/.vagrant` like everyone is talking about? 

I have `.vagrant.d` but that doesn't have a `machines` dir.

**Comment by adcuz** [comment]
@brycepj It's the `.vagrant` directory in your project folder that contains the machines directory.

**Comment by ecokeley** [comment]
@reynoldsalec ++
I had 2 versions of the same basebox and somehow the default/id changed to the other VM. I swapped the id and it worked.

**Comment by XzAeRo** [comment]
The only issue with this (besides all the hassle of the machine id), is that my machine isn't capable of provisioning anymore, because isn't capable of connecting through ssh (using private key, which I assume it was changed as well).

This is really annoying!

**Comment by abarry** [comment]
This solved the issue for me
First you need the vm's id which you can get with the following command :
vboxmanage list vms

Then  run :
echo "ea38889c-1103-4392-84a5-21420e662a18" > .vagrant/machines/cffbodev50/virtualbox/id

and finally run : 
vagrant up --no-provision

**Comment by mm0** [comment]
@abarry's Solution worked for me. However, a `vagrant reload` was required afterwards for me as SSH was not accessible via `vagrant provision` (using ansible)

**Comment by Harreh** [comment]
For me, there was an issue with going from laravel homestead v3.0.2 to v3.1.0. Downgrading back to my original version fixed it

**Comment by underscorefunk** [comment]
I had a really similar issue. I've got my vagrant configs in a /servers/ folder in my dropbox so that I can setup machines on the go and sync my configs. I noticed that after a day or so, running vagrant up would create a new machine. I found out how to set the machine name, but now I get the message: 

```
A VirtualBox machine with the name 'neptune' already exists.
Please use another name or delete the machine with the existing
name, and try again.

```
The odd thing is that I'm in the neptune directory, trying to turn on 'neptune', not create a new neptune. Something definitely seems broken here. 

I've been testing out this app called 'hobo' to help manage some of my vagrant boxes, and it gives the error. 

```
The machine with the name 'neptune' was not found configured for
this Vagrant environment.

```

I wonder why it seems to think things have changed. I thought it'd match on the name. 
I'm using VirtualBox Version 5.0.26 r108824 and Vagrant 1.8.6 on OSx 10.11.06

**Comment by nirajp** [comment]
For me, `.vagrant/machines/` already had a `default` folder, while `vagrant up` was trying to create a new folder with `machinename`.
It worked, after I deleted the new `machinename` that vagrant tried to create & renamed `default` to `machinename`.

**Comment by bgrrtt** [comment]
@DevJackSmith just happened to me.

**Comment by nilesh1791** [comment]
open virtualbox  select the required project and remove. vagrant up --provision.

**Comment by naumoff** [comment]
5 years and bug still exist. it is shame.

**Comment by Icedroid** [comment]
I has meet the same issue.

**Comment by tolmasky** [comment]
Can report this is still happening. Should re-open. Happened to me on Parallels (not VirtualBox).
