### ISSUE TITLE
Failed to upload a file to the guest VM via SCP due to a permissions

### ISSUE THREAD

**Issue by johntdyer** [hashicorp/vagrant#2994]
Creating a new ticket since I can't reopen #2804. 

So I am still getting this...

``` log
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the user running Vagrant doesn't have
read permission on the file. Please set proper permissions on the file:

/var/folders/wb/w7qzyksn56gc8pz5mjczx0kc0000gn/T/vagrant20140217-39023-7c8w5t
```

**Environment**
OSX 10.9 
Virtualbox 4.3.6
Vagrant 1.4.3

**Debug Logs**
https://gist.github.com/johntdyer/7512b2d8b2f5f64af8f3

I am only able to provision once, and then I have to destroy and create to apply configuration... As you can imaging it is quite frustrating.

**Comment by phpspider** [comment]
I am facing issue like that when i am running "vagrant up"

"Configuring and enabling network interfaces...
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the SSH user doesn't have permission
to write to the destination location. Alternately, the user running
Vagrant on the host machine may not have permission to read the file."
