### ISSUE TITLE
Vagrant could not detect VirtualBox!

### ISSUE THREAD

**Issue by juderosen** [hashicorp/vagrant#3024]
I installed the latest version of VirtualBox after installing Vagrant, and now when I `vagrant up`, I get this output:

```
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.

Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
```

So, I added the correct path to my PATH but to no success. I tried several different paths that should work, but none of them did. Currently, my PATH looks like this:

```
PATH=C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;
C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\Ruby200-x64\bin;"C:\P
rogram Files\Oracle\VirtualBox\VBoxManage.exe";"C:\Program Files\Oracle\VirtualB
ox\VBoxManage.exe";C:\Program Files\Oracle\VirtualBox\VBoxManage.exe;"C:\Program
 Files\Oracle\VirtualBox\";"C:\Program Files\Oracle\"
```

I got Vagrant working on a different computer with VirtualBox pre-installed, so, do I need to uninstall Vagrant and reinstall it (so it's after VirtualBox)?

By the way, to add stuff to my PATH, I did this:

``` batch
set PATH=%PATH%;C:\path\to\paths
:: or
set PATH=%PATH%;"C:\path\to\paths"
```

**EDIT:** I'm on Windows 7 Pro.

**Comment by SaintJude** [comment]
I had the same issue, adding the path to VirtualBox to the PATH environment variable worked. Not necessary to uninstall everything. Thanks.

**Comment by sahabi1** [comment]
Please I need your help.
I bought The book Mining the Social Web 2nd edition in order to get for some starting point for my capstone project. I am about to set up environment as instructed by the author of the book. I have installed the virtualbox 4.3.20-96997-win and installed ubuntu 12.04 LTS 32 bit as a guest system. After that I installed vagrant 1.7.2 . I cloned the (using git clone)the Mining-the-Social-Web-2nd-Edition from github but unfortunately when run the command "vagrant up" I found the following error mmessage:

The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
After I that i tried to manually add the path in the path environment variable as C:\Program Files\Oracle\Virtualbox\VBoxManage as suggested by many people in the forum but still no success 
Please can any one provide help to me. I have been running in this trouble for about a week.

**Comment by jackytedy** [comment]
The question run my computer agin

**Comment by lwebzem** [comment]
I have the same problem when I type vagrant up: it is saying Vagrant could not detect  Virtual Box.
Can someone help to resolve this.   My laptop is on win10  (upgraded from win 8 or win 8) and in VBox I am am using Ubantu 64 OS.  I updated path as was mentioned in prev posts and renamed environemt variable  to VBOX_INSTALL_PATH and it is set to C:\Program Files\Oracle\VirtualBox\     - but still it is not working.
Thanks.

**Comment by briancain** [comment]
Hi @lwebzem - I recommend asking the mailing list as you will get a proper response there. Thanks!

https://groups.google.com/forum/#!forum/vagrant-up
