### ISSUE TITLE
Vagrant 1.5 - cacert.pem

### ISSUE THREAD

**Issue by johnbellone** [hashicorp/vagrant#3160]
I noticed after installing Vagrant 1.5 on my Mac that I immediately started to get certificate errors when attempting to add plugins. I assumed originally this was because that something changed on my corporate network but ended up figuring out the solution this morning. I [followed the instructions to update the certificate chain](http://stackoverflow.com/questions/10246023/bundle-install-fails-with-ssl-certificate-verification-error) and copied over the _cacert.pem_ that is bundled in the embedded directory.

``` sh
sudo cp /opt/boxen/rbenv/versions/2.0.0-p353/openssl/ssl/cert.pem /Applications/Vagrant/embedded/cacert.pem
```

**Comment by kamazee** [comment]
Sorry for bumping an old issue but is there a way to make vagrant load also a custom pem without modifying original files provided by package manager?

@mitchellh is there a chance you reconsider because of the explanation @johnbellone posted right after you had closed the issue? Is an organization mitms https connections, there's no clean way to add local CA as trusted (or at least I haven't googled one so far and all my attempts to fetch a custom certificate to embedded openssl from OSX distribution have failed).

**Comment by chrisroberts** [comment]
@kamazee you can use the custom pem by setting the `SSL_CERT_FILE` environment variable:

```
export SSL_CERT_FILE=/path/to/cacert.pem
vagrant up
```
