### ISSUE TITLE
Cannot override default ssh port forwarding

### ISSUE THREAD

**Issue by abarani** [hashicorp/vagrant#3232]
The following configuration does not work anymore on Vagrant 1.5.1.
(Tested 1.5.1 and 1.5.0)

```
config.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true
config.vm.network :forwarded_port, guest: 22, host: 2230, id: "ssh"
```

```
vm:
* Forwarded port '2222' (host port) is declared multiple times
with the protocol 'tcp'.
```

Also tried using the last line alone:

```
config.vm.network :forwarded_port, guest: 22, host: 2230, id: "ssh"
```

results in Vagrant using the default port 2222 and ignoring the defined 2230.

```
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
```

The `disabled: true` setting is working as expected on vagrant 1.4.3.

**Comment by dragon788** [comment]
@rvangundy 'vagrant ssh' should work because the vagrant up should have recorded the running config for the vm. If you have multiple vms in the same file you can 'vagrant ssh $NAME' and even if they were all initially configured for port 2222, each successive machine if the auto_correct=true should have its own port, and vagrant keeps track of them. If this isn't the case, there is definitely a hole in the testing cases. In the case of multiple vms in different directories, the same logic should apply. You can run a vagrant global-status to see all the running VMs, which means it keeps track of their states and probably ports somewhere.

**Comment by jsanders** [comment]
By the way, this is probably obvious, but it stumped me for awhile: if it is an existing machine, you have to do `vagrant reload` because `vagrant up` will use the existing port forwarding configuration.

**Comment by hackeron** [comment]
Just doing this worked for me, thank you!

```ruby
config.vm.network :forwarded_port, guest: 22, host: 12345, id: 'ssh'
```

**Comment by wizwjw** [comment]
@hackeron it also worked for me. Vagrant version is '1.7.2'.

**Comment by joequery** [comment]
[hackeron's comment](https://github.com/mitchellh/vagrant/issues/3232#issuecomment-76710491) worked for me as well. Vagrant version is `1.7.2`.

**Comment by bluebiu** [comment]
@hackeron it also worked for me too!! Vagrant version is '1.7.4'.

**Comment by ascotan** [comment]
@dragon788 I think that @rvangundy is correct. When you deconflict a port using auto_correct and then set the port in config.ssh.host, this will break if the port is actually changed.

In my case I have 2 Vagrantfiles that need to do this and when you launch both vagrant's, one of the two will become deconflicted, but when you run ssh, both terminals will ssh into the same box.

If you run with VAGRANT_LOG=INFO you'll see that the 'undeconflicted' port is being used via vagrant ssh in both Vagrantfiles.

I'm not sure how to get around this.  It looks like the problem is that the 'deconfliction' algorithm is a runtime-only feature. When you run 'vagrant ssh'  it re-evaluates the Vagrantfile and pulls the 'undeconflicted' port out of the config. (makes sense because there is no way to determine the port collision mapping after the fact...)

I added this:
`  
config.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2222, auto_correct: true
config.vm.networks.each do |type, options|
    if type == :forwarded_port
      print options[:host]
    end
  end
`
To verify that even after port deconfliction, the wrong port is used for doing ssh. Again, this is because the config is re-evaluated  on a 'vagrant ssh'.

**Comment by dragon788** [comment]
Interesting, this could definitely be a bug. You can also run `vagrant
port` after you VM is running to see what ports are forwarded and `vagrant
ssh-config` to see the ports it think it will be using and the username/key
information.

Can you try this and paste back the results to see if it is indeed showing
one thing but using another?

**Comment by ascotan** [comment]
I can't do a 'vagrant port' because I'm using the docker provider and it apparently doesn't support that. However:

-------------------------------------------------------------------
....
default: Successfully built b03e6dcb7030
  default:
  default: Image: b03e6dcb7030
==> default: Creating the container...
  default:   Name: yyyy
  default:  Image: b03e6dcb7030
  default: Volume: /Users/name/Desktop/code/gitlab/yyyy:/vagrant
  default:   Port: 2222:22
  default:
  default: Container created: a7c7353b87ac8d7e
==> default: Starting container...
==> default: Waiting for machine to boot. This may take a few minutes...
  default: SSH address: localhost:2222
  default: SSH username: vagrant
  default: SSH auth method: password
  default:
  default: Inserting generated public key within guest...
  default: Removing insecure key from the guest if it's present...
  default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Running provisioner: ansible_local...
  default: Running ansible-playbook...
....
-------------------------------------------------------------------
....
  default: Successfully built b03e6dcb7030
  default:
  default: Image: b03e6dcb7030
  ==> default: Fixed port collision for 22 => 2222. Now on port 2200.
  ==> default: Creating the container...
  default:   Name: xxx
  default:  Image: b03e6dcb7030
  default: Volume: /Users/name/Desktop/code/gitlab/xxx:/vagrant
  default:   Port: 2200:22
  default:
  default: Container created: 6a38003c3d824346
  ==> default: Starting container...
  ==> default: Waiting for machine to boot. This may take a few minutes...
  default: SSH address: localhost:2222
  default: SSH username: vagrant
  default: SSH auth method: password
  default:
  default: Inserting generated public key within guest...
  default: Removing insecure key from the guest if it's present...
  default: Key inserted! Disconnecting and reconnecting using new SSH key...
  ==> default: Machine booted and ready!
  ==> default: Running provisioner: ansible_local...
  default: Running ansible-playbook...
  blah blah blah
....
-------------------------------------------------------------------
....
name ~/Desktop/code/gitlab/yyy (develop) $ vagrant ssh-config
Host default
  HostName localhost
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/name/Desktop/code/gitlab/yyy/.vagrant/machines/default/docker/private_key
  IdentitiesOnly yes
  LogLevel FATAL
....
-------------------------------------------------------------------
....
name ~/Desktop/code/gitlab/xxx (develop) $ vagrant ssh-config
Host default
  HostName localhost
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/name/Desktop/code/gitlab/xxx/.vagrant/machines/default/docker/private_key
  IdentitiesOnly yes
  LogLevel FATAL

**Comment by ascotan** [comment]
Both Vagrantfiles have the following:

`
config.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2222, auto_correct: true
config.ssh.host = "localhost"
config.ssh.port = 2222
`

**Comment by dragon788** [comment]
Since you've already given it a tagged name of SSH which should set a flag
for vagrant to follow, is there any reason you are providing the additional
specific ssh port configuration?

**Comment by dragon788** [comment]
So looking at the documentation the official way to pull this off is not to
set the config.ssh.port but to set config.ssh.guest_port.

config.ssh.guest_port - The port on the guest that SSH is running on. This
is used by some providers to detect forwarded ports for SSH. For example,
if this is set to 22 (the default), and Vagrant detects a forwarded port to
port 22 on the guest from port 4567 on the host, Vagrant will attempt to
use port 4567 to talk to the guest if there is no other option.

That way it doesn't matter which port it ends up on outside the VM, it will
examine the port forward config and anything forwarded to port 22 on the
guest will be assumed to be the SSH server.

**Comment by ascotan** [comment]
Sadly this does not appear to solve the problem. I wish it did. I've tried various permutations of guest_port/port and no go. If a port re-mapping occurs during the creation of the forwarded port, config.ssh appears to not be aware of the change and ssh connections fail. This only occurs when another Vagrantfile launches something with the exact same port forwards for ssh.

For now I'm using something like:
unique_host_port = 2300
config.vm.network "forwarded_port", id: "ssh", guest: 22, host: unique_host_port
config.ssh.host = "localhost"
config.ssh.port = unique_host_port

**Comment by ascotan** [comment]
@dragon788  Yea in answer to your question. The reason I was doing it this way is that I'm running docker for mac and they currently have a terrible limitation that there is no docker0 network native on the system. Because of that, 172.17.x.x address are not resolvable.  Therefore, if I leave off the config.ssh.xxx stuff, vagrant attempts to ssh into the actual IPV4 address of the container (which is unreachable).

Therefore, if you use the docker provider for vagrant (as opposed to docker compose...) and you want to use native docker, you end up here - overriding the ssh port on the container - and discovering that the host ports must be set manually for every container you launch :(

**Comment by andkirby** [comment]
Yeah, it would be great at least to keep config.ssh forwarding to 127.0.0.1 IP.
Could implement this?
Just to avoid global 0.0.0.0:22 in guest machine.

This construction is prohibited:
```
config.ssh.guest = '127.0.0.1'
```
Result after `vagrant up`:
```
SSH:
* The following settings shouldn't exist: guest
```
It'd be great to have it.
