### ISSUE TITLE
Rsync watcher is really slow

### ISSUE THREAD

**Issue by patrickheeney** [hashicorp/vagrant#3249]
Running version 1.5.1. The issue I have now is the rsync watcher is incredibly slow. It takes at least several minutes to detect that a file has changed and initiate rsync. 

After about 10 minutes sometimes it goes rsync crazy and does 7 or 8 in a row. 

Some others have issues https://github.com/mitchellh/vagrant/issues/3159#issuecomment-37634250. 

Also it may be helpful to have a whitelist of folders to watch. In my case I only need to watch the www/\* folder as the rest are irrelevant: 

```
config.vm.synced_folder ".", "/srv/www/", type: "rsync", rsync__include: ["www/"], rsync__exclude: [".git/", "tmp/", "cache/"]
```

(My original issue here was the fact that I had a packer .iso file and rsync was not outputting any progress so it looks like it was hanging for 15 minutes.)

**Comment by tslater** [comment]
I'm having slowness and I ran things with debug on. 
I'm wondering if the slowness is related to these errors? I get a bunch of these:
``DEBUG -- : unknown: file:/path/to/file ({})```
The file exists at that path and rsyncing seems to be working so I'm trying to figure out what the deal is. I CHMOD'ed them to 775 and their owned by my user that is running the command. Any thoughts?

**Comment by e2** [comment]
@tslater - open a new issue in https://github.com/guard/listen, and use `LISTEN_GEM_DEBUGGING=2` environment variable - this should give you full info what's going on and how long things take. You can then upload the log/output to a gist for analysis. You can also check out the Listen Wiki for additional troubleshooting and ideas (slowness can be caused by many things).
