### ISSUE TITLE
Masterless setup hangs on salt-call

### ISSUE THREAD

**Issue by iurquiza** [hashicorp/vagrant#3296]
I am using Vagrant 1.5.1.
I want to run a vagrant box with a salt masterless set up.
I have 'salt.minion_config' set to point to the minion file.
Inside the 'minion' I have 'file_client: local'.
When I run 'vagrant provision' it hangs in 'Calling state.highstate...'
I have 'salt.verbose = true', it shows no output
I am pretty sure it hangs because the '--local' flag is missing.
When I kill the hanging process and 'vagrant ssh' I run
'sudo salt-call -l debug state.highstate', and I get the following:
[ERROR ] This master address: 'salt' was previously resolvable but now fails to resolve! The previously resolved ip addr will continue to be used
When I run:
sudo salt-call --local -l debug state.highstate
everything works fine.
Is there a work around to have 'vagrant provision' do the salt provisioning for a masterless setup?
Is there a way to pass the '--local' flag to the salt-call executed by vagrant?

**Comment by falenn** [comment]
This item is closed, but was it resolved?  I have the same issue.

**Comment by iurquiza** [comment]
I am not sure if it was resolved. I just went back to using salty-vagrant.

**Comment by msarahan** [comment]
Necropost (sorry) but I found this post in my searches for the hanging behavior, and I think I found the fix.  It appears you can set the "masterless" option and this works:

https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/provisioner.rb#L323-L338

```
  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.run_highstate = true
  end
```

This is still broken with Windows because it can't find salt-call (not on PATH) but that's a separate issue.
