### ISSUE TITLE
Can't get simple docker configuration to work

### ISSUE THREAD

**Issue by thasmo** [hashicorp/vagrant#3646]
Here's the file:

```
Vagrant.configure('2') do |config|
    config.vm.provision 'docker' do |d|
        d.pull_images 'busybox'
    end
end
```

Error is:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* A box must be specified.
```

I thougt I don't need to specify a box for docker?
What am I doing wrong?

Thanks!

**Comment by carminexx** [comment]
I'm reopening this issue, because I get the same problem.
I have a multi-machine Vagrantfile, with both "standard" VMs and docker containers. Obviously, I can't use `vagrant up --provider=docker`, since not all machines in the Vagrantfile uses Docker provisioner.
And, I can't do what @jokeyrhyme suggests, since I don't want to spin a new boot2docker instance for each Docker container.
What is the "correct" Vagrant way to use the default boot2docker instance on Mac OS X?

**Comment by jokeyrhyme** [comment]
We can also just use Docker and Docker Compose directly. I've been doing this more and more recently. Or switch to otto if you need something easier: https://www.ottoproject.io/
