### ISSUE TITLE
VirtualBox check update fails with "the network operation failed"

### ISSUE THREAD

**Issue by HenrikBechmann** [hashicorp/vagrant#3995]
This is just a nuisance, but when I check for updates a dialog appears with

"Checking for a new Virtualbox version..."

"The network operation failed with the following error: Unknown reason"

Anyone know how to fix this?

Macbook pro, OSX 10.9.3 (Mavericks), Virtualbox 4.3.12

**Comment by shimmyshack** [comment]
it's back with 5.1.22

**Comment by easyyu** [comment]
Win 8.1, long time I can not update because of this annoying ssl message. I tried everything.. To delete certificate, to delete file vbox-ssl-cacertificate.crt, to uninstall, VB, the install again, and nothing.

In last let it say 7-8 version I have all the time this problem. Now Im on the latest release 5.2.8

Is there any tutorial how to solve this annoying problem?
