### ISSUE TITLE
Add bash completion to vagrant

### ISSUE THREAD

**Issue by dol** [hashicorp/vagrant#400]
It would be nice to add bash completion when entering 'vagrant [tab][tab]'.

[Debian example](http://www.debian-administration.org/articles/316)

**Comment by ping-the-one** [comment]
Seems like the kura project is abandoned but this fork is alive.
https://github.com/brbsix/vagrant-bash-completion

**Comment by PHLAK** [comment]
Any reason this hasn't been included with Vagrant yet? It seems like @mitchellh was ready to do so with another package **back in 2011**. Any chance of revisiting this now?

**Comment by alb-i986** [comment]
@PHLAK, guys:
it turns out the bash completion script is actually bundled in this repo since [2012](https://github.com/hashicorp/vagrant/commit/5038cc82b29bdb57875108bbb7765da0eb04583b#diff-9eef68dab654e68830aab0af2c3d3c5c):

https://github.com/hashicorp/vagrant/blob/master/contrib/bash/completion.sh

On Ubuntu you can find it at `/opt/vagrant/embedded/gems/gems/vagrant-1.9.8/contrib/bash/completion.sh`

And that's exactly what the [homebrew formula vagrant-completion](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vagrant-completion.rb) installs.
