### ISSUE TITLE
vagrant up w/docker takes a LONG time

### ISSUE THREAD

**Issue by cro** [hashicorp/vagrant#4049]
Greetings,

I'm experimenting with the new docker support.  I'm very excited that I could run one host Vagrant machine and a bunch of containers in different Vagrantfiles--this will be a huge help to development for me.

Anyway, I've tried a number of things, but Vagrant still waits a very long time at "waiting for machine to boot":

```
$ vagrant up default --provider=docker
Bringing machine 'default' up with 'docker' provider...
==> default: Docker host is required. One will be created if necessary...
    default: Docker host VM is already ready.
==> default: Syncing folders to the host VM...
    default: Waiting for HGFS kernel module to load...
    default: Enabling and configuring shared folders...
    default: -- /Users/cro/src/docktest: /var/lib/docker/docker_1402960164_92249
==> default: Warning: When using a remote Docker host, forwarded ports will NOT be
==> default: immediately available on your machine. They will still be forwarded on
==> default: the remote machine, however, so if you have a way to access the remote
==> default: machine, then you should be able to access those ports there. This is
==> default: not an error, it is only an informational message.
==> default: Creating the container...
    default:   Name: docktest_default_1402960165
    default:  Image: phusion/baseimage
    default:    Cmd: /sbin/my_init --enable-insecure-key
    default: Volume: /var/lib/docker/docker_1402960164_92249:/vagrant
    default:   Port: 2222:22
    default:
    default: Container created: 5fe2b5ddd87271e2
==> default: Starting container...
==> default: Waiting for machine to boot. This may take a few minutes...
```

If I ^C out I can 'vagrant ssh' just a few seconds after the start.  If I don't ^C it takes several minutes to get my prompt back.  How can I debug this?

Additionally I get "Vagrant has noticed that the synced folder definitions have changed", but I don't know what changed them.  I'm using the Fusion plugin.

**Comment by find4u** [comment]
Not duplicate this issue affects me and after the vagrant ssh when I do a ls there are no files. Here are the logs
D:\_dev\Scrapy\scrapyBook>vagrant up --no-parallel
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...
    web: Vagrant will now create or start a local VM to act as the Docker
    web: host. You'll see the output of the `vagrant up` for this VM below.
    web:
    docker-provider: Checking if box 'lookfwd/scrapybook' is up to date...
    docker-provider: Clearing any previously set forwarded ports...
    docker-provider: Clearing any previously set network interfaces...
    docker-provider: Preparing network interfaces based on configuration...
    docker-provider: Adapter 1: nat
    docker-provider: You are trying to forward to privileged ports (ports <= 1024). Most
    docker-provider: operating systems restrict this to only privileged process (typically
    docker-provider: processes running as an administrative user). This is a warning in case
    docker-provider: the port forwarding doesn't work. If any problems occur, please try a
    docker-provider: port higher than 1024.
    docker-provider: Forwarding ports...
    docker-provider: 9200 (guest) => 9200 (host) (adapter 1)
    docker-provider: 6379 (guest) => 6379 (host) (adapter 1)
    docker-provider: 3306 (guest) => 3306 (host) (adapter 1)
    docker-provider: 9312 (guest) => 9312 (host) (adapter 1)
    docker-provider: 6800 (guest) => 6800 (host) (adapter 1)
    docker-provider: 6801 (guest) => 6801 (host) (adapter 1)
    docker-provider: 6802 (guest) => 6802 (host) (adapter 1)
    docker-provider: 6803 (guest) => 6803 (host) (adapter 1)
    docker-provider: 21 (guest) => 21 (host) (adapter 1)
    docker-provider: 30000 (guest) => 30000 (host) (adapter 1)
    docker-provider: 30001 (guest) => 30001 (host) (adapter 1)
    docker-provider: 30002 (guest) => 30002 (host) (adapter 1)
    docker-provider: 30003 (guest) => 30003 (host) (adapter 1)
    docker-provider: 30004 (guest) => 30004 (host) (adapter 1)
    docker-provider: 30005 (guest) => 30005 (host) (adapter 1)
    docker-provider: 30006 (guest) => 30006 (host) (adapter 1)
    docker-provider: 30007 (guest) => 30007 (host) (adapter 1)
    docker-provider: 30008 (guest) => 30008 (host) (adapter 1)
    docker-provider: 30009 (guest) => 30009 (host) (adapter 1)
    docker-provider: 22 (guest) => 2222 (host) (adapter 1)
    docker-provider: Running 'pre-boot' VM customizations...
    docker-provider: Booting VM...
    docker-provider: Waiting for machine to boot. This may take a few minutes...
    docker-provider: SSH address: 127.0.0.1:2222
    docker-provider: SSH username: vagrant
    docker-provider: SSH auth method: private key
    docker-provider: Warning: Remote connection disconnect. Retrying...
    docker-provider: Machine booted and ready!
    docker-provider: Mounting shared folders...
    docker-provider: /vagrant => D:/_dev/Scrapy/scrapyBook
==> web: Starting container...
==> web: Provisioners will not be run since container doesn't support SSH.
==> spark: Docker host is required. One will be created if necessary...
    spark: Docker host VM is already ready.
==> spark: Syncing folders to the host VM...
    docker-provider: Mounting shared folders...
    docker-provider: /var/lib/docker/docker_1490089747_30833 => D:/_dev/Scrapy/scrapyBook
==> spark: Vagrant has noticed that the synced folder definitions have changed.
==> spark: With Docker, these synced folder changes won't take effect until you
==> spark: destroy the container and recreate it.
==> spark: Starting container...
==> spark: Provisioners will not be run since container doesn't support SSH.
==> es: Docker host is required. One will be created if necessary...
    es: Docker host VM is already ready.
==> es: Starting container...
==> es: Provisioners will not be run since container doesn't support SSH.
==> redis: Docker host is required. One will be created if necessary...
    redis: Docker host VM is already ready.
==> redis: Starting container...
==> redis: Provisioners will not be run since container doesn't support SSH.
==> mysql: Docker host is required. One will be created if necessary...
    mysql: Docker host VM is already ready.
==> mysql: Starting container...
==> mysql: Provisioners will not be run since container doesn't support SSH.
==> scrapyd1: Docker host is required. One will be created if necessary...
    scrapyd1: Docker host VM is already ready.
==> scrapyd1: Starting container...
==> scrapyd1: Provisioners will not be run since container doesn't support SSH.
==> scrapyd2: Docker host is required. One will be created if necessary...
    scrapyd2: Docker host VM is already ready.
==> scrapyd2: Starting container...
==> scrapyd2: Provisioners will not be run since container doesn't support SSH.
==> scrapyd3: Docker host is required. One will be created if necessary...
    scrapyd3: Docker host VM is already ready.
==> scrapyd3: Starting container...
==> scrapyd3: Provisioners will not be run since container doesn't support SSH.
==> dev: Docker host is required. One will be created if necessary...
    dev: Docker host VM is already ready.
==> dev: Syncing folders to the host VM...
    docker-provider: Mounting shared folders...
    docker-provider: /var/lib/docker/docker_1490089842_22654 => D:/_dev/Scrapy/scrapyBook
==> dev: Vagrant has noticed that the synced folder definitions have changed.
==> dev: With Docker, these synced folder changes won't take effect until you
==> dev: destroy the container and recreate it.
==> dev: Starting container...
==> dev: Provisioners will not be run since container doesn't support SSH.

D:\_dev\Scrapy\scrapyBook>vagrant ssh
==> dev: SSH will be proxied through the Docker virtual machine since we're
==> dev: not running Docker natively. This is just a notice, and not an error.
Warning: Permanently added '172.17.0.10' (ECDSA) to the list of known hosts.
Last login: Mon Mar 20 17:20:17 2017 from 172.17.0.1
root@dev:~# cd book
root@dev:~/book# ls
root@dev:~/book#
