### ISSUE TITLE
Vagrant Box not reachable anymore after VPN (CISCO AnyConnect) connection. 

### ISSUE THREAD

**Issue by jackblackCH** [hashicorp/vagrant#4060]
After a VPN connection ( to another location of my office ), my vagrant box is not reachable anymore via browser, even after closing the VPN connection.

VPNClient: CISCO AnyConnect Secure Mobile Client
- tried a `$ vagrant reload` -> (doesn't work)
- No response from browser over hostname nor the IP address, BUT
- **I can ping the BOX IP via Terminal**

**The only way I get it work again is a reboot of my OS.**

My System

```
OS: OS X 10.9.3
Vagrant: 1.6.3
```

Any ideas?

**Comment by alaska** [comment]
Workarounds?

**Comment by jeeftor** [comment]
i thought cisco was disabling various virtual host adapters but that doesn't "seem" to be the case.

**Comment by openface** [comment]
AnyConnect does not support split tunnelling and will force all network traffic from the host through the VPN tunnel (per the network access policy).    No workaround available.

**Comment by aweddleton** [comment]
My workaround for this was to set up port forwarding, and then use `http://localhost:8080` or `http://localhost:8081` in the browser instead of the ip addresses.

```Vagrantfile
Vagrant.configure("2") do |config|
    config.vm.define "main" do |main|
        main.vm.box = "ubuntu/xenial64"
        main.vm.network "private_network", ip: "192.168.33.10"
        main.vm.network "forwarded_port", guest: 80, host: 8080
    end
    config.vm.define "secondary" do |secondary|
        secondary.vm.box = "ubuntu/trusty64"
        secondary.vm.network "private_network", ip: "192.168.33.11"
        secondary.vm.network "forwarded_port", guest: 80, host: 8081
    end
end
```

I assume this works because the vpn will not capture localhost traffic.

[This link](https://www.cisco.com/c/en/us/support/docs/security/asa-5500-x-series-next-generation-firewalls/70847-local-lan-pix-asa.html) made me wonder if the vpn could be configured to allow a set of ip addresses to be reserved for Vagrant.  I don't administer the vpn, however, and didn't really understand what I was reading there.

**Comment by iamface** [comment]
I had this exact problem, `localhost` would not resolve through VPN/vagrant, and adding `config.vm.network "forwarded_port", guest: 80, host: 3000` to my Vagrantfile fixed the issue for BrowserSync. Thanks @aweddleton

**Comment by Thomasbehan** [comment]
Good work around is to run vagrant up before logging into/starting your cisco VPN
