### ISSUE TITLE
Files in NFS-sync folder not syncing from host to guest when changed.

### ISSUE THREAD

**Issue by briangonzalez** [hashicorp/vagrant#4204]
I am working with Vagrant 1.6.3 and VirtualBox (`VBoxManage -v` yields 4.3.12r93733).

I have noticed that changes to files on the host to do not always propagate to their corresponding shared file on the guest. 

In the screenshots below, notice that the change from `-50px` to `-22px` has not propagated to the guest, which still shows `-50px`. This is intermittent, but happens about every 5 saves or so.

We have verified the issue on hosts OSX 10.9.2 and OSX 10.8 running an Ubuntu 13.04 guest. 
### Host SCSS File

![screen shot 2014-07-16 at 1 02 59 pm](https://cloud.githubusercontent.com/assets/659829/3604985/3947c8a2-0d26-11e4-9667-c2aaf862f7b7.png)
### Guest SCSS File

![screen shot 2014-07-16 at 1 02 38 pm](https://cloud.githubusercontent.com/assets/659829/3604983/2b5f12b8-0d26-11e4-894b-769266a6f1b7.png)

**Comment by lmakarov** [comment]
I tried all possible mount_options combinations mentioned here and none of them would fix the ST3 issue for me.  
The `"atomic_save": false` setting in ST3 does help and does NOT require any mount_options overrides at all.

I did a little research on this and found out that the root cause is that ST3 by default does not update the `ctime` file attribute when saving a file. `"atomic_save": false` fixes this quirk.

**Comment by smazurov** [comment]
thats great if you're using sublime, but with other apps (PHPStorm, in my case) we're still suffering from this issue. Will try the mount settings and report back.

**Comment by lmakarov** [comment]
@smazurov I'm also using PHPStorm and have absolutely no issue with it. In fact I do not even have to hit save with PHPStorm - it saves files all the time as you type and NFS has no issues seeing those changes.

Here's my sync_folders config (using this with docker). The host is OS X.

    vagrant_root = File.dirname(__FILE__)
    config.vm.synced_folder vagrant_root, vagrant_root, type: "nfs", mount_options: ["nolock", "vers=3", "tcp"]

The only important option is "nolock" in my case. Without it the guest won't mount the NFS share.  
I think that has something to do with the guest OS/box, since I did not have to specify "nolock" with a different box.

**Comment by jacefarm** [comment]
Setting `atomic_save: false` was not sufficient to alleviate the problem for me.  Setting `mount_options: ['nolock,vers=3,udp,noatime,actimeo=1']` did the trick.

**Comment by itsazzad** [comment]
I am trying to share `/var/lib/mysql`
but failing.
```
==> default: chown: 
==> default: changing ownership of ‘/var/lib/mysql’
==> default: : Operation not permitted
```
