### ISSUE TITLE
Suspending removes the box

### ISSUE THREAD

**Issue by jkosecki** [hashicorp/vagrant#4276]
Hi, I'm running the latest version of VirtualBox (4.3.14) and Vagrant (1.6.3) on my Win8.1 x64 laptop and I'm having a strange problem that I couldn't find anywhere to be mentioned. After creating the box with <code>vagrant up</code>, <code>vagrant status</code> displays box status as running so everything is fine. However, when I run the <code>vagrant suspned</code> command, instead of having saved box, my vagrant status shows not created and so after <code>vagrant up</code> my box has to start all over from the beginning. Any ideas why does it behave so?

**Comment by merchantguru** [comment]
Was having the same issue on OSX. Downgraded from VirtualBox-4.3.26-98988-OSX.dmg to VirtualBox-4.3.20-96996-OSX.dmg. I tried a bunch of things, so not sure if the downgrade is what fixed it, but so far have not had a repeat of my vagrant virtualbox files disappearing.

**Comment by gabegm** [comment]
I am currently having the same problem on OSX 10.10 and will try @merchantguru 's solution

**Comment by mjmj** [comment]
Also having .vagrant/machines/default/virtualbox folder suddenly empty while using virtual box 5.0.2r102096 on OSX 10.10.5 and vagrant 1.7.4. Seen this on two different Mac's now, this one is brand new with only the above software added. Haven't issued any halt or suspend commands, but have closed the lid on my mbp. Saw the folder full with it's normal files (id, sync folder etc) then an ls on the directory moments later revealed all the files gone!

**Comment by gonewest818** [comment]
For what it is worth the virtualbox bug I reported months ago was supposedly fixed in 4.3.20.  However I have since moved on to using docker-machine (and happy with it) so I can't confirm if the bug has resurfaced in a new way.

I will say, however, that back in the day I had a pretty simple bash script to reproduce the bug if someone cares to go back and try. That script Is attached to the vbox ticket. 

https://www.virtualbox.org/ticket/13583
