### ISSUE TITLE
Plugin Installation failure in Windows 8.1 OS

### ISSUE THREAD

**Issue by shivapoudel** [hashicorp/vagrant#4351]
**Ugly Truth for Windows 8 Users:**
- EG-1. If user are from Windows 8 then they probably have account connected to Microsoft Account. And their home directory is `ex: Shiva Poudel`
- EG-2. If created a new local user account excluding space. And their home directory is `ex: shivapoudel`.

Finally, I concluded with decision that Vagrant doesn't like spaces in user's home directory. So by default many User's have their home directory setup similar like `EG-1` and vagrant loves especially `EG-2`. Thus in result it fails for plugin installatin `ex: vagrant plugin install vagrant-hostmanager`

``` shell
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing json (1.8.1), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.1'` succeeds before bundling.
```

**Solve this error but receiving another tough?**

By default Environmental Variable `VAGRANT_HOME` is set to `~/.vagrant.d` and vagrant doesn't love `c:/Users/Shiva Poudel/.vagrant.d`, I have to set it to `C:/vagrant/.vagrant.d` and hiphop that problem is solve and again I am getting another error.

``` shell
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.6.3.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.3.1'` succeeds before bundling.
```

Thus, @mitchellh please add support to love `EG-1` by vagrant and solve nogiri related errors in release 1.6.4.

**Comment by filipebezerra** [comment]
I'm using vagrant 1.7.4 and I tried to install vagrant-cachier plugin and I faced the same error.

**Comment by an0nh4x0r** [comment]
yo brothers! I posted the solution for this problem on my blog http://hackencode.blogspot.in/2015/11/solution-vagrant-plugin-installation.html

**Comment by apupier** [comment]
Hi,

the problem is supposed to be fixed on Ruby side for a very long time: https://bugs.ruby-lang.org/issues/7036
Can you double-check that Vagrant is calling Ruby the right way?

**Comment by minkoko91** [comment]
Dear All ,
I install vagrant plugin on window 8.
I run under command,
vagrant plugin install vagrant-hostmanager vagrant-winnfsd vagrant-bindfs 

Vagrant failed to load a configured plugin source.This can be caused by a variety of issues including: transient connectivity isseus, proxy filtering rejecting access to a configured plugin source, or a configured plugin source not responding correctly.Please review the error message below to help resolve the isste:

 Errno::ECONNREFUSED: Failed to open TCP connection to localhost:80 <No connection could  be made because the target machine actively refused it. -connect<2>for "localhost" port 80> <https://api.rubygems.org/specs.4.8.gz>)


How can I solve this problem?pla help me
