### ISSUE TITLE
HGFS issue after updating kernel drivers

### ISSUE THREAD

**Issue by dcramer** [hashicorp/vagrant#4362]
I've raised this issue before, but I'm now confident that the problem happens consistently when upgrading kernel drivers.

How to reproduce:
- Install the hashicorp/precise64
- Install linux-signed-generic-lts-trusty
- vagrant reload

VMWare's GUI doesnt exhibit the same issues as Vagrant, but I believe the key issue is that VMWare Tools need to be reconfigured. I dont know how the GUI gets around this, but it does.

**Comment by dragon788** [comment]
Just a note for anyone who comes back here with concerns that it no longer works under the latest kernel 3.13.0-46-generic on Ubuntu (and potentially other distros). This fix still works, the issue is that VMware Tools itself hasn't caught up to some code changes in the kernel. According to https://communities.vmware.com/message/2477575#2477575 it will be fixed soon for Workstation 11 and Fusion 7, and potentially backported to Workstation 10 and Fusion 6.

This thread has some potential workarounds, the best of which is downgrading your kernel to -45 or earlier and rebuilding VMware Tools.
http://askubuntu.com/questions/586221/vmhgfs-module-not-compilable-for-vmware-tools-9-9-0-fusion7-1-after-ubuntu-lin

If anybody is using dist-upgrade in their Vagrant or Packer scripts, this will probably bite them shortly. Here's an excellent article on why system administrators don't dist-upgrade automatically. http://askubuntu.com/a/226213

**Comment by fireproofsocks** [comment]
There has to be a better way to debug/troubleshoot this issue.  It fundamentally destroys the usefulness of using Vagrant in the first place and at present, it takes massive amounts of time to fix.  I would fully support any work to help make the functionality here and any glitches more transparent.

**Comment by rehmanzile** [comment]
The [workaround](https://www.vagrantup.com/docs/vmware/kernel-upgrade.html) for Kernel auto upgrade does not work for Ubuntu 14.04.4 version. Had to go back to 14.04.3
