### ISSUE TITLE
Ship ssh.exe by default in the Windows installer

### ISSUE THREAD

**Issue by Jalle19** [hashicorp/vagrant#4396]
I'm attempting to put together a guide for having Vagrant installed by default in some of the computer class rooms in our university so it's easier for students to get a course-specific environment up and running quickly. After testing it out on my own I realized that `vagrant ssh` doesn't work out of the box on Windows (like it does on all other platforms). The accepted solution seems to be to install Git or any other software that happens to ship `ssh.exe` then adjust the PATH variable. This is not exactly ideal, especially if I'm going to convince the adminstrators to deploy this.

I propose the ssh.exe is included in the MSI installer for Windows and put in the same path as `Vagrant.exe` so that the existing PATH amendment the installer does will be enough. The required binary is just 250 KB and I assume it's statically linked so it works standalone.

**Comment by batkuip** [comment]
Or atleast provide a link to a proper ssh.exe somewhere.  5 min vagrant install, 40 min working out how to ssh into the box. Sort of kills the whole idea.  Putty is not trivial, since you have to do this silly key conversion everytime.  Bitvise doesn't even like the key at all.  My version of git only has a ssh lib not ssh.exe.  Googling "ssh.exe" will give you so much dodgy stuff you are just asking for trouble.

**Comment by derak-kilgo** [comment]
Install git for windows and you'll get ssh installed and configured from a reputable source. 
( added to your path, put in the right windows approved folder, etc... )
