### ISSUE TITLE
NFS is reporting that your exports file is invalid.

### ISSUE THREAD

**Issue by sandywater** [hashicorp/vagrant#4448]
I tried running on a flash drive and it didn't like how it was formated so I vagrant destroyed it and deleted the folder and moved it to my main hard drive (OSX) and it still has the old location mapped.

``` bash
/V/L/V/coreos-vagrant git:master ❯❯❯ vagrant up --provider=vmware_fusion
Bringing machine 'core-01' up with 'vmware_fusion' provider...
==> core-01: Cloning VMware VM: 'coreos-alpha'. This can take some time...
==> core-01: Checking if box 'coreos-alpha' is up to date...
==> core-01: Verifying vmnet devices are healthy...
==> core-01: Preparing network adapters...
==> core-01: Starting the VMware VM...
==> core-01: Waiting for machine to boot. This may take a few minutes...
    core-01: SSH address: 192.168.76.146:22
    core-01: SSH username: core
    core-01: SSH auth method: private key
==> core-01: Machine booted and ready!
==> core-01: Forwarding ports...
    core-01: -- 2375 => 2375
    core-01: -- 22 => 2222
==> core-01: Setting hostname...
==> core-01: Configuring network adapters within the VM...
==> core-01: Configuring proxy environment variables...
==> core-01: Exporting NFS shared folders...
NFS is reporting that your exports file is invalid. Vagrant does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:2: path contains non-directory or non-existent components: /Volumes/KINGSTON/vagrant VMs/coreos-vagrant
exports:2: no usable directories in export entry
exports:2: using fallback (marked offline): /Volumes/KINGSTON
```

**Comment by mlachance** [comment]
Since this is the first result I got when I googled the same problem, here's the short version: after updating to macOS Sierra, NFS was choking on an older obsolete entry into `etc/exports` that was still rattling around in it. Deleting this invalid entry fixed the problem.

**Comment by s3w47m88** [comment]
This also worked for me.

To clarify I deleted the contents of `/etc/exports` rather than deleting the whole file because I didn't want to have to check what the perms were and reset them when I created a new file.

In my case, the `exports` file only contained some Vagrant lines (about 9 lines) that I knew (because they were commented at the top and bottom) were created by the commands I had just run. So that's how I knew I could delete all of the files.

I happened to be using Vagrant via Roots.io's Trellis + Bedrock + Sage WordPress stack in case others encounter this issue along the way.
