### ISSUE TITLE
allow to change where Vagrant VMs disks are stored

### ISSUE THREAD

**Issue by npf** [hashicorp/vagrant#4482]
Hello

When running vagrant up using VirtualBox as a provider on Linux (Vagrant version 1.6.3), I get a new directory created in "~/VirtualBox VMs/" which contains the .box and the .vmdk files.
Since Vagrant is quite greedy on disk space, I'd like to change that base location to another disk for Vagrant VMs (and Vagrant VMs only). 

Would it be possible to specify where to actually store Vagrant's VMs files in the Vagrantfile ? (I see VirtualBox createvm has a --basefolder option) ?
Or simpler: would it be possible to have Vagrant store all it's VMs files in a subdirectory, e.g. "~/VirtualBox VMs/vagrant/", so that one could make it a mount point or a symlink to another storage (disk).

Thanks !!

PS: I'm also eager to see the "linked clone" feature come to the VirtualBox provider ! :-)

**Comment by burnpanck** [comment]
I don't think that the work-around used by @npf is a solution that warrants closing this issue. I too would like to have the VM's stored in a different location. I set `VAGRANT_HOME` to a suitable path exactly to make vagrant put all the heavy files to that location. It would be great if vagrant could create the vbox VMs in a subdirectory below VAGRANT_HOME by default, by utilising the `--basefolder` option of VBoxManage.

**Comment by dragon788** [comment]
You can change the location that Virtualbox stores all its VMs from the CLI or GUI. It likes to put them in one place rather than leaving them wherever they might be spread across one or many folders or disks like VMware.

`vboxmanage list systemproperties | grep machine`
Default machine folder:          ${HOME}/VirtualBox VMs
`vboxmanage setproperty machinefolder /path/where/you/want/VirtualboxVMs`

You still need to `mv` any VMs from the old path to the new one, but any newly created VMs will end up in the `machinefolder`. This in conjuction with `VAGRANT_HOME` should let you better control where the bulky VM files go.

See also https://stackoverflow.com/a/59218437/3794873 and a separate comment that came to the same conclusion, https://stackoverflow.com/questions/14733681/vagrant-d-outside-of-the-home-folder#comment20775618_14804694
