### ISSUE TITLE
Host machine hangs on shutdown under certain conditions

### ISSUE THREAD

**Issue by jbrower** [hashicorp/vagrant#4628]
When using Vagrant (any version) under Ubuntu with Virtualbox, I can cause my host machine to not shutdown properly (it hangs). To reproduce these steps do the following:

Start a vagrant machine normally (ie. vagrant up)
Tell Ubuntu to shutdown (ie. go to cog in the top right of the desktop and select the shutdown option)

After everything has shut down, the system won't power off and it won't finish all of the shutdown since it will be in a state of "Waiting for virtualbox".

This issue doesn't occur when all vagrant boxes have been halted.

I see two possible ways of resolving this.

1) Add a script to Ubuntu's shutdown processes, which would shutdown all vagrant machines during a host shutdown.

2) Add an easy way to script this, something like vagrant halt --all that would halt all VMs currently running by vagrant so that it's easier for a user to add a shutdown command themselves.

I would rather see option 1 as it would be automatically taken care of and would prevent others in my team from running into this issue when they forget to halt their vagrant machines before shutting down.

**Comment by DASPRiD** [comment]
Just for the record, this is easily solved by editing ```/etc/default/virtualbox``` and setting the following values:

```bash
SHUTDOWN_USERS="all"
SHUTDOWN=acpibutton
```

**Comment by marrs** [comment]
@mitchellh: Surely Vagrant should at least report that it failed to shutdown the machine.  It can't be Virtualbox's fault that Vagrant hangs indefinitely

**Comment by gitfoxi** [comment]
Well, I have a janky solution that could be integrated with Vagrant or maybe a plugin. Inspired by: https://askubuntu.com/a/548449/315998

When (most) Linux shuts down, it will call a script at

    /sbin/halt.local

Make it contain:

    /usr/bin/VBoxControl guestproperty unset RUNNING

When the host tries tries to halt the guest, it sets the guestproperty RUNNING then waits for the guest to unset it.

    VBoxManage guestproperty set "guestname" RUNNING 1 --flags TRANSIENT
    VBoxManage guestproperty wait "guestname" RUNNING
    VBoxManage controlvm "guestname" poweroff

**Comment by silenced1** [comment]
@mitchellh - I have to say... when it comes to owning a problem "go to the other guy" is really not helpful. If you can't fix it, then you can just say that... but collaboration between Vagrant and Virtualbox is a must if Vagrant is going to succeed (it only takes another competitor who's willing to look at a situation like this to take away a customer).

Utilizing a Windows 7 Pro x64bit with Vagrant 2.0.0 and Virtualbox 5.1.30 r118389, I find that Vagrant doesn't know how to actually shut down a Virtualbox VM without causing this odd disconnect between the VM and it's status.

Now if I skip Vagrant, I can run the VM with Virtualbox and shut it down using all of the usual options and not end up with Windows itself "thinking" that the VM's are still running, nor do I have issues when I start them back up.

That would tell me that Vagrant's idea of managing VM's for other providers is faulty. I'm not saying that Vagrant isn't a great product, but as someone using this for a multi-VM setup, it's a real pain when I update the host with security updates after shutting down Vagrant and the VM's, just to have to reconnect all the VM's so that Vagrant and Virtualbox are again on the same page.

Two issues I've had to find fixes for so far:
1. Disassociation of ID's due to improper shutdown's and/or access from other means (Git Bash).
2. SSH Key Authentication failure

We're not asking for miracles... we just want Vagrant and the systems/products it's touching to be looked at with a serious eye. If not, build a fancy plugin for Docker or something... but don't discard the views of your users just because you don't want to be a little more pragmatic about fixing the issue. If I can run Virtualbox's controller (or shutdown from the VM itself) to shutdown the VM's properly, then so can Vagrant. We have faith in you!

**Comment by silenced1** [comment]
P.S.

If it helps at all, there is one clear indication that Vagrant is a bit confused:

```
> vagrant status
Current machine states:

vm1     poweroff (virtualbox)
vm2     poweroff (virtualbox)
vm3     poweroff (virtualbox)
```

.. then try..


```
> vagrant global-status
id          name          provider          state          directory
------------------------------------------------------------------------
09sdf0s vm1            virtualbox        running    c:/Vagrant/Testbox
f43dh5e vm2            virtualbox        running    c:/Vagrant/Testbox
16d3f8v vm3            virtualbox        running    c:/Vagrant/Testbox

```
Values are replaced, but that's what I see even 30m after I've used the halt command individually or globally. Any clarification on that result would be pretty interesting for sure.
