### ISSUE TITLE
Is there any real reason behind not naming 'vagrant halt' to 'vagrant down'

### ISSUE THREAD

**Issue by iamkirkbater** [hashicorp/vagrant#4772]
Just wondering if this is maybe something you would want to add an alias to in the code itself?  I've added a bash alias myself, but intuitively when I first started using Vagrant I though that since it was `vagrant up` to start a vagrant machine, that it would be `vagrant down` to shut it down.  Obviously the documentation is clear in saying that it's `vagrant halt` but would it be too much to ask that you add the command `vagrant down` and then write something along the lines of "Alias of 'halt'" in the documentation?

**Comment by amirbehzad** [comment]
It is still confusing.

This could have been prevented if User-centered design (UCD), and Card Sorting were used for naming menus and actions in Vagrant. It's intuitive to expect *down* to initiate *shutdown*, when *up* translates to *start*, isn't it?  Replacing *down* with *halt* does not address the root cause. In fact, the Up-Down combo shouldn't been used in the first place.

Just as an average user, I'd suggest *start/shutdown**, as in **start/reload/suspend/resume/shutdown** ?
or **create/destroy** or **build/destroy** or **new/delete** instead of **init/destroy** ?
