### ISSUE TITLE
vagrant's vmware-networks call breaks active tcp sessions on all other VMs

### ISSUE THREAD

**Issue by digitalsushi** [hashicorp/vagrant#4844]
Vagrant calls the "vmware-networks --stop;vmware-networks --start" command each time it creates a new VM.  This breaks all of the active TCP sessions on the other VMs that are running.

**Comment by feliksik** [comment]
I had the same issue you experienced, @Xylakant : vm ip's addresses being taken over. It was not because of the vmware-networks start/stop issue, but due to the dhcpd leases file being full for the relevant vmnet, after which the dhcpd was reusing ip addresses quickly instead of using really old ones. I cleaned up the file and thing worked again.
