### ISSUE TITLE
Running Vagrant within Vagrant: Possible?

### ISSUE THREAD

**Issue by geraldalewis** [hashicorp/vagrant#572]
## The Turducken of Computing

I've been banging my head against the issue for a couple days now and have had no luck making it work.

It occurred to me that it _may not be possible_, or that it may be possible, but only through `VBox` directly.

I'm happy to continue exploring the issue, but this kind of hacking is not within my wheelhouse, and any tips would be really appreciated!
## Some general info on my (lack of) progress

(`vm1 $` indicates the prompt within the 1st VM)

Inside the 1st Vagrant VM, `vm1 $ vagrant up` (to create the 2nd Vagrant VM) responds with:

```
[default] Failed to connect to VM!
Failed to connect to VM via SSH. Please verify the VM successfully booted
by looking at the VirtualBox GUI.
```

though it appears I do indeed have the 2nd VM inside the 1st Vagrant VM running:

```
vm1 $ BoxManage list vms --long
   Name:            vagrant_1322502151
   Guest OS:        Ubuntu
   UUID:            9d1ab03d-00d3-4745-bbc4-9b8209429820
   <snip>
   State:           running
```

`vm1 $ ssh vagrant@second_vm -vvvv` dies after:

```
debug1: identity file /opt/ruby/lib/ruby/gems/1.8/gems/vagrant-0.8.7/keys/vagrant type 1
debug1: Checking blacklist file /usr/share/ssh/blacklist.RSA-2048
debug1: Checking blacklist file /etc/ssh/blacklist.RSA-2048
ssh_exchange_identification: Connection closed by remote host
```

guest additions on the 2nd VM:

```
vm1 $ VBoxManage guestcontrol vagrant_1322502151  exec --image /bin/ls --username vagrant --password vagrant --wait-exit --wait-stdout -- -l /usr
```

result in the message:

```
VBoxManage: error: The guest execution service is not ready (yet).
```

Shutting down the 2nd VM via VBoxManage and restarting as headless:

```
vm1 $ VBoxHeadless --startvm vagrant_1322502151
```

Responds with 

```
Oracle VM VirtualBox Headless Interface 4.1.6
(C) 2008-2011 Oracle Corporation
All rights reserved.
```

and then hangs...

**Comment by dragon788** [comment]
I've been able to accomplish this with VMware (Workstation) as the outer VM layer (with Vagrant) and Virtualbox as the inner layer (with Vagrant). I actually made it even more ridiculous by running VMware on Windows with a Linux guest, with Vbox installed in Linux and a Windows guest running in that Vbox.

There are some tricks you need to do in order to avoid the networks clobbering each other (set a range for Vbox), and I'd highly suggest not trying to bridge the inner network to any network adapters (bad things happen).

**Comment by Crenshinibon** [comment]
@dragon788 I would be interested in the specifics. I have a Windows VirtualBox-box on an Ubuntu host. Inside this Windows box I'm trying to use Vagrant to create and test Ubuntu boxes that later need to be "rolled out" to other (in most cases) real Windows-Hosts, to act as testing-satellites for performance testing.

So far I was testing on VirtualBox only and just discovered this issue. 

The problem is the networking as depicted above.

But I was able to create a fully functional and networking enabled Ubuntu VM inside the Windows VM both with VirtualBox. So it seems as if VirtualBox is now (v5.0.14) capable of Boxes inside Boxes. I have tested NAT only, though.

But Vagrant isn't able to bring those Ubuntu boxes up inside the Windows VM, with working network.

**Comment by XedinUnknown** [comment]
Here's my reason:
I have a high-end desktop PC with an excellent GPU and 2 huge monitors.
I also have a low-spec, but i7, laptop with Ubuntu 14 on it.
The Ubuntu doesn't run so great on the laptop, not to mention the inability to connect both monitors. Also, Ubuntu looks like rubbish next to Win10 or even Win8.
So, I want to be able to do all the things I do on the laptop on the desktop too, because editing code rocks on the Win desktop, but running the code in an environment sucks on it. I also want all the development stuff encapsulated in a separate reproducible environment.

**Comment by dragon788** [comment]
So the first step to getting this working under VMware or VirtualBox, is to
make sure that you are using  completely separate network ranges for the
virtual network interfaces in your VM 'host' and on your host OS. This
means if you have a 192.168.x.x as the virtual network for your host
virtualization layer, you should use a 10.x.x.x inside your VM for the
second virtualization layer (not eth0, but virtual interfaces).

You should also if using a graphical Linux environment disable dnsmasq in
the Network Manager configuration, this behaves poorly when coupled with
virtualization solutions because the DNS doesn't properly resolve when
going through NAT and multiple layers of abstraction.
