### ISSUE TITLE
More support for disabling provisioners

### ISSUE THREAD

**Issue by kruthar** [hashicorp/vagrant#6343]
I'm using vagrant version: 1.7.4

I frequently have multiple provisioners in my Vagrantfile for organization and reuse of tasks. I commonly use 

``` sh
vagrant provision --provision-with x,y,z
```

to provision with specific provisioners. I have found that it would be really useful to do the opposite of this action, meaning specify provisioners I DO NOT want to run and vagrant will run all others. I can see this being done one (or both) of two ways:
1. adding a --[no-]provision-with x,y,z. Running `vagrant provision --no-provision-with x,y,z` should run all provisioners except x, y and z
2. adding a disabled: [true|false] parameter to provisioners in the Vagrantfile. `disabled: false` (default) would cause the provisioner to act as provisioners normally act. `disabled: true` would cause the provisioner to not run on normal provisioning steps unless explicitly told to do so with --provision-with x,y,z

Personally, I like the second one better, but both options seem useful to me. Adding this functionality would give the user more convenient control over which provisioners are being run.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
