### ISSUE TITLE
Implement --all for suspend or vagrant suspend-all.

### ISSUE THREAD

**Issue by kenorb** [hashicorp/vagrant#7221]
I'd like to have have command or option which allows me to suspend or halt all the running machine.

This can be implemented either by `vagrant suspend-all`, or by extra option `--all` for existing `vagrant suspend` command.

The current workaround include the following syntax in order to achieve that:

```
vagrant global-status | awk '/running/{print $1}' | xargs -r -d '\n' -n 1 -- vagrant suspend
```

Current workarounds: [Shutting down all VirtualBox VMs](http://askubuntu.com/q/457329/78223) at Ask Ubuntu

**Comment by sethvargo** [comment]
Hi @kenorb 

Thank you for opening an issue. The `suspend` argument should accept a regular expression for the list of VMs to suspend, in the current environment, so something like:

```
vagrant suspend '*'
```

_should_ work, but you may need to escape the `*` depending on your shell.

To suspend _all_ machines, even those outside of the current environment, using global-status is the best bet. Note you can use --machine-readable on the `global-status` command which will reduce the awk/grep.

Does that answer your question? I don't think it makes sense to add another command for this functionality since it's easily achievable through the other commands.

**Comment by kenorb** [comment]
Tested:

    $ vagrant suspend '*'

but it's saying:

> The machine with the name '*' was not found configured for this Vagrant environment.

Vagrant 1.8.1

**Comment by tKammy** [comment]
I guess we can use `/.*/` as regular expression instead of `'*'` like following:

`vagrant suspend /.*/`

Is this a bug?

**Comment by chrisroberts** [comment]
Might be better to implement this with glob syntax instead of regex (just as a thought when circling back to this)
