### ISSUE TITLE
Do not run validations on disabled provisioners

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vagrant#7367]
### Vagrant version

1.8.1
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.provision "file", source: "./dafa", destination: "foo"
  config.vm.provision "shell", inline: "echo hi"
end
```
### Expected behavior

When running:

```
$ vagrant up --no-provision
```

or

```
$ vagrant up --provision-with=shell
```

Vagrant should not throw a validation error that the `source` file does not exist.
### Actual behavior

Vagrant performs validation at the configuration stage, regardless of whether the provisioner is enabled.
### Steps to reproduce
1. Create the Vagrantfile above
2. Run any of the above commands
### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-6613

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
