### ISSUE TITLE
Vagrant nighly build

### ISSUE THREAD

**Issue by bbrala** [hashicorp/vagrant#7920]
I'm wondering, sometimes it is nice to be able to test the current master to if things work, or make certian builds available since they fixed some issues. Have you ever thought of supplying nightly builds? Running vagrant from dev is a bit of a hassle to communicate to people.

**Comment by chrisroberts** [comment]
This enhancement was delayed multiple times due to some internal coordination. However, I am very pleased to be able to finally close this issue as complete :tada:

Nightly(-ish) builds are posted on the [hashicorp/vagrant-installers](https://github.com/hashicorp/vagrant-installers) repository. The release will be named `vVERSION.dev+master` with the assets being replaced on each successful new build.

Cheers!
