### ISSUE TITLE
Cancelled 'vagrant destroy' should return exit status <> 0

### ISSUE THREAD

**Issue by ergonlogic** [hashicorp/vagrant#811]
Right not, if we call 'vagrant destroy' from a script we cannot easily react to the choice the user makes when prompted with:

```
Are you sure you want to destroy the 'hm' VM? [Y/N]
```

Whether we proceed to destroy the VM or not, it returns exit status 0. So instead, we have to check for the continued existence of .vagrant or parse the output text, etc.

**Comment by dgonano** [comment]
I know this is old but I just ran into an issue using scripts to manage vagrant and destroy machines. Scripts expect an exit status of 0 if all went well. 
Regardless of if machines were originally created or not, the exit on `destroy` should be 0 if the end result is the machine doesn't exist anymore. 

My script calls destroy to ensure machines are not created before bringing up fresh ones. If I have to ignore the output (because it may be 0 1 or 2) then I loose the ability to check if that step of the script worked. I don't care what was destroyed, I just care that all of them are now destroyed. 

Just my 2 cents. I'm assuming there's a reason it hasn't been done this way.
