### ISSUE TITLE
Ubuntu 16.04 - vagrant still hangs on mounting nfs shares

### ISSUE THREAD

**Issue by COLABORATI** [hashicorp/vagrant#8177]
Freshly installed Ubuntu 16.04 - new Virtualbox 5.1.12 from their repos - vagrant still hangs on mounting nfs shares. yes, I tried the bento box, no difference. Sometimes it works on the first time, but usually it hangs. nfs-kernel-server is installed, of course, and runs and has no problems with real boxes. No fun.

```
Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
mount.nfs: Connection timed out
```

**Comment by richard-scott** [comment]
Do you have Ubuntu Livepatch setup on that box?
I have had the same issue, and had to remove livepatch to get Vagrant to mount NFS shares.
Initial attempts with Vagrant v1.9.1 are looking better than v1.9.0

**Comment by richard-scott** [comment]
I also seem to remember that I found restarting 'rpcbind' before starting a VM seemed to help, but that may have been the late time of the day that I was attempting to diagnose this.

**Comment by richard-scott** [comment]
ok, an upgrade to Vagrant v1.9.1 didn't help. it seems that restarting rpcbind was the fix for me.

**Comment by chadfurman** [comment]
For me, I needed to make sure my host interface was up so my Host had an IP on the virtualbox's network

Solution:
```
$ sudo ip a add 192.168.33.1/255.255.255.0 dev vboxnet0
$ sudo ip link set vboxnet0 up
```

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
