### ISSUE TITLE
vagrant up with docker provider not working with password setting set

### ISSUE THREAD

**Issue by sebastianreloaded** [hashicorp/vagrant#8732]
### Vagrant version
Vagrant 1.9.5

### Host operating system
Ubuntu 16.04.2 LTS

### Guest operating system
Ubuntu 16.04.2 LTS

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "sebastianreloaded/test:latest"
    d.username = "sebastianreloaded"
    d.password = "censored"
  end
end
```

### Debug output
https://gist.github.com/sebastianreloaded/d6d97a59b29427f268a6ab39c00dad49

### Expected behavior
download the image from the private repository and start container

### Actual behavior
No usable default provider could be found for your system.

### Steps to reproduce
1. vagrant up

### Additional Notes
- It works with public images
- It works when using docker login and then vagrant up without username and password in the file
- Setting anything to the d.password setting leads to the error described above, even when the image is already locally available
- i can't reproduce this on my mac osx sierra

**Comment by briancain** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier 

Cheers!
