### ISSUE TITLE
Vagrant CLI spits out escape sequences when TERM is "dumb"

### ISSUE THREAD

**Issue by janssen** [hashicorp/vagrant#8826]
Vagrant version

1.9.7
Host operating system

MacOS Sierra
Guest operating system

N/A
Vagrantfile

N/A
Expected behavior

% vagrant box list
test (parallels, 0)
%
Actual behavior

% echo $TERM
dumb
% vagrant box list
�[0mtest (parallels, 0)�[0m
%
Steps to reproduce

    Fire up an Emacs.
    Type M-x shell
    List your boxes.

References

https://github.com/mitchellh/vagrant/issues/8800

**Comment by janssen** [comment]
@briancain  Using vagrant --no-color does suppress the escape sequences.  But to have to do this kind of thing explicitly for every tool that one installs leads to insanity.  That's why the TERM env var was invented.

By the way, you can try these things yourself:

```
  $ sudo apt install emacs vagrant
  $ emacs
  M-x shell
  [emacs] $ vagrant info
```

**Comment by janssen** [comment]
In Python, the appropriate code would be

`python -c "import curses; curses.initscr(); print curses.has_colors()"`

Don't know about Ruby, though.

**Comment by janssen** [comment]
Looks like the Ruby functionality is in http://ruby-doc.org/stdlib-2.0.0/libdoc/curses/rdoc/Curses.html#method-c-has_colors-3F.

**Comment by jbonhag** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

As a side note, you could set `VAGRANT_NO_COLOR=1` in your shell and that will get picked up by any tool running Vagrant.

Again, thank you for suggesting this and it is a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!

**Comment by janssen** [comment]
Yeah, well, if you're going to deal with reasonable issues by closing them,
I think there's also a bug in your workflow.
