### ISSUE TITLE
Couldn't start on WSL due version mismatch

### ISSUE THREAD

**Issue by vvasilev-** [hashicorp/vagrant#8858]
I think the problem is on [this line](https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/util/platform.rb#L400) because Vagrant reports `Vagrant 1.9.7`, while the code tries to match something different.

### Vagrant version
1.9.7 - Windows/WSL

### Host operating system
Windows 10 Home (Creators Update)

### Debug output
https://gist.github.com/vvasilev-/a751d7ff604c64c8ccfc75c9e78e2978

**Comment by vvasilev-** [comment]
Yes, I have it. The version again is 1.9.7.

On Aug 7, 2017 7:07 PM, "Chris Roberts" <notifications@github.com> wrote:

@vvasilev- <https://github.com/vvasilev-> Do you have the Windows version
of Vagrant installed? If so, what version is it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mitchellh/vagrant/issues/8858#issuecomment-320706855>,
or mute the thread

**Comment by robwiss** [comment]
I have been having the same error today! It's driving me crazy because it seemed to happen spontaneously in the middle of the day without any updates or anything. One minute things worked the next they didn't.

I have 1.9.7 installed in windows and WSL. I have VAGRANT_WSL_ENABLE_WINDOWS_ACCESS=1. vagrant.exe is in my path. When I run vagrant from inside the WSL I get:
```
Vagrant cannot currently enable access to manage machines within the Windows
environment because the version of Vagrant installed on Windows does not
match this version of Vagrant running within the Windows Subsystem for Linux.
Please ensure both installation of Vagrant are the same. If you do not want
update your Vagrant installations you can disable Windows access by unsetting
the `VAGRANT_WSL_ACCESS_WINDOWS_USER` environment variable.

  Windows Vagrant version: unknown
  Windows Subsystem for Linux Vagrant version: 1.9.7
```

When I try to run vagrant.exe from inside the WSL I get:
```
$ vagrant.exe
stdin is not a tty
```

I checked on a coworker's machine and theirs is able to run vagrant and vagrant.exe inside the WSL.

**Comment by poma** [comment]
Temporary workaround: replace bin/vagrant.exe with the one from version 1.9.6 (I've uploaded one [here](https://drive.google.com/open?id=0BxCiZaWjl6fxa0F1cUdxNnZaT28)). It is just a wrapper so your real version will still be 1.9.7

**Comment by robwiss** [comment]
Upgrading to 1.9.8 made vagrant work in WSL for me.

**Comment by pori** [comment]
So I'm having an issue similar to @robwiss. Differences are that I am running Vagrant 2.0.0. It's installed on both wsl and Windows, no stdin error when trying to run `vagrant.exe`. I'm a bit stumped.

**Comment by chrisroberts** [comment]
Hi there,

This should be resolved in recent versions of Vagrant. If after upgrading to the latest version of Vagrant you are still experiencing this issue, please open a new issue and I will investigate further.

Cheers!

**Comment by Fd8326032** [comment]
One hour ago I had vagrant 2.26 installed  on Windows 10. I uninstalled it and installed 2.02_x86_64,restarted... Inside Windows 10's local Ubuntu, I ran' vagrant up'. (after export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"), It gives this 
"
Vagrant cannot currently enable access to manage machines within the Windows
environment because the version of Vagrant installed on Windows does not
match this version of Vagrant running within the Windows Subsystem for Linux.
Please ensure both installation of Vagrant are the same. If you do not want
update your Vagrant installations you can disable Windows access by unsetting
the `VAGRANT_WSL_ACCESS_WINDOWS_USER` environment variable.

  Windows Vagrant version: unknown
  Windows Subsystem for Linux Vagrant version: 2.0.2"

But the version on Windows 10 is 2.0.2. Any idea? Is this because Windows system path still carries old memory of 2.2.6? I can go there to delete, restart and repoint to the same directory and bin... Thanks.
