### ISSUE TITLE
Mouse stopped worked in tmux

### ISSUE THREAD

**Issue by petrov-ivan** [hashicorp/vagrant#8904]
Hello! I encountered this bug and want to share my findings.

### Steps to reproduce
1. vagrant ssh
2. try to use mouse in tmux

### Expected behavior
Mouse events are passed correctly.

### Actual behavior
Mouse events are passed incorrectly.

### My research

I tried sshing into the box via third party ssh (supplied with Git Bash). And... mouse worked! So, probably built-in operation of ssh is the culprit.

I tested versions 1.9.5, 1.9.6 and 1.9.7. The bug first appears in 1.9.6. I wonder if it's somehow related with splitting to 32-bit and 64-bit versions.

### Vagrant version
1.9.7 (64-bit)

### Host operating system
Windows 10 15063 64-bit

### Guest operating system
Ubuntu 16.04

### Terminal emulator
Mintty (from default Git Bash install)

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
