### ISSUE TITLE
Complain more loudly when sudo_command fails

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9158]
When an internal Vagrant command that requires superuser privileges, and therefore config.ssh.sudo_command, fails, please make this more clear in the default `vagrant up [--provision]`/`vagrant provision` output. Currently, Vagrant quietly hides such errors, and only indicates the true problem (often lack of sudo support in the guest) when the `--debug` flag is added.

**Comment by soapy1** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it is a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
