### ISSUE TITLE
Vagrant Cloud index updates slowly

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9176]
Not sure where the best place to post this is, but after several days, none of my new Vagrant boxes published to Vagrant Cloud are searchable, e.g. "minix" doesn't show mcandre/minix in the results. And when I search "mcandre", of the several boxes I have published, only the dummy mcandre/chocolatey box appears in results. Something's off with the indexing, I dunno.

**Comment by justincampbell** [comment]
@mcandre For [mcandre/minix](https://app.vagrantup.com/mcandre/boxes/minix), this box does not have any released versions. In order to release v0.0.1, click the blue "Release" button on that page next to v0.0.1, or you can release it from the [v0.0.1 edit page](https://app.vagrantup.com/mcandre/boxes/minix/versions/0.0.1/edit).

Thanks! I hope this helps. If you have any other questions you can ask here, or email [support+vagrantcloud@hashicorp.com](mailto:support+vagrantcloud@hashicorp.com).
