### ISSUE TITLE
EXT4-fs error / Buffer I/O error on dev sda

### ISSUE THREAD

**Issue by fredngo** [hashicorp/vagrant#9288]
After upgrading to OS X High Sierra 10.13.2, my Ubuntu vagrant machines are experiencing filesystem errors. 

Is this possibly related to the new APFS file system on High Sierra 10.13.2?

### Vagrant version
2.0.1 (Previously 1.9.7)

### Host operating system
OS X High Sierra 10.13.2 (Previously El Capitan 10.11.6)

### Guest operating system
Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-137-generic x86_64)
VirtualBox 5.2.2 (Previously VirtualBox 5.1.26)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  # https://github.com/mitchellh/vagrant/issues/5186
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "1024"
  end
end
```

### Debug output
<img width="804" alt="screen shot 2017-12-19 at 11 11 13 pm" src="https://user-images.githubusercontent.com/11791/34190998-f2cebde6-e511-11e7-9269-e870fb251ce3.png">

<img width="804" alt="screen shot 2017-12-19 at 11 16 57 pm" src="https://user-images.githubusercontent.com/11791/34191149-b9f4503e-e512-11e7-8f51-909514626ff0.png">

### Expected behavior
No filesystem type errors

### Actual behavior
Filesystem type errors

### Steps to reproduce
Unfortunately, unknown

### References
None that I could find

**Comment by fredngo** [comment]
I also created new VMs from scratch, and still experiencing these errors.

**Comment by fredngo** [comment]
More information: I downgraded back to 5.1.26, and it seems to work well again. My guess is that it's some problem with VirtualBox 5.2.2. Closing this issue for now!

**Comment by fredngo** [comment]
Upgraded to VirtualBox 5.1.30, the last release for 5.1, and my VMs are still working fine.

This means that something is seriously wrong with VirtualBox 5.2.x!

Just documenting this from random googlers.

**Comment by ndouglas** [comment]
I've just started seeing this after updating from Vagrant 1.9.5 to 2.0.2 and rebuilding -- or trying to rebuild -- the VM.  My VirtualBox version is 5.1.22, though.  It functioned well earlier today.  I updated Vagrant since I otherwise couldn't seem to find the base box, and suddenly building fails.

I'm actually trying to use this computer because my other Mac started showing me similar errors.  It's running Vagrant 2.0.2 and VirtualBox 5.2.6.  It functioned well until a week or two ago.  I updated Vagrant and Virtualbox because I couldn't get NFS to work, presumably because of the APFS issues.  Then it started failing whenever I had significant I/O.

**Comment by fredngo** [comment]
After some experimentation, my stable configuration is as follows:

On the Host machine: Vagrant 2.0.2, VirtualBox 5.2.6, macOS High Sierra 10.13.3
On my Guest machines: Ubuntu 14.04.5 Trusty LTS

If I use Ubuntu 16.04 Xenial on the Guest machines, then all hell breaks loose when there is significant I/O.

After spending a couple days trying to figure out why 16.04 sucks so much on Vagrant, I was unsuccessful so I am sticking with Ubuntu 14.04. I figure 18.04 will soon be released anyway, maybe it'll behave better.

**Comment by ndouglas** [comment]
Interestingly, I'm also seeing this on another computer (a Dell XPS 15) running a completely different OS (Debian Stretch).  I've encountered it with Vagrant 1.98 and 2.02, VirtualBox 5.2.6, 5.1.30, and 5.1.32.  Host OS was installed yesterday, so it's pretty much as up-to-date otherwise as Debian gets.

Kind of bewildered at this point.

**Comment by fredngo** [comment]
What's your Guest OS? Like I mentioned, only Ubuntu 14.04.5 works for me as a Guest OS without experiencing these errors, not Ubuntu 16.04. 

No idea if Host has any bearing on this. And I have not bothered to used any other Guest OS other than Ubuntu.

**Comment by ndouglas** [comment]
Debian Jessie and Stretch and Ubuntu Xenial/16.04.  Maybe I'll try with 14.  I've tried Debian boxes from three different people and get the same errors each time.  Been screwing with it all day... pretty frustrated.  I'll try Ubuntu 14 and update this thread with what I find.

**Comment by fredngo** [comment]
Yep, my guess is that 14.04 will work just fine, based on my own screwing around for several days. Please do update in case others find this thread.

**Comment by conceptdeluxe** [comment]
I have the same trouble. I've upgraded MacOS from El Capitan to Mojave and for this reason needed to upgrade from Vagrant 1.9.8 to 2.2.0 and VirtualBox 5.1.30 to 5.2.20.

Since then all 14.04, 16.04 and 18.04 boxes fail with I/O errors.

I've tried destroying and re-creating the boxes without success. I've tried to find a way to install VirtualBox 5.1 versions but without luck. I've tried installing Vagrant 1.9.8 and changing the provider configuration so that it works with VirtualBox 5.2 but the I/O errors remain.

So there is a major issue with VirtualBox 5.2 and Vagrant and Ubuntu.

**Comment by fredngo** [comment]
Reopening as it seems the problem is still there.

**Comment by soapy1** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier ☹️

Cheers!
