### ISSUE TITLE
Windows 10 - Installer loads very long when selecting other destination

### ISSUE THREAD

**Issue by LukBukkit** [hashicorp/vagrant#9310]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.0

### Host operating system
Windows 10 - Version 1709

### Debug output
Not possible with the installer.

### Expected behavior
The installer for the version 2.0.1 should accept the path and let me continue with the upgrade.

### Actual behavior
It just loads and nothing happens. 
(Edit: After a while (about 10 minutes) I was able to continue with the installation)

![dwm_2017-12-27_13-31-39](https://user-images.githubusercontent.com/8070210/34381676-555b503e-eb0a-11e7-9600-775dbf0ac8b9.png)

### Steps to reproduce
1. Start the installer
2. Select another path
3. Click OK

### References
Are there any other GitHub issues (open or closed) that should be linked here?
I couldn't find any references.

**Comment by kikitux** [comment]
Hello

We are trying to repro but we haven't been able.

Is your machine in a corporate network? ie windows domain, profile in a share folder?

does the sale happen when you are off the network? ie cable disconnected?

Alvaro.

**Comment by LukBukkit** [comment]
No I'm not in a corporate network, but I try to install it without a network connection and report the result to you.

**Comment by LukBukkit** [comment]
It tested it without a network connection and it still took about 6 minutes. Here's a video: https://youtu.be/ELhJy4bEiVc

**Comment by gstewart** [comment]
I have the same issue on Windows 7. It's only when I try to update and it looks like it triggers my virus scanner on all the current files under `embedded` when I point it to my existing install path. I am on a corporate network.

If I uninstall my current version, it takes about the same amount of time (10-15 minutes) for the uninstaller to remove all of those files. When I try to install to the same location after this (with only a few files left under `embedded/gems/gems/`), it accepts the path immediately.

It's maybe just a little confusing that the installer hangs at the path selection step instead of just taking a long time during the install itself, but I don't think you have much control over this.

**Comment by eurico-nerd** [comment]
This is still happening, I'm upgrading from 2.2.3 to 2.2.4 on a Windows 10 PC.

I select to change the destination folder (because it's not installed on the default location and the installer doesn't know where vagrant was installed before), then select the folder. Disk starts crunching (yes, I have it on a mechanical drive), task manager shows 100% usage for that disk, installer becomes unresponsive. After a good while (around 10 minutes), disk stops crunching and installer moves to next step.

I have no clue what the installer is trying to do on the disk when I select another destination folder, but it's definitely not normal.

**Comment by jbonhag** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier ☹️ 

Cheers!
