### ISSUE TITLE
Permit --box-version when importing local *.box's

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9321]
For development purposes, it would be more convenient if --box-version were allowed to be specified when importing local *.box files, so that a box can be tested more quickly.

As a workaround, downstream test Vagrantfile's can tweak their config.vm.box_version to match the default version that the local *.box imports as, but this creates extra work for the developer compared to just being able to actually specify `--box-version` when manipulating the .box file in the first place.

**Comment by daks** [comment]
When I needed the same, the only solution I found was to create a manifest file (.json) containing versions linked to files, like Vagrant except to found in Vagrant official or unofficial repository.

**Comment by jbonhag** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it is a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
