### ISSUE TITLE
Udacity/CV box doesn't download after 30%

### ISSUE THREAD

**Issue by SHRIVP** [hashicorp/vagrant#9359]
### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 10

### Guest operating system
NA

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "udacity/cv"  
end
```

### Debug output
https://gist.github.com/SHRIVP/26088ddcecdb5282a43b64b34d1011c3

### Expected behavior
Udacity/CV box should have been downloaded

### Actual behavior
The download stops and then times out after approx 30%.

### Steps to reproduce
1.vagrant up

### References
NA
- ...

**Comment by briancain** [comment]
@SHRIVP - Are you able to download other boxes from Vagrantcloud just fine?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
