### ISSUE TITLE
[Feature request] Allow distribution and retrieval of boxes using different protocols e.g torrent, ipfs, ftp, etc.

### ISSUE THREAD

**Issue by LoveIsGrief** [hashicorp/vagrant#9454]
Somewhat related to #5319 and @faddat's [comment](https://github.com/hashicorp/vagrant/issues/5319#issuecomment-291019093)

It would be great if vagrant had the possibility to add and push boxes from/to torrents, ipfs, tahoelfs, tor, i2p, basically any protocol we wish to support.

This could be introduced in 2 phases:

1. `box add`

Allow the `url` field in the `metadata.json` to be either:
  - a string e.g `"https://location.test/box/1.0/wat.box"`
  - an array of strings `[ "https://location.test/box/1.0/wat.box", "sftp://location.test//opt/vagrant//box/1.0/wat.box", "ipfs://someridiculuouslylonghash", "magnet://amagnethash"]`
  - a dict with keys being the protocol and the values being either string or an array of string with alternatives for the protocol

Let box add choose which program or lib to use depending on the protocol and download the box

2. `box push `

Using the new `metadata.json` push the box to the destinations specified and push the new `metadata.json` on the remote endpoint too.

Since I don't have an account for Hashicorp Atlas, I don't know if something similar already exists and would just need to be extended to support other protocols.

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
