### ISSUE TITLE
Vagrant Share missing from v2.0.2

### ISSUE THREAD

**Issue by devopskatas** [hashicorp/vagrant#9485]
### Vagrant version
v2.0.2

### Host operating system
Windows 10 Pro 64bit

### Guest operating system
Ubuntu 16.04 (bento)

### Expected behavior

'vagrant share' should be a CLI command.  It is still listed in the documentation but is no longer functional.

 ### Actual behavior
'share' is no longer listed as an option.  Executing 'vagrant share' lists the help page.

### Steps to reproduce
1.  Download Vagrant v2.0.2
2.  Install Vagrant v2.0.2 (I upgraded from v2.0.1)
3.  Attempt to execute vagrant share

**Comment by briancain** [comment]
@devopskatas - This plugin was removed in 2.0.2. You can still install and use it if you run the following command:

```
vagrant plugin install vagrant-share
```

We're going to update the documentation to mention the removal and instruct users on how to install the plugin. Thanks!

**Comment by konstantingoretzki** [comment]
## Same problem - however installing the plugin hasn't helped.

### Vagrant version
v2.0.2

### vagrant-share version
v1.1.9 from Arch repo (https://www.archlinux.org/packages/community/x86_64/vagrant/)

### Host operating system
Antergos (Arch Linux)

### Guest operating system
Ubuntu 16.04 (ubuntu/xenial64)

### Expected behavior
'vagrant share' should be a CLI command. It is still listed in the documentation but is no longer functional. Installing the plugin with `vagrant plugin install vagrant-share` should install the plugin.

### Actual behavior
'share' is no longer listed as an option. Executing 'vagrant share' lists the help page. Even after installing the plugin manually it did not work --> 'vagrant share' lists the help page. However installing other plugins like vbguest did work.

### Steps to reproduce

    Download Vagrant v2.0.2
    Install Vagrant v2.0.2
    Attempt to execute vagrant share/ attempt to install the vagrant-share plugin

**Comment by vitorhub** [comment]
best solution with any program. chose best version and keep changin until works. my case, without losing time instaled older versions, witch is vagrant 1.9.8 in my case. seems to me like a shorcut. I did it with other softwares. Sublime, virtualbox, etc.
