### ISSUE TITLE
smartos guest plugin assumes fragile path to SSH key

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9527]
### Vagrant version

Vagrant 2.0.1

### Host operating system

macOS High Sierra 10.13

### Guest operating system

SmartOS 20180203T031130Z

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.guest = :smartos
  config.solaris.suexec_cmd = ""
  config.ssh.sudo_command = "print \".\nvagrant\n\" | /usr/lib/embedded_su root -c '%c'"
  config.vm.synced_folder ".", "/opt/vagrant", type: "rsync", rsync__chown: false
end
```

### Expected behavior

`vagrant up`, `vagrant ssh`, `vagrant rsync`, and `vagrant rsync-back` perform an SSH public key insertion once, and continue operating normally.

### Actual behavior

`vagrant rsync[-back]` tries to insert an SSH key and fails, due to hardcoded assumptions about SSH configuration for SmartOS guests. In fact, the guest plugin encourages developers to place authorized keys in a directory that does not exist by default, and to make the root account available by public key. A more flexible guest plugin implementation would identify where the current key actually resides, and place the new key there.

I am currently working around this glitch, and a few other SmartOS guest plugin oddities, by configuring my SmartOS box as a Solaris11 box instead.

### Steps to reproduce

1. `vagrant up`
2. `vagrant rsync`

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
