### ISSUE TITLE
Improvement: Vagrant box remove by index

### ISSUE THREAD

**Issue by Spamme1** [hashicorp/vagrant#9560]
### Vagrant version
2.0.2

### Host operating system
Windows 7

Many vagrant boxes have very long and somehow complicated names, moreover in windows 7 the only way to copy paste something in the console is to select all, copy and paste it in a separate text editor, re-select the name of the box and paste it back in the console. Actually it would be easier if it would be possible to remove the boxes by an index. In this way there would be no need of any copy and paste of the box name.

```
C:\>vagrant box list
1 - Windows 7 SP 1
2 - Windows 10
3 - Windows 2012

C:\>vagrant box remove  1
```

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
