### ISSUE TITLE
Vagrant Cloud API call Fails When There are Special Characters in my Password.

### ISSUE THREAD

**Issue by zipzit** [hashicorp/vagrant#9566]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.2

### Host operating system
MacOS High Sierra Version 10.13.3

### Guest operating system
N/A

### Vagrantfile
N/A

I'm trying to use the [Vagrant Cloud API](https://www.vagrantup.com/docs/vagrant-cloud/api.html) to obtain an authentication token.  I want to look at a private resource.  Turns out when my password contains unusual punctuation characters, the API call fails.

Note: I use a password vault.  I never ever use the same password twice.  Instead I just use the vault password generator, copy paste, etc... The password `>IsJ{_di<B\w` makes the API call fail.   Yes that was the real password, but its dead now.  

Original request:  
$     curl \
>       --header "Content-Type: application/json" \
>       https://app.vagrantup.com/api/v1/authenticate \
>       --data '
>         {
>           "token": {
>             "description": "Login from cURL"
>           },
>           "user": {
>             "login": "myLoginName",
>             "password": ">IsJ{_di<B\w"
>           }
>         }
>       '

response: **{"status":400,"errors":["Invalid JSON"]}**

tests  #1-16, invalid JSON, Huh?  Wasted a whole lot of time here...

test #17:   use the fake password "secretpassword" in lieu of the actual password in the registry.

$ curl \
>   --header "Content-Type: application/json" \
>   https://app.vagrantup.com/api/v1/authenticate \
>   --data '
>     {
>       "token": {
>         "description": "Login from cURL"
>       },
>       "user": {
>         "login": "myLoginName",
>         "password": "fakesecretpassword"
>       }
>     }
>   '
response:  **{"errors":["Bad access token!"],"success":false}**

Test #18.  Go to the Vagrant Cloud website, and change the password in the registry to all random lowercase ascii characters, retest

$ curl \
>   --header "Content-Type: application/json" \
>   https://app.vagrantup.com/api/v1/authenticate \
>   --data '
>     {
>       "token": {
>         "description": "Login from cURL"
>       },
>       "user": {
>         "login": "myLoginName",
>         "password": "truesecretpassword"
>       }
>     }
>   '

response: **{"description":"Login from cURL","token":"xxxxxxx","token_hash":"yyyyyyy","created_at":"2018-03-13T07:26:02.646Z"}**

(Success, yipee!)

### Expected behavior
What should have happened?  I should have been able to make the API call to receive authentication tokens no matter what the password was.  If you require special password setup, that's fine, but please tell us so at password registration time. 

### Actual behavior
What actually happened?  See Above

### Steps to reproduce
See Above

**Comment by briancain** [comment]
Hi @zipzit - there could potentially be an escaping issue with your shell. I notice the password you used has a `\w` in it. Please place your json in a file and try the request again and let us know if that still fails, thanks!

**Comment by zipzit** [comment]
Er, right.  Where are you going with this?  I'm quite sure you are exactly correct, that a combo of characters within the original passsword creates a magic escape sequence somehow and corrupts the API call.  No doubt. 

And that's exactly why I posted this the way I did... so if anybody else hits the error and then does a search for `vagrant {"status":400,"errors":["Invalid JSON"]}` they end up at this issue.  

Are you asking me to pull a branch that updates the instructions on the Vagrant Cloud API readme that includes submission of login/password via file?   Or perhaps a warning on the Vagrant registration page that warns to not use escape characters in one's password....   (which isn't part of this repo...)

I'm missing the point of the file test.  I get that the team doesn't like having too many open issues in the inbox of life.  This isn't the way to make the issue disappear.  

Frankly, I'd be happy if the issue was noted on a readme somewhere, no code action required . It's a pretty obtuse error, and had my password vault not generated that password, no one the wiser..

I will say, many thanks to the entire Vagrant team for a pretty awesome product.

**Comment by briancain** [comment]
The problem here is that your password string field does actually contain invalid json (via [JSONLint](https://jsonlint.com/)):

<img width="1085" alt="screen shot 2018-03-13 at 3 33 29 pm" src="https://user-images.githubusercontent.com/810277/37373500-04f5cdf8-26d4-11e8-9d5b-525f1475801e.png">

Fixing the `\w` ...

<img width="1099" alt="screen shot 2018-03-13 at 3 33 39 pm" src="https://user-images.githubusercontent.com/810277/37373503-08f8ab32-26d4-11e8-8ea5-e64f8a758c70.png">

Escaping the `\w` with `\\w` makes it "valid" json.

> I'm missing the point of the file test.

Asking to make the same request with a file was just to see if your shell was doing something funky with that character when making the curl request, but it turns out that it's just not valid json anyway on its own.

The API expects valid JSON when receiving requests. The error it returned is the expected and proper error as the JSON data provided was invalid. A better way to prevent running into this error may be to not generate JSON manually but use a language (like ruby or python) to create the serialization data for you. This will ensure proper data format and handle any character escaping that may be required. Thanks!
