### ISSUE TITLE
Can't create vagrant box from Coreos box

### ISSUE THREAD

**Issue by abelgana** [hashicorp/vagrant#9573]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.1

### Host operating system
macos

### Guest operating system
coreos

I am using the following Vagrantfile to create the new box based on coreos box.

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# # vi: set ft=ruby :

update_channel = "stable"

num_etcds = 1

instance_etcd_prefix = "etcd"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "coreos-%s" % update_channel
  config.vm.box_url = "http://%s.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json" % update_channel

  (1..num_etcds).each do |i|
    vm_name = "%s-%02d" % [instance_etcd_prefix, i]
    config.vm.define vm_name do |host|
      host.vm.hostname = vm_name
    end
  end

    config.vm.post_up_message = "Vagrant has finished"
end
```
Once the VM is create I package the VM to create a new box. 

When I use the new box on my Vagrant file. I have the following error.

### Debug output
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

systemctl stop etcd
ifconfig 172.17.8.101 netmask 255.255.255.0
mv /tmp/etcd-cluster.service /media/state/units/
systemctl restart local-enable.service

# Restart default etcd
systemctl start etcd

Stdout from the command:

Stderr from the command:

Failed to stop etcd.service: Unit etcd.service not loaded.
SIOCSIFNETMASK: No such device
mv: cannot move '/tmp/etcd-cluster.service' to '/media/state/units/': No such file or directory
Failed to restart local-enable.service: Unit local-enable.service not found.
Failed to start etcd.service: Unit etcd.service not found.
```

How to reproduce it:
1 - Run `vagrant up` for the first vagrant file provided.
2- Run `vagrant package --output kube.box ` to create the new box
3- Use the following Vagrantfile to recreate the issue:
### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "/private/tmp/box/kube.box"
  config.ssh.username = "core"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.network :private_network, ip: "172.17.8.101"
end
```

Thanks a lot for you support.

**Comment by chrisroberts** [comment]
Hi there, would you please provide a gist of the full debug output from the failed command. Thanks!

**Comment by abelgana** [comment]
Do you mean the full output?

```
11661  1:12PM  /tmp/box-test  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box '/private/tmp/box/kube.box'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: box-test_default_1521047553890_52892
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: core
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

systemctl stop etcd
ifconfig 172.17.8.101 netmask 255.255.255.0
mv /tmp/etcd-cluster.service /media/state/units/
systemctl restart local-enable.service

# Restart default etcd
systemctl start etcd


Stdout from the command:



Stderr from the command:

Failed to stop etcd.service: Unit etcd.service not loaded.
SIOCSIFNETMASK: No such device
mv: cannot move '/tmp/etcd-cluster.service' to '/media/state/units/': No such file or directory
Failed to restart local-enable.service: Unit local-enable.service not found.
Failed to start etcd.service: Unit etcd.service not found.
```

**Comment by chrisroberts** [comment]
Yep, that's what I was looking for, thanks. The issue appears to be that the etcd service is not loaded in the box you have packaged. The guest support for coreos assumes the service is enabled when configuring the network, so the guest you are packaging needs to be properly configured before it is packaged. 

Cheers!

**Comment by abelgana** [comment]
Thanks a lot.

**Comment by peterrosell** [comment]
@chrisroberts That's true that the etcd service is not loaded. CoreOS has since a while removed etcd from the box. I have exactly the same error when I do a PXE boot and installation with CoreOS with network interface names enp0s3 and enp0s8.
I have another VM where I use a coreos box and that box doesn't have this problem, network interface names eth0 and eth1. There isn't any etcd service in that box.

I found the this code (https://github.com/hashicorp/vagrant/blob/0ce6e9891e00c34620c057b6075b1fafc1e4c796/plugins/guests/coreos/cap/configure_networks.rb#L15:84). I see that the grep there matches on a specific pattern (eg. enp0s8) of the interface and runs the command on the matched interfaces. When I boot the box I get interfaces eth0, eth1. So I don't get any match and the failing commands is not run.
I tested the latest Vagrantfile from CoreOS (https://github.com/coreos/coreos-vagrant) and it creates interfaces named eth0 and eth1. That's why it doesn't get any error.

I guess that the guestCoreOS plugin previous needed to update some network info in the etcd service, but this is not needed and in the standard coreos box is not run due to new(?) interface name. I think the etcd service code in this guestCoreOS plugin should be removed to match changes in coreos. 

@abelgana What was the name of the interface on your VM?

**Comment by deblasis** [comment]
I can confirm that this is still an issue.
Repro steps:
- create a box from https://github.com/coreos/coreos-vagrant
- package it
- use it as a base for another Vagrantfile (taking care of the ssh key as specified in the docs, otherwise Vagrant can't login via ssh)
- add a network interface, for example "public_network"
- ```vagrant up```
- you should see the error

`configure_networks.rb` tries to be smart about etcd, while I reckon it should simply manage the network.

I am sure that it used to work at some point, CoreOS evolved, as etcd did (v1, v2 and now we are at v3) meanwhile. 

More details in the PR #10650

**Comment by deblasis** [comment]
Hi @chrisroberts would it be possible to address this? We just upgraded to 2.2.4 and we had to reapply my patch #10650. Sorry to ping you directly but this issue is erroneously closed. Thanks in advance
