### ISSUE TITLE
Status is "not created"

### ISSUE THREAD

**Issue by mahmoodn** [hashicorp/vagrant#9610]
An issue has been reported in 2014 [1] which I think is still present. Please see the output below. As yo can see the machines are not created (actually they had been destroyed before this command) but it seems that they are present.

```
PS D:\dcos-vagrant> vagrant status
 INFO dcos-vagrant: Validating Plugins...
 INFO dcos-vagrant: Validating User Config...
 INFO dcos-vagrant: Validating Installer Checksum...
 INFO dcos-vagrant: Using DC/OS Installer: installers/dcos/dcos_generate_config-1.11.0.sh
 INFO dcos-vagrant: Using DC/OS Config: etc/config-1.11.yaml
 INFO dcos-vagrant: Validating Machine Config...
 INFO dcos-vagrant: Validating Command...
 INFO dcos-vagrant: Configuring VirtualBox Host-Only Network...
Current machine states:

m1                        not created (virtualbox)
a1                        not created (virtualbox)
p1                        not created (virtualbox)
boot                      not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
PS D:\dcos-vagrant> vagrant destroy m1
 INFO dcos-vagrant: Validating Plugins...
 INFO dcos-vagrant: Validating User Config...
 INFO dcos-vagrant: Validating Installer Checksum...
 INFO dcos-vagrant: Using DC/OS Installer: installers/dcos/dcos_generate_config-1.11.0.sh
 INFO dcos-vagrant: Using DC/OS Config: etc/config-1.11.yaml
 INFO dcos-vagrant: Validating Machine Config...
 INFO dcos-vagrant: Validating Command...
 INFO dcos-vagrant: Configuring VirtualBox Host-Only Network...
==> m1: VM not created. Moving on...
PS D:\dcos-vagrant>
```

[1] https://github.com/hashicorp/vagrant/issues/4550

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. What you shared was running `vagrant status` and `vagrant destroy`, which demonstrates expected behavior. No machines were created or running when you ran the status command.

When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!
