### ISSUE TITLE
openwrt guest plugin

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9663]
OpenWrt boxes could benefit from a basic guest plugin.

* Extend the Linux guest plugin.
* Define rsync install capability as run `opkg update` then `opkg install rsync` (using sudo privileges for both commands).
* Default `config.ssh.shell` to `/bin/ash`.
* Replace `--compress` in `rsync__args` with `-zz`.
* Shutdown command is `halt`, with no flags, sudo privileged.
* Rewrite the UNIX `find` command involved in chowning rsync files avoid relying on `-or`, which is unavailable in OpenWrt's `find`. This can be accomplished by separating the conditionals into multiple `find` commands.

I'm currently working around that last tweak by disabling rsync chowning in my `Vagrantfile`s.

**Comment by briancain** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it is a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
