### ISSUE TITLE
Vagrant error with special characters

### ISSUE THREAD

**Issue by YannikFirre** [hashicorp/vagrant#9678]
Hello,

### Vagrant version
2.0.3

### Host operating system
Windows 10 - Virtualbox 5.2.8

### Guest operating system
Ubuntu

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.box = "gitlab"

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 80, host: 8888
	
  config.vm.network "public_network", ip: "10.1.1.198"

  config.vm.synced_folder "//10.1.1.170/vagrant_web/", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "3048"
   end

end
```

### Debug output
https://gist.github.com/InfinityWebMe/e59730f0d567977e5d7fd67aa9dd73c2#file-vagrant-log

### Actual behavior
![vagrant-error](https://user-images.githubusercontent.com/3316758/38604138-c4318836-3d6f-11e8-89c5-a6f64ad48d92.jpg)

Thanks =)

**Comment by briancain** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier 

Cheers!
