### ISSUE TITLE
Russian's goverment blocks Amazon IP's

### ISSUE THREAD

**Issue by tbazadaykin** [hashicorp/vagrant#9697]
It's not an issue, it's more entreaty.

A russian government agency "Roskomnadzor" now [blocking Telegram Messenger](https://www.reuters.com/article/us-russia-telegram-blocking/russia-starts-blocking-telegram-messenger-idUSKBN1HN13J). The formal pretext is the Telegram's refusal to issue encryption keys.

In an attempt to bypass the blocking of Telegrams "hiding" behind Amazon. According to Russian media, this has already resulted in the blocking of 2 million Amazon' IP. As a result of this confrontation, innocent services also suffer.

Today I ran into this problem:

```
$ vagrant.exe box add bento/ubuntu-17.10
==> box: Loading metadata for box 'bento/ubuntu-17.10'
    box: URL: https://vagrantcloud.com/bento/ubuntu-17.10
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) hyperv
2) parallels
3) virtualbox
4) vmware_desktop

Enter your choice: 3
==> box: Adding box 'bento/ubuntu-17.10' (v201803.24.0) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-17.10/versions/201803.24.0/providers/virtualbox.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Failed to connect to vagrantcloud-files-production.s3.amazonaws.com port 443: Socket is not connected
```

Downloading was completed only with 3 attempts. Perhaps this is just the echo of this confrontation.

In connection with the foregoing, I want to ask the developers: do not throw the Russian segment to the mercy of fate! Please, if possible, take measures to maintain the service in Russia.

**Comment by chrisroberts** [comment]
Hi there,

My apologies that access to the Vagrant Cloud has been hindered by the Russian government. At this point the effect of the actions currently being taken are very widespread and causing connectivity issues for quite a large number of services which utilize not only AWS but a number of other cloud providers as well. Being unable to determine what services may be subject to blacklisting in the future, we cannot implement any kind of "fix" for this situation as it may become ineffective at any moment. For now, the best way to work around this problem is via remote proxy or VPN service. 

Again my apologies for the difficulty in accessing the Vagrant Cloud service and I hope that this blacklisting approach is halted soon.

Cheers!
