### ISSUE TITLE
continuation of issue 9815

### ISSUE THREAD

**Issue by whiggs** [hashicorp/vagrant#9820]
This is a continuation of #9815.  Exactly what part of the issue is "too complicated to reproduce"?  Unfortunately, due to the lack of suitable hardware in my current device, I am unable to host virtual machines locally, and am limited to only using services which host the virtual machine on a remote server and allow me to connect, so I am unable to see what happens when I use virtualbox as a provider.  However, I fail to see why one would think that would result in a different result, as the vmware vsphere provider is able to use all of vagrant's other features successfully, including the functionality which the issue I submitted is in regards to, with the exception that I have only gotten it to work when the device was not domain joined and using the default "vagrant" username and password to authenticate with winrm.  I do not know the advanced details as to how vagrant works and utilizes its providers, but given that it works in one instance rather but not the other would makes me think that it is an issue with vagrant itself, seeing as the shell provisioner AND the winrm configuration are both configurations that are native to vagrant, not the vmware vsphere provider.  If it were native to the provider, then I would have submitted the issue on that page.  But it is not.  It is native to vagrant, and would, therefore, expect a more thorough attempt to at least test the issue on your end (perhaps, as was recommended in the ticket, using virtualbox) rather than throwing in the towel without having even tried, which is exactly what appears to have happened.  The whole point of submitting issues like this is to start a dialog so that user and developer can go over the issue, test out different scenarios on BOTH ENDS, and determine the source of the issue, so I would appreciate it if that is the mindset that is used by whoever picks up this ticket, rather than that of doing as little work as possible.  I take the time to submit these issues because I want to determine the source of the issue, and contribute to the improvement of the project if the issue lies with you, so it is very insulting when the issues are immediately closed without any work being put into it whatsoever.  Thank you.

**Comment by briancain** [comment]
Hi @whiggs - Apologies if you felt like you got treated unfairly on the previous issue, however with the size and complexity of Vagrantfile you posted, it's very difficult for us to diagnose the issue especially with the volume of tickets that we see on the Vagrant project. When we ask for a minimal reproduction Vagrantfile it's because that makes it a lot easier for us to help you with your issue and eliminates any potential factors not related to Vagrant. An example of a minimal Vagrantfile that *could* have a shell provisioner issue might be:

```ruby
Vagrant.configure("2") do |config|
  config.vm.define "windows" do |w|
    w.vm.box = "windows"
    w.vm.communicator = :winrm
    w.vm.provision "shell", inline: <<-SHELL
    Write-Host "Hello"
    SHELL
  end
end
```

As the issue stands now, I cannot reproduce your problem with Virtualbox or VMWare with a PowerShell provisioner...

VMWare provider running a PowerShell provisioner:

```
Bringing machine 'windows' up with 'vmware_fusion' provider...
==> windows: Cloning VMware VM: 'windowsbase'. This can take some time...
==> windows: Verifying vmnet devices are healthy...
==> windows: Preparing network adapters...
WARNING: The VMX file for this box contains a setting that is automatically overwritten by Vagrant
WARNING: when started. Vagrant will stop overwriting this setting in an upcoming release which may
WARNING: prevent proper networking setup. Below is the detected VMX setting:
WARNING:
WARNING:   ethernet0.pcislotnumber = "33"
WARNING:
WARNING: If networking fails to properly configure, it may require this VMX setting. It can be manually
WARNING: applied via the Vagrantfile:
WARNING:
WARNING:   Vagrant.configure(2) do |config|
WARNING:     config.vm.provider :vmare_desktop do |vmware|
WARNING:       vmware.vmx["ethernet0.pcislotnumber"] = "33"
WARNING:     end
WARNING:   end
WARNING:
WARNING: For more information: https://www.vagrantup.com/docs/vmware/boxes.html#vmx-whitelisting
==> windows: Starting the VMware VM...
==> windows: Waiting for the VM to receive an address...
==> windows: Forwarding ports...
    windows: -- 3389 => 3389
    windows: -- 22 => 2222
    windows: -- 5985 => 55985
    windows: -- 5986 => 55986
==> windows: Waiting for machine to boot. This may take a few minutes...
    windows: WinRM address: 172.16.151.131:5985
    windows: WinRM username: vagrant
    windows: WinRM execution_time_limit: PT2H
    windows: WinRM transport: negotiate
==> windows: Machine booted and ready!
==> windows: Configuring network adapters within the VM...
==> windows: Configuring secondary network adapters through VMware
==> windows: on Windows is not yet supported. You will need to manually
==> windows: configure the network adapter.
==> windows: Enabling and configuring shared folders...
    windows: -- /Users/brian/code/vagrant-sandbox: /vagrant
==> windows: Running provisioner: shell...
    windows: Running: inline PowerShell script
    windows: Hello
```


VirtualBox provider running a PowerShell provisioner:

```
Bringing machine 'windows' up with 'virtualbox' provider...
==> windows: Importing base box 'windows10vbox'...
Progress: 10%
==> windows: Matching MAC address for NAT networking...
==> windows: Setting the name of the VM: vagrant-sandbox_windows_1525969721694_37572
==> windows: Clearing any previously set network interfaces...
==> windows: Preparing network interfaces based on configuration...
    windows: Adapter 1: nat
==> windows: Forwarding ports...
    windows: 3389 (guest) => 3389 (host) (adapter 1)
    windows: 22 (guest) => 2222 (host) (adapter 1)
    windows: 5985 (guest) => 55985 (host) (adapter 1)
    windows: 5986 (guest) => 55986 (host) (adapter 1)
==> windows: Running 'pre-boot' VM customizations...
==> windows: Booting VM...
==> windows: Waiting for machine to boot. This may take a few minutes...
    windows: WinRM address: 127.0.0.1:55985
    windows: WinRM username: vagrant
    windows: WinRM execution_time_limit: PT2H
    windows: WinRM transport: negotiate
==> windows: Machine booted and ready!
==> windows: Checking for guest additions in VM...
==> windows: Mounting shared folders...
    windows: /vagrant => /Users/brian/code/vagrant-sandbox
==> windows: Running provisioner: shell...
    windows: Running: inline PowerShell script
    windows: Hello
```

If you can reproduce your problem with a minimal reproducible example of the problem, please feel free to open a new issue on the project and we will be happy to investigate. Thanks!

**Comment by kikitux** [comment]
@whiggs by hard to reproduce is, you haven't shared how I can reproduce this on my machine.

What do you want me to have?

- vsphere?
- esxi?
- Windows Vm template?
- How was provisoned?
- hows the domain part?

and a long etc.

If we can't preproduce your setup to the very same moment it fails, not sure how you expect we will be able to see the error first hand.

We are not talking about error logs, we are talking to have a local Machine/Vagrantfile that present the error so we can review, troubleshoot and work on the fix is something Vagrant local.

If you can:

- Create a Vagrant file
- Using Virtualbox
- With a guest on vagrant cloud

the chances are higher than using vsphere/esxi and no steps to get to the error.

hope this helps to clarify the "hard to reproduce part"
