### ISSUE TITLE
URL for downloading the latest version

### ISSUE THREAD

**Issue by AsharLohmar** [hashicorp/vagrant#9821]
Please add a way to easily access/download the latest version for "automatic" installations.
An solution would be to add a folder "latest" in https://releases.hashicorp.com/vagrant/ and have the "files" inside with "fixed" names, no version numbers.
Or urls with parameters, something like:
https://releases.hashicorp.com/vagrant/download?version=latest&arch=x86_64&format=deb
https://releases.hashicorp.com/vagrant/checksum?version=latest&arch=x86_64&format=deb

https://releases.hashicorp.com/vagrant/download?version=1.9.8&arch=i686&format=msi

**Comment by espoelstra** [comment]
Since they use simple directory lists I'm not sure it makes sense to maintain a symlink or an unversioned binary when you can just `curl https://releases.hashicorp.com/vagrant/ | grep href | grep -v '\.\.' | head -1` to get the most recent version, and the output, `<a href="/vagrant/2.1.1/">vagrant_2.1.1</a>` is only an easy to Google regex away from giving you a folder name to curl again for the filenames and then you can match for your platform. See also the ansible/Chef/Puppet/SaltStack recipes or Homebrew/Linuxbrew/Chromebrew for other specific implementations.

**Comment by chrisroberts** [comment]
Hi there,

Thank you for this suggestion but at this time there are currently no plans to include this functionality within the release process. As stated above, the functionality can easily be implemented locally to achieve the desired result. Cheers!
