### ISSUE TITLE
Set context of synced folder to prevent SELinux from complaining

### ISSUE THREAD

**Issue by leem32** [hashicorp/vagrant#9827]
Vagrant 2.1.1
Host OS: Windows 7 Pro
Guest OS: Centos 7.4

Using either the default Vagrant synced folder or nfs vagrant synced folder I keep getting SELinux errors telling me I need to change the context to `httpd_sys_content_t`. All files in the default synced folders are set to `default_t` context and all files using nfs sync are set to `nft_t`.

files are always default_t context
`config.vm.synced_folder '.', '/vagrant'`
files are always nfs_t context
`config.vm.synced_folder ".", "/vagrant",  type: "nfs"`

I have tried to change the files context the normal way using `fcontext` and `restorecon`, but `restorecon` just fails silently.

How can I set the context of synced files/folders to avoid SELinux errors??

I've tried using `:mount_options`, but they're ignored.
Example:    
`config.vm.synced_folder "./www", "/var/www",  type: "nfs", create: true, id: "sites", mount_options: ['vers=3', :udp, :nolock, :noatime, 'context=system_u:object_r:httpd_sys_content_t:s0']`

Maybe I'm adding the context in mount options the wrong way??

**Comment by apolopena** [comment]
I have the same issue running a vagrant centos7 box on Virtualbox. The synced folder always takes on the SELinux content "system_u:object_r:vmblock_t:s0" regardless of what I have set using any of the SELinux context commands including semanage. As soon as I do not sync  the folder ( by commenting the sync folder line out in vagrantfile and reboot the machine with a vagrant reload then the proper context I set comes back: "unconfined_u:object_r:httpd_sys_content_t:s0"

**Comment by leem32** [comment]
Let me know if you figure this out. In the end, I just turned off selinux and deal with selinux issues on a staging server instead.

**Comment by apolopena** [comment]
It is a limitation of what synced_folders is a wrapper for which is vboxfs

rsync seems like the best workaround for this issue:
https://www.vagrantup.com/docs/synced-folders/rsync.html

**Comment by apolopena** [comment]
I got it working with rsync -avz. This solution assumes that SELinux context has been persistently and recursively for the target directory to `'httpd_sys_content_t'` using `semanage` (which my need to be installed on the guest via `yum install policycoreutils-python`) and restorecon as per this [post](https://serverfault.com/questions/409464/permission-denied-in-vhost-document-root/409488#409488). So that would look something like this in the guests cli:
``semanage` fcontext -a -t httpd_sys_content_t "/var/www(/.*)?"``
then
`$ restorecon -r -v /var/www`
Note:  There seemed to be a bug on my centos/7 box where the semanage command threw an error the first time around, but it did work the second time. just make sure the target directory is not currently synced or it will be in use and the command will be ignored.

Finally the vagrant rsync workaround (in vagrantfile on the host):
``config.vm.synced_folder "sync/apdev1/html", "/var/www/apdev1.com/public_html/synced", :owner => "apache", :group => "apache", type: "rsync", rsync__exclude: [".git",  ".DS_Store"], rsync__args:["-avz", "--rsync-path='sudo rsync'"]``

**Comment by leem32** [comment]
Nice. I'll check this out tomorrow. Thanks for posting. :)

**Comment by leem32** [comment]
I got rsync working and the web root `fcontexts` where correctly set as `'httpd_sys_content_t`, but I'm on a windows 7 host and for the life of me could not get rsync to sync when I update a file. I tried with Powershell, Cygwin, Git Bash.  When I open a new shell and run `vagrant rsync-auto` it says watching the synced files but just never syncs.

**Comment by apolopena** [comment]
Yeah I finally found out through extensive tests and research that it is a
limitation of Virtual box and will not be fixed due to having to support to
many protocols. Also The vagrant rsync-auto and polling options were super
buggy and did not work with a windows host and additionally caused
persistent one-time syncing on vagrant up or reload which was frustrating.
https://www.virtualbox.org/ticket/10660
The Bottom line is that anything shared and synced in vagrant with a
windows host uses some type of file mount and any of those mounts do not
support file system events.
I was able to get rsync working properly both ways guest to host and host
to guest but I had to use the Virtual box mounting solution found here
<https://forums.virtualbox.org/viewtopic.php?t=15868> which revolves back
to the original SELinux issue of sentenforce 0 needing to be set.
I even went so far as to implement inotifywait to listen for file system
events on the guest which worked great until I tried to use it on a mounted
file system and then it didn't work because it is not supported
<https://www.virtualbox.org/ticket/10660> on mounted file systems :(

So in conclusion is looks like the only way to auto sync files from a
mounted filesystem in vagrant virtualbox would be to use a polling chron
job which I don't really like any better than using setenforce 0 on a
development box.

Lastly I may try to see if this vagrant-fsnotify plugin
<https://github.com/adrienkohlbecker/vagrant-fsnotify> will work to be able
to copy files from outside the apache html folder into the semanaged
apached folder, thus allowing me to keep setenforce 1 set on a development
centos7 vagrant box still synced to a windows host but that plugin has a
limitation of a 2 second delay on all file changes so that is something to
keep in mind.
I guess if you must sync from a windows host to a vagrant centos box you
will have to rely on polling chron jobs on the guest or log another vagrant
bug alerting them to the fact that rysync-auto is broken for windows hosts
but even then they will probably run into the Virtual box will not fix bug
<https://www.virtualbox.org/ticket/10660> regarding file events for mounted
file systems.

**Comment by soapy1** [comment]
Closing this as this issue can not be resolved in Vagrant.
