### ISSUE TITLE
Docker provider doesn't handle relative paths for volumes properly on windows

### ISSUE THREAD

**Issue by Shadowesque** [hashicorp/vagrant#9858]
The comments in the following lines state that the gsub! statement is done because docker doesn't support UNC paths.
https://github.com/hashicorp/vagrant/blob/dbba41a7ec3d87830f9b1895266d6a807c1cd2e0/plugins/providers/docker/driver.rb#L54-L57
https://github.com/hashicorp/vagrant/blob/dbba41a7ec3d87830f9b1895266d6a807c1cd2e0/plugins/providers/docker/driver/compose.rb#L100-L103
However the regular expression is too broad and breaks relative paths which start with one or more of "../"; for example:
"../foo" becomes "foo"
"../../foo" becomes "foo"

**Comment by briancain** [comment]
Hi there! As far as I can tell, it looks like the docker provider on windows is doing the right thing:

![screenshot from 2018-10-18 14-30-14](https://user-images.githubusercontent.com/810277/47185770-41e90700-d2e3-11e8-85b7-f60068b3d816.png)

If you have some debug output showing otherwise though I'll be happy to reopen this issue! Thanks.
