### ISSUE TITLE
"vagrant ssh" causes ":up" trigger to run

### ISSUE THREAD

**Issue by craigglennie** [hashicorp/vagrant#9868]
### Vagrant version
Vagrant 2.1.1

### Host operating system
macOS 10.13.4

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.trigger.before :up do
    system("date >> trigger_times.txt")
  end
  config.vm.box = "bento/ubuntu-16.04"
end
```

### Expected behavior
Trigger should only run when `vagrant up` is executed. That's how the old trigger plugin worked.

### Actual behavior
Running `vagrant ssh` also runs the trigger

### Steps to reproduce
1. Run `vagrant up`, see that timestamp has been appended to `trigger_times.txt`
2. In a shell, `tail -f trigger_times.txt`
3. Run `vagrant ssh`, see that another timestamp has been added to `trigger_times`.txt

**Comment by briancain** [comment]
Hi there @craigglennie ! At the moment, you cannot run ruby code like this inside a trigger. The reason why you're seeing this behavior is because Vagrant parses your config file and evaluates what's inside the config block (which will execute your `system` function). What you actually want right now is this:

```ruby
config.trigger.before :up do |trigger|
  trigger.run = {inline: "date >> trigger_times.txt"}
end
```

I'll go ahead and close this, because it is a duplicate of https://github.com/hashicorp/vagrant/issues/9840. Thanks!
