### ISSUE TITLE
Is there a way for vagrant to continue processing a vagrantfile when vagrant encounters an error?

### ISSUE THREAD

**Issue by whiggs** [hashicorp/vagrant#9914]
Ok.  So I have been trying (unsuccessfully) to create a vagrantfile which can deploy windows guest machines, but I continue to encounter error after error after error, whether this is due to shared folders already existing, winrm authentication issues, etc, etc, etc.  It wouldn't be all that bad if it weren't for the fact that vagrant stops processing the "vagrant up" command when it encounters any error, regardless of how trivial.  Is there some hidden functionality that perform the equivilant of Powershell's "-silentlycontinue" parameter for vagrant, in other words, continue to process the remainder of the vagrantfile if the error that vagrant encounters is not a fatal error.  For example, I would expect that the inability to connect to the vagrant machine using the defined communicator would be a "lethal error", but would expect that the inability to create a smb file share due to the fact that the share in question is already being shared would be a "non-lethal" error, and vagrant would be able to easily skip to the next part of the vagrantfile (or maybe even mitigate the error and connect to the already shared resource).  Encountering these errors always prevents my machine from being fully provisioned before the console returns, requiring that I manually configure the portion which vagrant was unable to, which defeats the purpose of even using vagrant in the first place.

**Comment by chrisroberts** [comment]
Hi there,

There is no support in Vagrant to "ignore errors". If errors are encountered, Vagrant will halt and report the error as it was unable to configure the guest as requested. If an error is being generated while a guest is being created and/or provisioned, then those errors should be debugged and rectified either within the the configured box, the provision scripts, or Vagrant itself if that is where the problem is originating.

If it seems that Vagrant is at fault for the failure of the guest provisioning, please create a new issue providing the details requested in the template and we will be happy to investigate.

Cheers!
