### ISSUE TITLE
Vagrant 2.x breaks with config.ssh.pty setting

### ISSUE THREAD

**Issue by peterrehm** [hashicorp/vagrant#9921]
`vagrant up` hangs with Configuring and enabling network interfaces due to config.ssh.pty.
Once this is set to false everything works as expected.

### Vagrant version
I tried 2.0.0, 2.0.3 and 2.1.1 which all show that issue.

### Host operating system
Mac OSX 10.13.5

### Guest operating system
Ubuntu 16.04 (bento/ubuntu-16.04)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
    config.vm.network :private_network, ip: "10.20.99.99"
    config.ssh.pty = true
end
```

### Debug output

It gets in a loop with:

````
DEBUG ssh: Sending SSH keep-alive...
````

If needed I will provide the full log.

### Expected behavior
Vagrant up should provision the box.

### Actual behavior
Vagrant up stops at the step

````
==> default: Configuring and enabling network interfaces...
````

### Steps to reproduce
1.  vagrant up with the Vagrantfile above

Same also on Ubuntu host.

**Comment by chrisroberts** [comment]
Hi there. Yes, would you please provide a gist of the debug output. Thanks!

**Comment by peterrehm** [comment]
https://gist.github.com/peterrehm/9c6e2c390368efb8f05e62b19d96cd2b

**Comment by peterrehm** [comment]
@chrisroberts can it be reproduced?

**Comment by soapy1** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier ☹️

Cheers!
